In [3]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

from plotly.offline import init_notebook_mode, iplot
import plotly.graph_objs as go
init_notebook_mode(connected=True)
import warnings
warnings.filterwarnings("ignore")
%matplotlib inline

In [ ]:
# não excluir os cnpjs de teste da base, será util na analise de outliers
teste = ['60701190000104']

In [4]:
# read required datasets
df_dividas = pd.read_excel("../tabelas/base_dividas_201904.xlsx")
df_dividas['cnpj'] = df_dividas.apply(lambda x : '0' + str(x['cnpj']) if len(str(x['cnpj']))==13
                              else ('00' + str(x['cnpj']) if len(str(x['cnpj']))==12 else str(x['cnpj'])), axis=1)

df_p = df_dividas[df_dividas['tipo']=='processos']
df_dividas = df_dividas[df_dividas['tipo']!='processos']
df_p['modalidade_natureza'] = df_p['descricao_natureza']
df_p.drop(columns=['descricao_natureza'], axis=1, inplace=True)
df_dividas.drop(columns=['descricao_natureza'], axis=1, inplace=True)
df = pd.concat([df_dividas, df_p])
df['modalidade_natureza'] = df.apply(lambda x : x['modalidade_natureza'].replace(" ", "") if isinstance(x['modalidade_natureza'], str) else "OUTROS", axis=1)

In [5]:
df['valor'] = df.apply(lambda x : x['valor'].split("R$ ")[1].replace(",", "."), axis=1)
df["valor"] = df.apply(lambda x : float(x["valor"]), axis=1)

In [6]:
df.head()

,cnpj,data_ocorrencia,modalidade_natureza,natureza,tipo,uf,valor
0,19008188000142,21/05/2018,Dívidanãocontestada.,Falta Pagamento,protestos,SP,892.53
1,19008188000142,22/03/2018,Dívidanãocontestada.,Falta Pagamento,protestos,SP,560.00
2,19008188000142,15/03/2018,Dívidanãocontestada.,Falta Pagamento,protestos,SP,560.80
3,19008188000142,01/03/2018,Dívidanãocontestada.,Falta Pagamento,protestos,SP,452.50
4,19008188000142,22/02/2018,Dívidanãocontestada.,Falta Pagamento,protestos,SP,452.50

In [10]:
df[df['cnpj']=='00000000000191']

Empty DataFrame
Columns: [cnpj, data_ocorrencia, modalidade_natureza, natureza, tipo, uf, valor]
Index: []

Definindo segmentos

In [7]:
segmento_infra = ['FATAGUA', 'TELEFFX', 'TELEFFIXA', 'TELEFMOVEL', 'CONDOMINIO', 'ENERGIAELET', 'ALUGUEL', 
                  'SERVTELEFON']

segmento_credito = ['EMPRESCONTA', 'CREDCARTAO', 'FINANCIAMENT', 'CREDITOEFINANCIAMENTO-FINANC']

segmento_processos = ['EXCJUDTRAB', 'FISCALESTADUAL', 'EXECUCAO', 'FISCALFEDERAL', 'FISCALMUNICIPAL',
                     'EXECUCAO-JE', 'BUSCAEAPREENSAO']

In [8]:
df['segmento'] = df.apply(lambda x : 'processos' if x['tipo']=='processos'
                          else('credito' if x['modalidade_natureza'] in segmento_credito
                              else ('infra' if x['modalidade_natureza'] in segmento_infra else "outros")), axis=1)

In [11]:
df = df[["cnpj", "valor", "segmento"]]

In [12]:
# dataset com alguns parametros já calculados
df_comp = pd.read_excel("../tabelas/dataset_variaveis_completo_201904.xlsx")
df_comp["cnpj"] = df_comp.apply(lambda x : str(x["cnpj"]), axis=1)
df_comp["cnpj"] = df_comp.apply(lambda x : "0" + x["cnpj"] if len(x["cnpj"])==13 else
                                ("00" + x["cnpj"] if len(x["cnpj"])==12 else x["cnpj"]), axis=1)

In [14]:
df_comp.shape

(983, 12)

In [19]:
df_comp[(df_comp["prop_divida"]<=1.5) & (df_comp["quantidade_cheques"]==0)]["cnpj"].unique().tolist().__len__()

422

### 1 - Probabilidade

In [42]:
def calcula_probabilidade(cnpj, df):
    dt = df[df["cnpj"]==cnpj]
    dt = dt.groupby("segmento").count().reset_index()[["segmento", "valor"]]
    dt.columns = ["segmento", "ocorrencias"]
    dt["probabilidade"] = dt["ocorrencias"]/dt["ocorrencias"].sum()
    dt["cnpj"] = cnpj
    return dt

In [43]:
calcula_probabilidade(cnpj, df)

    segmento  ocorrencias  probabilidade            cnpj
0    credito            7       0.039548  00178663000281
1      infra           17       0.096045  00178663000281
2     outros          151       0.853107  00178663000281
3  processos            2       0.011299  00178663000281

In [44]:
ret = []
for el in df["cnpj"].unique().tolist():
    _df = calcula_probabilidade(el, df)
    ret.append(_df)

In [45]:
dcalc = pd.concat(ret)

dcalc = dcalc[["cnpj", "segmento", "ocorrencias", "probabilidade"]]

In [49]:
dcalc.head()

             cnpj   segmento  ocorrencias  probabilidade
0  19008188000142     outros           23       1.000000
0  00748390000182     outros           28       1.000000
0  00272073000302     outros            6       1.000000
0  03403405000169     outros           80       0.963855
1  03403405000169  processos            3       0.036145

### 2 -  Composicao da Dívida

In [64]:
def calcula_composicao(cnpj, df):
    dt = df[df["cnpj"]==cnpj]
    dt = dt.groupby("segmento").sum().reset_index()
    dt.columns = ["segmento", "valor_divida"]
    dt["composicao"] = dt["valor_divida"]/dt["valor_divida"].sum()
    dt["cnpj"] = cnpj
    return dt

In [65]:
ret = []
for el in df["cnpj"].unique().tolist():
    _df = calcula_composicao(el, df)
    ret.append(_df)

In [67]:
_df = pd.concat(ret)

In [69]:
_df = _df[["cnpj", "segmento", "valor_divida", "composicao"]]

In [72]:
dcalc.shape

(980, 4)

In [73]:
_df.shape

(980, 4)

In [76]:
dcalc = dcalc.merge(_df, left_on=["cnpj", "segmento"], right_on=["cnpj", "segmento"], how="left")

In [78]:
dcalc.head()

,cnpj,segmento,ocorrencias,probabilidade,valor_divida,composicao
0,19008188000142,outros,23,1.000000,125364.55,1.000000
1,00748390000182,outros,28,1.000000,594828.06,1.000000
2,00272073000302,outros,6,1.000000,9659.96,1.000000
3,03403405000169,outros,80,0.963855,11431587.35,0.991936
4,03403405000169,processos,3,0.036145,92932.30,0.008064

### Faturamento Medio

In [82]:
dfat = df_comp[["cnpj", "fat_medio"]].drop_duplicates()

In [88]:
dfat = dfat[dfat["cnpj"]!="60701190000104"]

In [98]:
dfat = dfat[dfat["cnpj"]!="191"]

In [93]:
dcalc = dcalc[dcalc["cnpj"]!='60701190000104']

In [96]:
dcalc = dcalc[dcalc["cnpj"]!="191"]

In [99]:
dfat.shape

(715, 2)

In [100]:
dcalc["cnpj"].unique().tolist().__len__()

715

In [105]:
dcalc = dcalc.merge(dfat, left_on="cnpj", right_on="cnpj", how="left")

In [107]:
dcalc["pi"] = dcalc["valor_divida"]/dcalc["fat_medio"]

In [109]:
dcalc.head()

,cnpj,segmento,ocorrencias,probabilidade,valor_divida,composicao,fat_medio,pi
0,19008188000142,outros,23,1.000000,125364.55,1.000000,83401.116667,1.503152
1,00748390000182,outros,28,1.000000,594828.06,1.000000,35540.883333,16.736446
2,00272073000302,outros,6,1.000000,9659.96,1.000000,139381.200000,0.069306
3,03403405000169,outros,80,0.963855,11431587.35,0.991936,15075.161667,758.306120
4,03403405000169,processos,3,0.036145,92932.30,0.008064,15075.161667,6.164597

Aplicando o criterio de elegibilidade para a variavel pi

In [113]:
lista_reprovados = dcalc[dcalc["pi"]>1.5]["cnpj"].unique().tolist()

In [118]:
dcalc = dcalc[~dcalc["cnpj"].isin(lista_reprovados)]

In [120]:
# normalizando pi
dcalc["pi"] = (2/3)*dcalc["pi"]

In [124]:
dcalc.sort_values("pi", ascending=False).head()

,cnpj,segmento,ocorrencias,probabilidade,valor_divida,composicao,fat_medio,pi
952,51452795000100,outros,44,0.977778,23307.19,0.986214,15673.768333,0.991346
446,22248860000181,outros,8,1.000000,18268.85,1.000000,12290.895000,0.990915
232,08022764000190,outros,5,1.000000,15381.27,1.000000,10352.674167,0.990486
308,04509695000192,credito,1,1.000000,34146.03,1.000000,23566.275000,0.965957
657,10313196000128,outros,3,0.750000,34757.92,0.588842,24048.138889,0.963565

### Calculo do  $\lambda$

In [126]:
dcalc["lambda"] = dcalc["composicao"]*dcalc["pi"]

In [129]:
dcalc[dcalc["cnpj"]=='04247535000112']

,cnpj,segmento,ocorrencias,probabilidade,valor_divida,composicao,fat_medio,pi,lambda
787,04247535000112,infra,1,0.5,75.71,0.269671,61691.85,0.000818,0.000221
788,04247535000112,outros,1,0.5,205.04,0.730329,61691.85,0.002216,0.001618

In [131]:
# escala do impacto
escala_impacto = {"credito" : {"i0" : 0.75, "i1" : 1},
                 "processos" : {"i0" : 0.5, "i1" : 0.75},
                  "infra" : {"i0" : 0.25, "i1" : 0.5},
                  "outros" : {"i0" : 0, "i1" : 0.25},
                 }

In [132]:
escala_impacto

{'credito': {'i0': 0.75, 'i1': 1},
 'processos': {'i0': 0.5, 'i1': 0.75},
 'infra': {'i0': 0.25, 'i1': 0.5},
 'outros': {'i0': 0, 'i1': 0.25}}

In [135]:
def impacto_segmento(lambda_, segmento, escala_impacto):
    escala = escala_impacto.get(segmento)
    i0 = escala.get("i0")
    i1 = escala.get("i1")
    return (i1 - i0)*lambda_ + i0

In [137]:
impacto_segmento(0.269671, "infra", escala_impacto)

0.31741775

In [138]:
impacto_segmento(0.000221, "infra", escala_impacto)

0.25005525

In [139]:
dcalc["impacto_segmento"] = dcalc.apply(lambda x : impacto_segmento(x["lambda"], x["segmento"], escala_impacto), axis=1)

In [142]:
dcalc.sort_values("impacto_segmento", ascending=False).head()

,cnpj,segmento,ocorrencias,probabilidade,valor_divida,composicao,fat_medio,pi,lambda,impacto_segmento
308,04509695000192,credito,1,1.000000,34146.03,1.000000,23566.275000,0.965957,0.965957,0.991489
138,11223079000136,credito,2,1.000000,10794.48,1.000000,7836.491667,0.918309,0.918309,0.979577
841,10736773000194,credito,3,0.500000,46580.96,0.987631,35680.928333,0.870324,0.859559,0.964890
365,14373103000101,credito,1,1.000000,2668.79,1.000000,2202.320833,0.807872,0.807872,0.951968
883,15699778000108,credito,1,0.166667,23254.02,0.876881,16860.703333,0.919456,0.806254,0.951563

In [145]:
_df = dcalc[(dcalc["segmento"]=="credito") & (dcalc["composicao"]==1)]

In [148]:
_df.sort_values("pi").head()

,cnpj,segmento,ocorrencias,probabilidade,valor_divida,composicao,fat_medio,pi,lambda,impacto_segmento
877,13640726000130,credito,1,1.0,470.51,1.0,26147.185833,0.011996,0.011996,0.752999
606,24247971000107,credito,2,1.0,703.18,1.0,33055.850000,0.014182,0.014182,0.753545
716,02862111000132,credito,1,1.0,1999.07,1.0,52606.245714,0.025334,0.025334,0.756333
762,02865596000118,credito,1,1.0,2113.67,1.0,49526.550000,0.028452,0.028452,0.757113
199,12148895000195,credito,1,1.0,1150.65,1.0,22757.441667,0.033708,0.033708,0.758427

#### Calculo do risco

In [150]:
dcalc["risco"] = dcalc["probabilidade"]*dcalc["impacto_segmento"]

In [153]:
dcalc.sort_values("risco", ascending=False).head()

,cnpj,segmento,ocorrencias,probabilidade,valor_divida,composicao,fat_medio,pi,lambda,impacto_segmento,risco
308,04509695000192,credito,1,1.0,34146.03,1.0,23566.275000,0.965957,0.965957,0.991489,0.991489
138,11223079000136,credito,2,1.0,10794.48,1.0,7836.491667,0.918309,0.918309,0.979577,0.979577
365,14373103000101,credito,1,1.0,2668.79,1.0,2202.320833,0.807872,0.807872,0.951968,0.951968
758,02458665000179,credito,1,1.0,828.79,1.0,689.000000,0.801925,0.801925,0.950481,0.950481
170,15285941000196,credito,1,1.0,18423.64,1.0,15602.779167,0.787195,0.787195,0.946799,0.946799

In [154]:
dcalc[dcalc["cnpj"]=='04509695000192']

,cnpj,segmento,ocorrencias,probabilidade,valor_divida,composicao,fat_medio,pi,lambda,impacto_segmento,risco
308,04509695000192,credito,1,1.0,34146.03,1.0,23566.275,0.965957,0.965957,0.991489,0.991489

In [155]:
_df = dcalc[(dcalc["segmento"]=="credito") & (dcalc["composicao"]==1)]

#### Calculo do score

In [162]:
def calcula_dscore(risco_, score_limite):
    return -score_limite*risco_ + score_limite

In [163]:
dcalc["dscore"] = dcalc.apply(lambda x : calcula_dscore(x["risco"], 700), axis=1)

In [172]:
# definindo pesos para o score final

In [173]:
W = {"credito" : 4,
    "processos" : 3,
    "infra" : 2,
    "outros" : 1}

In [174]:
W

{'credito': 4, 'processos': 3, 'infra': 2, 'outros': 1}

In [165]:
dcalc.head()

,cnpj,segmento,ocorrencias,probabilidade,valor_divida,composicao,fat_medio,pi,lambda,impacto_segmento,risco,dscore
2,00272073000302,outros,6,1.0,9659.96,1.0,139381.200000,0.046204,0.046204,0.011551,0.011551,691.914295
8,05164765000180,outros,2,1.0,3100.56,1.0,94885.300000,0.021785,0.021785,0.005446,0.005446,696.187692
9,05674948000146,outros,3,1.0,6202.47,1.0,14578.056667,0.283644,0.283644,0.070911,0.070911,650.362280
11,06135496000197,outros,1,1.0,74.77,1.0,7751.399167,0.006431,0.006431,0.001608,0.001608,698.874633
12,07127571000130,outros,4,1.0,2648.22,1.0,147721.475000,0.011951,0.011951,0.002988,0.002988,697.908503

In [187]:
dcalc["peso"] = dcalc.apply(lambda x : W.get(x["segmento"]), axis=1)

In [188]:
def calcula_score_total(cnpj, df):
    dt = df[df['cnpj']==cnpj]
    dt["score"] = dt["dscore"]*dt["peso"]
    score = dt["score"].sum()/dt["peso"].sum()
    dt["score"] = score
    return dt

In [184]:
dcalc.drop(columns=["peso", "score", "socore"], axis=1, inplace=True)

In [189]:
dcalc.head()

,cnpj,segmento,ocorrencias,probabilidade,valor_divida,composicao,fat_medio,pi,lambda,impacto_segmento,risco,dscore,peso
2,00272073000302,outros,6,1.0,9659.96,1.0,139381.200000,0.046204,0.046204,0.011551,0.011551,691.914295,1
8,05164765000180,outros,2,1.0,3100.56,1.0,94885.300000,0.021785,0.021785,0.005446,0.005446,696.187692,1
9,05674948000146,outros,3,1.0,6202.47,1.0,14578.056667,0.283644,0.283644,0.070911,0.070911,650.362280,1
11,06135496000197,outros,1,1.0,74.77,1.0,7751.399167,0.006431,0.006431,0.001608,0.001608,698.874633,1
12,07127571000130,outros,4,1.0,2648.22,1.0,147721.475000,0.011951,0.011951,0.002988,0.002988,697.908503,1

In [190]:
calcula_score_total('71673990000177', dcalc)

,cnpj,segmento,ocorrencias,probabilidade,valor_divida,composicao,fat_medio,pi,lambda,impacto_segmento,risco,dscore,peso,score
692,71673990000177,infra,10,0.136986,33498.08,0.003193,25773475.0,0.000866,0.000003,0.250001,0.034247,676.027331,2,683.871956
693,71673990000177,outros,60,0.821918,137891.79,0.013143,25773475.0,0.003567,0.000047,0.000012,0.000010,699.993257,1,683.871956
694,71673990000177,processos,3,0.041096,10320422.53,0.983664,25773475.0,0.266952,0.262591,0.565648,0.023246,683.727940,3,683.871956

In [191]:
resp = []
for el in dcalc["cnpj"].unique().tolist():
    _df = calcula_score_total(el, dcalc)
    resp.append(_df)

In [192]:
dcalc = pd.concat(resp)

In [196]:
dcalc[dcalc["cnpj"]=='14534748000189']

,cnpj,segmento,ocorrencias,probabilidade,valor_divida,composicao,fat_medio,pi,lambda,impacto_segmento,risco,dscore,peso,score
76,14534748000189,credito,1,0.005376,668.26,0.009443,47309.444167,0.009417,0.000089,0.750022,0.004032,697.177336,4,678.538902
77,14534748000189,outros,183,0.983871,65944.51,0.931811,47309.444167,0.929265,0.865900,0.216475,0.212983,550.911628,1,678.538902
78,14534748000189,processos,2,0.010753,4157.46,0.058746,47309.444167,0.058585,0.003442,0.500860,0.005386,696.230083,3,678.538902

In [197]:
df_score = dcalc[["cnpj", "segmento", "dscore", "score"]]

In [2]:
trace = go.Histogram(
    x = df_score[["cnpj", "score"]].drop_duplicates()["score"].tolist(),
    marker = dict(color='rgb(247,234,95)', line=dict(color="rgb(0, 0, 0)", width=1))
)
layout = go.Layout(title="Distribuicao dscore")
fig = go.Figure(data = [trace], layout=layout)
iplot(fig)

NameError: name 'go' is not defined

In [1]:
# dcalc.to_excel("../tabelas/dataset_metricas_score_completo_20190425.xlsx")

#### Analises dos Resultados

In [208]:
dcalc.drop(columns=["ocorrencias"], axis=1, inplace=True)

In [210]:
dcalc.head()

,cnpj,segmento,probabilidade,valor_divida,composicao,fat_medio,pi,lambda,impacto_segmento,risco,dscore,peso,score
2,00272073000302,outros,1.0,9659.96,1.0,139381.200000,0.046204,0.046204,0.011551,0.011551,691.914295,1,691.914295
8,05164765000180,outros,1.0,3100.56,1.0,94885.300000,0.021785,0.021785,0.005446,0.005446,696.187692,1,696.187692
9,05674948000146,outros,1.0,6202.47,1.0,14578.056667,0.283644,0.283644,0.070911,0.070911,650.362280,1,650.362280
11,06135496000197,outros,1.0,74.77,1.0,7751.399167,0.006431,0.006431,0.001608,0.001608,698.874633,1,698.874633
12,07127571000130,outros,1.0,2648.22,1.0,147721.475000,0.011951,0.011951,0.002988,0.002988,697.908503,1,697.908503

In [217]:
color_menu = {"credito" : 'rgb(252,110,110)',
             "processos" : "rgb(146,233,249)",
              "infra" : "rgb(185,232,119)",
              "outros" : "rgb(247,241,86)"
             }

def plot_dividas(cnpj, df_dividas):
    dt = df_dividas[df_dividas["cnpj"]==cnpj]
    labels = dt["segmento"].tolist()
    values = dt["composicao"].tolist()
    values = [np.around(el*100, 2) for el in values]
    colors = [color_menu.get(el) for el in labels]
    data = []
    trace1 = go.Pie(
            labels = labels,
            values = values,
            hoverinfo = "label+percent",
            textinfo = "value",
            marker = dict(colors=colors, line = dict(color="rgb(0, 0, 0)", width=1))
    )
    
    layout = go.Layout(title="Composição da Dívida e Probabilidades: {}".format(cnpj),
                      
                      
                      )
    fig = go.Figure(data=[trace1], layout=layout)
    iplot(fig)
    return

def plot_probabilidade(cnpj, df_dividas):
    dt = df_dividas[df_dividas["cnpj"]==cnpj]
    labels = dt["segmento"].tolist()
    values = dt["probabilidade"].tolist()
    values = [np.around(el, 2) for el in values]
    colors = [color_menu.get(el) for el in labels]
    
    trace1 = go.Pie(
            labels = labels,
            values = values,
            hoverinfo = "label+percent",
            textinfo = "value",
            marker = dict(colors=colors, line = dict(color="rgb(0, 0, 0)", width=1))
    )
    
    
    
    layout = go.Layout(title="Probabilidades: {}".format(cnpj))
    fig = go.Figure(data=[trace1], layout=layout)
    iplot(fig)
    return

def plot_risco(cnpj, resp):
    dt = resp[resp['cnpj']==cnpj]
    score = int(dt["score"].iloc[0])
    dt.sort_values("risco", ascending=False, inplace=True)
    labels = dt["segmento"].tolist()
    data = []
    for el in labels:
        d = dt[dt['segmento']==el]
        trace = go.Bar(
            x = [el],
            y = [d["risco"].iloc[0]],
            marker = dict(color = color_menu.get(el), line=dict(color='rgb(0, 0, 0)', width=1)),
            name = el
        )
        data.append(trace)
    layout = go.Layout(title = "Risco por segmento de dívida - Score : {}".format(score), bargap=0.5
                      )
    fig = go.Figure(data=data, layout=layout)
    iplot(fig)
    return

In [232]:
plot_dividas('14534748000189', dcalc)
plot_probabilidade('14534748000189', dcalc)
plot_risco('14534748000189', dcalc)

In [233]:
cnpj = '10532480000195'
plot_dividas(cnpj, dcalc)
plot_risco(cnpj, dcalc)

In [234]:
cnpj = "71673990000177"
plot_dividas(cnpj, dcalc)
plot_probabilidade(cnpj, dcalc)
plot_risco(cnpj, dcalc)

In [238]:
cnpj = '61607164000176'
plot_dividas(cnpj, dcalc)
plot_probabilidade(cnpj, dcalc)
plot_risco(cnpj, dcalc)

In [239]:
cnpj = '00437101000124'
plot_dividas(cnpj, dcalc)
plot_probabilidade(cnpj, dcalc)
plot_risco(cnpj, dcalc)

In [241]:
cnpj = "04247535000112"
plot_dividas(cnpj, dcalc)
plot_probabilidade(cnpj, dcalc)
plot_risco(cnpj, dcalc)

In [242]:
dcalc[dcalc['cnpj']=='04247535000112']

,cnpj,segmento,probabilidade,valor_divida,composicao,fat_medio,pi,lambda,impacto_segmento,risco,dscore,peso,score
787,04247535000112,infra,0.5,75.71,0.269671,61691.85,0.000818,0.000221,0.250055,0.125028,612.480695,2,641.606598
788,04247535000112,outros,0.5,205.04,0.730329,61691.85,0.002216,0.001618,0.000405,0.000202,699.858405,1,641.606598

In [244]:
cnpj = '17464661000170'
plot_dividas(cnpj, dcalc)
plot_probabilidade(cnpj, dcalc)
plot_risco(cnpj, dcalc)

In [252]:
dcalc[dcalc["segmento"]=="infra"].sort_values("pi", ascending=False).head()

,cnpj,segmento,probabilidade,valor_divida,composicao,fat_medio,pi,lambda,impacto_segmento,risco,dscore,peso,score
896,17464661000170,infra,0.583333,4581.31,0.093712,27415.364167,0.111405,0.010440,0.252610,0.147356,596.850920,2,655.478595
939,20124081000149,infra,1.000000,176.84,1.000000,1830.187500,0.064416,0.064416,0.266104,0.266104,513.727202,2,513.727202
754,02306070000106,infra,0.200000,1061.73,0.046720,16531.064167,0.042818,0.002000,0.250500,0.050100,664.929984,2,637.754392
910,20687292000190,infra,1.000000,1190.17,1.000000,20499.032500,0.038707,0.038707,0.259677,0.259677,518.226355,2,518.226355
868,11377065000177,infra,0.888889,3714.19,0.165534,69926.810833,0.035410,0.005862,0.251465,0.223525,543.532637,2,594.722970

In [220]:
dcalc[dcalc['cnpj']=='71673990000177']

,cnpj,segmento,probabilidade,valor_divida,composicao,fat_medio,pi,lambda,impacto_segmento,risco,dscore,peso,score
692,71673990000177,infra,0.136986,33498.08,0.003193,25773475.0,0.000866,0.000003,0.250001,0.034247,676.027331,2,683.871956
693,71673990000177,outros,0.821918,137891.79,0.013143,25773475.0,0.003567,0.000047,0.000012,0.000010,699.993257,1,683.871956
694,71673990000177,processos,0.041096,10320422.53,0.983664,25773475.0,0.266952,0.262591,0.565648,0.023246,683.727940,3,683.871956

In [229]:
df[df['segmento']=='processos'].groupby('cnpj').count().sort_values('segmento', ascending=False).head(10)

                valor  segmento
cnpj
60701190000104     99        99
61365284001186     17        17
03317210000104     11        11
191                10        10
38936787000170      8         8
01927818000117      8         8
60889128000180      5         5
10532480000195      4         4
04501499000171      4         4
27922913000111      3         3

In [231]:
dcalc[dcalc['cnpj']=='10532480000195']

,cnpj,segmento,probabilidade,valor_divida,composicao,fat_medio,pi,lambda,impacto_segmento,risco,dscore,peso,score
383,10532480000195,outros,0.6,3500.04,0.242942,11800.843333,0.197728,0.048036,0.012009,0.007205,694.956170,1,569.249316
384,10532480000195,processos,0.4,10906.86,0.757058,11800.843333,0.616163,0.466471,0.616618,0.246647,527.347031,3,569.249316

In [248]:
dcalc[dcalc['cnpj']=='00661205000118']

,cnpj,segmento,probabilidade,valor_divida,composicao,fat_medio,pi,lambda,impacto_segmento,risco,dscore,peso,score
279,00661205000118,credito,1.0,27496.75,1.0,28635.588333,0.640153,0.640153,0.910038,0.910038,62.973171,4,62.973171

In [249]:
df[df['cnpj']=='00661205000118']

             cnpj     valor segmento
0  00661205000118  27496.75  credito

In [215]:
dcalc.groupby("cnpj").count().sort_values("segmento", ascending=False).head()

,segmento,probabilidade,valor_divida,composicao,fat_medio,pi,lambda,impacto_segmento,risco,dscore,peso,score
cnpj,,,,,,,,,,,,
14534748000189,3,3,3,3,3,3,3,3,3,3,3,3
71673990000177,3,3,3,3,3,3,3,3,3,3,3,3
11296199000163,3,3,3,3,3,3,3,3,3,3,3,3
06102005000101,3,3,3,3,3,3,3,3,3,3,3,3
13231036000128,3,3,3,3,3,3,3,3,3,3,3,3

In [251]:
dcalc[dcalc['cnpj']=='01828181000101']["score"]

730    636.236195
Name: score, dtype: float64

#### Calculo do Score Total

In [256]:
from sqlalchemy import create_engine
engine = create_engine("mysql+pymysql://capMaster:#jackpot123#@captalys.cmrbivuuu7sv.sa-east-1.rds.amazonaws.com:23306/varejo")
con = engine.connect()
dfpv = pd.read_sql("select cpf_cnpj as cnpj, data, valor from fluxo_pv where flag_aprovacao=1", con)
con.close()

In [259]:
dfpv = dfpv[dfpv['cnpj']!='00.000.000/0001-91']

In [262]:
dfpv["cnpj"] = dfpv.apply(lambda x : x['cnpj'].replace(".", "").replace("-", "").replace("/", ""), axis=1)

In [264]:
dfpv['flag_cnpj'] = dfpv.apply(lambda x : int(len(x['cnpj'])==14), axis=1)

In [267]:
dfpv = dfpv[dfpv['flag_cnpj']==1]

In [269]:
dfpv.head()

              cnpj        data    valor  flag_cnpj
16  00066987000147  2017-09-01   574.39          1
17  00066987000147  2017-10-01  1225.11          1
18  00066987000147  2017-11-01  1826.72          1
19  00066987000147  2017-12-01  1771.39          1
20  00066987000147  2018-01-01  2625.87          1

calculando o lscore para a base pv

In [275]:
from pricing.service.scoring.lscore import LScoring

In [272]:
dfpv = dfpv[dfpv['cnpj'].isin(dcalc['cnpj'].tolist())]

In [273]:
dfpv['cnpj'].unique().tolist().__len__()

170

In [276]:
resp = []
for el in dfpv['cnpj'].unique().tolist():
    dt = dfpv[dfpv['cnpj']==el]
    dados = {'dados' : dt[['data', 'valor']].to_dict("records"), "id_produto" : "tomatico"}
    ls = LScoring(dados)
    ret = ls.calcula()
    score = ret['score']
    resp.append(pd.DataFrame({'cnpj' : [el], "lscore" : [score]}))

         data    valor
0  2014-01-01  22686.0
1  2014-02-01  14580.0
2  2014-03-01  10440.0
3  2014-04-01  12240.0
4  2014-05-01   7020.0
5  2014-06-01   4500.0
6  2014-07-01   3630.0
7  2014-08-01   5130.0
8  2014-09-01   4500.0
9  2014-10-01   2850.0
10 2014-11-01    930.0
11 2014-12-01    450.0
12 2015-01-01   1690.0
13 2015-02-01   1720.0
14 2015-03-01   1680.0
15 2015-04-01   4420.0
16 2015-05-01   1760.0
17 2015-06-01   2865.0
18 2015-07-01   6605.0
19 2015-08-01   4035.0
20 2015-09-01   5280.0
21 2015-10-01   3940.0
22 2015-11-01   2940.0
23 2015-12-01    840.0
24 2016-01-01   2380.0
25 2016-02-01   2180.0
26 2016-03-01   5740.0
27 2016-04-01   2365.0
28 2016-05-01    560.0
29 2016-06-01   3284.0
..        ...      ...
33 2016-10-01    960.0
34 2016-11-01   1280.0
35 2016-12-01   1440.0
36 2017-01-01    480.0
37 2017-02-01    480.0
38 2017-03-01    480.0
39 2017-04-01    258.0
40 2017-05-01  10320.0
41 2017-06-01  17028.0
42 2017-07-01  30702.0
43 2017-08-01  25800.0
44 2017-09-01  21930.0
45 2017-10-01  24252.0
46 2017-11-01  29670.0
47 2017-12-01  26832.0
48 2018-01-01  38958.0
49 2018-02-01  30444.0
50 2018-03-01  28896.0
51 2018-04-01  27864.0
52 2018-05-01  18060.0
53 2018-06-01  24252.0
54 2018-07-01  28122.0
55 2018-08-01  28380.0
56 2018-09-01  23994.0
57 2018-10-01  25800.0
58 2018-11-01  22704.0
59 2018-12-01  20640.0
60 2019-01-01  28122.0
61 2019-02-01  30444.0
62 2019-03-01  15222.0

[63 rows x 2 columns]
periodo de elegibilidade : [datetime.date(2018, 10, 1), datetime.date(2018, 11, 1), datetime.date(2018, 12, 1), datetime.date(2019, 1, 1), datetime.date(2019, 2, 1), datetime.date(2019, 3, 1)]
         data    valor
0  2014-01-01  22686.0
1  2014-02-01  14580.0
2  2014-03-01  10440.0
3  2014-04-01  12240.0
4  2014-05-01   7020.0
5  2014-06-01   4500.0
6  2014-07-01   3630.0
7  2014-08-01   5130.0
8  2014-09-01   4500.0
9  2014-10-01   2850.0
10 2014-11-01    930.0
11 2014-12-01    450.0
12 2015-01-01   1690.0
13 2015-02-01   1720.0
14 2015-03-01   1680.0
15 2015-04-01   4420.0
16 2015-05-01   1760.0
17 2015-06-01   2865.0
18 2015-07-01   6605.0
19 2015-08-01   4035.0
20 2015-09-01   5280.0
21 2015-10-01   3940.0
22 2015-11-01   2940.0
23 2015-12-01    840.0
24 2016-01-01   2380.0
25 2016-02-01   2180.0
26 2016-03-01   5740.0
27 2016-04-01   2365.0
28 2016-05-01    560.0
29 2016-06-01   3284.0
..        ...      ...
33 2016-10-01    960.0
34 2016-11-01   1280.0
35 2016-12-01   1440.0
36 2017-01-01    480.0
37 2017-02-01    480.0
38 2017-03-01    480.0
39 2017-04-01    258.0
40 2017-05-01  10320.0
41 2017-06-01  17028.0
42 2017-07-01  30702.0
43 2017-08-01  25800.0
44 2017-09-01  21930.0
45 2017-10-01  24252.0
46 2017-11-01  29670.0
47 2017-12-01  26832.0
48 2018-01-01  38958.0
49 2018-02-01  30444.0
50 2018-03-01  28896.0
51 2018-04-01  27864.0
52 2018-05-01  18060.0
53 2018-06-01  24252.0
54 2018-07-01  28122.0
55 2018-08-01  28380.0
56 2018-09-01  23994.0
57 2018-10-01  25800.0
58 2018-11-01  22704.0
59 2018-12-01  20640.0
60 2019-01-01  28122.0
61 2019-02-01  30444.0
62 2019-03-01  15222.0

[63 rows x 2 columns]
probabilidade_zeros :0.0
score : 688.2606060606059
         data      valor
0  2015-11-01   25969.05
1  2015-12-01   40408.64
2  2016-01-01   59346.17
3  2016-02-01   40789.55
4  2016-03-01   51399.56
5  2016-04-01   47853.91
6  2016-05-01   41531.47
7  2016-06-01   34054.03
8  2016-07-01   52171.47
9  2016-08-01   46747.20
10 2016-09-01   39951.05
11 2016-10-01   34193.10
12 2016-11-01   50730.30
13 2016-12-01   47172.55
14 2017-01-01   70078.58
15 2017-02-01   38043.34
16 2017-03-01   27776.75
17 2017-04-01   43122.15
18 2017-05-01   36463.14
19 2017-06-01   32344.64
20 2017-07-01   34779.44
21 2017-08-01   54086.74
22 2017-09-01   50576.82
23 2017-10-01   64086.44
24 2017-11-01   54579.44
25 2017-12-01   46732.82
26 2018-01-01   53177.56
27 2018-02-01   27224.24
28 2018-03-01   79618.30
29 2018-04-01   96348.87
30 2018-05-01   89758.24
31 2018-06-01   58360.44
32 2018-07-01   53369.11
33 2018-08-01   51039.50
34 2018-09-01   81416.86
35 2018-10-01   61327.84
36 2018-11-01   66754.60
37 2018-12-01   58392.46
38 2019-01-01  113958.42
39 2019-02-01   70632.10
40 2019-03-01   12590.18
periodo de elegibilidade : [datetime.date(2018, 10, 1), datetime.date(2018, 11, 1), datetime.date(2018, 12, 1), datetime.date(2019, 1, 1), datetime.date(2019, 2, 1), datetime.date(2019, 3, 1)]
         data      valor
0  2015-11-01   25969.05
1  2015-12-01   40408.64
2  2016-01-01   59346.17
3  2016-02-01   40789.55
4  2016-03-01   51399.56
5  2016-04-01   47853.91
6  2016-05-01   41531.47
7  2016-06-01   34054.03
8  2016-07-01   52171.47
9  2016-08-01   46747.20
10 2016-09-01   39951.05
11 2016-10-01   34193.10
12 2016-11-01   50730.30
13 2016-12-01   47172.55
14 2017-01-01   70078.58
15 2017-02-01   38043.34
16 2017-03-01   27776.75
17 2017-04-01   43122.15
18 2017-05-01   36463.14
19 2017-06-01   32344.64
20 2017-07-01   34779.44
21 2017-08-01   54086.74
22 2017-09-01   50576.82
23 2017-10-01   64086.44
24 2017-11-01   54579.44
25 2017-12-01   46732.82
26 2018-01-01   53177.56
27 2018-02-01   27224.24
28 2018-03-01   79618.30
29 2018-04-01   96348.87
30 2018-05-01   89758.24
31 2018-06-01   58360.44
32 2018-07-01   53369.11
33 2018-08-01   51039.50
34 2018-09-01   81416.86
35 2018-10-01   61327.84
36 2018-11-01   66754.60
37 2018-12-01   58392.46
38 2019-01-01  113958.42
39 2019-02-01   70632.10
40 2019-03-01   12590.18
probabilidade_zeros :0.0
         data     valor
0  2016-02-01   5354.46
1  2016-03-01   8441.82
2  2016-04-01  19476.38
3  2016-05-01  16097.99
4  2016-06-01   8490.39
5  2016-07-01  18842.78
6  2016-08-01  19981.26
7  2016-09-01  15432.65
8  2016-10-01  24749.31
9  2016-11-01  18300.63
10 2016-12-01  30951.01
11 2017-01-01  25740.12
12 2017-02-01  14703.71
13 2017-03-01  23294.28
14 2017-04-01  13648.64
15 2017-05-01  29043.11
16 2017-06-01  24092.16
17 2017-07-01  20614.23
18 2017-08-01  15355.85
19 2017-09-01  20008.19
20 2017-10-01  14749.24
21 2017-11-01  16583.50
22 2017-12-01  31999.58
23 2018-01-01  26427.03
24 2018-02-01  18519.77
25 2018-03-01  23024.70
26 2018-04-01  24900.22
27 2018-05-01  29102.03
28 2018-06-01  21165.92
29 2018-07-01  27669.70
30 2018-08-01  30532.30
31 2018-09-01  28847.88
32 2018-10-01  24680.45
33 2018-11-01  27381.16
34 2018-12-01  36832.89
35 2019-01-01  32934.69
36 2019-02-01  26287.00
37 2019-03-01  33292.82
periodo de elegibilidade : [datetime.date(2018, 10, 1), datetime.date(2018, 11, 1), datetime.date(2018, 12, 1), datetime.date(2019, 1, 1), datetime.date(2019, 2, 1), datetime.date(2019, 3, 1)]
         data     valor
0  2016-02-01   5354.46
1  2016-03-01   8441.82
2  2016-04-01  19476.38
3  2016-05-01  16097.99
4  2016-06-01   8490.39
5  2016-07-01  18842.78
6  2016-08-01  19981.26
7  2016-09-01  15432.65
8  2016-10-01  24749.31
9  2016-11-01  18300.63
10 2016-12-01  30951.01
11 2017-01-01  25740.12
12 2017-02-01  14703.71
13 2017-03-01  23294.28
14 2017-04-01  13648.64
15 2017-05-01  29043.11
16 2017-06-01  24092.16
17 2017-07-01  20614.23
18 2017-08-01  15355.85
19 2017-09-01  20008.19
20 2017-10-01  14749.24
21 2017-11-01  16583.50
22 2017-12-01  31999.58
23 2018-01-01  26427.03
24 2018-02-01  18519.77
25 2018-03-01  23024.70
26 2018-04-01  24900.22
27 2018-05-01  29102.03
28 2018-06-01  21165.92
29 2018-07-01  27669.70
30 2018-08-01  30532.30
31 2018-09-01  28847.88
32 2018-10-01  24680.45
33 2018-11-01  27381.16
34 2018-12-01  36832.89
35 2019-01-01  32934.69
36 2019-02-01  26287.00
37 2019-03-01  33292.82
probabilidade_zeros :0.0
score : 738.1090909090912
         data     valor
0  2017-05-01   2887.19
1  2017-06-01   6416.81
2  2017-07-01   7689.41
3  2017-08-01  15142.46
4  2017-09-01  10049.51
5  2017-10-01  12791.01
6  2017-11-01  18714.02
7  2017-12-01  11618.55
8  2018-01-01   4665.13
9  2018-02-01   4894.75
10 2018-03-01  15126.58
11 2018-04-01  18277.09
12 2018-05-01   7938.56
13 2018-06-01  17292.75
14 2018-07-01  14908.88
15 2018-08-01  13651.12
16 2018-09-01   8727.51
17 2018-10-01  17017.03
18 2018-11-01  11710.79
19 2018-12-01  14698.24
20 2019-01-01  11296.45
21 2019-02-01   6802.63
22 2019-03-01  21517.14
periodo de elegibilidade : [datetime.date(2018, 10, 1), datetime.date(2018, 11, 1), datetime.date(2018, 12, 1), datetime.date(2019, 1, 1), datetime.date(2019, 2, 1), datetime.date(2019, 3, 1)]
         data     valor
0  2017-05-01   2887.19
1  2017-06-01   6416.81
2  2017-07-01   7689.41
3  2017-08-01  15142.46
4  2017-09-01  10049.51
5  2017-10-01  12791.01
6  2017-11-01  18714.02
7  2017-12-01  11618.55
8  2018-01-01   4665.13
9  2018-02-01   4894.75
10 2018-03-01  15126.58
11 2018-04-01  18277.09
12 2018-05-01   7938.56
13 2018-06-01  17292.75
14 2018-07-01  14908.88
15 2018-08-01  13651.12
16 2018-09-01   8727.51
17 2018-10-01  17017.03
18 2018-11-01  11710.79
19 2018-12-01  14698.24
20 2019-01-01  11296.45
21 2019-02-01   6802.63
22 2019-03-01  21517.14
probabilidade_zeros :0.0

score : 781.218181818182
         data     valor
0  2016-12-01  18130.30
1  2017-01-01  17742.05
2  2017-02-01  23738.17
3  2017-03-01  27591.56
4  2017-04-01  14265.05
5  2017-05-01   6338.16
6  2017-06-01  33177.83
7  2017-07-01  29283.26
8  2017-08-01  26978.15
9  2017-09-01  30216.22
10 2017-10-01  12022.46
11 2017-11-01  17943.90
12 2017-12-01  19994.22
13 2018-01-01  19908.09
14 2018-02-01  15049.58
15 2018-03-01  14197.47
16 2018-04-01   5204.37
17 2018-05-01  16172.65
18 2018-06-01    729.10
19 2018-07-01   2922.09
20 2018-08-01  12970.25
21 2018-09-01  17550.32
22 2018-10-01  17121.10
23 2018-11-01  16467.20
24 2018-12-01  14030.12
25 2019-01-01  24295.21
26 2019-02-01   7588.04
27 2019-03-01   6832.95
periodo de elegibilidade : [datetime.date(2018, 10, 1), datetime.date(2018, 11, 1), datetime.date(2018, 12, 1), datetime.date(2019, 1, 1), datetime.date(2019, 2, 1), datetime.date(2019, 3, 1)]
         data     valor
0  2016-12-01  18130.30
1  2017-01-01  17742.05
2  2017-02-01  23738.17
3  2017-03-01  27591.56
4  2017-04-01  14265.05
5  2017-05-01   6338.16
6  2017-06-01  33177.83
7  2017-07-01  29283.26
8  2017-08-01  26978.15
9  2017-09-01  30216.22
10 2017-10-01  12022.46
11 2017-11-01  17943.90
12 2017-12-01  19994.22
13 2018-01-01  19908.09
14 2018-02-01  15049.58
15 2018-03-01  14197.47
16 2018-04-01   5204.37
17 2018-05-01  16172.65
18 2018-06-01    729.10
19 2018-07-01   2922.09
20 2018-08-01  12970.25
21 2018-09-01  17550.32
22 2018-10-01  17121.10
23 2018-11-01  16467.20
24 2018-12-01  14030.12
25 2019-01-01  24295.21
26 2019-02-01   7588.04
27 2019-03-01   6832.95
probabilidade_zeros :0.08333333333333333
score : 626.230303030303
         data     valor
0  2016-09-01  18998.38
1  2016-10-01  21611.54
2  2016-11-01  28303.81
3  2016-12-01  22135.34
4  2017-01-01  25105.86
5  2017-02-01  22484.02
6  2017-03-01  29418.44
7  2017-04-01   8428.28
8  2017-05-01  26322.18
9  2017-06-01  16679.26
10 2017-07-01  20975.48
11 2017-08-01  25655.52
12 2017-09-01  23881.02
13 2017-10-01  19894.78
14 2017-11-01  22622.80
15 2017-12-01  30398.96
16 2018-01-01  16812.82
17 2018-02-01   5584.42
18 2018-03-01  20036.88
19 2018-04-01  33754.82
20 2018-05-01  53190.96
21 2018-06-01  38557.56
22 2018-07-01  28080.24
23 2018-08-01  38835.76
24 2018-09-01  31225.02
25 2018-10-01  51380.10
26 2018-11-01  44625.42
27 2018-12-01  37707.70
28 2019-01-01  27486.34
29 2019-02-01  24336.26
30 2019-03-01  33552.30
periodo de elegibilidade : [datetime.date(2018, 10, 1), datetime.date(2018, 11, 1), datetime.date(2018, 12, 1), datetime.date(2019, 1, 1), datetime.date(2019, 2, 1), datetime.date(2019, 3, 1)]
         data     valor
0  2016-09-01  18998.38
1  2016-10-01  21611.54
2  2016-11-01  28303.81
3  2016-12-01  22135.34
4  2017-01-01  25105.86
5  2017-02-01  22484.02
6  2017-03-01  29418.44
7  2017-04-01   8428.28
8  2017-05-01  26322.18
9  2017-06-01  16679.26
10 2017-07-01  20975.48
11 2017-08-01  25655.52
12 2017-09-01  23881.02
13 2017-10-01  19894.78
14 2017-11-01  22622.80
15 2017-12-01  30398.96
16 2018-01-01  16812.82
17 2018-02-01   5584.42
18 2018-03-01  20036.88
19 2018-04-01  33754.82
20 2018-05-01  53190.96
21 2018-06-01  38557.56
22 2018-07-01  28080.24
23 2018-08-01  38835.76
24 2018-09-01  31225.02
25 2018-10-01  51380.10
26 2018-11-01  44625.42
27 2018-12-01  37707.70
28 2019-01-01  27486.34
29 2019-02-01  24336.26
30 2019-03-01  33552.30
probabilidade_zeros :0.0
score : 709.7878787878786
         data     valor
0  2018-01-01   8703.22
1  2018-02-01   4803.78
2  2018-03-01      0.00
3  2018-04-01   9457.47
4  2018-05-01   3382.14
5  2018-06-01      0.00
6  2018-07-01   9266.82
7  2018-08-01   4355.48
8  2018-09-01   4857.02
9  2018-10-01   9268.78
10 2018-11-01   4647.14
11 2018-12-01  23922.75
12 2019-01-01  18089.56
13 2019-02-01   4454.12
14 2019-03-01   9035.57
periodo de elegibilidade : [datetime.date(2018, 10, 1), datetime.date(2018, 11, 1), datetime.date(2018, 12, 1), datetime.date(2019, 1, 1), datetime.date(2019, 2, 1), datetime.date(2019, 3, 1)]
         data     valor
0  2018-01-01   8703.22
1  2018-02-01   4803.78
2  2018-03-01      0.00
3  2018-04-01   9457.47
4  2018-05-01   3382.14
5  2018-06-01      0.00
6  2018-07-01   9266.82
7  2018-08-01   4355.48
8  2018-09-01   4857.02
9  2018-10-01   9268.78
10 2018-11-01   4647.14
11 2018-12-01  23922.75
12 2019-01-01  18089.56
13 2019-02-01   4454.12
14 2019-03-01   9035.57
probabilidade_zeros :0.08333333333333333
score : 625.2363636363636
         data     valor
0  2015-10-01   3272.11
1  2015-11-01   3139.64
2  2015-12-01   6921.57
3  2016-01-01  15049.12
4  2016-02-01   9370.00
5  2016-03-01  14307.10
6  2016-04-01  15676.70
7  2016-05-01   6988.20
8  2016-06-01   7757.85
9  2016-07-01  58059.90
10 2016-08-01   5283.35
11 2016-09-01  45222.01
12 2016-10-01  18072.40
13 2016-11-01  14989.50
14 2016-12-01  12072.15
15 2017-01-01  27166.60
16 2017-02-01  25757.30
17 2017-03-01   3698.10
18 2017-04-01  13377.12
19 2017-05-01   7439.02
20 2017-06-01   2191.45
21 2017-07-01   5212.09
22 2017-08-01   9130.67
23 2017-09-01  36726.43
24 2017-10-01  28946.16
25 2017-11-01  32285.38
26 2017-12-01  16590.25
27 2018-01-01  14669.35
28 2018-02-01  15914.89
29 2018-03-01  25002.11
30 2018-04-01  11507.05
31 2018-05-01  38888.96
32 2018-06-01  25854.83
33 2018-07-01  16324.61
34 2018-08-01  36510.39
35 2018-09-01  25327.68
36 2018-10-01  37594.87
37 2018-11-01  25142.88
38 2018-12-01  11275.06
39 2019-01-01  38351.02
40 2019-02-01  19579.64
41 2019-03-01  33716.04
periodo de elegibilidade : [datetime.date(2018, 10, 1), datetime.date(2018, 11, 1), datetime.date(2018, 12, 1), datetime.date(2019, 1, 1), datetime.date(2019, 2, 1), datetime.date(2019, 3, 1)]
         data     valor
0  2015-10-01   3272.11
1  2015-11-01   3139.64
2  2015-12-01   6921.57
3  2016-01-01  15049.12
4  2016-02-01   9370.00
5  2016-03-01  14307.10
6  2016-04-01  15676.70
7  2016-05-01   6988.20
8  2016-06-01   7757.85
9  2016-07-01  58059.90
10 2016-08-01   5283.35
11 2016-09-01  45222.01
12 2016-10-01  18072.40
13 2016-11-01  14989.50
14 2016-12-01  12072.15
15 2017-01-01  27166.60
16 2017-02-01  25757.30
17 2017-03-01   3698.10
18 2017-04-01  13377.12
19 2017-05-01   7439.02
20 2017-06-01   2191.45
21 2017-07-01   5212.09
22 2017-08-01   9130.67
23 2017-09-01  36726.43
24 2017-10-01  28946.16
25 2017-11-01  32285.38
26 2017-12-01  16590.25
27 2018-01-01  14669.35
28 2018-02-01  15914.89
29 2018-03-01  25002.11
30 2018-04-01  11507.05
31 2018-05-01  38888.96
32 2018-06-01  25854.83
33 2018-07-01  16324.61
34 2018-08-01  36510.39
35 2018-09-01  25327.68
36 2018-10-01  37594.87
37 2018-11-01  25142.88
38 2018-12-01  11275.06
39 2019-01-01  38351.02
40 2019-02-01  19579.64
41 2019-03-01  33716.04
probabilidade_zeros :0.0
        data     valor
0 2018-09-01   1402.02
1 2018-10-01   3496.39
2 2018-11-01   7710.68
3 2018-12-01   3080.59
4 2019-01-01   6547.55
5 2019-02-01  11699.30
6 2019-03-01   3796.06
periodo de elegibilidade : [datetime.date(2018, 10, 1), datetime.date(2018, 11, 1), datetime.date(2018, 12, 1), datetime.date(2019, 1, 1), datetime.date(2019, 2, 1), datetime.date(2019, 3, 1)]
        data     valor
0 2018-09-01   1402.02
1 2018-10-01   3496.39
2 2018-11-01   7710.68
3 2018-12-01   3080.59
4 2019-01-01   6547.55
5 2019-02-01  11699.30
6 2019-03-01   3796.06
probabilidade_zeros :0.0
score : 607.1515151515152
         data     valor
0  2016-11-01      2.06
1  2016-12-01   9443.52
2  2017-01-01   1521.59
3  2017-02-01   3437.93
4  2017-03-01   2272.12
5  2017-04-01      0.00
6  2017-05-01    850.67
7  2017-06-01   5582.52
8  2017-07-01   5677.89
9  2017-08-01    231.42
10 2017-09-01    744.45
11 2017-10-01   1195.37
12 2017-11-01   1492.29
13 2017-12-01  20904.55
14 2018-01-01   5373.56
15 2018-02-01   3494.21
16 2018-03-01  12202.03
17 2018-04-01   6741.64
18 2018-05-01   2623.99
19 2018-06-01   6750.49
20 2018-07-01  12396.46
21 2018-08-01   5582.37
22 2018-09-01   9879.86
23 2018-10-01   7539.89
24 2018-11-01   9385.09
25 2018-12-01  13276.64
26 2019-01-01  17786.19
27 2019-02-01  14399.98
28 2019-03-01   7300.26
periodo de elegibilidade : [datetime.date(2018, 10, 1), datetime.date(2018, 11, 1), datetime.date(2018, 12, 1), datetime.date(2019, 1, 1), datetime.date(2019, 2, 1), datetime.date(2019, 3, 1)]
         data     valor
0  2016-11-01      2.06
1  2016-12-01   9443.52
2  2017-01-01   1521.59
3  2017-02-01   3437.93
4  2017-03-01   2272.12
5  2017-04-01      0.00
6  2017-05-01    850.67
7  2017-06-01   5582.52
8  2017-07-01   5677.89
9  2017-08-01    231.42
10 2017-09-01    744.45
11 2017-10-01   1195.37
12 2017-11-01   1492.29
13 2017-12-01  20904.55
14 2018-01-01   5373.56
15 2018-02-01   3494.21
16 2018-03-01  12202.03
17 2018-04-01   6741.64
18 2018-05-01   2623.99
19 2018-06-01   6750.49
20 2018-07-01  12396.46
21 2018-08-01   5582.37
22 2018-09-01   9879.86
23 2018-10-01   7539.89
24 2018-11-01   9385.09
25 2018-12-01  13276.64
26 2019-01-01  17786.19
27 2019-02-01  14399.98
28 2019-03-01   7300.26
probabilidade_zeros :0.0

score : 669.6969696969697
         data     valor
0  2016-12-01   3189.71
1  2017-01-01   7663.48
2  2017-02-01      0.00
3  2017-03-01   4021.77
4  2017-04-01  13125.33
5  2017-05-01   9073.16
6  2017-06-01  14553.89
7  2017-07-01   4485.97
8  2017-08-01   8841.99
9  2017-09-01  10220.09
10 2017-10-01  12636.39
11 2017-11-01   4384.15
12 2017-12-01   5296.24
13 2018-01-01    296.48
14 2018-02-01    938.35
15 2018-03-01   2720.59
16 2018-04-01  18359.54
17 2018-05-01  15507.17
18 2018-06-01  13187.05
19 2018-07-01   8243.73
20 2018-08-01   8900.21
21 2018-09-01  14019.06
22 2018-10-01  15594.36
23 2018-11-01   7001.89
24 2018-12-01  17996.17
25 2019-01-01  11554.34
26 2019-02-01   6440.78
27 2019-03-01   7763.87
periodo de elegibilidade : [datetime.date(2018, 10, 1), datetime.date(2018, 11, 1), datetime.date(2018, 12, 1), datetime.date(2019, 1, 1), datetime.date(2019, 2, 1), datetime.date(2019, 3, 1)]
         data     valor
0  2016-12-01   3189.71
1  2017-01-01   7663.48
2  2017-02-01      0.00
3  2017-03-01   4021.77
4  2017-04-01  13125.33
5  2017-05-01   9073.16
6  2017-06-01  14553.89
7  2017-07-01   4485.97
8  2017-08-01   8841.99
9  2017-09-01  10220.09
10 2017-10-01  12636.39
11 2017-11-01   4384.15
12 2017-12-01   5296.24
13 2018-01-01    296.48
14 2018-02-01    938.35
15 2018-03-01   2720.59
16 2018-04-01  18359.54
17 2018-05-01  15507.17
18 2018-06-01  13187.05
19 2018-07-01   8243.73
20 2018-08-01   8900.21
21 2018-09-01  14019.06
22 2018-10-01  15594.36
23 2018-11-01   7001.89
24 2018-12-01  17996.17
25 2019-01-01  11554.34
26 2019-02-01   6440.78
27 2019-03-01   7763.87
probabilidade_zeros :0.0
        data     valor
0 2018-08-01  13799.95
1 2018-09-01  27602.01
2 2018-10-01  19280.49
3 2018-11-01  20382.78
4 2018-12-01  13402.42
5 2019-01-01  21621.16
6 2019-02-01  23643.12
7 2019-03-01  23248.31
periodo de elegibilidade : [datetime.date(2018, 10, 1), datetime.date(2018, 11, 1), datetime.date(2018, 12, 1), datetime.date(2019, 1, 1), datetime.date(2019, 2, 1), datetime.date(2019, 3, 1)]
        data     valor
0 2018-08-01  13799.95
1 2018-09-01  27602.01
2 2018-10-01  19280.49
3 2018-11-01  20382.78
4 2018-12-01  13402.42
5 2019-01-01  21621.16
6 2019-02-01  23643.12
7 2019-03-01  23248.31
probabilidade_zeros :0.0
score : 734.2931129476583
         data     valor
0  2018-03-01   1742.76
1  2018-04-01  13611.92
2  2018-05-01  13393.98
3  2018-06-01  17363.76
4  2018-07-01  15635.01
5  2018-08-01  27555.05
6  2018-09-01  28551.64
7  2018-10-01  11650.30
8  2018-11-01  13868.52
9  2018-12-01  15926.16
10 2019-01-01  22999.55
11 2019-02-01  14520.50
12 2019-03-01  41612.03
periodo de elegibilidade : [datetime.date(2018, 10, 1), datetime.date(2018, 11, 1), datetime.date(2018, 12, 1), datetime.date(2019, 1, 1), datetime.date(2019, 2, 1), datetime.date(2019, 3, 1)]
         data     valor
0  2018-03-01   1742.76
1  2018-04-01  13611.92
2  2018-05-01  13393.98
3  2018-06-01  17363.76
4  2018-07-01  15635.01
5  2018-08-01  27555.05
6  2018-09-01  28551.64
7  2018-10-01  11650.30
8  2018-11-01  13868.52
9  2018-12-01  15926.16
10 2019-01-01  22999.55
11 2019-02-01  14520.50
12 2019-03-01  41612.03
probabilidade_zeros :0.0
score : 835.3181818181816
         data     valor
0  2018-03-01  16363.15
1  2018-04-01  28201.31
2  2018-05-01  17429.00
3  2018-06-01  23576.61
4  2018-07-01  30476.94
5  2018-08-01  37693.47
6  2018-09-01  45014.25
7  2018-10-01  45684.24
8  2018-11-01  40462.86
9  2018-12-01  48186.13
10 2019-01-01  46948.91
11 2019-02-01  16293.72
12 2019-03-01  18808.40
periodo de elegibilidade : [datetime.date(2018, 10, 1), datetime.date(2018, 11, 1), datetime.date(2018, 12, 1), datetime.date(2019, 1, 1), datetime.date(2019, 2, 1), datetime.date(2019, 3, 1)]
         data     valor
0  2018-03-01  16363.15
1  2018-04-01  28201.31
2  2018-05-01  17429.00
3  2018-06-01  23576.61
4  2018-07-01  30476.94
5  2018-08-01  37693.47
6  2018-09-01  45014.25
7  2018-10-01  45684.24
8  2018-11-01  40462.86
9  2018-12-01  48186.13
10 2019-01-01  46948.91
11 2019-02-01  16293.72
12 2019-03-01  18808.40
probabilidade_zeros :0.0
score : 670.5575757575758
         data     valor
0  2017-11-01      1.04
1  2017-12-01   6960.11
2  2018-01-01   8600.94
3  2018-02-01  22906.34
4  2018-03-01  15898.29
5  2018-04-01  22759.58
6  2018-05-01  30911.46
7  2018-06-01  35116.87
8  2018-07-01  26847.97
9  2018-08-01  32273.87
10 2018-09-01  26616.73
11 2018-10-01  24076.38
12 2018-11-01  39910.08
13 2018-12-01  26977.51
14 2019-01-01  27288.48
15 2019-02-01  21241.34
16 2019-03-01  33630.61
periodo de elegibilidade : [datetime.date(2018, 10, 1), datetime.date(2018, 11, 1), datetime.date(2018, 12, 1), datetime.date(2019, 1, 1), datetime.date(2019, 2, 1), datetime.date(2019, 3, 1)]
         data     valor
0  2017-11-01      1.04
1  2017-12-01   6960.11
2  2018-01-01   8600.94
3  2018-02-01  22906.34
4  2018-03-01  15898.29
5  2018-04-01  22759.58
6  2018-05-01  30911.46
7  2018-06-01  35116.87
8  2018-07-01  26847.97
9  2018-08-01  32273.87
10 2018-09-01  26616.73
11 2018-10-01  24076.38
12 2018-11-01  39910.08
13 2018-12-01  26977.51
14 2019-01-01  27288.48
15 2019-02-01  21241.34
16 2019-03-01  33630.61
probabilidade_zeros :0.0
score : 728.9606060606061
         data     valor
0  2016-02-01   9229.75
1  2016-03-01  38095.38
2  2016-04-01  38938.26
3  2016-05-01  36396.82
4  2016-06-01  62266.27
5  2016-07-01  66750.92
6  2016-08-01  60615.61
7  2016-09-01  41787.58
8  2016-10-01  58975.55
9  2016-11-01  42759.18
10 2016-12-01  71770.77
11 2017-01-01  40751.28
12 2017-02-01  52709.16
13 2017-03-01  47773.45
14 2017-04-01  43072.07
15 2017-05-01  58503.23
16 2017-06-01  39417.70
17 2017-07-01  33166.36
18 2017-08-01  30572.45
19 2017-09-01  42889.68
20 2017-10-01  35641.40
21 2017-11-01  22395.01
22 2017-12-01  66373.76
23 2018-01-01  46009.93
24 2018-02-01  48484.41
25 2018-03-01  66138.94
26 2018-04-01  57322.62
27 2018-05-01  82583.75
28 2018-06-01  40926.12
29 2018-07-01  41290.98
30 2018-08-01  53824.32
31 2018-09-01  60848.93
32 2018-10-01  53634.39
33 2018-11-01  51825.00
34 2018-12-01  57078.08
35 2019-01-01  74415.76
36 2019-02-01  57697.27
37 2019-03-01  50679.80
periodo de elegibilidade : [datetime.date(2018, 10, 1), datetime.date(2018, 11, 1), datetime.date(2018, 12, 1), datetime.date(2019, 1, 1), datetime.date(2019, 2, 1), datetime.date(2019, 3, 1)]
         data     valor
0  2016-02-01   9229.75
1  2016-03-01  38095.38
2  2016-04-01  38938.26
3  2016-05-01  36396.82
4  2016-06-01  62266.27
5  2016-07-01  66750.92
6  2016-08-01  60615.61
7  2016-09-01  41787.58
8  2016-10-01  58975.55
9  2016-11-01  42759.18
10 2016-12-01  71770.77
11 2017-01-01  40751.28
12 2017-02-01  52709.16
13 2017-03-01  47773.45
14 2017-04-01  43072.07
15 2017-05-01  58503.23
16 2017-06-01  39417.70
17 2017-07-01  33166.36
18 2017-08-01  30572.45
19 2017-09-01  42889.68
20 2017-10-01  35641.40
21 2017-11-01  22395.01
22 2017-12-01  66373.76
23 2018-01-01  46009.93
24 2018-02-01  48484.41
25 2018-03-01  66138.94
26 2018-04-01  57322.62
27 2018-05-01  82583.75
28 2018-06-01  40926.12
29 2018-07-01  41290.98
30 2018-08-01  53824.32
31 2018-09-01  60848.93
32 2018-10-01  53634.39
33 2018-11-01  51825.00
34 2018-12-01  57078.08
35 2019-01-01  74415.76
36 2019-02-01  57697.27
37 2019-03-01  50679.80
probabilidade_zeros :0.0
        data     valor
0 2018-09-01  44018.26
1 2018-10-01  42672.13
2 2018-11-01  40315.01
3 2018-12-01  44744.41
4 2019-01-01  72516.19
5 2019-02-01  61892.22
6 2019-03-01  62085.50
periodo de elegibilidade : [datetime.date(2018, 10, 1), datetime.date(2018, 11, 1), datetime.date(2018, 12, 1), datetime.date(2019, 1, 1), datetime.date(2019, 2, 1), datetime.date(2019, 3, 1)]
        data     valor
0 2018-09-01  44018.26
1 2018-10-01  42672.13
2 2018-11-01  40315.01
3 2018-12-01  44744.41
4 2019-01-01  72516.19
5 2019-02-01  61892.22
6 2019-03-01  62085.50
probabilidade_zeros :0.0
score : 799.4038961038963
         data     valor
0  2015-11-01   5494.50
1  2015-12-01   7466.35
2  2016-01-01  29596.35
3  2016-02-01  24629.40
4  2016-03-01  30094.65
5  2016-04-01  16953.50
6  2016-05-01  21416.15
7  2016-06-01  33137.20
8  2016-07-01  42740.35
9  2016-08-01  38270.50
10 2016-09-01  29324.38
11 2016-10-01  25762.09
12 2016-11-01  24344.61
13 2016-12-01  32738.38
14 2017-01-01  37618.86
15 2017-02-01  19780.84
16 2017-03-01   8485.55
17 2017-04-01  18829.92
18 2017-05-01  42033.25
19 2017-06-01  27425.95
20 2017-07-01  45147.09
21 2017-08-01  51180.99
22 2017-09-01  45243.43
23 2017-10-01  37174.57
24 2017-11-01  52446.03
25 2017-12-01  42129.65
26 2018-01-01  54745.43
27 2018-02-01  34956.05
28 2018-03-01  63321.60
29 2018-04-01  54050.14
30 2018-05-01  42435.40
31 2018-06-01  53448.08
32 2018-07-01  52687.72
33 2018-08-01  41296.57
34 2018-09-01  50115.16
35 2018-10-01  45144.22
36 2018-11-01  65980.91
37 2018-12-01  42279.98
38 2019-01-01  74083.82
39 2019-02-01  69604.68
40 2019-03-01   3191.92
periodo de elegibilidade : [datetime.date(2018, 10, 1), datetime.date(2018, 11, 1), datetime.date(2018, 12, 1), datetime.date(2019, 1, 1), datetime.date(2019, 2, 1), datetime.date(2019, 3, 1)]
         data     valor
0  2015-11-01   5494.50
1  2015-12-01   7466.35
2  2016-01-01  29596.35
3  2016-02-01  24629.40
4  2016-03-01  30094.65
5  2016-04-01  16953.50
6  2016-05-01  21416.15
7  2016-06-01  33137.20
8  2016-07-01  42740.35
9  2016-08-01  38270.50
10 2016-09-01  29324.38
11 2016-10-01  25762.09
12 2016-11-01  24344.61
13 2016-12-01  32738.38
14 2017-01-01  37618.86
15 2017-02-01  19780.84
16 2017-03-01   8485.55
17 2017-04-01  18829.92
18 2017-05-01  42033.25
19 2017-06-01  27425.95
20 2017-07-01  45147.09
21 2017-08-01  51180.99
22 2017-09-01  45243.43
23 2017-10-01  37174.57
24 2017-11-01  52446.03
25 2017-12-01  42129.65
26 2018-01-01  54745.43
27 2018-02-01  34956.05
28 2018-03-01  63321.60
29 2018-04-01  54050.14
30 2018-05-01  42435.40
31 2018-06-01  53448.08
32 2018-07-01  52687.72
33 2018-08-01  41296.57
34 2018-09-01  50115.16
35 2018-10-01  45144.22
36 2018-11-01  65980.91
37 2018-12-01  42279.98
38 2019-01-01  74083.82
39 2019-02-01  69604.68
40 2019-03-01   3191.92
probabilidade_zeros :0.0

score : 444.2457912457914
         data     valor
0  2015-11-01   4495.50
1  2015-12-01   8781.75
2  2016-01-01  15850.00
3  2016-02-01  13094.05
4  2016-03-01  10825.00
5  2016-04-01  17532.00
6  2016-05-01  20529.55
7  2016-06-01  18341.80
8  2016-07-01  25779.75
9  2016-08-01  21840.05
10 2016-09-01  33041.16
11 2016-10-01  43582.33
12 2016-11-01  28926.75
13 2016-12-01  19622.85
14 2017-01-01  21328.50
15 2017-02-01  28453.20
16 2017-03-01  15714.60
17 2017-04-01  38060.00
18 2017-05-01  12948.81
19 2017-06-01  30951.12
20 2017-07-01  29423.38
21 2017-08-01  30688.74
22 2017-09-01  31498.94
23 2017-10-01  25208.76
24 2017-11-01  33205.00
25 2017-12-01  29420.79
26 2018-01-01  34874.55
27 2018-02-01  37044.69
28 2018-03-01  52374.11
29 2018-04-01  33355.72
30 2018-05-01  32345.26
31 2018-06-01  33772.14
32 2018-07-01  45830.51
33 2018-08-01  46138.46
34 2018-09-01  43206.50
35 2018-10-01  33007.36
36 2018-11-01  35966.01
37 2018-12-01  41508.05
38 2019-01-01  29857.96
39 2019-02-01  22286.06
40 2019-03-01   3587.14
periodo de elegibilidade : [datetime.date(2018, 10, 1), datetime.date(2018, 11, 1), datetime.date(2018, 12, 1), datetime.date(2019, 1, 1), datetime.date(2019, 2, 1), datetime.date(2019, 3, 1)]
         data     valor
0  2015-11-01   4495.50
1  2015-12-01   8781.75
2  2016-01-01  15850.00
3  2016-02-01  13094.05
4  2016-03-01  10825.00
5  2016-04-01  17532.00
6  2016-05-01  20529.55
7  2016-06-01  18341.80
8  2016-07-01  25779.75
9  2016-08-01  21840.05
10 2016-09-01  33041.16
11 2016-10-01  43582.33
12 2016-11-01  28926.75
13 2016-12-01  19622.85
14 2017-01-01  21328.50
15 2017-02-01  28453.20
16 2017-03-01  15714.60
17 2017-04-01  38060.00
18 2017-05-01  12948.81
19 2017-06-01  30951.12
20 2017-07-01  29423.38
21 2017-08-01  30688.74
22 2017-09-01  31498.94
23 2017-10-01  25208.76
24 2017-11-01  33205.00
25 2017-12-01  29420.79
26 2018-01-01  34874.55
27 2018-02-01  37044.69
28 2018-03-01  52374.11
29 2018-04-01  33355.72
30 2018-05-01  32345.26
31 2018-06-01  33772.14
32 2018-07-01  45830.51
33 2018-08-01  46138.46
34 2018-09-01  43206.50
35 2018-10-01  33007.36
36 2018-11-01  35966.01
37 2018-12-01  41508.05
38 2019-01-01  29857.96
39 2019-02-01  22286.06
40 2019-03-01   3587.14
probabilidade_zeros :0.0
score : 481.5824915824915
         data     valor
0  2018-03-01    354.14
1  2018-04-01   2507.34
2  2018-05-01  15960.08
3  2018-06-01  17336.88
4  2018-07-01  25136.08
5  2018-08-01  24855.76
6  2018-09-01  18592.26
7  2018-10-01  16260.46
8  2018-11-01  23600.54
9  2018-12-01  15757.18
10 2019-01-01  16904.07
11 2019-02-01  14221.05
12 2019-03-01  13448.81
periodo de elegibilidade : [datetime.date(2018, 10, 1), datetime.date(2018, 11, 1), datetime.date(2018, 12, 1), datetime.date(2019, 1, 1), datetime.date(2019, 2, 1), datetime.date(2019, 3, 1)]
         data     valor
0  2018-03-01    354.14
1  2018-04-01   2507.34
2  2018-05-01  15960.08
3  2018-06-01  17336.88
4  2018-07-01  25136.08
5  2018-08-01  24855.76
6  2018-09-01  18592.26
7  2018-10-01  16260.46
8  2018-11-01  23600.54
9  2018-12-01  15757.18
10 2019-01-01  16904.07
11 2019-02-01  14221.05
12 2019-03-01  13448.81
probabilidade_zeros :0.0
score : 689.7090909090908
         data     valor
0  2015-11-01   9473.09
1  2015-12-01  22904.59
2  2016-01-01  23896.23
3  2016-02-01  16187.82
4  2016-03-01  33639.37
5  2016-04-01  18311.80
6  2016-05-01  14201.85
7  2016-06-01  23113.70
8  2016-07-01  19691.90
9  2016-08-01  29508.25
10 2016-09-01  22772.41
11 2016-10-01  16126.87
12 2016-11-01  13919.25
13 2016-12-01  34565.64
14 2017-01-01  19307.98
15 2017-02-01  16234.47
16 2017-03-01  26815.39
17 2017-04-01  12328.28
18 2017-05-01  25301.21
19 2017-06-01  25137.24
20 2017-07-01  28080.48
21 2017-08-01  22381.32
22 2017-09-01  16541.25
23 2017-10-01  29065.56
24 2017-11-01  32217.12
25 2017-12-01  41726.66
26 2018-01-01  58866.39
27 2018-02-01  29934.23
28 2018-03-01  30795.89
29 2018-04-01  30781.01
30 2018-05-01  23226.29
31 2018-06-01  24043.31
32 2018-07-01  35214.58
33 2018-08-01  44227.20
34 2018-09-01  26473.90
35 2018-10-01  34585.67
36 2018-11-01  58035.24
37 2018-12-01  43771.00
38 2019-01-01  87621.87
39 2019-02-01  39241.02
40 2019-03-01   4194.92
periodo de elegibilidade : [datetime.date(2018, 10, 1), datetime.date(2018, 11, 1), datetime.date(2018, 12, 1), datetime.date(2019, 1, 1), datetime.date(2019, 2, 1), datetime.date(2019, 3, 1)]
         data     valor
0  2015-11-01   9473.09
1  2015-12-01  22904.59
2  2016-01-01  23896.23
3  2016-02-01  16187.82
4  2016-03-01  33639.37
5  2016-04-01  18311.80
6  2016-05-01  14201.85
7  2016-06-01  23113.70
8  2016-07-01  19691.90
9  2016-08-01  29508.25
10 2016-09-01  22772.41
11 2016-10-01  16126.87
12 2016-11-01  13919.25
13 2016-12-01  34565.64
14 2017-01-01  19307.98
15 2017-02-01  16234.47
16 2017-03-01  26815.39
17 2017-04-01  12328.28
18 2017-05-01  25301.21
19 2017-06-01  25137.24
20 2017-07-01  28080.48
21 2017-08-01  22381.32
22 2017-09-01  16541.25
23 2017-10-01  29065.56
24 2017-11-01  32217.12
25 2017-12-01  41726.66
26 2018-01-01  58866.39
27 2018-02-01  29934.23
28 2018-03-01  30795.89
29 2018-04-01  30781.01
30 2018-05-01  23226.29
31 2018-06-01  24043.31
32 2018-07-01  35214.58
33 2018-08-01  44227.20
34 2018-09-01  26473.90
35 2018-10-01  34585.67
36 2018-11-01  58035.24
37 2018-12-01  43771.00
38 2019-01-01  87621.87
39 2019-02-01  39241.02
40 2019-03-01   4194.92
probabilidade_zeros :0.0
         data      valor
0  2015-11-01    9154.80
1  2015-12-01   20582.05
2  2016-01-01   25261.00
3  2016-02-01   23804.75
4  2016-03-01   27926.05
5  2016-04-01   13604.40
6  2016-05-01   18187.85
7  2016-06-01   42911.59
8  2016-07-01   46260.77
9  2016-08-01   74116.80
10 2016-09-01   72374.73
11 2016-10-01   12380.40
12 2016-11-01   22900.65
13 2016-12-01  151206.45
14 2017-01-01   31343.46
15 2017-02-01   25157.61
16 2017-03-01   31406.90
17 2017-04-01   17390.34
18 2017-05-01   13023.10
19 2017-06-01   29874.61
20 2017-07-01   68357.13
21 2017-08-01   40614.55
22 2017-09-01   62711.29
23 2017-10-01   28764.13
24 2017-11-01   28658.22
25 2017-12-01   42153.51
26 2018-01-01   26520.63
27 2018-02-01   45756.44
28 2018-03-01   43036.87
29 2018-04-01   25950.63
30 2018-05-01   73178.50
31 2018-06-01   60984.24
32 2018-07-01   55671.45
33 2018-08-01   77552.04
34 2018-09-01   39086.64
35 2018-10-01   40765.06
36 2018-11-01   51900.25
37 2018-12-01   82492.15
38 2019-01-01   69840.39
39 2019-02-01   46885.88
40 2019-03-01   40760.90
periodo de elegibilidade : [datetime.date(2018, 10, 1), datetime.date(2018, 11, 1), datetime.date(2018, 12, 1), datetime.date(2019, 1, 1), datetime.date(2019, 2, 1), datetime.date(2019, 3, 1)]
         data      valor
0  2015-11-01    9154.80
1  2015-12-01   20582.05
2  2016-01-01   25261.00
3  2016-02-01   23804.75
4  2016-03-01   27926.05
5  2016-04-01   13604.40
6  2016-05-01   18187.85
7  2016-06-01   42911.59
8  2016-07-01   46260.77
9  2016-08-01   74116.80
10 2016-09-01   72374.73
11 2016-10-01   12380.40
12 2016-11-01   22900.65
13 2016-12-01  151206.45
14 2017-01-01   31343.46
15 2017-02-01   25157.61
16 2017-03-01   31406.90
17 2017-04-01   17390.34
18 2017-05-01   13023.10
19 2017-06-01   29874.61
20 2017-07-01   68357.13
21 2017-08-01   40614.55
22 2017-09-01   62711.29
23 2017-10-01   28764.13
24 2017-11-01   28658.22
25 2017-12-01   42153.51
26 2018-01-01   26520.63
27 2018-02-01   45756.44
28 2018-03-01   43036.87
29 2018-04-01   25950.63
30 2018-05-01   73178.50
31 2018-06-01   60984.24
32 2018-07-01   55671.45
33 2018-08-01   77552.04
34 2018-09-01   39086.64
35 2018-10-01   40765.06
36 2018-11-01   51900.25
37 2018-12-01   82492.15
38 2019-01-01   69840.39
39 2019-02-01   46885.88
40 2019-03-01   40760.90
probabilidade_zeros :0.0
         data     valor
0  2017-08-01   8025.20
1  2017-09-01   6191.31
2  2017-10-01  15015.52
3  2017-11-01  29597.08
4  2017-12-01   5133.41
5  2018-01-01  17395.40
6  2018-02-01   2426.65
7  2018-03-01  20021.30
8  2018-04-01   2158.98
9  2018-05-01  13201.43
10 2018-06-01  16045.67
11 2018-07-01   3374.80
12 2018-08-01   4747.97
13 2018-09-01  21230.95
14 2018-10-01   4501.78
15 2018-11-01   7490.19
16 2018-12-01  12743.88
17 2019-01-01  14569.60
18 2019-02-01  29167.10
19 2019-03-01  33821.89
periodo de elegibilidade : [datetime.date(2018, 10, 1), datetime.date(2018, 11, 1), datetime.date(2018, 12, 1), datetime.date(2019, 1, 1), datetime.date(2019, 2, 1), datetime.date(2019, 3, 1)]
         data     valor
0  2017-08-01   8025.20
1  2017-09-01   6191.31
2  2017-10-01  15015.52
3  2017-11-01  29597.08
4  2017-12-01   5133.41
5  2018-01-01  17395.40
6  2018-02-01   2426.65
7  2018-03-01  20021.30
8  2018-04-01   2158.98
9  2018-05-01  13201.43
10 2018-06-01  16045.67
11 2018-07-01   3374.80
12 2018-08-01   4747.97
13 2018-09-01  21230.95
14 2018-10-01   4501.78
15 2018-11-01   7490.19
16 2018-12-01  12743.88
17 2019-01-01  14569.60
18 2019-02-01  29167.10
19 2019-03-01  33821.89
probabilidade_zeros :0.0

score : 822.8060606060604
        data     valor
0 2018-10-01  14792.22
1 2018-11-01  16149.57
2 2018-12-01   3289.33
3 2019-01-01   5993.27
4 2019-02-01  13225.84
5 2019-03-01  10929.36
periodo de elegibilidade : [datetime.date(2018, 10, 1), datetime.date(2018, 11, 1), datetime.date(2018, 12, 1), datetime.date(2019, 1, 1), datetime.date(2019, 2, 1), datetime.date(2019, 3, 1)]
        data     valor
0 2018-10-01  14792.22
1 2018-11-01  16149.57
2 2018-12-01   3289.33
3 2019-01-01   5993.27
4 2019-02-01  13225.84
5 2019-03-01  10929.36
probabilidade_zeros :0.0
score : 720.5939393939394
         data     valor
0  2015-11-01  10561.51
1  2015-12-01  23005.05
2  2016-01-01  23875.74
3  2016-02-01  27645.75
4  2016-03-01  24165.26
5  2016-04-01  14809.23
6  2016-05-01  19691.55
7  2016-06-01  27171.40
8  2016-07-01  24269.50
9  2016-08-01  40031.45
10 2016-09-01  33423.49
11 2016-10-01  28614.39
12 2016-11-01  33570.95
13 2016-12-01  32823.80
14 2017-01-01  35989.30
15 2017-02-01  15955.80
16 2017-03-01  23839.49
17 2017-04-01  36658.28
18 2017-05-01  46935.60
19 2017-06-01  44417.89
20 2017-07-01  50532.67
21 2017-08-01  44883.93
22 2017-09-01  55039.00
23 2017-10-01  57930.19
24 2017-11-01  44144.20
25 2017-12-01  40195.83
26 2018-01-01  51332.47
27 2018-02-01  35814.28
28 2018-03-01  67071.12
29 2018-04-01  54290.19
30 2018-05-01  65360.66
31 2018-06-01  42212.31
32 2018-07-01  46144.39
33 2018-08-01  81732.59
34 2018-09-01  73106.02
35 2018-10-01  58325.67
36 2018-11-01  64638.84
37 2018-12-01  50806.62
38 2019-01-01  79711.32
39 2019-02-01  67835.86
40 2019-03-01  58842.66
periodo de elegibilidade : [datetime.date(2018, 10, 1), datetime.date(2018, 11, 1), datetime.date(2018, 12, 1), datetime.date(2019, 1, 1), datetime.date(2019, 2, 1), datetime.date(2019, 3, 1)]
         data     valor
0  2015-11-01  10561.51
1  2015-12-01  23005.05
2  2016-01-01  23875.74
3  2016-02-01  27645.75
4  2016-03-01  24165.26
5  2016-04-01  14809.23
6  2016-05-01  19691.55
7  2016-06-01  27171.40
8  2016-07-01  24269.50
9  2016-08-01  40031.45
10 2016-09-01  33423.49
11 2016-10-01  28614.39
12 2016-11-01  33570.95
13 2016-12-01  32823.80
14 2017-01-01  35989.30
15 2017-02-01  15955.80
16 2017-03-01  23839.49
17 2017-04-01  36658.28
18 2017-05-01  46935.60
19 2017-06-01  44417.89
20 2017-07-01  50532.67
21 2017-08-01  44883.93
22 2017-09-01  55039.00
23 2017-10-01  57930.19
24 2017-11-01  44144.20
25 2017-12-01  40195.83
26 2018-01-01  51332.47
27 2018-02-01  35814.28
28 2018-03-01  67071.12
29 2018-04-01  54290.19
30 2018-05-01  65360.66
31 2018-06-01  42212.31
32 2018-07-01  46144.39
33 2018-08-01  81732.59
34 2018-09-01  73106.02
35 2018-10-01  58325.67
36 2018-11-01  64638.84
37 2018-12-01  50806.62
38 2019-01-01  79711.32
39 2019-02-01  67835.86
40 2019-03-01  58842.66
probabilidade_zeros :0.0
score : 747.5272727272728
         data     valor
0  2015-11-01    249.75
1  2015-12-01   2497.50
2  2016-01-01  18801.13
3  2016-02-01  18529.23
4  2016-03-01  14318.80
5  2016-04-01  14299.30
6  2016-05-01  16837.85
7  2016-06-01  17551.30
8  2016-07-01  33629.55
9  2016-08-01  35083.35
10 2016-09-01  49566.36
11 2016-10-01  36433.00
12 2016-11-01  25209.95
13 2016-12-01  16292.55
14 2017-01-01  28711.90
15 2017-02-01  20677.00
16 2017-03-01  13501.85
17 2017-04-01  24576.99
18 2017-05-01  64082.71
19 2017-06-01  49115.98
20 2017-07-01  27698.48
21 2017-08-01  36784.17
22 2017-09-01  29071.17
23 2017-10-01  36953.38
24 2017-11-01  27660.77
25 2017-12-01  25050.06
26 2018-01-01  50434.94
27 2018-02-01  23116.45
28 2018-03-01  15207.12
29 2018-04-01  34571.23
30 2018-05-01  27532.29
31 2018-06-01  36901.84
32 2018-07-01  28561.88
33 2018-08-01  33150.74
34 2018-09-01  56486.36
35 2018-10-01  32178.08
36 2018-11-01  58027.30
37 2018-12-01  27855.28
38 2019-01-01  66809.92
39 2019-02-01  33556.76
40 2019-03-01  24902.64
periodo de elegibilidade : [datetime.date(2018, 10, 1), datetime.date(2018, 11, 1), datetime.date(2018, 12, 1), datetime.date(2019, 1, 1), datetime.date(2019, 2, 1), datetime.date(2019, 3, 1)]
         data     valor
0  2015-11-01    249.75
1  2015-12-01   2497.50
2  2016-01-01  18801.13
3  2016-02-01  18529.23
4  2016-03-01  14318.80
5  2016-04-01  14299.30
6  2016-05-01  16837.85
7  2016-06-01  17551.30
8  2016-07-01  33629.55
9  2016-08-01  35083.35
10 2016-09-01  49566.36
11 2016-10-01  36433.00
12 2016-11-01  25209.95
13 2016-12-01  16292.55
14 2017-01-01  28711.90
15 2017-02-01  20677.00
16 2017-03-01  13501.85
17 2017-04-01  24576.99
18 2017-05-01  64082.71
19 2017-06-01  49115.98
20 2017-07-01  27698.48
21 2017-08-01  36784.17
22 2017-09-01  29071.17
23 2017-10-01  36953.38
24 2017-11-01  27660.77
25 2017-12-01  25050.06
26 2018-01-01  50434.94
27 2018-02-01  23116.45
28 2018-03-01  15207.12
29 2018-04-01  34571.23
30 2018-05-01  27532.29
31 2018-06-01  36901.84
32 2018-07-01  28561.88
33 2018-08-01  33150.74
34 2018-09-01  56486.36
35 2018-10-01  32178.08
36 2018-11-01  58027.30
37 2018-12-01  27855.28
38 2019-01-01  66809.92
39 2019-02-01  33556.76
40 2019-03-01  24902.64
probabilidade_zeros :0.0
         data     valor
0  2017-08-01   1420.26
1  2017-09-01      0.00
2  2017-10-01      0.00
3  2017-11-01      0.00
4  2017-12-01      0.00
5  2018-01-01      0.00
6  2018-02-01      0.00
7  2018-03-01      0.00
8  2018-04-01      0.00
9  2018-05-01      0.00
10 2018-06-01      0.00
11 2018-07-01      0.00
12 2018-08-01      0.00
13 2018-09-01  40030.46
14 2018-10-01  43729.20
15 2018-11-01  57498.50
16 2018-12-01  42765.51
17 2019-01-01  60448.39
18 2019-02-01  38673.95
19 2019-03-01  61225.99
periodo de elegibilidade : [datetime.date(2018, 10, 1), datetime.date(2018, 11, 1), datetime.date(2018, 12, 1), datetime.date(2019, 1, 1), datetime.date(2019, 2, 1), datetime.date(2019, 3, 1)]
         data     valor
0  2017-08-01   1420.26
1  2017-09-01      0.00
2  2017-10-01      0.00
3  2017-11-01      0.00
4  2017-12-01      0.00
5  2018-01-01      0.00
6  2018-02-01      0.00
7  2018-03-01      0.00
8  2018-04-01      0.00
9  2018-05-01      0.00
10 2018-06-01      0.00
11 2018-07-01      0.00
12 2018-08-01      0.00
13 2018-09-01  40030.46
14 2018-10-01  43729.20
15 2018-11-01  57498.50
16 2018-12-01  42765.51
17 2019-01-01  60448.39
18 2019-02-01  38673.95
19 2019-03-01  61225.99
probabilidade_zeros :0.4166666666666667
score : 745.7393939393942
         data     valor
0  2015-11-01    499.50
1  2015-12-01   8150.45
2  2016-01-01  16783.65
3  2016-02-01  18031.60
4  2016-03-01  13386.80
5  2016-04-01  16781.90
6  2016-05-01  17737.30
7  2016-06-01  23852.70
8  2016-07-01  28094.60
9  2016-08-01  27604.05
10 2016-09-01  15789.07
11 2016-10-01  28170.02
12 2016-11-01  24622.20
13 2016-12-01  23312.75
14 2017-01-01  29663.95
15 2017-02-01  17701.85
16 2017-03-01   8655.23
17 2017-04-01  16853.26
18 2017-05-01  33909.35
19 2017-06-01  19236.23
20 2017-07-01  29900.32
21 2017-08-01   5482.32
22 2017-09-01  14608.91
23 2017-10-01  20513.07
24 2017-11-01  28119.68
25 2017-12-01  17489.14
26 2018-01-01  25479.55
27 2018-02-01  26202.87
28 2018-03-01  48363.94
29 2018-04-01   6498.18
30 2018-05-01  36094.28
31 2018-06-01  14504.21
32 2018-07-01  16913.56
33 2018-08-01   9747.16
34 2018-09-01   4345.38
35 2018-10-01   3035.32
36 2018-11-01   1596.92
37 2018-12-01   1680.38
38 2019-01-01  19697.86
39 2019-02-01  36658.06
40 2019-03-01  23356.52
periodo de elegibilidade : [datetime.date(2018, 10, 1), datetime.date(2018, 11, 1), datetime.date(2018, 12, 1), datetime.date(2019, 1, 1), datetime.date(2019, 2, 1), datetime.date(2019, 3, 1)]
         data     valor
0  2015-11-01    499.50
1  2015-12-01   8150.45
2  2016-01-01  16783.65
3  2016-02-01  18031.60
4  2016-03-01  13386.80
5  2016-04-01  16781.90
6  2016-05-01  17737.30
7  2016-06-01  23852.70
8  2016-07-01  28094.60
9  2016-08-01  27604.05
10 2016-09-01  15789.07
11 2016-10-01  28170.02
12 2016-11-01  24622.20
13 2016-12-01  23312.75
14 2017-01-01  29663.95
15 2017-02-01  17701.85
16 2017-03-01   8655.23
17 2017-04-01  16853.26
18 2017-05-01  33909.35
19 2017-06-01  19236.23
20 2017-07-01  29900.32
21 2017-08-01   5482.32
22 2017-09-01  14608.91
23 2017-10-01  20513.07
24 2017-11-01  28119.68
25 2017-12-01  17489.14
26 2018-01-01  25479.55
27 2018-02-01  26202.87
28 2018-03-01  48363.94
29 2018-04-01   6498.18
30 2018-05-01  36094.28
31 2018-06-01  14504.21
32 2018-07-01  16913.56
33 2018-08-01   9747.16
34 2018-09-01   4345.38
35 2018-10-01   3035.32
36 2018-11-01   1596.92
37 2018-12-01   1680.38
38 2019-01-01  19697.86
39 2019-02-01  36658.06
40 2019-03-01  23356.52
probabilidade_zeros :0.0

         data     valor
0  2015-11-01    249.75
1  2015-12-01   4297.25
2  2016-01-01   5146.00
3  2016-02-01   1985.15
4  2016-03-01   4657.25
5  2016-04-01   8713.20
6  2016-05-01   8981.80
7  2016-06-01   4163.15
8  2016-07-01  25546.55
9  2016-08-01  26798.45
10 2016-09-01  26363.62
11 2016-10-01  43237.77
12 2016-11-01  15419.38
13 2016-12-01  22731.75
14 2017-01-01  19421.35
15 2017-02-01  12572.25
16 2017-03-01  10887.30
17 2017-04-01  16054.44
18 2017-05-01  19211.70
19 2017-06-01  21812.60
20 2017-07-01  47263.14
21 2017-08-01  36490.65
22 2017-09-01  36698.89
23 2017-10-01  30289.76
24 2017-11-01  33987.07
25 2017-12-01  39807.01
26 2018-01-01  45709.12
27 2018-02-01  33883.73
28 2018-03-01  46735.89
29 2018-04-01  24777.69
30 2018-05-01  34512.03
31 2018-06-01  25697.76
32 2018-07-01  56797.70
33 2018-08-01  18556.78
34 2018-09-01  32353.75
35 2018-10-01  30441.52
36 2018-11-01  30159.58
37 2018-12-01  27710.00
38 2019-01-01  46040.03
39 2019-02-01  16178.66
40 2019-03-01    520.00
periodo de elegibilidade : [datetime.date(2018, 10, 1), datetime.date(2018, 11, 1), datetime.date(2018, 12, 1), datetime.date(2019, 1, 1), datetime.date(2019, 2, 1), datetime.date(2019, 3, 1)]
         data     valor
0  2015-11-01    249.75
1  2015-12-01   4297.25
2  2016-01-01   5146.00
3  2016-02-01   1985.15
4  2016-03-01   4657.25
5  2016-04-01   8713.20
6  2016-05-01   8981.80
7  2016-06-01   4163.15
8  2016-07-01  25546.55
9  2016-08-01  26798.45
10 2016-09-01  26363.62
11 2016-10-01  43237.77
12 2016-11-01  15419.38
13 2016-12-01  22731.75
14 2017-01-01  19421.35
15 2017-02-01  12572.25
16 2017-03-01  10887.30
17 2017-04-01  16054.44
18 2017-05-01  19211.70
19 2017-06-01  21812.60
20 2017-07-01  47263.14
21 2017-08-01  36490.65
22 2017-09-01  36698.89
23 2017-10-01  30289.76
24 2017-11-01  33987.07
25 2017-12-01  39807.01
26 2018-01-01  45709.12
27 2018-02-01  33883.73
28 2018-03-01  46735.89
29 2018-04-01  24777.69
30 2018-05-01  34512.03
31 2018-06-01  25697.76
32 2018-07-01  56797.70
33 2018-08-01  18556.78
34 2018-09-01  32353.75
35 2018-10-01  30441.52
36 2018-11-01  30159.58
37 2018-12-01  27710.00
38 2019-01-01  46040.03
39 2019-02-01  16178.66
40 2019-03-01    520.00
probabilidade_zeros :0.0
score : 385.57575757575756
         data     valor
0  2015-11-01   5744.25
1  2015-12-01   7252.35
2  2016-01-01  35013.20
3  2016-02-01  22817.90
4  2016-03-01  21594.35
5  2016-04-01  41045.95
6  2016-05-01  27231.75
7  2016-06-01  30631.75
8  2016-07-01  49367.85
9  2016-08-01  37635.70
10 2016-09-01  61634.50
11 2016-10-01  49586.55
12 2016-11-01  44530.55
13 2016-12-01  60063.95
14 2017-01-01  40657.58
15 2017-02-01  25781.84
16 2017-03-01  16179.38
17 2017-04-01  24667.54
18 2017-05-01  38003.28
19 2017-06-01  48945.25
20 2017-07-01  58290.77
21 2017-08-01  70556.55
22 2017-09-01  56141.26
23 2017-10-01  32931.18
24 2017-11-01  57657.58
25 2017-12-01  50633.24
26 2018-01-01  57187.59
27 2018-02-01  40465.46
28 2018-03-01  41929.85
29 2018-04-01  49164.73
30 2018-05-01  42366.41
31 2018-06-01  39409.77
32 2018-07-01  45540.32
33 2018-08-01  69420.57
34 2018-09-01  62841.32
35 2018-10-01  79464.72
36 2018-11-01  71386.49
37 2018-12-01  48421.92
38 2019-01-01  78072.66
39 2019-02-01  90882.10
40 2019-03-01    185.52
periodo de elegibilidade : [datetime.date(2018, 10, 1), datetime.date(2018, 11, 1), datetime.date(2018, 12, 1), datetime.date(2019, 1, 1), datetime.date(2019, 2, 1), datetime.date(2019, 3, 1)]
         data     valor
0  2015-11-01   5744.25
1  2015-12-01   7252.35
2  2016-01-01  35013.20
3  2016-02-01  22817.90
4  2016-03-01  21594.35
5  2016-04-01  41045.95
6  2016-05-01  27231.75
7  2016-06-01  30631.75
8  2016-07-01  49367.85
9  2016-08-01  37635.70
10 2016-09-01  61634.50
11 2016-10-01  49586.55
12 2016-11-01  44530.55
13 2016-12-01  60063.95
14 2017-01-01  40657.58
15 2017-02-01  25781.84
16 2017-03-01  16179.38
17 2017-04-01  24667.54
18 2017-05-01  38003.28
19 2017-06-01  48945.25
20 2017-07-01  58290.77
21 2017-08-01  70556.55
22 2017-09-01  56141.26
23 2017-10-01  32931.18
24 2017-11-01  57657.58
25 2017-12-01  50633.24
26 2018-01-01  57187.59
27 2018-02-01  40465.46
28 2018-03-01  41929.85
29 2018-04-01  49164.73
30 2018-05-01  42366.41
31 2018-06-01  39409.77
32 2018-07-01  45540.32
33 2018-08-01  69420.57
34 2018-09-01  62841.32
35 2018-10-01  79464.72
36 2018-11-01  71386.49
37 2018-12-01  48421.92
38 2019-01-01  78072.66
39 2019-02-01  90882.10
40 2019-03-01    185.52
probabilidade_zeros :0.0
         data     valor
0  2015-11-01   6747.75
1  2015-12-01   2017.20
2  2016-01-01  18112.15
3  2016-02-01  18760.75
4  2016-03-01  11962.90
5  2016-04-01  13986.00
6  2016-05-01  23407.25
7  2016-06-01  24967.05
8  2016-07-01  26254.70
9  2016-08-01  23471.75
10 2016-09-01  28799.79
11 2016-10-01  12263.61
12 2016-11-01  23089.35
13 2016-12-01  24126.80
14 2017-01-01  33636.80
15 2017-02-01  20358.97
16 2017-03-01  15770.65
17 2017-04-01  17193.79
18 2017-05-01  31980.34
19 2017-06-01  11655.51
20 2017-07-01  25754.10
21 2017-08-01  40345.46
22 2017-09-01  27767.59
23 2017-10-01  25230.60
24 2017-11-01  31992.48
25 2017-12-01  34313.09
26 2018-01-01  26776.99
27 2018-02-01  25887.03
28 2018-03-01  31363.55
29 2018-04-01  28021.18
30 2018-05-01  31635.20
31 2018-06-01  27882.58
32 2018-07-01  36358.20
33 2018-08-01  41228.72
34 2018-09-01  29593.52
35 2018-10-01  43547.60
36 2018-11-01  26846.44
37 2018-12-01  42629.16
38 2019-01-01  45574.74
39 2019-02-01  44255.78
40 2019-03-01   9365.72
periodo de elegibilidade : [datetime.date(2018, 10, 1), datetime.date(2018, 11, 1), datetime.date(2018, 12, 1), datetime.date(2019, 1, 1), datetime.date(2019, 2, 1), datetime.date(2019, 3, 1)]
         data     valor
0  2015-11-01   6747.75
1  2015-12-01   2017.20
2  2016-01-01  18112.15
3  2016-02-01  18760.75
4  2016-03-01  11962.90
5  2016-04-01  13986.00
6  2016-05-01  23407.25
7  2016-06-01  24967.05
8  2016-07-01  26254.70
9  2016-08-01  23471.75
10 2016-09-01  28799.79
11 2016-10-01  12263.61
12 2016-11-01  23089.35
13 2016-12-01  24126.80
14 2017-01-01  33636.80
15 2017-02-01  20358.97
16 2017-03-01  15770.65
17 2017-04-01  17193.79
18 2017-05-01  31980.34
19 2017-06-01  11655.51
20 2017-07-01  25754.10
21 2017-08-01  40345.46
22 2017-09-01  27767.59
23 2017-10-01  25230.60
24 2017-11-01  31992.48
25 2017-12-01  34313.09
26 2018-01-01  26776.99
27 2018-02-01  25887.03
28 2018-03-01  31363.55
29 2018-04-01  28021.18
30 2018-05-01  31635.20
31 2018-06-01  27882.58
32 2018-07-01  36358.20
33 2018-08-01  41228.72
34 2018-09-01  29593.52
35 2018-10-01  43547.60
36 2018-11-01  26846.44
37 2018-12-01  42629.16
38 2019-01-01  45574.74
39 2019-02-01  44255.78
40 2019-03-01   9365.72
probabilidade_zeros :0.0
score : 617.1952861952861
         data     valor
0  2015-11-01    499.50
1  2015-12-01   6743.25
2  2016-01-01  12537.60
3  2016-02-01  17658.85
4  2016-03-01   8406.65
5  2016-04-01  10942.85
6  2016-05-01  10915.85
7  2016-06-01   8003.70
8  2016-07-01  36725.05
9  2016-08-01  79629.50
10 2016-09-01  68113.97
11 2016-10-01  46968.57
12 2016-11-01  55442.55
13 2016-12-01  48314.55
14 2017-01-01  33380.20
15 2017-02-01  20875.00
16 2017-03-01  43404.17
17 2017-04-01  35042.31
18 2017-05-01  36891.40
19 2017-06-01  10366.04
20 2017-07-01  35667.74
21 2017-08-01  48666.04
22 2017-09-01  33161.89
23 2017-10-01  35427.72
24 2017-11-01  29318.07
25 2017-12-01  30488.44
26 2018-01-01  61753.43
27 2018-02-01  39544.00
28 2018-03-01  39697.61
29 2018-04-01  41063.96
30 2018-05-01  53380.99
31 2018-06-01  37450.33
32 2018-07-01  51853.27
33 2018-08-01  50421.72
34 2018-09-01  54024.02
35 2018-10-01  59207.86
36 2018-11-01  65122.24
37 2018-12-01  58562.34
38 2019-01-01  66814.66
39 2019-02-01  63618.64
40 2019-03-01  46751.57
periodo de elegibilidade : [datetime.date(2018, 10, 1), datetime.date(2018, 11, 1), datetime.date(2018, 12, 1), datetime.date(2019, 1, 1), datetime.date(2019, 2, 1), datetime.date(2019, 3, 1)]
         data     valor
0  2015-11-01    499.50
1  2015-12-01   6743.25
2  2016-01-01  12537.60
3  2016-02-01  17658.85
4  2016-03-01   8406.65
5  2016-04-01  10942.85
6  2016-05-01  10915.85
7  2016-06-01   8003.70
8  2016-07-01  36725.05
9  2016-08-01  79629.50
10 2016-09-01  68113.97
11 2016-10-01  46968.57
12 2016-11-01  55442.55
13 2016-12-01  48314.55
14 2017-01-01  33380.20
15 2017-02-01  20875.00
16 2017-03-01  43404.17
17 2017-04-01  35042.31
18 2017-05-01  36891.40
19 2017-06-01  10366.04
20 2017-07-01  35667.74
21 2017-08-01  48666.04
22 2017-09-01  33161.89
23 2017-10-01  35427.72
24 2017-11-01  29318.07
25 2017-12-01  30488.44
26 2018-01-01  61753.43
27 2018-02-01  39544.00
28 2018-03-01  39697.61
29 2018-04-01  41063.96
30 2018-05-01  53380.99
31 2018-06-01  37450.33
32 2018-07-01  51853.27
33 2018-08-01  50421.72
34 2018-09-01  54024.02
35 2018-10-01  59207.86
36 2018-11-01  65122.24
37 2018-12-01  58562.34
38 2019-01-01  66814.66
39 2019-02-01  63618.64
40 2019-03-01  46751.57
probabilidade_zeros :0.0

score : 720.5515151515152
         data     valor
0  2017-08-01   6265.40
1  2017-09-01   3406.64
2  2017-10-01      0.00
3  2017-11-01      0.00
4  2017-12-01    321.47
5  2018-01-01  12835.12
6  2018-02-01   3047.56
7  2018-03-01   6346.85
8  2018-04-01   7350.01
9  2018-05-01  16097.64
10 2018-06-01  22727.58
11 2018-07-01  25242.71
12 2018-08-01   9189.72
13 2018-09-01  12171.86
14 2018-10-01  16204.80
15 2018-11-01  14643.62
16 2018-12-01  31543.39
17 2019-01-01  25889.57
18 2019-02-01  28561.94
19 2019-03-01  26175.83
periodo de elegibilidade : [datetime.date(2018, 10, 1), datetime.date(2018, 11, 1), datetime.date(2018, 12, 1), datetime.date(2019, 1, 1), datetime.date(2019, 2, 1), datetime.date(2019, 3, 1)]
         data     valor
0  2017-08-01   6265.40
1  2017-09-01   3406.64
2  2017-10-01      0.00
3  2017-11-01      0.00
4  2017-12-01    321.47
5  2018-01-01  12835.12
6  2018-02-01   3047.56
7  2018-03-01   6346.85
8  2018-04-01   7350.01
9  2018-05-01  16097.64
10 2018-06-01  22727.58
11 2018-07-01  25242.71
12 2018-08-01   9189.72
13 2018-09-01  12171.86
14 2018-10-01  16204.80
15 2018-11-01  14643.62
16 2018-12-01  31543.39
17 2019-01-01  25889.57
18 2019-02-01  28561.94
19 2019-03-01  26175.83
probabilidade_zeros :0.0
score : 764.5393939393939
         data     valor
0  2015-10-01   2564.14
1  2015-11-01  19171.73
2  2015-12-01  36656.19
3  2016-01-01  27812.43
4  2016-02-01  28995.82
5  2016-03-01  24392.62
6  2016-04-01   8089.60
7  2016-05-01  29815.31
8  2016-06-01  24246.95
9  2016-07-01  34152.30
10 2016-08-01  18808.20
11 2016-09-01  13390.39
12 2016-10-01  14318.32
13 2016-11-01   8428.90
14 2016-12-01  14181.80
15 2017-01-01  19816.45
16 2017-02-01   7954.40
17 2017-03-01   4768.35
18 2017-04-01  15277.40
19 2017-05-01  18334.94
20 2017-06-01  23513.22
21 2017-07-01  14860.86
22 2017-08-01  22986.06
23 2017-09-01  13643.61
24 2017-10-01  16748.34
25 2017-11-01  26394.06
26 2017-12-01  20101.65
27 2018-01-01  29381.60
28 2018-02-01  27107.91
29 2018-03-01  23736.16
30 2018-04-01  20347.65
31 2018-05-01  29948.06
32 2018-06-01  17535.60
33 2018-07-01  28609.63
34 2018-08-01  30581.51
35 2018-09-01  22591.26
36 2018-10-01  25926.47
37 2018-11-01  35830.80
38 2018-12-01  18522.57
39 2019-01-01  29603.72
40 2019-02-01  36046.70
41 2019-03-01    650.00
periodo de elegibilidade : [datetime.date(2018, 10, 1), datetime.date(2018, 11, 1), datetime.date(2018, 12, 1), datetime.date(2019, 1, 1), datetime.date(2019, 2, 1), datetime.date(2019, 3, 1)]
         data     valor
0  2015-10-01   2564.14
1  2015-11-01  19171.73
2  2015-12-01  36656.19
3  2016-01-01  27812.43
4  2016-02-01  28995.82
5  2016-03-01  24392.62
6  2016-04-01   8089.60
7  2016-05-01  29815.31
8  2016-06-01  24246.95
9  2016-07-01  34152.30
10 2016-08-01  18808.20
11 2016-09-01  13390.39
12 2016-10-01  14318.32
13 2016-11-01   8428.90
14 2016-12-01  14181.80
15 2017-01-01  19816.45
16 2017-02-01   7954.40
17 2017-03-01   4768.35
18 2017-04-01  15277.40
19 2017-05-01  18334.94
20 2017-06-01  23513.22
21 2017-07-01  14860.86
22 2017-08-01  22986.06
23 2017-09-01  13643.61
24 2017-10-01  16748.34
25 2017-11-01  26394.06
26 2017-12-01  20101.65
27 2018-01-01  29381.60
28 2018-02-01  27107.91
29 2018-03-01  23736.16
30 2018-04-01  20347.65
31 2018-05-01  29948.06
32 2018-06-01  17535.60
33 2018-07-01  28609.63
34 2018-08-01  30581.51
35 2018-09-01  22591.26
36 2018-10-01  25926.47
37 2018-11-01  35830.80
38 2018-12-01  18522.57
39 2019-01-01  29603.72
40 2019-02-01  36046.70
41 2019-03-01    650.00
probabilidade_zeros :0.0
         data      valor
0  2016-05-01   89393.85
1  2016-06-01   49243.03
2  2016-07-01   49101.06
3  2016-08-01   11582.00
4  2016-09-01   68245.21
5  2016-10-01   46683.33
6  2016-11-01  127125.37
7  2016-12-01  162988.32
8  2017-01-01   99017.30
9  2017-02-01  121590.08
10 2017-03-01  153523.64
11 2017-04-01  105980.30
12 2017-05-01  142776.36
13 2017-06-01    5114.60
14 2017-07-01    7499.87
15 2017-08-01     835.14
16 2017-09-01   18958.75
17 2017-10-01    3912.67
18 2017-11-01    1759.29
19 2017-12-01    8786.91
20 2018-01-01   13160.14
21 2018-02-01    7493.07
22 2018-03-01   13035.72
23 2018-04-01   13772.13
24 2018-05-01    2386.75
25 2018-06-01   10345.07
26 2018-07-01    1892.49
27 2018-08-01    7937.01
28 2018-09-01   16069.03
29 2018-10-01    5117.72
30 2018-11-01   12651.73
31 2018-12-01    6235.01
32 2019-01-01    3314.75
33 2019-02-01    2970.87
34 2019-03-01    2239.34
periodo de elegibilidade : [datetime.date(2018, 10, 1), datetime.date(2018, 11, 1), datetime.date(2018, 12, 1), datetime.date(2019, 1, 1), datetime.date(2019, 2, 1), datetime.date(2019, 3, 1)]
         data      valor
0  2016-05-01   89393.85
1  2016-06-01   49243.03
2  2016-07-01   49101.06
3  2016-08-01   11582.00
4  2016-09-01   68245.21
5  2016-10-01   46683.33
6  2016-11-01  127125.37
7  2016-12-01  162988.32
8  2017-01-01   99017.30
9  2017-02-01  121590.08
10 2017-03-01  153523.64
11 2017-04-01  105980.30
12 2017-05-01  142776.36
13 2017-06-01    5114.60
14 2017-07-01    7499.87
15 2017-08-01     835.14
16 2017-09-01   18958.75
17 2017-10-01    3912.67
18 2017-11-01    1759.29
19 2017-12-01    8786.91
20 2018-01-01   13160.14
21 2018-02-01    7493.07
22 2018-03-01   13035.72
23 2018-04-01   13772.13
24 2018-05-01    2386.75
25 2018-06-01   10345.07
26 2018-07-01    1892.49
27 2018-08-01    7937.01
28 2018-09-01   16069.03
29 2018-10-01    5117.72
30 2018-11-01   12651.73
31 2018-12-01    6235.01
32 2019-01-01    3314.75
33 2019-02-01    2970.87
34 2019-03-01    2239.34
probabilidade_zeros :0.0
score : 569.2119865319866
         data     valor
0  2016-07-01  11691.36
1  2016-08-01  26113.00
2  2016-09-01  18879.17
3  2016-10-01  21019.00
4  2016-11-01  29083.76
5  2016-12-01  36001.68
6  2017-01-01  22870.70
7  2017-02-01  23389.89
8  2017-03-01  30261.76
9  2017-04-01  27520.54
10 2017-05-01  22302.34
11 2017-06-01  18784.94
12 2017-07-01  22895.10
13 2017-08-01  22265.92
14 2017-09-01  24320.95
15 2017-10-01  20786.14
16 2017-11-01  13287.77
17 2017-12-01  17530.84
18 2018-01-01  29485.89
19 2018-02-01  16114.63
20 2018-03-01  22468.06
21 2018-04-01  24116.69
22 2018-05-01  21898.01
23 2018-06-01  23408.81
24 2018-07-01  21624.51
25 2018-08-01  12791.39
26 2018-09-01  29819.27
27 2018-10-01  21226.70
28 2018-11-01  25142.76
29 2018-12-01  27976.76
30 2019-01-01  28010.67
31 2019-02-01  24387.42
32 2019-03-01  22392.31
periodo de elegibilidade : [datetime.date(2018, 10, 1), datetime.date(2018, 11, 1), datetime.date(2018, 12, 1), datetime.date(2019, 1, 1), datetime.date(2019, 2, 1), datetime.date(2019, 3, 1)]
         data     valor
0  2016-07-01  11691.36
1  2016-08-01  26113.00
2  2016-09-01  18879.17
3  2016-10-01  21019.00
4  2016-11-01  29083.76
5  2016-12-01  36001.68
6  2017-01-01  22870.70
7  2017-02-01  23389.89
8  2017-03-01  30261.76
9  2017-04-01  27520.54
10 2017-05-01  22302.34
11 2017-06-01  18784.94
12 2017-07-01  22895.10
13 2017-08-01  22265.92
14 2017-09-01  24320.95
15 2017-10-01  20786.14
16 2017-11-01  13287.77
17 2017-12-01  17530.84
18 2018-01-01  29485.89
19 2018-02-01  16114.63
20 2018-03-01  22468.06
21 2018-04-01  24116.69
22 2018-05-01  21898.01
23 2018-06-01  23408.81
24 2018-07-01  21624.51
25 2018-08-01  12791.39
26 2018-09-01  29819.27
27 2018-10-01  21226.70
28 2018-11-01  25142.76
29 2018-12-01  27976.76
30 2019-01-01  28010.67
31 2019-02-01  24387.42
32 2019-03-01  22392.31
probabilidade_zeros :0.0
         data     valor
0  2015-11-01   1263.90
1  2015-12-01   6051.25
2  2016-01-01   7384.45
3  2016-02-01  10691.15
4  2016-03-01  12865.70
5  2016-04-01  11549.86
6  2016-05-01  10790.40
7  2016-06-01  15241.70
8  2016-07-01  14674.65
9  2016-08-01  28836.80
10 2016-09-01  22517.67
11 2016-10-01  30088.26
12 2016-11-01  22596.45
13 2016-12-01  20714.70
14 2017-01-01  40097.24
15 2017-02-01  19922.60
16 2017-03-01  20757.09
17 2017-04-01  28595.29
18 2017-05-01   8511.94
19 2017-06-01  12824.27
20 2017-07-01  21264.66
21 2017-08-01  12534.13
22 2017-09-01  20389.24
23 2017-10-01  16288.39
24 2017-11-01   9401.77
25 2017-12-01  12712.62
26 2018-01-01  18752.27
27 2018-02-01   8707.22
28 2018-03-01  17492.57
29 2018-04-01  15333.49
30 2018-05-01  11928.78
31 2018-06-01  17243.04
32 2018-07-01  19783.00
33 2018-08-01  13050.94
34 2018-09-01   8019.94
35 2018-10-01  21727.50
36 2018-11-01  10976.24
37 2018-12-01  24149.37
38 2019-01-01  14341.36
39 2019-02-01  25690.98
40 2019-03-01  27033.74
periodo de elegibilidade : [datetime.date(2018, 10, 1), datetime.date(2018, 11, 1), datetime.date(2018, 12, 1), datetime.date(2019, 1, 1), datetime.date(2019, 2, 1), datetime.date(2019, 3, 1)]
         data     valor
0  2015-11-01   1263.90
1  2015-12-01   6051.25
2  2016-01-01   7384.45
3  2016-02-01  10691.15
4  2016-03-01  12865.70
5  2016-04-01  11549.86
6  2016-05-01  10790.40
7  2016-06-01  15241.70
8  2016-07-01  14674.65
9  2016-08-01  28836.80
10 2016-09-01  22517.67
11 2016-10-01  30088.26
12 2016-11-01  22596.45
13 2016-12-01  20714.70
14 2017-01-01  40097.24
15 2017-02-01  19922.60
16 2017-03-01  20757.09
17 2017-04-01  28595.29
18 2017-05-01   8511.94
19 2017-06-01  12824.27
20 2017-07-01  21264.66
21 2017-08-01  12534.13
22 2017-09-01  20389.24
23 2017-10-01  16288.39
24 2017-11-01   9401.77
25 2017-12-01  12712.62
26 2018-01-01  18752.27
27 2018-02-01   8707.22
28 2018-03-01  17492.57
29 2018-04-01  15333.49
30 2018-05-01  11928.78
31 2018-06-01  17243.04
32 2018-07-01  19783.00
33 2018-08-01  13050.94
34 2018-09-01   8019.94
35 2018-10-01  21727.50
36 2018-11-01  10976.24
37 2018-12-01  24149.37
38 2019-01-01  14341.36
39 2019-02-01  25690.98
40 2019-03-01  27033.74
probabilidade_zeros :0.0

        data     valor
0 2018-06-01   3956.66
1 2018-07-01    552.80
2 2018-08-01   7205.20
3 2018-09-01   3676.22
4 2018-10-01  11398.87
5 2018-11-01   7066.30
6 2018-12-01  12267.00
7 2019-01-01  12583.02
8 2019-02-01   6584.55
9 2019-03-01  11383.39
periodo de elegibilidade : [datetime.date(2018, 10, 1), datetime.date(2018, 11, 1), datetime.date(2018, 12, 1), datetime.date(2019, 1, 1), datetime.date(2019, 2, 1), datetime.date(2019, 3, 1)]
        data     valor
0 2018-06-01   3956.66
1 2018-07-01    552.80
2 2018-08-01   7205.20
3 2018-09-01   3676.22
4 2018-10-01  11398.87
5 2018-11-01   7066.30
6 2018-12-01  12267.00
7 2019-01-01  12583.02
8 2019-02-01   6584.55
9 2019-03-01  11383.39
probabilidade_zeros :0.1
score : 742.5757575757576
         data     valor
0  2017-11-01  42792.62
1  2017-12-01  54332.12
2  2018-01-01  25133.02
3  2018-02-01  19447.82
4  2018-03-01   9940.15
5  2018-04-01  31260.18
6  2018-05-01  29713.69
7  2018-06-01  25692.23
8  2018-07-01  31458.00
9  2018-08-01  24777.54
10 2018-09-01  21215.97
11 2018-10-01   9905.33
12 2018-11-01   5781.93
13 2018-12-01  26424.59
14 2019-01-01  66938.74
15 2019-02-01  17028.76
16 2019-03-01  39345.34
periodo de elegibilidade : [datetime.date(2018, 10, 1), datetime.date(2018, 11, 1), datetime.date(2018, 12, 1), datetime.date(2019, 1, 1), datetime.date(2019, 2, 1), datetime.date(2019, 3, 1)]
         data     valor
0  2017-11-01  42792.62
1  2017-12-01  54332.12
2  2018-01-01  25133.02
3  2018-02-01  19447.82
4  2018-03-01   9940.15
5  2018-04-01  31260.18
6  2018-05-01  29713.69
7  2018-06-01  25692.23
8  2018-07-01  31458.00
9  2018-08-01  24777.54
10 2018-09-01  21215.97
11 2018-10-01   9905.33
12 2018-11-01   5781.93
13 2018-12-01  26424.59
14 2019-01-01  66938.74
15 2019-02-01  17028.76
16 2019-03-01  39345.34
probabilidade_zeros :0.0
        data     valor
0 2018-06-01  15398.86
1 2018-07-01  30363.73
2 2018-08-01  33200.36
3 2018-09-01  20761.69
4 2018-10-01  27516.55
5 2018-11-01  15010.22
6 2018-12-01  27721.11
7 2019-01-01  44666.71
8 2019-02-01  29880.96
9 2019-03-01  33072.68
periodo de elegibilidade : [datetime.date(2018, 10, 1), datetime.date(2018, 11, 1), datetime.date(2018, 12, 1), datetime.date(2019, 1, 1), datetime.date(2019, 2, 1), datetime.date(2019, 3, 1)]
        data     valor
0 2018-06-01  15398.86
1 2018-07-01  30363.73
2 2018-08-01  33200.36
3 2018-09-01  20761.69
4 2018-10-01  27516.55
5 2018-11-01  15010.22
6 2018-12-01  27721.11
7 2019-01-01  44666.71
8 2019-02-01  29880.96
9 2019-03-01  33072.68
probabilidade_zeros :0.0
score : 731.2247086247086
         data     valor
0  2017-08-01   1595.96
1  2017-09-01   8083.50
2  2017-10-01  12007.98
3  2017-11-01  18704.26
4  2017-12-01  11717.62
5  2018-01-01   4445.97
6  2018-02-01   7128.03
7  2018-03-01   8813.29
8  2018-04-01   6210.85
9  2018-05-01   6717.92
10 2018-06-01   3004.29
11 2018-07-01   4723.10
12 2018-08-01   3163.53
13 2018-09-01   8673.58
14 2018-10-01  17562.09
15 2018-11-01   8401.66
16 2018-12-01  10945.56
17 2019-01-01   5598.27
18 2019-02-01  12468.09
19 2019-03-01   5930.45
periodo de elegibilidade : [datetime.date(2018, 10, 1), datetime.date(2018, 11, 1), datetime.date(2018, 12, 1), datetime.date(2019, 1, 1), datetime.date(2019, 2, 1), datetime.date(2019, 3, 1)]
         data     valor
0  2017-08-01   1595.96
1  2017-09-01   8083.50
2  2017-10-01  12007.98
3  2017-11-01  18704.26
4  2017-12-01  11717.62
5  2018-01-01   4445.97
6  2018-02-01   7128.03
7  2018-03-01   8813.29
8  2018-04-01   6210.85
9  2018-05-01   6717.92
10 2018-06-01   3004.29
11 2018-07-01   4723.10
12 2018-08-01   3163.53
13 2018-09-01   8673.58
14 2018-10-01  17562.09
15 2018-11-01   8401.66
16 2018-12-01  10945.56
17 2019-01-01   5598.27
18 2019-02-01  12468.09
19 2019-03-01   5930.45
probabilidade_zeros :0.0
        data     valor
0 2018-06-01  29832.21
1 2018-07-01  19126.81
2 2018-08-01  16397.72
3 2018-09-01  25754.12
4 2018-10-01  37775.88
5 2018-11-01   9353.82
6 2018-12-01  49110.06
7 2019-01-01   6096.39
8 2019-02-01  14204.84
9 2019-03-01  13193.84
periodo de elegibilidade : [datetime.date(2018, 10, 1), datetime.date(2018, 11, 1), datetime.date(2018, 12, 1), datetime.date(2019, 1, 1), datetime.date(2019, 2, 1), datetime.date(2019, 3, 1)]
        data     valor
0 2018-06-01  29832.21
1 2018-07-01  19126.81
2 2018-08-01  16397.72
3 2018-09-01  25754.12
4 2018-10-01  37775.88
5 2018-11-01   9353.82
6 2018-12-01  49110.06
7 2019-01-01   6096.39
8 2019-02-01  14204.84
9 2019-03-01  13193.84
probabilidade_zeros :0.0
score : 618.5181818181817
        data      valor
0 2018-06-01    2256.88
1 2018-07-01   25024.44
2 2018-08-01   73927.82
3 2018-09-01   81775.34
4 2018-10-01  102242.47
5 2018-11-01   79304.19
6 2018-12-01  104921.72
7 2019-01-01   52311.87
8 2019-02-01   65598.83
9 2019-03-01   59199.94
periodo de elegibilidade : [datetime.date(2018, 10, 1), datetime.date(2018, 11, 1), datetime.date(2018, 12, 1), datetime.date(2019, 1, 1), datetime.date(2019, 2, 1), datetime.date(2019, 3, 1)]
        data      valor
0 2018-06-01    2256.88
1 2018-07-01   25024.44
2 2018-08-01   73927.82
3 2018-09-01   81775.34
4 2018-10-01  102242.47
5 2018-11-01   79304.19
6 2018-12-01  104921.72
7 2019-01-01   52311.87
8 2019-02-01   65598.83
9 2019-03-01   59199.94
probabilidade_zeros :0.1
score : 670.4484848484848
         data    valor
0  2017-12-01   300.00
1  2018-01-01   943.04
2  2018-02-01   652.00
3  2018-03-01  1509.36
4  2018-04-01   824.79
5  2018-05-01   392.00
6  2018-06-01   392.00
7  2018-07-01  1220.33
8  2018-08-01   629.00
9  2018-09-01   412.00
10 2018-10-01   703.00
11 2018-11-01  1115.00
12 2018-12-01   950.00
13 2019-01-01   890.00
14 2019-02-01   842.50
15 2019-03-01  1380.00
periodo de elegibilidade : [datetime.date(2018, 10, 1), datetime.date(2018, 11, 1), datetime.date(2018, 12, 1), datetime.date(2019, 1, 1), datetime.date(2019, 2, 1), datetime.date(2019, 3, 1)]
         data    valor
0  2017-12-01   300.00
1  2018-01-01   943.04
2  2018-02-01   652.00
3  2018-03-01  1509.36
4  2018-04-01   824.79
5  2018-05-01   392.00
6  2018-06-01   392.00
7  2018-07-01  1220.33
8  2018-08-01   629.00
9  2018-09-01   412.00
10 2018-10-01   703.00
11 2018-11-01  1115.00
12 2018-12-01   950.00
13 2019-01-01   890.00
14 2019-02-01   842.50
15 2019-03-01  1380.00
probabilidade_zeros :0.0
score : 785.1121212121212
        data     valor
0 2018-07-01   7496.71
1 2018-08-01  11217.00
2 2018-09-01  10127.28
3 2018-10-01   9126.59
4 2018-11-01  10155.49
5 2018-12-01  10457.90
6 2019-01-01  13248.14
7 2019-02-01   9557.00
8 2019-03-01   6935.63
periodo de elegibilidade : [datetime.date(2018, 10, 1), datetime.date(2018, 11, 1), datetime.date(2018, 12, 1), datetime.date(2019, 1, 1), datetime.date(2019, 2, 1), datetime.date(2019, 3, 1)]
        data     valor
0 2018-07-01   7496.71
1 2018-08-01  11217.00
2 2018-09-01  10127.28
3 2018-10-01   9126.59
4 2018-11-01  10155.49
5 2018-12-01  10457.90
6 2019-01-01  13248.14
7 2019-02-01   9557.00
8 2019-03-01   6935.63
probabilidade_zeros :0.0
        data      valor
0 2018-08-01   19239.74
1 2018-09-01   54132.79
2 2018-10-01   56153.97
3 2018-11-01   30015.33
4 2018-12-01   38945.54
5 2019-01-01  115765.76
6 2019-02-01   30925.78
7 2019-03-01   65953.21
periodo de elegibilidade : [datetime.date(2018, 10, 1), datetime.date(2018, 11, 1), datetime.date(2018, 12, 1), datetime.date(2019, 1, 1), datetime.date(2019, 2, 1), datetime.date(2019, 3, 1)]
        data      valor
0 2018-08-01   19239.74
1 2018-09-01   54132.79
2 2018-10-01   56153.97
3 2018-11-01   30015.33
4 2018-12-01   38945.54
5 2019-01-01  115765.76
6 2019-02-01   30925.78
7 2019-03-01   65953.21
probabilidade_zeros :0.0
score : 710.0363636363636
         data     valor
0  2017-11-01   1853.74
1  2017-12-01   5800.76
2  2018-01-01   4984.63
3  2018-02-01   2569.68
4  2018-03-01   1568.16
5  2018-04-01    536.29
6  2018-05-01      0.00
7  2018-06-01      0.00
8  2018-07-01      0.00
9  2018-08-01    762.08
10 2018-09-01  17528.92
11 2018-10-01  16332.69
12 2018-11-01  19265.17
13 2018-12-01  55599.05
14 2019-01-01  75001.31
15 2019-02-01   5075.28
16 2019-03-01   1267.50
periodo de elegibilidade : [datetime.date(2018, 10, 1), datetime.date(2018, 11, 1), datetime.date(2018, 12, 1), datetime.date(2019, 1, 1), datetime.date(2019, 2, 1), datetime.date(2019, 3, 1)]
         data     valor
0  2017-11-01   1853.74
1  2017-12-01   5800.76
2  2018-01-01   4984.63
3  2018-02-01   2569.68
4  2018-03-01   1568.16
5  2018-04-01    536.29
6  2018-05-01      0.00
7  2018-06-01      0.00
8  2018-07-01      0.00
9  2018-08-01    762.08
10 2018-09-01  17528.92
11 2018-10-01  16332.69
12 2018-11-01  19265.17
13 2018-12-01  55599.05
14 2019-01-01  75001.31
15 2019-02-01   5075.28
16 2019-03-01   1267.50
probabilidade_zeros :0.4166666666666667

score : 224.68013468013464
         data     valor
0  2018-03-01   4682.72
1  2018-04-01  11698.68
2  2018-05-01  33695.52
3  2018-06-01   5450.82
4  2018-07-01  14616.46
5  2018-08-01  20806.01
6  2018-09-01   9654.06
7  2018-10-01  14786.12
8  2018-11-01  22600.34
9  2018-12-01  17117.42
10 2019-01-01  19005.11
11 2019-02-01  13623.63
12 2019-03-01  12199.33
periodo de elegibilidade : [datetime.date(2018, 10, 1), datetime.date(2018, 11, 1), datetime.date(2018, 12, 1), datetime.date(2019, 1, 1), datetime.date(2019, 2, 1), datetime.date(2019, 3, 1)]
         data     valor
0  2018-03-01   4682.72
1  2018-04-01  11698.68
2  2018-05-01  33695.52
3  2018-06-01   5450.82
4  2018-07-01  14616.46
5  2018-08-01  20806.01
6  2018-09-01   9654.06
7  2018-10-01  14786.12
8  2018-11-01  22600.34
9  2018-12-01  17117.42
10 2019-01-01  19005.11
11 2019-02-01  13623.63
12 2019-03-01  12199.33
probabilidade_zeros :0.0
        data     valor
0 2018-07-01   5946.58
1 2018-08-01  18060.22
2 2018-09-01  25819.15
3 2018-10-01  26443.95
4 2018-11-01  20452.81
5 2018-12-01   1814.51
6 2019-01-01  37495.86
7 2019-02-01  36663.11
8 2019-03-01  30827.48
periodo de elegibilidade : [datetime.date(2018, 10, 1), datetime.date(2018, 11, 1), datetime.date(2018, 12, 1), datetime.date(2019, 1, 1), datetime.date(2019, 2, 1), datetime.date(2019, 3, 1)]
        data     valor
0 2018-07-01   5946.58
1 2018-08-01  18060.22
2 2018-09-01  25819.15
3 2018-10-01  26443.95
4 2018-11-01  20452.81
5 2018-12-01   1814.51
6 2019-01-01  37495.86
7 2019-02-01  36663.11
8 2019-03-01  30827.48
probabilidade_zeros :0.0
score : 805.5636363636364
         data     valor
0  2015-10-01   1252.65
1  2015-11-01   4271.91
2  2015-12-01   5934.74
3  2016-01-01  17281.85
4  2016-02-01   6579.75
5  2016-03-01  10025.90
6  2016-04-01   9766.90
7  2016-05-01  16478.40
8  2016-06-01  13448.69
9  2016-07-01  33790.20
10 2016-08-01  17877.10
11 2016-09-01  31852.41
12 2016-10-01  15705.45
13 2016-11-01  23264.10
14 2016-12-01  31295.92
15 2017-01-01  18761.85
16 2017-02-01   5776.78
17 2017-03-01   5009.55
18 2017-04-01  10072.89
19 2017-05-01   7106.32
20 2017-06-01  12742.33
21 2017-07-01   8492.00
22 2017-08-01  21853.49
23 2017-09-01  12079.28
24 2017-10-01   8306.53
25 2017-11-01   9507.11
26 2017-12-01  15568.90
27 2018-01-01  19411.10
28 2018-02-01   8120.34
29 2018-03-01  11543.70
30 2018-04-01  13144.85
31 2018-05-01   3442.62
32 2018-06-01  10684.91
33 2018-07-01  13025.45
34 2018-08-01  24699.16
35 2018-09-01  21529.52
36 2018-10-01  15920.65
37 2018-11-01   7323.01
38 2018-12-01   7309.43
39 2019-01-01   7523.12
40 2019-02-01   6767.00
41 2019-03-01   7480.41
periodo de elegibilidade : [datetime.date(2018, 10, 1), datetime.date(2018, 11, 1), datetime.date(2018, 12, 1), datetime.date(2019, 1, 1), datetime.date(2019, 2, 1), datetime.date(2019, 3, 1)]
         data     valor
0  2015-10-01   1252.65
1  2015-11-01   4271.91
2  2015-12-01   5934.74
3  2016-01-01  17281.85
4  2016-02-01   6579.75
5  2016-03-01  10025.90
6  2016-04-01   9766.90
7  2016-05-01  16478.40
8  2016-06-01  13448.69
9  2016-07-01  33790.20
10 2016-08-01  17877.10
11 2016-09-01  31852.41
12 2016-10-01  15705.45
13 2016-11-01  23264.10
14 2016-12-01  31295.92
15 2017-01-01  18761.85
16 2017-02-01   5776.78
17 2017-03-01   5009.55
18 2017-04-01  10072.89
19 2017-05-01   7106.32
20 2017-06-01  12742.33
21 2017-07-01   8492.00
22 2017-08-01  21853.49
23 2017-09-01  12079.28
24 2017-10-01   8306.53
25 2017-11-01   9507.11
26 2017-12-01  15568.90
27 2018-01-01  19411.10
28 2018-02-01   8120.34
29 2018-03-01  11543.70
30 2018-04-01  13144.85
31 2018-05-01   3442.62
32 2018-06-01  10684.91
33 2018-07-01  13025.45
34 2018-08-01  24699.16
35 2018-09-01  21529.52
36 2018-10-01  15920.65
37 2018-11-01   7323.01
38 2018-12-01   7309.43
39 2019-01-01   7523.12
40 2019-02-01   6767.00
41 2019-03-01   7480.41
probabilidade_zeros :0.0
        data    valor
0 2018-10-01  6765.04
1 2018-11-01  3006.21
2 2018-12-01  6294.75
3 2019-01-01  5567.86
4 2019-02-01  7005.81
5 2019-03-01  1654.30
periodo de elegibilidade : [datetime.date(2018, 10, 1), datetime.date(2018, 11, 1), datetime.date(2018, 12, 1), datetime.date(2019, 1, 1), datetime.date(2019, 2, 1), datetime.date(2019, 3, 1)]
        data    valor
0 2018-10-01  6765.04
1 2018-11-01  3006.21
2 2018-12-01  6294.75
3 2019-01-01  5567.86
4 2019-02-01  7005.81
5 2019-03-01  1654.30
probabilidade_zeros :0.0
score : 306.3333333333333
         data     valor
0  2016-04-01  17945.32
1  2016-05-01  46987.98
2  2016-06-01  53553.32
3  2016-07-01  39001.72
4  2016-08-01  47556.59
5  2016-09-01  43507.14
6  2016-10-01  30201.58
7  2016-11-01  44606.06
8  2016-12-01  64740.50
9  2017-01-01  45723.57
10 2017-02-01  29622.30
11 2017-03-01  49735.64
12 2017-04-01  24054.95
13 2017-05-01  23370.70
14 2017-06-01  18804.30
15 2017-07-01  22744.07
16 2017-08-01  18926.38
17 2017-09-01  23597.68
18 2017-10-01  16087.43
19 2017-11-01   4358.98
20 2017-12-01  40900.63
21 2018-01-01  36748.70
22 2018-02-01  29984.06
23 2018-03-01  45314.50
24 2018-04-01  47717.67
25 2018-05-01  22066.95
26 2018-06-01  40137.65
27 2018-07-01  43514.40
28 2018-08-01  48977.46
29 2018-09-01  57566.66
30 2018-10-01  77945.01
31 2018-11-01  50014.45
32 2018-12-01  56854.59
33 2019-01-01  48138.68
34 2019-02-01  39346.04
35 2019-03-01  52600.77
periodo de elegibilidade : [datetime.date(2018, 10, 1), datetime.date(2018, 11, 1), datetime.date(2018, 12, 1), datetime.date(2019, 1, 1), datetime.date(2019, 2, 1), datetime.date(2019, 3, 1)]
         data     valor
0  2016-04-01  17945.32
1  2016-05-01  46987.98
2  2016-06-01  53553.32
3  2016-07-01  39001.72
4  2016-08-01  47556.59
5  2016-09-01  43507.14
6  2016-10-01  30201.58
7  2016-11-01  44606.06
8  2016-12-01  64740.50
9  2017-01-01  45723.57
10 2017-02-01  29622.30
11 2017-03-01  49735.64
12 2017-04-01  24054.95
13 2017-05-01  23370.70
14 2017-06-01  18804.30
15 2017-07-01  22744.07
16 2017-08-01  18926.38
17 2017-09-01  23597.68
18 2017-10-01  16087.43
19 2017-11-01   4358.98
20 2017-12-01  40900.63
21 2018-01-01  36748.70
22 2018-02-01  29984.06
23 2018-03-01  45314.50
24 2018-04-01  47717.67
25 2018-05-01  22066.95
26 2018-06-01  40137.65
27 2018-07-01  43514.40
28 2018-08-01  48977.46
29 2018-09-01  57566.66
30 2018-10-01  77945.01
31 2018-11-01  50014.45
32 2018-12-01  56854.59
33 2019-01-01  48138.68
34 2019-02-01  39346.04
35 2019-03-01  52600.77
probabilidade_zeros :0.0
         data     valor
0  2016-10-01   8802.08
1  2016-11-01   7507.10
2  2016-12-01  21007.98
3  2017-01-01  11027.68
4  2017-02-01   3043.62
5  2017-03-01  21274.86
6  2017-04-01   9313.97
7  2017-05-01  12955.98
8  2017-06-01   8124.44
9  2017-07-01      0.00
10 2017-08-01      0.00
11 2017-09-01      0.00
12 2017-10-01      0.00
13 2017-11-01      0.00
14 2017-12-01      0.00
15 2018-01-01      0.00
16 2018-02-01      0.00
17 2018-03-01      0.00
18 2018-04-01   6758.76
19 2018-05-01  32007.05
20 2018-06-01  31045.92
21 2018-07-01  44612.20
22 2018-08-01   8266.71
23 2018-09-01  37518.90
24 2018-10-01  42439.85
25 2018-11-01  51878.15
26 2018-12-01  23269.16
27 2019-01-01  39362.59
28 2019-02-01  47598.51
29 2019-03-01  37099.40
periodo de elegibilidade : [datetime.date(2018, 10, 1), datetime.date(2018, 11, 1), datetime.date(2018, 12, 1), datetime.date(2019, 1, 1), datetime.date(2019, 2, 1), datetime.date(2019, 3, 1)]
         data     valor
0  2016-10-01   8802.08
1  2016-11-01   7507.10
2  2016-12-01  21007.98
3  2017-01-01  11027.68
4  2017-02-01   3043.62
5  2017-03-01  21274.86
6  2017-04-01   9313.97
7  2017-05-01  12955.98
8  2017-06-01   8124.44
9  2017-07-01      0.00
10 2017-08-01      0.00
11 2017-09-01      0.00
12 2017-10-01      0.00
13 2017-11-01      0.00
14 2017-12-01      0.00
15 2018-01-01      0.00
16 2018-02-01      0.00
17 2018-03-01      0.00
18 2018-04-01   6758.76
19 2018-05-01  32007.05
20 2018-06-01  31045.92
21 2018-07-01  44612.20
22 2018-08-01   8266.71
23 2018-09-01  37518.90
24 2018-10-01  42439.85
25 2018-11-01  51878.15
26 2018-12-01  23269.16
27 2019-01-01  39362.59
28 2019-02-01  47598.51
29 2019-03-01  37099.40
probabilidade_zeros :0.0
score : 699.590909090909
         data     valor
0  2014-05-01   2695.00
1  2014-06-01   6550.56
2  2014-07-01   7627.67
3  2014-08-01  12421.14
4  2014-09-01  14894.64
5  2014-10-01  14626.81
6  2014-11-01  14026.07
7  2014-12-01  14238.67
8  2015-01-01   9517.34
9  2015-02-01   9402.82
10 2015-03-01  16094.59
11 2015-04-01  15158.78
12 2015-05-01  13837.81
13 2015-06-01  19030.46
14 2015-07-01  15544.30
15 2015-08-01  12959.79
16 2015-09-01  10057.57
17 2015-10-01  10180.83
18 2015-11-01  14363.96
19 2015-12-01   8378.36
20 2016-01-01   6842.59
21 2016-02-01   9039.68
22 2016-03-01  12362.88
23 2016-04-01  11753.58
24 2016-05-01  18909.35
25 2016-06-01  16903.34
26 2016-07-01  16234.13
27 2016-08-01  19375.51
28 2016-09-01  15728.86
29 2016-10-01  17493.18
30 2016-11-01  12357.70
31 2016-12-01  10482.30
32 2017-01-01  10732.61
33 2017-02-01   8288.44
34 2017-03-01  14482.39
35 2017-04-01   7119.93
36 2017-05-01  11277.24
37 2017-06-01   9095.84
38 2017-07-01  10592.39
39 2017-08-01  11853.72
40 2017-09-01  11432.25
41 2017-10-01  14991.18
42 2017-11-01  10443.31
43 2017-12-01  13164.85
44 2018-01-01   7345.93
45 2018-02-01   8345.18
46 2018-03-01  13325.74
47 2018-04-01   9935.56
48 2018-05-01   5978.87
49 2018-06-01   6228.87
50 2018-07-01   1702.98
51 2018-08-01   3587.33
52 2018-09-01   5355.16
53 2018-10-01   5270.19
54 2018-11-01   3686.39
55 2018-12-01   6502.14
56 2019-01-01   3470.47
57 2019-02-01   1805.00
58 2019-03-01   5602.82
periodo de elegibilidade : [datetime.date(2018, 10, 1), datetime.date(2018, 11, 1), datetime.date(2018, 12, 1), datetime.date(2019, 1, 1), datetime.date(2019, 2, 1), datetime.date(2019, 3, 1)]
         data     valor
0  2014-05-01   2695.00
1  2014-06-01   6550.56
2  2014-07-01   7627.67
3  2014-08-01  12421.14
4  2014-09-01  14894.64
5  2014-10-01  14626.81
6  2014-11-01  14026.07
7  2014-12-01  14238.67
8  2015-01-01   9517.34
9  2015-02-01   9402.82
10 2015-03-01  16094.59
11 2015-04-01  15158.78
12 2015-05-01  13837.81
13 2015-06-01  19030.46
14 2015-07-01  15544.30
15 2015-08-01  12959.79
16 2015-09-01  10057.57
17 2015-10-01  10180.83
18 2015-11-01  14363.96
19 2015-12-01   8378.36
20 2016-01-01   6842.59
21 2016-02-01   9039.68
22 2016-03-01  12362.88
23 2016-04-01  11753.58
24 2016-05-01  18909.35
25 2016-06-01  16903.34
26 2016-07-01  16234.13
27 2016-08-01  19375.51
28 2016-09-01  15728.86
29 2016-10-01  17493.18
30 2016-11-01  12357.70
31 2016-12-01  10482.30
32 2017-01-01  10732.61
33 2017-02-01   8288.44
34 2017-03-01  14482.39
35 2017-04-01   7119.93
36 2017-05-01  11277.24
37 2017-06-01   9095.84
38 2017-07-01  10592.39
39 2017-08-01  11853.72
40 2017-09-01  11432.25
41 2017-10-01  14991.18
42 2017-11-01  10443.31
43 2017-12-01  13164.85
44 2018-01-01   7345.93
45 2018-02-01   8345.18
46 2018-03-01  13325.74
47 2018-04-01   9935.56
48 2018-05-01   5978.87
49 2018-06-01   6228.87
50 2018-07-01   1702.98
51 2018-08-01   3587.33
52 2018-09-01   5355.16
53 2018-10-01   5270.19
54 2018-11-01   3686.39
55 2018-12-01   6502.14
56 2019-01-01   3470.47
57 2019-02-01   1805.00
58 2019-03-01   5602.82
probabilidade_zeros :0.0

         data     valor
0  2016-11-01   6449.26
1  2016-12-01   8733.30
2  2017-01-01   7723.86
3  2017-02-01   6751.78
4  2017-03-01  10517.24
5  2017-04-01   7267.52
6  2017-05-01  13974.44
7  2017-06-01  15213.85
8  2017-07-01   2903.46
9  2017-08-01   4793.58
10 2017-09-01   3896.32
11 2017-10-01  15324.06
12 2017-11-01   7239.92
13 2017-12-01  13717.44
14 2018-01-01   6422.40
15 2018-02-01   1015.08
16 2018-03-01   7343.50
17 2018-04-01   9085.92
18 2018-05-01   6853.87
19 2018-06-01  21525.91
20 2018-07-01  11645.21
21 2018-08-01  17599.25
22 2018-09-01  15632.28
23 2018-10-01  13174.85
24 2018-11-01  15958.16
25 2018-12-01  25810.62
26 2019-01-01  11416.41
27 2019-02-01  14864.80
28 2019-03-01  12007.77
periodo de elegibilidade : [datetime.date(2018, 10, 1), datetime.date(2018, 11, 1), datetime.date(2018, 12, 1), datetime.date(2019, 1, 1), datetime.date(2019, 2, 1), datetime.date(2019, 3, 1)]
         data     valor
0  2016-11-01   6449.26
1  2016-12-01   8733.30
2  2017-01-01   7723.86
3  2017-02-01   6751.78
4  2017-03-01  10517.24
5  2017-04-01   7267.52
6  2017-05-01  13974.44
7  2017-06-01  15213.85
8  2017-07-01   2903.46
9  2017-08-01   4793.58
10 2017-09-01   3896.32
11 2017-10-01  15324.06
12 2017-11-01   7239.92
13 2017-12-01  13717.44
14 2018-01-01   6422.40
15 2018-02-01   1015.08
16 2018-03-01   7343.50
17 2018-04-01   9085.92
18 2018-05-01   6853.87
19 2018-06-01  21525.91
20 2018-07-01  11645.21
21 2018-08-01  17599.25
22 2018-09-01  15632.28
23 2018-10-01  13174.85
24 2018-11-01  15958.16
25 2018-12-01  25810.62
26 2019-01-01  11416.41
27 2019-02-01  14864.80
28 2019-03-01  12007.77
probabilidade_zeros :0.0
score : 691.7303030303029
         data     valor
0  2015-12-01   1998.00
1  2016-01-01    749.25
2  2016-02-01   2279.85
3  2016-03-01   8623.45
4  2016-04-01   2688.15
5  2016-05-01   4092.55
6  2016-06-01   6307.30
7  2016-07-01  12297.15
8  2016-08-01  12974.15
9  2016-09-01  13629.10
10 2016-10-01   2858.55
11 2016-11-01  15574.35
12 2016-12-01  32095.70
13 2017-01-01  16073.04
14 2017-02-01   3391.81
15 2017-03-01   4318.42
16 2017-04-01   3013.98
17 2017-05-01    809.52
18 2017-06-01    486.72
19 2017-07-01    809.52
20 2017-08-01      0.00
21 2017-09-01  22093.87
22 2017-10-01  12476.74
23 2017-11-01  11333.05
24 2017-12-01  17480.83
25 2018-01-01  23261.43
26 2018-02-01  11038.28
27 2018-03-01  20274.61
28 2018-04-01  16732.91
29 2018-05-01  20691.94
30 2018-06-01  11376.39
31 2018-07-01  30703.76
32 2018-08-01  29697.98
33 2018-09-01  26203.81
34 2018-10-01  14052.52
35 2018-11-01  29016.28
36 2018-12-01  23335.14
37 2019-01-01  38041.96
38 2019-02-01  18719.33
39 2019-03-01    250.00
periodo de elegibilidade : [datetime.date(2018, 10, 1), datetime.date(2018, 11, 1), datetime.date(2018, 12, 1), datetime.date(2019, 1, 1), datetime.date(2019, 2, 1), datetime.date(2019, 3, 1)]
         data     valor
0  2015-12-01   1998.00
1  2016-01-01    749.25
2  2016-02-01   2279.85
3  2016-03-01   8623.45
4  2016-04-01   2688.15
5  2016-05-01   4092.55
6  2016-06-01   6307.30
7  2016-07-01  12297.15
8  2016-08-01  12974.15
9  2016-09-01  13629.10
10 2016-10-01   2858.55
11 2016-11-01  15574.35
12 2016-12-01  32095.70
13 2017-01-01  16073.04
14 2017-02-01   3391.81
15 2017-03-01   4318.42
16 2017-04-01   3013.98
17 2017-05-01    809.52
18 2017-06-01    486.72
19 2017-07-01    809.52
20 2017-08-01      0.00
21 2017-09-01  22093.87
22 2017-10-01  12476.74
23 2017-11-01  11333.05
24 2017-12-01  17480.83
25 2018-01-01  23261.43
26 2018-02-01  11038.28
27 2018-03-01  20274.61
28 2018-04-01  16732.91
29 2018-05-01  20691.94
30 2018-06-01  11376.39
31 2018-07-01  30703.76
32 2018-08-01  29697.98
33 2018-09-01  26203.81
34 2018-10-01  14052.52
35 2018-11-01  29016.28
36 2018-12-01  23335.14
37 2019-01-01  38041.96
38 2019-02-01  18719.33
39 2019-03-01    250.00
probabilidade_zeros :0.0
score : 383.1750841750841
        data     valor
0 2018-08-01   7282.15
1 2018-09-01  17890.28
2 2018-10-01  29327.53
3 2018-11-01   8284.20
4 2018-12-01  12478.46
5 2019-01-01  15251.20
6 2019-02-01  15226.34
7 2019-03-01   7586.31
periodo de elegibilidade : [datetime.date(2018, 10, 1), datetime.date(2018, 11, 1), datetime.date(2018, 12, 1), datetime.date(2019, 1, 1), datetime.date(2019, 2, 1), datetime.date(2019, 3, 1)]
        data     valor
0 2018-08-01   7282.15
1 2018-09-01  17890.28
2 2018-10-01  29327.53
3 2018-11-01   8284.20
4 2018-12-01  12478.46
5 2019-01-01  15251.20
6 2019-02-01  15226.34
7 2019-03-01   7586.31
probabilidade_zeros :0.0
score : 570.4612794612793
         data     valor
0  2013-09-01    200.00
1  2013-10-01   8200.00
2  2013-11-01   9365.00
3  2013-12-01   4800.00
4  2014-01-01   8053.40
5  2014-02-01   8754.21
6  2014-03-01   4263.62
7  2014-04-01   4120.83
8  2014-05-01   4607.28
9  2014-06-01   2466.38
10 2014-07-01   9079.32
11 2014-08-01   7536.25
12 2014-09-01   8680.70
13 2014-10-01   8031.82
14 2014-11-01   8946.54
15 2014-12-01   4091.81
16 2015-01-01   3347.37
17 2015-02-01   3734.01
18 2015-03-01   4904.44
19 2015-04-01   2583.00
20 2015-05-01   3491.00
21 2015-06-01   2318.30
22 2015-07-01   1450.01
23 2015-08-01   1506.11
24 2015-09-01   1891.38
25 2015-10-01   3709.64
26 2015-11-01   4164.12
27 2015-12-01   4599.59
28 2016-01-01   4245.12
29 2016-02-01   5731.61
..        ...       ...
37 2016-10-01   5583.95
38 2016-11-01   2933.27
39 2016-12-01   3262.62
40 2017-01-01   3128.75
41 2017-02-01   4530.66
42 2017-03-01   5265.10
43 2017-04-01   3805.47
44 2017-05-01   3496.37
45 2017-06-01   5611.13
46 2017-07-01  10910.75
47 2017-08-01   7039.05
48 2017-09-01   7239.87
49 2017-10-01   5960.51
50 2017-11-01   6994.01
51 2017-12-01   3962.58
52 2018-01-01   3775.25
53 2018-02-01   6994.41
54 2018-03-01   8405.47
55 2018-04-01   6410.36
56 2018-05-01   4569.42
57 2018-06-01   4450.13
58 2018-07-01   3140.00
59 2018-08-01   4327.90
60 2018-09-01   4794.87
61 2018-10-01   4553.22
62 2018-11-01   3191.00
63 2018-12-01   3586.00
64 2019-01-01   7194.67
65 2019-02-01   5663.05
66 2019-03-01   5281.26

[67 rows x 2 columns]
periodo de elegibilidade : [datetime.date(2018, 10, 1), datetime.date(2018, 11, 1), datetime.date(2018, 12, 1), datetime.date(2019, 1, 1), datetime.date(2019, 2, 1), datetime.date(2019, 3, 1)]
         data     valor
0  2013-09-01    200.00
1  2013-10-01   8200.00
2  2013-11-01   9365.00
3  2013-12-01   4800.00
4  2014-01-01   8053.40
5  2014-02-01   8754.21
6  2014-03-01   4263.62
7  2014-04-01   4120.83
8  2014-05-01   4607.28
9  2014-06-01   2466.38
10 2014-07-01   9079.32
11 2014-08-01   7536.25
12 2014-09-01   8680.70
13 2014-10-01   8031.82
14 2014-11-01   8946.54
15 2014-12-01   4091.81
16 2015-01-01   3347.37
17 2015-02-01   3734.01
18 2015-03-01   4904.44
19 2015-04-01   2583.00
20 2015-05-01   3491.00
21 2015-06-01   2318.30
22 2015-07-01   1450.01
23 2015-08-01   1506.11
24 2015-09-01   1891.38
25 2015-10-01   3709.64
26 2015-11-01   4164.12
27 2015-12-01   4599.59
28 2016-01-01   4245.12
29 2016-02-01   5731.61
..        ...       ...
37 2016-10-01   5583.95
38 2016-11-01   2933.27
39 2016-12-01   3262.62
40 2017-01-01   3128.75
41 2017-02-01   4530.66
42 2017-03-01   5265.10
43 2017-04-01   3805.47
44 2017-05-01   3496.37
45 2017-06-01   5611.13
46 2017-07-01  10910.75
47 2017-08-01   7039.05
48 2017-09-01   7239.87
49 2017-10-01   5960.51
50 2017-11-01   6994.01
51 2017-12-01   3962.58
52 2018-01-01   3775.25
53 2018-02-01   6994.41
54 2018-03-01   8405.47
55 2018-04-01   6410.36
56 2018-05-01   4569.42
57 2018-06-01   4450.13
58 2018-07-01   3140.00
59 2018-08-01   4327.90
60 2018-09-01   4794.87
61 2018-10-01   4553.22
62 2018-11-01   3191.00
63 2018-12-01   3586.00
64 2019-01-01   7194.67
65 2019-02-01   5663.05
66 2019-03-01   5281.26

[67 rows x 2 columns]
probabilidade_zeros :0.0
         data     valor
0  2015-11-01   3796.78
1  2015-12-01   8877.50
2  2016-01-01   9093.45
3  2016-02-01   7990.95
4  2016-03-01  11250.40
5  2016-04-01  13675.15
6  2016-05-01  11357.50
7  2016-06-01  17818.95
8  2016-07-01  10204.15
9  2016-08-01  17868.90
10 2016-09-01  11298.48
11 2016-10-01  21079.09
12 2016-11-01  19283.38
13 2016-12-01   8597.39
14 2017-01-01  22196.05
15 2017-02-01  11778.13
16 2017-03-01   9184.05
17 2017-04-01  14167.38
18 2017-05-01  14132.38
19 2017-06-01   7109.13
20 2017-07-01  15155.13
21 2017-08-01  23334.18
22 2017-09-01  24094.91
23 2017-10-01  21316.61
24 2017-11-01  32667.43
25 2017-12-01  38989.29
26 2018-01-01  30752.08
27 2018-02-01  21769.98
28 2018-03-01  36911.49
29 2018-04-01  31215.99
30 2018-05-01  22564.69
31 2018-06-01  14558.86
32 2018-07-01  24212.34
33 2018-08-01  19882.82
34 2018-09-01  21298.10
35 2018-10-01  23887.29
36 2018-11-01  16166.08
37 2018-12-01  21239.00
38 2019-01-01  32658.46
39 2019-02-01  15651.70
40 2019-03-01   4989.68
periodo de elegibilidade : [datetime.date(2018, 10, 1), datetime.date(2018, 11, 1), datetime.date(2018, 12, 1), datetime.date(2019, 1, 1), datetime.date(2019, 2, 1), datetime.date(2019, 3, 1)]
         data     valor
0  2015-11-01   3796.78
1  2015-12-01   8877.50
2  2016-01-01   9093.45
3  2016-02-01   7990.95
4  2016-03-01  11250.40
5  2016-04-01  13675.15
6  2016-05-01  11357.50
7  2016-06-01  17818.95
8  2016-07-01  10204.15
9  2016-08-01  17868.90
10 2016-09-01  11298.48
11 2016-10-01  21079.09
12 2016-11-01  19283.38
13 2016-12-01   8597.39
14 2017-01-01  22196.05
15 2017-02-01  11778.13
16 2017-03-01   9184.05
17 2017-04-01  14167.38
18 2017-05-01  14132.38
19 2017-06-01   7109.13
20 2017-07-01  15155.13
21 2017-08-01  23334.18
22 2017-09-01  24094.91
23 2017-10-01  21316.61
24 2017-11-01  32667.43
25 2017-12-01  38989.29
26 2018-01-01  30752.08
27 2018-02-01  21769.98
28 2018-03-01  36911.49
29 2018-04-01  31215.99
30 2018-05-01  22564.69
31 2018-06-01  14558.86
32 2018-07-01  24212.34
33 2018-08-01  19882.82
34 2018-09-01  21298.10
35 2018-10-01  23887.29
36 2018-11-01  16166.08
37 2018-12-01  21239.00
38 2019-01-01  32658.46
39 2019-02-01  15651.70
40 2019-03-01   4989.68
probabilidade_zeros :0.0

         data     valor
0  2017-02-01   5636.61
1  2017-03-01   6149.40
2  2017-04-01   3954.33
3  2017-05-01   5782.33
4  2017-06-01   6401.59
5  2017-07-01   3329.02
6  2017-08-01   8532.73
7  2017-09-01  11236.42
8  2017-10-01  10547.70
9  2017-11-01  13745.12
10 2017-12-01  17779.34
11 2018-01-01  12459.47
12 2018-02-01  13602.69
13 2018-03-01   8004.81
14 2018-04-01  10889.86
15 2018-05-01  11003.70
16 2018-06-01  32769.80
17 2018-07-01  26922.14
18 2018-08-01  28891.43
19 2018-09-01  22360.99
20 2018-10-01  22341.48
21 2018-11-01  19952.37
22 2018-12-01  32896.34
23 2019-01-01  31683.82
24 2019-02-01  26271.47
25 2019-03-01  28420.04
periodo de elegibilidade : [datetime.date(2018, 10, 1), datetime.date(2018, 11, 1), datetime.date(2018, 12, 1), datetime.date(2019, 1, 1), datetime.date(2019, 2, 1), datetime.date(2019, 3, 1)]
         data     valor
0  2017-02-01   5636.61
1  2017-03-01   6149.40
2  2017-04-01   3954.33
3  2017-05-01   5782.33
4  2017-06-01   6401.59
5  2017-07-01   3329.02
6  2017-08-01   8532.73
7  2017-09-01  11236.42
8  2017-10-01  10547.70
9  2017-11-01  13745.12
10 2017-12-01  17779.34
11 2018-01-01  12459.47
12 2018-02-01  13602.69
13 2018-03-01   8004.81
14 2018-04-01  10889.86
15 2018-05-01  11003.70
16 2018-06-01  32769.80
17 2018-07-01  26922.14
18 2018-08-01  28891.43
19 2018-09-01  22360.99
20 2018-10-01  22341.48
21 2018-11-01  19952.37
22 2018-12-01  32896.34
23 2019-01-01  31683.82
24 2019-02-01  26271.47
25 2019-03-01  28420.04
probabilidade_zeros :0.0
score : 824.3030303030304
         data     valor
0  2016-04-01    251.62
1  2016-05-01   1958.31
2  2016-06-01      0.00
3  2016-07-01   1674.59
4  2016-08-01      0.00
5  2016-09-01      0.00
6  2016-10-01      0.00
7  2016-11-01      0.00
8  2016-12-01      0.00
9  2017-01-01      0.00
10 2017-02-01      0.00
11 2017-03-01      0.00
12 2017-04-01      0.00
13 2017-05-01      0.00
14 2017-06-01      0.00
15 2017-07-01      0.00
16 2017-08-01      0.00
17 2017-09-01   8396.36
18 2017-10-01  28816.22
19 2017-11-01  22560.14
20 2017-12-01  29112.50
21 2018-01-01  20520.50
22 2018-02-01  11122.96
23 2018-03-01  16831.12
24 2018-04-01  20646.17
25 2018-05-01  30389.52
26 2018-06-01  31992.92
27 2018-07-01  26859.44
28 2018-08-01  63541.42
29 2018-09-01  39557.01
30 2018-10-01  43351.20
31 2018-11-01  47993.22
32 2018-12-01  42441.92
33 2019-01-01  44336.36
34 2019-02-01  43997.11
35 2019-03-01  52596.80
periodo de elegibilidade : [datetime.date(2018, 10, 1), datetime.date(2018, 11, 1), datetime.date(2018, 12, 1), datetime.date(2019, 1, 1), datetime.date(2019, 2, 1), datetime.date(2019, 3, 1)]
         data     valor
0  2016-04-01    251.62
1  2016-05-01   1958.31
2  2016-06-01      0.00
3  2016-07-01   1674.59
4  2016-08-01      0.00
5  2016-09-01      0.00
6  2016-10-01      0.00
7  2016-11-01      0.00
8  2016-12-01      0.00
9  2017-01-01      0.00
10 2017-02-01      0.00
11 2017-03-01      0.00
12 2017-04-01      0.00
13 2017-05-01      0.00
14 2017-06-01      0.00
15 2017-07-01      0.00
16 2017-08-01      0.00
17 2017-09-01   8396.36
18 2017-10-01  28816.22
19 2017-11-01  22560.14
20 2017-12-01  29112.50
21 2018-01-01  20520.50
22 2018-02-01  11122.96
23 2018-03-01  16831.12
24 2018-04-01  20646.17
25 2018-05-01  30389.52
26 2018-06-01  31992.92
27 2018-07-01  26859.44
28 2018-08-01  63541.42
29 2018-09-01  39557.01
30 2018-10-01  43351.20
31 2018-11-01  47993.22
32 2018-12-01  42441.92
33 2019-01-01  44336.36
34 2019-02-01  43997.11
35 2019-03-01  52596.80
probabilidade_zeros :0.0
score : 826.9757575757576
         data     valor
0  2016-08-01     70.02
1  2016-09-01   3505.20
2  2016-10-01   1059.26
3  2016-11-01    946.28
4  2016-12-01   4403.80
5  2017-01-01      0.00
6  2017-02-01   5581.90
7  2017-03-01   6028.82
8  2017-04-01   2026.52
9  2017-05-01   5241.38
10 2017-06-01   5431.44
11 2017-07-01   2957.50
12 2017-08-01   4476.08
13 2017-09-01   7628.94
14 2017-10-01   2221.70
15 2017-11-01    375.58
16 2017-12-01  10402.86
17 2018-01-01   2636.46
18 2018-02-01    636.98
19 2018-03-01    448.58
20 2018-04-01   5292.58
21 2018-05-01   4474.68
22 2018-06-01   4247.74
23 2018-07-01   1695.28
24 2018-08-01   7281.94
25 2018-09-01   2166.58
26 2018-10-01    564.16
27 2018-11-01   6060.42
28 2018-12-01   6163.74
29 2019-01-01   3466.76
30 2019-02-01   1701.76
31 2019-03-01   2648.68
periodo de elegibilidade : [datetime.date(2018, 10, 1), datetime.date(2018, 11, 1), datetime.date(2018, 12, 1), datetime.date(2019, 1, 1), datetime.date(2019, 2, 1), datetime.date(2019, 3, 1)]
         data     valor
0  2016-08-01     70.02
1  2016-09-01   3505.20
2  2016-10-01   1059.26
3  2016-11-01    946.28
4  2016-12-01   4403.80
5  2017-01-01      0.00
6  2017-02-01   5581.90
7  2017-03-01   6028.82
8  2017-04-01   2026.52
9  2017-05-01   5241.38
10 2017-06-01   5431.44
11 2017-07-01   2957.50
12 2017-08-01   4476.08
13 2017-09-01   7628.94
14 2017-10-01   2221.70
15 2017-11-01    375.58
16 2017-12-01  10402.86
17 2018-01-01   2636.46
18 2018-02-01    636.98
19 2018-03-01    448.58
20 2018-04-01   5292.58
21 2018-05-01   4474.68
22 2018-06-01   4247.74
23 2018-07-01   1695.28
24 2018-08-01   7281.94
25 2018-09-01   2166.58
26 2018-10-01    564.16
27 2018-11-01   6060.42
28 2018-12-01   6163.74
29 2019-01-01   3466.76
30 2019-02-01   1701.76
31 2019-03-01   2648.68
probabilidade_zeros :0.0
         data     valor
0  2017-11-01   4457.15
1  2017-12-01  25817.65
2  2018-01-01  45620.27
3  2018-02-01  17426.27
4  2018-03-01  26027.49
5  2018-04-01  19703.11
6  2018-05-01  13940.54
7  2018-06-01  18612.09
8  2018-07-01  16087.49
9  2018-08-01  33689.09
10 2018-09-01  11819.84
11 2018-10-01  20167.54
12 2018-11-01  24408.57
13 2018-12-01  15604.04
14 2019-01-01  33618.61
15 2019-02-01  37525.27
16 2019-03-01  29185.78
periodo de elegibilidade : [datetime.date(2018, 10, 1), datetime.date(2018, 11, 1), datetime.date(2018, 12, 1), datetime.date(2019, 1, 1), datetime.date(2019, 2, 1), datetime.date(2019, 3, 1)]
         data     valor
0  2017-11-01   4457.15
1  2017-12-01  25817.65
2  2018-01-01  45620.27
3  2018-02-01  17426.27
4  2018-03-01  26027.49
5  2018-04-01  19703.11
6  2018-05-01  13940.54
7  2018-06-01  18612.09
8  2018-07-01  16087.49
9  2018-08-01  33689.09
10 2018-09-01  11819.84
11 2018-10-01  20167.54
12 2018-11-01  24408.57
13 2018-12-01  15604.04
14 2019-01-01  33618.61
15 2019-02-01  37525.27
16 2019-03-01  29185.78
probabilidade_zeros :0.0
score : 748.0060606060606
         data     valor
0  2017-07-01   2482.25
1  2017-08-01   8834.47
2  2017-09-01   7786.09
3  2017-10-01   9012.71
4  2017-11-01   6360.08
5  2017-12-01   8772.27
6  2018-01-01   6824.87
7  2018-02-01   4786.36
8  2018-03-01   6717.16
9  2018-04-01   6839.55
10 2018-05-01   8228.71
11 2018-06-01   6512.62
12 2018-07-01   6176.67
13 2018-08-01  12017.02
14 2018-09-01   8580.76
15 2018-10-01   9464.24
16 2018-11-01  11953.20
17 2018-12-01  10983.12
18 2019-01-01  13404.02
19 2019-02-01  11114.28
20 2019-03-01  10043.98
periodo de elegibilidade : [datetime.date(2018, 10, 1), datetime.date(2018, 11, 1), datetime.date(2018, 12, 1), datetime.date(2019, 1, 1), datetime.date(2019, 2, 1), datetime.date(2019, 3, 1)]
         data     valor
0  2017-07-01   2482.25
1  2017-08-01   8834.47
2  2017-09-01   7786.09
3  2017-10-01   9012.71
4  2017-11-01   6360.08
5  2017-12-01   8772.27
6  2018-01-01   6824.87
7  2018-02-01   4786.36
8  2018-03-01   6717.16
9  2018-04-01   6839.55
10 2018-05-01   8228.71
11 2018-06-01   6512.62
12 2018-07-01   6176.67
13 2018-08-01  12017.02
14 2018-09-01   8580.76
15 2018-10-01   9464.24
16 2018-11-01  11953.20
17 2018-12-01  10983.12
18 2019-01-01  13404.02
19 2019-02-01  11114.28
20 2019-03-01  10043.98
probabilidade_zeros :0.0
score : 763.0
        data     valor
0 2018-10-01  12461.13
1 2018-11-01   5490.14
2 2018-12-01   5682.28
3 2019-01-01   6590.75
4 2019-02-01  15008.69
5 2019-03-01  12429.88
periodo de elegibilidade : [datetime.date(2018, 10, 1), datetime.date(2018, 11, 1), datetime.date(2018, 12, 1), datetime.date(2019, 1, 1), datetime.date(2019, 2, 1), datetime.date(2019, 3, 1)]
        data     valor
0 2018-10-01  12461.13
1 2018-11-01   5490.14
2 2018-12-01   5682.28
3 2019-01-01   6590.75
4 2019-02-01  15008.69
5 2019-03-01  12429.88
probabilidade_zeros :0.0

score : 834.9515151515152
         data     valor
0  2017-10-01   1019.34
1  2017-11-01  10194.54
2  2017-12-01      0.00
3  2018-01-01   5481.67
4  2018-02-01  54450.07
5  2018-03-01  17911.03
6  2018-04-01  12663.72
7  2018-05-01  15090.28
8  2018-06-01  15581.66
9  2018-07-01  14728.30
10 2018-08-01  61532.73
11 2018-09-01  37155.14
12 2018-10-01  14612.72
13 2018-11-01  13644.06
14 2018-12-01  17781.46
15 2019-01-01  31400.97
16 2019-02-01  27121.24
17 2019-03-01  20591.17
periodo de elegibilidade : [datetime.date(2018, 10, 1), datetime.date(2018, 11, 1), datetime.date(2018, 12, 1), datetime.date(2019, 1, 1), datetime.date(2019, 2, 1), datetime.date(2019, 3, 1)]
         data     valor
0  2017-10-01   1019.34
1  2017-11-01  10194.54
2  2017-12-01      0.00
3  2018-01-01   5481.67
4  2018-02-01  54450.07
5  2018-03-01  17911.03
6  2018-04-01  12663.72
7  2018-05-01  15090.28
8  2018-06-01  15581.66
9  2018-07-01  14728.30
10 2018-08-01  61532.73
11 2018-09-01  37155.14
12 2018-10-01  14612.72
13 2018-11-01  13644.06
14 2018-12-01  17781.46
15 2019-01-01  31400.97
16 2019-02-01  27121.24
17 2019-03-01  20591.17
probabilidade_zeros :0.0
score : 646.7666666666668
         data     valor
0  2013-11-01   5983.76
1  2013-12-01   9050.52
2  2014-01-01   9598.29
3  2014-02-01  14362.50
4  2014-03-01  14519.07
5  2014-04-01  12224.98
6  2014-05-01  12363.35
7  2014-06-01   7214.57
8  2014-07-01   9325.59
9  2014-08-01   5968.24
10 2014-09-01   5373.54
11 2014-10-01   7437.05
12 2014-11-01  10832.60
13 2014-12-01  10565.25
14 2015-01-01   9044.39
15 2015-02-01   6415.84
16 2015-03-01   4744.78
17 2015-04-01   5638.67
18 2015-05-01   6994.84
19 2015-06-01  11186.12
20 2015-07-01  11730.89
21 2015-08-01   9594.36
22 2015-09-01   7529.86
23 2015-10-01   5675.46
24 2015-11-01   3416.67
25 2015-12-01   4255.43
26 2016-01-01   4241.74
27 2016-02-01   5400.13
28 2016-03-01   8961.32
29 2016-04-01   5675.00
..        ...       ...
35 2016-10-01   1140.00
36 2016-11-01      0.00
37 2016-12-01   1770.00
38 2017-01-01   3225.00
39 2017-02-01   3253.50
40 2017-03-01   3225.00
41 2017-04-01   3221.66
42 2017-05-01   2141.67
43 2017-06-01   1826.67
44 2017-07-01   3060.00
45 2017-08-01   3400.00
46 2017-09-01   2195.00
47 2017-10-01   2195.00
48 2017-11-01   1375.00
49 2017-12-01    330.00
50 2018-01-01   1355.00
51 2018-02-01   1315.00
52 2018-03-01   1360.00
53 2018-04-01    870.00
54 2018-05-01    870.00
55 2018-06-01    835.00
56 2018-07-01    275.00
57 2018-08-01    677.01
58 2018-09-01      0.00
59 2018-10-01    333.33
60 2018-11-01    833.33
61 2018-12-01    250.00
62 2019-01-01    250.00
63 2019-02-01   3263.24
64 2019-03-01   7611.96

[65 rows x 2 columns]
periodo de elegibilidade : [datetime.date(2018, 10, 1), datetime.date(2018, 11, 1), datetime.date(2018, 12, 1), datetime.date(2019, 1, 1), datetime.date(2019, 2, 1), datetime.date(2019, 3, 1)]
         data     valor
0  2013-11-01   5983.76
1  2013-12-01   9050.52
2  2014-01-01   9598.29
3  2014-02-01  14362.50
4  2014-03-01  14519.07
5  2014-04-01  12224.98
6  2014-05-01  12363.35
7  2014-06-01   7214.57
8  2014-07-01   9325.59
9  2014-08-01   5968.24
10 2014-09-01   5373.54
11 2014-10-01   7437.05
12 2014-11-01  10832.60
13 2014-12-01  10565.25
14 2015-01-01   9044.39
15 2015-02-01   6415.84
16 2015-03-01   4744.78
17 2015-04-01   5638.67
18 2015-05-01   6994.84
19 2015-06-01  11186.12
20 2015-07-01  11730.89
21 2015-08-01   9594.36
22 2015-09-01   7529.86
23 2015-10-01   5675.46
24 2015-11-01   3416.67
25 2015-12-01   4255.43
26 2016-01-01   4241.74
27 2016-02-01   5400.13
28 2016-03-01   8961.32
29 2016-04-01   5675.00
..        ...       ...
35 2016-10-01   1140.00
36 2016-11-01      0.00
37 2016-12-01   1770.00
38 2017-01-01   3225.00
39 2017-02-01   3253.50
40 2017-03-01   3225.00
41 2017-04-01   3221.66
42 2017-05-01   2141.67
43 2017-06-01   1826.67
44 2017-07-01   3060.00
45 2017-08-01   3400.00
46 2017-09-01   2195.00
47 2017-10-01   2195.00
48 2017-11-01   1375.00
49 2017-12-01    330.00
50 2018-01-01   1355.00
51 2018-02-01   1315.00
52 2018-03-01   1360.00
53 2018-04-01    870.00
54 2018-05-01    870.00
55 2018-06-01    835.00
56 2018-07-01    275.00
57 2018-08-01    677.01
58 2018-09-01      0.00
59 2018-10-01    333.33
60 2018-11-01    833.33
61 2018-12-01    250.00
62 2019-01-01    250.00
63 2019-02-01   3263.24
64 2019-03-01   7611.96

[65 rows x 2 columns]
probabilidade_zeros :0.08333333333333333
score : 744.0
         data     valor
0  2017-03-01   2865.52
1  2017-04-01  15089.01
2  2017-05-01  13791.34
3  2017-06-01   6018.46
4  2017-07-01  18708.46
5  2017-08-01   3161.64
6  2017-09-01    602.19
7  2017-10-01   3971.10
8  2017-11-01   7074.66
9  2017-12-01  18063.62
10 2018-01-01  15202.65
11 2018-02-01   7635.24
12 2018-03-01  19087.97
13 2018-04-01  16966.82
14 2018-05-01   3049.55
15 2018-06-01  14581.71
16 2018-07-01    814.89
17 2018-08-01  33380.99
18 2018-09-01  38389.69
19 2018-10-01  19326.94
20 2018-11-01   5232.63
21 2018-12-01  35042.09
22 2019-01-01  21938.43
23 2019-02-01  12746.60
24 2019-03-01  12298.57
periodo de elegibilidade : [datetime.date(2018, 10, 1), datetime.date(2018, 11, 1), datetime.date(2018, 12, 1), datetime.date(2019, 1, 1), datetime.date(2019, 2, 1), datetime.date(2019, 3, 1)]
         data     valor
0  2017-03-01   2865.52
1  2017-04-01  15089.01
2  2017-05-01  13791.34
3  2017-06-01   6018.46
4  2017-07-01  18708.46
5  2017-08-01   3161.64
6  2017-09-01    602.19
7  2017-10-01   3971.10
8  2017-11-01   7074.66
9  2017-12-01  18063.62
10 2018-01-01  15202.65
11 2018-02-01   7635.24
12 2018-03-01  19087.97
13 2018-04-01  16966.82
14 2018-05-01   3049.55
15 2018-06-01  14581.71
16 2018-07-01    814.89
17 2018-08-01  33380.99
18 2018-09-01  38389.69
19 2018-10-01  19326.94
20 2018-11-01   5232.63
21 2018-12-01  35042.09
22 2019-01-01  21938.43
23 2019-02-01  12746.60
24 2019-03-01  12298.57
probabilidade_zeros :0.08333333333333333
score : 614.9757575757575
        data    valor
0 2018-08-01  3224.94
1 2018-09-01  4097.48
2 2018-10-01  7760.82
3 2018-11-01  2852.01
4 2018-12-01  2383.60
5 2019-01-01  1617.51
6 2019-02-01  1550.87
7 2019-03-01  2237.16
periodo de elegibilidade : [datetime.date(2018, 10, 1), datetime.date(2018, 11, 1), datetime.date(2018, 12, 1), datetime.date(2019, 1, 1), datetime.date(2019, 2, 1), datetime.date(2019, 3, 1)]
        data    valor
0 2018-08-01  3224.94
1 2018-09-01  4097.48
2 2018-10-01  7760.82
3 2018-11-01  2852.01
4 2018-12-01  2383.60
5 2019-01-01  1617.51
6 2019-02-01  1550.87
7 2019-03-01  2237.16
probabilidade_zeros :0.0
score : 616.5272727272727
         data     valor
0  2018-02-01    599.89
1  2018-03-01   8653.52
2  2018-04-01   3901.75
3  2018-05-01   4401.57
4  2018-06-01  10027.00
5  2018-07-01   8157.27
6  2018-08-01   2444.68
7  2018-09-01   1873.69
8  2018-10-01   6729.92
9  2018-11-01   2666.77
10 2018-12-01   7070.00
11 2019-01-01   4932.00
12 2019-02-01   8091.90
13 2019-03-01   8479.97
periodo de elegibilidade : [datetime.date(2018, 10, 1), datetime.date(2018, 11, 1), datetime.date(2018, 12, 1), datetime.date(2019, 1, 1), datetime.date(2019, 2, 1), datetime.date(2019, 3, 1)]
         data     valor
0  2018-02-01    599.89
1  2018-03-01   8653.52
2  2018-04-01   3901.75
3  2018-05-01   4401.57
4  2018-06-01  10027.00
5  2018-07-01   8157.27
6  2018-08-01   2444.68
7  2018-09-01   1873.69
8  2018-10-01   6729.92
9  2018-11-01   2666.77
10 2018-12-01   7070.00
11 2019-01-01   4932.00
12 2019-02-01   8091.90
13 2019-03-01   8479.97
probabilidade_zeros :0.0
score : 738.0848484848484
         data     valor
0  2015-12-01   1512.60
1  2016-01-01   4656.50
2  2016-02-01   5469.45
3  2016-03-01  12067.23
4  2016-04-01   8307.62
5  2016-05-01  11720.50
6  2016-06-01  14248.10
7  2016-07-01  14470.35
8  2016-08-01  14869.65
9  2016-09-01  23849.50
10 2016-10-01  17620.05
11 2016-11-01   8132.50
12 2016-12-01  12173.50
13 2017-01-01  10995.30
14 2017-02-01  12680.50
15 2017-03-01  10038.75
16 2017-04-01  17135.50
17 2017-05-01  26009.54
18 2017-06-01   9807.86
19 2017-07-01  17982.89
20 2017-08-01    486.72
21 2017-09-01  25210.27
22 2017-10-01  25271.84
23 2017-11-01  22836.63
24 2017-12-01   9919.45
25 2018-01-01  24924.86
26 2018-02-01  17784.21
27 2018-03-01  13606.37
28 2018-04-01  19494.33
29 2018-05-01  15221.68
30 2018-06-01  16098.71
31 2018-07-01  19744.08
32 2018-08-01   9322.61
33 2018-09-01  27133.36
34 2018-10-01   9864.56
35 2018-11-01  36140.06
36 2018-12-01  25244.56
37 2019-01-01  28410.84
38 2019-02-01  22531.46
39 2019-03-01  11236.66
periodo de elegibilidade : [datetime.date(2018, 10, 1), datetime.date(2018, 11, 1), datetime.date(2018, 12, 1), datetime.date(2019, 1, 1), datetime.date(2019, 2, 1), datetime.date(2019, 3, 1)]
         data     valor
0  2015-12-01   1512.60
1  2016-01-01   4656.50
2  2016-02-01   5469.45
3  2016-03-01  12067.23
4  2016-04-01   8307.62
5  2016-05-01  11720.50
6  2016-06-01  14248.10
7  2016-07-01  14470.35
8  2016-08-01  14869.65
9  2016-09-01  23849.50
10 2016-10-01  17620.05
11 2016-11-01   8132.50
12 2016-12-01  12173.50
13 2017-01-01  10995.30
14 2017-02-01  12680.50
15 2017-03-01  10038.75
16 2017-04-01  17135.50
17 2017-05-01  26009.54
18 2017-06-01   9807.86
19 2017-07-01  17982.89
20 2017-08-01    486.72
21 2017-09-01  25210.27
22 2017-10-01  25271.84
23 2017-11-01  22836.63
24 2017-12-01   9919.45
25 2018-01-01  24924.86
26 2018-02-01  17784.21
27 2018-03-01  13606.37
28 2018-04-01  19494.33
29 2018-05-01  15221.68
30 2018-06-01  16098.71
31 2018-07-01  19744.08
32 2018-08-01   9322.61
33 2018-09-01  27133.36
34 2018-10-01   9864.56
35 2018-11-01  36140.06
36 2018-12-01  25244.56
37 2019-01-01  28410.84
38 2019-02-01  22531.46
39 2019-03-01  11236.66
probabilidade_zeros :0.0

         data     valor
0  2015-11-01    499.50
1  2015-12-01   2789.46
2  2016-01-01   4797.22
3  2016-02-01  12255.16
4  2016-03-01   5285.50
5  2016-04-01  14732.50
6  2016-05-01  14905.25
7  2016-06-01  13222.88
8  2016-07-01  24652.92
9  2016-08-01  21659.77
10 2016-09-01  18478.75
11 2016-10-01  15045.75
12 2016-11-01  17554.62
13 2016-12-01  16255.48
14 2017-01-01  20267.69
15 2017-02-01   6021.17
16 2017-03-01    792.45
17 2017-04-01   2140.00
18 2017-05-01   6900.41
19 2017-06-01      0.00
20 2017-07-01   7816.16
21 2017-08-01  14335.92
22 2017-09-01   9395.19
23 2017-10-01  21093.51
24 2017-11-01   4176.13
25 2017-12-01  16755.74
26 2018-01-01  16154.07
27 2018-02-01   8714.08
28 2018-03-01  12695.16
29 2018-04-01  18446.77
30 2018-05-01  15554.30
31 2018-06-01  20875.88
32 2018-07-01  33277.52
33 2018-08-01  16409.83
34 2018-09-01  20117.59
35 2018-10-01  27704.29
36 2018-11-01  17648.70
37 2018-12-01  18564.83
38 2019-01-01  44894.88
39 2019-02-01  21398.76
40 2019-03-01  31900.13
periodo de elegibilidade : [datetime.date(2018, 10, 1), datetime.date(2018, 11, 1), datetime.date(2018, 12, 1), datetime.date(2019, 1, 1), datetime.date(2019, 2, 1), datetime.date(2019, 3, 1)]
         data     valor
0  2015-11-01    499.50
1  2015-12-01   2789.46
2  2016-01-01   4797.22
3  2016-02-01  12255.16
4  2016-03-01   5285.50
5  2016-04-01  14732.50
6  2016-05-01  14905.25
7  2016-06-01  13222.88
8  2016-07-01  24652.92
9  2016-08-01  21659.77
10 2016-09-01  18478.75
11 2016-10-01  15045.75
12 2016-11-01  17554.62
13 2016-12-01  16255.48
14 2017-01-01  20267.69
15 2017-02-01   6021.17
16 2017-03-01    792.45
17 2017-04-01   2140.00
18 2017-05-01   6900.41
19 2017-06-01      0.00
20 2017-07-01   7816.16
21 2017-08-01  14335.92
22 2017-09-01   9395.19
23 2017-10-01  21093.51
24 2017-11-01   4176.13
25 2017-12-01  16755.74
26 2018-01-01  16154.07
27 2018-02-01   8714.08
28 2018-03-01  12695.16
29 2018-04-01  18446.77
30 2018-05-01  15554.30
31 2018-06-01  20875.88
32 2018-07-01  33277.52
33 2018-08-01  16409.83
34 2018-09-01  20117.59
35 2018-10-01  27704.29
36 2018-11-01  17648.70
37 2018-12-01  18564.83
38 2019-01-01  44894.88
39 2019-02-01  21398.76
40 2019-03-01  31900.13
probabilidade_zeros :0.0
        data     valor
0 2018-08-01   1701.00
1 2018-09-01   1220.40
2 2018-10-01  15453.94
3 2018-11-01   5720.40
4 2018-12-01   7701.80
5 2019-01-01  23614.86
6 2019-02-01  12707.68
7 2019-03-01  12275.04
periodo de elegibilidade : [datetime.date(2018, 10, 1), datetime.date(2018, 11, 1), datetime.date(2018, 12, 1), datetime.date(2019, 1, 1), datetime.date(2019, 2, 1), datetime.date(2019, 3, 1)]
        data     valor
0 2018-08-01   1701.00
1 2018-09-01   1220.40
2 2018-10-01  15453.94
3 2018-11-01   5720.40
4 2018-12-01   7701.80
5 2019-01-01  23614.86
6 2019-02-01  12707.68
7 2019-03-01  12275.04
probabilidade_zeros :0.0
score : 663.9030303030303
        data     valor
0 2018-10-01      1.04
1 2018-11-01   9085.45
2 2018-12-01  20316.77
3 2019-01-01  35246.84
4 2019-02-01  31125.74
5 2019-03-01  36947.86
periodo de elegibilidade : [datetime.date(2018, 10, 1), datetime.date(2018, 11, 1), datetime.date(2018, 12, 1), datetime.date(2019, 1, 1), datetime.date(2019, 2, 1), datetime.date(2019, 3, 1)]
        data     valor
0 2018-10-01      1.04
1 2018-11-01   9085.45
2 2018-12-01  20316.77
3 2019-01-01  35246.84
4 2019-02-01  31125.74
5 2019-03-01  36947.86
probabilidade_zeros :0.0
score : 890.0181818181818
         data      valor
0  2015-10-01     593.50
1  2015-11-01    2097.25
2  2015-12-01   52040.45
3  2016-01-01   32523.50
4  2016-02-01   30137.00
5  2016-03-01   55703.50
6  2016-04-01   89866.20
7  2016-05-01   81154.55
8  2016-06-01   82520.55
9  2016-07-01   76275.55
10 2016-08-01  167417.30
11 2016-09-01   82557.86
12 2016-10-01   55109.73
13 2016-11-01   87361.40
14 2016-12-01   70083.71
15 2017-01-01  119748.95
16 2017-02-01   90278.62
17 2017-03-01   68202.80
18 2017-04-01   59402.46
19 2017-05-01   39679.29
20 2017-06-01  105801.82
21 2017-07-01   83115.52
22 2017-08-01   72900.84
23 2017-09-01   56565.39
24 2017-10-01   83437.65
25 2017-11-01   55232.60
26 2017-12-01   55367.00
27 2018-01-01  112180.72
28 2018-02-01   54926.68
29 2018-03-01   49185.28
30 2018-04-01   58100.07
31 2018-05-01   90736.25
32 2018-06-01   79749.88
33 2018-07-01   88589.68
34 2018-08-01   92686.78
35 2018-09-01  106016.91
36 2018-10-01   97049.06
37 2018-11-01   54801.72
38 2018-12-01   37888.90
39 2019-01-01  110668.90
40 2019-02-01   61451.52
41 2019-03-01     187.12
periodo de elegibilidade : [datetime.date(2018, 10, 1), datetime.date(2018, 11, 1), datetime.date(2018, 12, 1), datetime.date(2019, 1, 1), datetime.date(2019, 2, 1), datetime.date(2019, 3, 1)]
         data      valor
0  2015-10-01     593.50
1  2015-11-01    2097.25
2  2015-12-01   52040.45
3  2016-01-01   32523.50
4  2016-02-01   30137.00
5  2016-03-01   55703.50
6  2016-04-01   89866.20
7  2016-05-01   81154.55
8  2016-06-01   82520.55
9  2016-07-01   76275.55
10 2016-08-01  167417.30
11 2016-09-01   82557.86
12 2016-10-01   55109.73
13 2016-11-01   87361.40
14 2016-12-01   70083.71
15 2017-01-01  119748.95
16 2017-02-01   90278.62
17 2017-03-01   68202.80
18 2017-04-01   59402.46
19 2017-05-01   39679.29
20 2017-06-01  105801.82
21 2017-07-01   83115.52
22 2017-08-01   72900.84
23 2017-09-01   56565.39
24 2017-10-01   83437.65
25 2017-11-01   55232.60
26 2017-12-01   55367.00
27 2018-01-01  112180.72
28 2018-02-01   54926.68
29 2018-03-01   49185.28
30 2018-04-01   58100.07
31 2018-05-01   90736.25
32 2018-06-01   79749.88
33 2018-07-01   88589.68
34 2018-08-01   92686.78
35 2018-09-01  106016.91
36 2018-10-01   97049.06
37 2018-11-01   54801.72
38 2018-12-01   37888.90
39 2019-01-01  110668.90
40 2019-02-01   61451.52
41 2019-03-01     187.12
probabilidade_zeros :0.0
        data     valor
0 2018-10-01    922.98
1 2018-11-01  23273.71
2 2018-12-01   5432.84
3 2019-01-01   3128.76
4 2019-02-01  14620.55
5 2019-03-01  62072.49
periodo de elegibilidade : [datetime.date(2018, 10, 1), datetime.date(2018, 11, 1), datetime.date(2018, 12, 1), datetime.date(2019, 1, 1), datetime.date(2019, 2, 1), datetime.date(2019, 3, 1)]
        data     valor
0 2018-10-01    922.98
1 2018-11-01  23273.71
2 2018-12-01   5432.84
3 2019-01-01   3128.76
4 2019-02-01  14620.55
5 2019-03-01  62072.49
probabilidade_zeros :0.0
score : 811.0
         data     valor
0  2017-09-01    937.66
1  2017-10-01   5792.60
2  2017-11-01   7478.81
3  2017-12-01   4216.78
4  2018-01-01   6928.32
5  2018-02-01   5657.87
6  2018-03-01   7335.49
7  2018-04-01  10339.94
8  2018-05-01   8930.46
9  2018-06-01   7058.83
10 2018-07-01   7746.28
11 2018-08-01   7042.44
12 2018-09-01   6242.25
13 2018-10-01   2881.49
14 2018-11-01  10337.54
15 2018-12-01   2987.79
16 2019-01-01   2750.95
17 2019-02-01  12133.14
18 2019-03-01   5686.36
periodo de elegibilidade : [datetime.date(2018, 10, 1), datetime.date(2018, 11, 1), datetime.date(2018, 12, 1), datetime.date(2019, 1, 1), datetime.date(2019, 2, 1), datetime.date(2019, 3, 1)]
         data     valor
0  2017-09-01    937.66
1  2017-10-01   5792.60
2  2017-11-01   7478.81
3  2017-12-01   4216.78
4  2018-01-01   6928.32
5  2018-02-01   5657.87
6  2018-03-01   7335.49
7  2018-04-01  10339.94
8  2018-05-01   8930.46
9  2018-06-01   7058.83
10 2018-07-01   7746.28
11 2018-08-01   7042.44
12 2018-09-01   6242.25
13 2018-10-01   2881.49
14 2018-11-01  10337.54
15 2018-12-01   2987.79
16 2019-01-01   2750.95
17 2019-02-01  12133.14
18 2019-03-01   5686.36
probabilidade_zeros :0.0
         data     valor
0  2018-05-01  12501.70
1  2018-06-01  10759.65
2  2018-07-01   7486.61
3  2018-08-01   8375.44
4  2018-09-01  14022.76
5  2018-10-01   8813.68
6  2018-11-01  10687.55
7  2018-12-01  14100.71
8  2019-01-01  13840.79
9  2019-02-01   7143.34
10 2019-03-01   9779.31
periodo de elegibilidade : [datetime.date(2018, 10, 1), datetime.date(2018, 11, 1), datetime.date(2018, 12, 1), datetime.date(2019, 1, 1), datetime.date(2019, 2, 1), datetime.date(2019, 3, 1)]
         data     valor
0  2018-05-01  12501.70
1  2018-06-01  10759.65
2  2018-07-01   7486.61
3  2018-08-01   8375.44
4  2018-09-01  14022.76
5  2018-10-01   8813.68
6  2018-11-01  10687.55
7  2018-12-01  14100.71
8  2019-01-01  13840.79
9  2019-02-01   7143.34
10 2019-03-01   9779.31
probabilidade_zeros :0.0

         data    valor
0  2016-11-01   4280.0
1  2016-12-01  13621.0
2  2017-01-01  25105.0
3  2017-02-01   9195.0
4  2017-03-01  16092.0
5  2017-04-01  15895.0
6  2017-05-01  18310.0
7  2017-06-01  17335.0
8  2017-07-01  15785.0
9  2017-08-01  15607.0
10 2017-09-01  15203.0
11 2017-10-01  14330.0
12 2017-11-01  15420.0
13 2017-12-01  16000.0
14 2018-01-01  30720.0
15 2018-02-01  14400.0
16 2018-03-01  12810.0
17 2018-04-01  12200.0
18 2018-05-01   9120.0
19 2018-06-01  10100.0
20 2018-07-01  10650.0
21 2018-08-01   7750.0
22 2018-09-01   7200.0
23 2018-10-01   7485.0
24 2018-11-01   5163.0
25 2018-12-01   2550.0
26 2019-01-01   1050.0
27 2019-02-01    150.0
28 2019-03-01    150.0
periodo de elegibilidade : [datetime.date(2018, 10, 1), datetime.date(2018, 11, 1), datetime.date(2018, 12, 1), datetime.date(2019, 1, 1), datetime.date(2019, 2, 1), datetime.date(2019, 3, 1)]
         data    valor
0  2016-11-01   4280.0
1  2016-12-01  13621.0
2  2017-01-01  25105.0
3  2017-02-01   9195.0
4  2017-03-01  16092.0
5  2017-04-01  15895.0
6  2017-05-01  18310.0
7  2017-06-01  17335.0
8  2017-07-01  15785.0
9  2017-08-01  15607.0
10 2017-09-01  15203.0
11 2017-10-01  14330.0
12 2017-11-01  15420.0
13 2017-12-01  16000.0
14 2018-01-01  30720.0
15 2018-02-01  14400.0
16 2018-03-01  12810.0
17 2018-04-01  12200.0
18 2018-05-01   9120.0
19 2018-06-01  10100.0
20 2018-07-01  10650.0
21 2018-08-01   7750.0
22 2018-09-01   7200.0
23 2018-10-01   7485.0
24 2018-11-01   5163.0
25 2018-12-01   2550.0
26 2019-01-01   1050.0
27 2019-02-01    150.0
28 2019-03-01    150.0
probabilidade_zeros :0.0
         data      valor
0  2015-10-01    8081.64
1  2015-11-01    9308.77
2  2015-12-01   21585.70
3  2016-01-01   20464.18
4  2016-02-01   33377.55
5  2016-03-01   22171.10
6  2016-04-01   33490.50
7  2016-05-01   49822.10
8  2016-06-01   39461.05
9  2016-07-01   95795.99
10 2016-08-01   94966.55
11 2016-09-01   57530.36
12 2016-10-01   40740.40
13 2016-11-01   64152.77
14 2016-12-01   77208.05
15 2017-01-01   66784.60
16 2017-02-01   33141.40
17 2017-03-01   23017.98
18 2017-04-01   51004.19
19 2017-05-01   43149.29
20 2017-06-01   53185.88
21 2017-07-01   72998.78
22 2017-08-01   65603.11
23 2017-09-01   81740.89
24 2017-10-01   92013.49
25 2017-11-01   94523.54
26 2017-12-01   89342.16
27 2018-01-01  147909.79
28 2018-02-01  101887.08
29 2018-03-01  138340.01
30 2018-04-01   99342.03
31 2018-05-01   83292.99
32 2018-06-01   77186.99
33 2018-07-01  103986.16
34 2018-08-01  100247.70
35 2018-09-01   97087.74
36 2018-10-01  102811.39
37 2018-11-01  125175.25
38 2018-12-01   89004.02
39 2019-01-01  151062.91
40 2019-02-01  107719.90
41 2019-03-01    1860.00
periodo de elegibilidade : [datetime.date(2018, 10, 1), datetime.date(2018, 11, 1), datetime.date(2018, 12, 1), datetime.date(2019, 1, 1), datetime.date(2019, 2, 1), datetime.date(2019, 3, 1)]
         data      valor
0  2015-10-01    8081.64
1  2015-11-01    9308.77
2  2015-12-01   21585.70
3  2016-01-01   20464.18
4  2016-02-01   33377.55
5  2016-03-01   22171.10
6  2016-04-01   33490.50
7  2016-05-01   49822.10
8  2016-06-01   39461.05
9  2016-07-01   95795.99
10 2016-08-01   94966.55
11 2016-09-01   57530.36
12 2016-10-01   40740.40
13 2016-11-01   64152.77
14 2016-12-01   77208.05
15 2017-01-01   66784.60
16 2017-02-01   33141.40
17 2017-03-01   23017.98
18 2017-04-01   51004.19
19 2017-05-01   43149.29
20 2017-06-01   53185.88
21 2017-07-01   72998.78
22 2017-08-01   65603.11
23 2017-09-01   81740.89
24 2017-10-01   92013.49
25 2017-11-01   94523.54
26 2017-12-01   89342.16
27 2018-01-01  147909.79
28 2018-02-01  101887.08
29 2018-03-01  138340.01
30 2018-04-01   99342.03
31 2018-05-01   83292.99
32 2018-06-01   77186.99
33 2018-07-01  103986.16
34 2018-08-01  100247.70
35 2018-09-01   97087.74
36 2018-10-01  102811.39
37 2018-11-01  125175.25
38 2018-12-01   89004.02
39 2019-01-01  151062.91
40 2019-02-01  107719.90
41 2019-03-01    1860.00
probabilidade_zeros :0.0
score : 410.24242424242425
         data     valor
0  2015-11-01   1752.15
1  2015-12-01   6191.00
2  2016-01-01   7429.30
3  2016-02-01   7987.20
4  2016-03-01  11209.40
5  2016-04-01   7111.75
6  2016-05-01   9928.55
7  2016-06-01   7618.15
8  2016-07-01   5797.35
9  2016-08-01   9348.50
10 2016-09-01  13942.00
11 2016-10-01   7004.93
12 2016-11-01  13541.90
13 2016-12-01   2835.85
14 2017-01-01   6294.60
15 2017-02-01      0.00
16 2017-03-01   6905.95
17 2017-04-01  10043.40
18 2017-05-01  10283.00
19 2017-06-01   8125.50
20 2017-07-01  12530.87
21 2017-08-01  13434.15
22 2017-09-01  14607.32
23 2017-10-01   4265.03
24 2017-11-01  20158.57
25 2017-12-01   7819.73
26 2018-01-01  10731.82
27 2018-02-01  17023.69
28 2018-03-01  28026.08
29 2018-04-01  13940.62
30 2018-05-01  13320.49
31 2018-06-01   5350.72
32 2018-07-01  19560.02
33 2018-08-01   7399.60
34 2018-09-01  27862.94
35 2018-10-01  18933.80
36 2018-11-01  25905.05
37 2018-12-01  16244.70
38 2019-01-01  39752.74
39 2019-02-01   9364.62
40 2019-03-01  34523.56
periodo de elegibilidade : [datetime.date(2018, 10, 1), datetime.date(2018, 11, 1), datetime.date(2018, 12, 1), datetime.date(2019, 1, 1), datetime.date(2019, 2, 1), datetime.date(2019, 3, 1)]
         data     valor
0  2015-11-01   1752.15
1  2015-12-01   6191.00
2  2016-01-01   7429.30
3  2016-02-01   7987.20
4  2016-03-01  11209.40
5  2016-04-01   7111.75
6  2016-05-01   9928.55
7  2016-06-01   7618.15
8  2016-07-01   5797.35
9  2016-08-01   9348.50
10 2016-09-01  13942.00
11 2016-10-01   7004.93
12 2016-11-01  13541.90
13 2016-12-01   2835.85
14 2017-01-01   6294.60
15 2017-02-01      0.00
16 2017-03-01   6905.95
17 2017-04-01  10043.40
18 2017-05-01  10283.00
19 2017-06-01   8125.50
20 2017-07-01  12530.87
21 2017-08-01  13434.15
22 2017-09-01  14607.32
23 2017-10-01   4265.03
24 2017-11-01  20158.57
25 2017-12-01   7819.73
26 2018-01-01  10731.82
27 2018-02-01  17023.69
28 2018-03-01  28026.08
29 2018-04-01  13940.62
30 2018-05-01  13320.49
31 2018-06-01   5350.72
32 2018-07-01  19560.02
33 2018-08-01   7399.60
34 2018-09-01  27862.94
35 2018-10-01  18933.80
36 2018-11-01  25905.05
37 2018-12-01  16244.70
38 2019-01-01  39752.74
39 2019-02-01   9364.62
40 2019-03-01  34523.56
probabilidade_zeros :0.0
score : 767.8969696969698
         data     valor
0  2016-09-01   4494.74
1  2016-10-01   5417.10
2  2016-11-01  15135.52
3  2016-12-01   4974.28
4  2017-01-01   4121.50
5  2017-02-01   1733.40
6  2017-03-01   9683.20
7  2017-04-01   7903.46
8  2017-05-01   5570.12
9  2017-06-01   5224.08
10 2017-07-01   7609.20
11 2017-08-01   7213.62
12 2017-09-01   8079.92
13 2017-10-01  11976.36
14 2017-11-01   3581.90
15 2017-12-01   2010.92
16 2018-01-01   3643.28
17 2018-02-01   8990.30
18 2018-03-01   8171.80
19 2018-04-01  17321.00
20 2018-05-01   9741.04
21 2018-06-01   8547.44
22 2018-07-01   3429.30
23 2018-08-01  12198.30
24 2018-09-01  10181.02
25 2018-10-01  13144.56
26 2018-11-01  10380.38
27 2018-12-01  11680.42
28 2019-01-01  11687.18
29 2019-02-01  12393.10
30 2019-03-01   8315.44
periodo de elegibilidade : [datetime.date(2018, 10, 1), datetime.date(2018, 11, 1), datetime.date(2018, 12, 1), datetime.date(2019, 1, 1), datetime.date(2019, 2, 1), datetime.date(2019, 3, 1)]
         data     valor
0  2016-09-01   4494.74
1  2016-10-01   5417.10
2  2016-11-01  15135.52
3  2016-12-01   4974.28
4  2017-01-01   4121.50
5  2017-02-01   1733.40
6  2017-03-01   9683.20
7  2017-04-01   7903.46
8  2017-05-01   5570.12
9  2017-06-01   5224.08
10 2017-07-01   7609.20
11 2017-08-01   7213.62
12 2017-09-01   8079.92
13 2017-10-01  11976.36
14 2017-11-01   3581.90
15 2017-12-01   2010.92
16 2018-01-01   3643.28
17 2018-02-01   8990.30
18 2018-03-01   8171.80
19 2018-04-01  17321.00
20 2018-05-01   9741.04
21 2018-06-01   8547.44
22 2018-07-01   3429.30
23 2018-08-01  12198.30
24 2018-09-01  10181.02
25 2018-10-01  13144.56
26 2018-11-01  10380.38
27 2018-12-01  11680.42
28 2019-01-01  11687.18
29 2019-02-01  12393.10
30 2019-03-01   8315.44
probabilidade_zeros :0.0
score : 739.4727272727273
         data     valor
0  2018-04-01   1666.94
1  2018-05-01   9664.54
2  2018-06-01   5342.12
3  2018-07-01   8235.74
4  2018-08-01  12182.66
5  2018-09-01   4223.30
6  2018-10-01  10724.82
7  2018-11-01  12973.56
8  2018-12-01   7694.86
9  2019-01-01   4776.96
10 2019-02-01   5332.62
11 2019-03-01  12934.46
periodo de elegibilidade : [datetime.date(2018, 10, 1), datetime.date(2018, 11, 1), datetime.date(2018, 12, 1), datetime.date(2019, 1, 1), datetime.date(2019, 2, 1), datetime.date(2019, 3, 1)]
         data     valor
0  2018-04-01   1666.94
1  2018-05-01   9664.54
2  2018-06-01   5342.12
3  2018-07-01   8235.74
4  2018-08-01  12182.66
5  2018-09-01   4223.30
6  2018-10-01  10724.82
7  2018-11-01  12973.56
8  2018-12-01   7694.86
9  2019-01-01   4776.96
10 2019-02-01   5332.62
11 2019-03-01  12934.46
probabilidade_zeros :0.0

score : 760.278787878788
         data     valor
0  2016-02-01   5400.00
1  2016-03-01   4860.00
2  2016-04-01   1065.00
3  2016-05-01    675.00
4  2016-06-01    355.00
5  2016-07-01   1030.00
6  2016-08-01   4297.00
7  2016-09-01   3506.36
8  2016-10-01   6644.83
9  2016-11-01   1523.75
10 2016-12-01      0.00
11 2017-01-01      0.00
12 2017-02-01      0.00
13 2017-03-01      0.00
14 2017-04-01      0.00
15 2017-05-01      0.00
16 2017-06-01      0.00
17 2017-07-01      0.00
18 2017-08-01   1402.80
19 2017-09-01   7554.00
20 2017-10-01    270.00
21 2017-11-01   1887.16
22 2017-12-01   5505.40
23 2018-01-01   6398.64
24 2018-02-01  14050.30
25 2018-03-01   8513.44
26 2018-04-01   1587.58
27 2018-05-01     94.00
28 2018-06-01   8356.55
29 2018-07-01  12056.04
30 2018-08-01   6130.34
31 2018-09-01   8040.60
32 2018-10-01   3717.66
33 2018-11-01   5380.04
34 2018-12-01   1670.48
35 2019-01-01   4484.51
36 2019-02-01   9087.30
37 2019-03-01   2107.00
periodo de elegibilidade : [datetime.date(2018, 10, 1), datetime.date(2018, 11, 1), datetime.date(2018, 12, 1), datetime.date(2019, 1, 1), datetime.date(2019, 2, 1), datetime.date(2019, 3, 1)]
         data     valor
0  2016-02-01   5400.00
1  2016-03-01   4860.00
2  2016-04-01   1065.00
3  2016-05-01    675.00
4  2016-06-01    355.00
5  2016-07-01   1030.00
6  2016-08-01   4297.00
7  2016-09-01   3506.36
8  2016-10-01   6644.83
9  2016-11-01   1523.75
10 2016-12-01      0.00
11 2017-01-01      0.00
12 2017-02-01      0.00
13 2017-03-01      0.00
14 2017-04-01      0.00
15 2017-05-01      0.00
16 2017-06-01      0.00
17 2017-07-01      0.00
18 2017-08-01   1402.80
19 2017-09-01   7554.00
20 2017-10-01    270.00
21 2017-11-01   1887.16
22 2017-12-01   5505.40
23 2018-01-01   6398.64
24 2018-02-01  14050.30
25 2018-03-01   8513.44
26 2018-04-01   1587.58
27 2018-05-01     94.00
28 2018-06-01   8356.55
29 2018-07-01  12056.04
30 2018-08-01   6130.34
31 2018-09-01   8040.60
32 2018-10-01   3717.66
33 2018-11-01   5380.04
34 2018-12-01   1670.48
35 2019-01-01   4484.51
36 2019-02-01   9087.30
37 2019-03-01   2107.00
probabilidade_zeros :0.08333333333333333
         data     valor
0  2018-04-01  22407.87
1  2018-05-01  39772.27
2  2018-06-01  20632.05
3  2018-07-01  21836.42
4  2018-08-01  14342.91
5  2018-09-01  23161.32
6  2018-10-01  15082.13
7  2018-11-01  17841.62
8  2018-12-01  32778.28
9  2019-01-01  22658.44
10 2019-02-01  20920.65
11 2019-03-01  27720.71
periodo de elegibilidade : [datetime.date(2018, 10, 1), datetime.date(2018, 11, 1), datetime.date(2018, 12, 1), datetime.date(2019, 1, 1), datetime.date(2019, 2, 1), datetime.date(2019, 3, 1)]
         data     valor
0  2018-04-01  22407.87
1  2018-05-01  39772.27
2  2018-06-01  20632.05
3  2018-07-01  21836.42
4  2018-08-01  14342.91
5  2018-09-01  23161.32
6  2018-10-01  15082.13
7  2018-11-01  17841.62
8  2018-12-01  32778.28
9  2019-01-01  22658.44
10 2019-02-01  20920.65
11 2019-03-01  27720.71
probabilidade_zeros :0.0
         data     valor
0  2015-11-01   1065.00
1  2015-12-01   1114.60
2  2016-01-01   2637.20
3  2016-02-01   5368.30
4  2016-03-01   5377.40
5  2016-04-01   8363.86
6  2016-05-01   6259.56
7  2016-06-01   4810.50
8  2016-07-01   5061.70
9  2016-08-01   9984.45
10 2016-09-01  13759.31
11 2016-10-01   2679.81
12 2016-11-01   5139.55
13 2016-12-01   6308.70
14 2017-01-01  10020.50
15 2017-02-01   6322.55
16 2017-03-01   4893.00
17 2017-04-01   5332.50
18 2017-05-01   5020.00
19 2017-06-01   2264.25
20 2017-07-01   3063.00
21 2017-08-01   4533.75
22 2017-09-01   3912.75
23 2017-10-01   5616.00
24 2017-11-01   5046.00
25 2017-12-01   6453.00
26 2018-01-01  11101.75
27 2018-02-01   6278.18
28 2018-03-01   4947.88
29 2018-04-01   7669.50
30 2018-05-01   9851.50
31 2018-06-01   5402.72
32 2018-07-01  10147.00
33 2018-08-01   4902.56
34 2018-09-01  12618.24
35 2018-10-01   9955.22
36 2018-11-01   8377.37
37 2018-12-01   9793.00
38 2019-01-01  17814.06
39 2019-02-01   3856.92
40 2019-03-01  13353.84
periodo de elegibilidade : [datetime.date(2018, 10, 1), datetime.date(2018, 11, 1), datetime.date(2018, 12, 1), datetime.date(2019, 1, 1), datetime.date(2019, 2, 1), datetime.date(2019, 3, 1)]
         data     valor
0  2015-11-01   1065.00
1  2015-12-01   1114.60
2  2016-01-01   2637.20
3  2016-02-01   5368.30
4  2016-03-01   5377.40
5  2016-04-01   8363.86
6  2016-05-01   6259.56
7  2016-06-01   4810.50
8  2016-07-01   5061.70
9  2016-08-01   9984.45
10 2016-09-01  13759.31
11 2016-10-01   2679.81
12 2016-11-01   5139.55
13 2016-12-01   6308.70
14 2017-01-01  10020.50
15 2017-02-01   6322.55
16 2017-03-01   4893.00
17 2017-04-01   5332.50
18 2017-05-01   5020.00
19 2017-06-01   2264.25
20 2017-07-01   3063.00
21 2017-08-01   4533.75
22 2017-09-01   3912.75
23 2017-10-01   5616.00
24 2017-11-01   5046.00
25 2017-12-01   6453.00
26 2018-01-01  11101.75
27 2018-02-01   6278.18
28 2018-03-01   4947.88
29 2018-04-01   7669.50
30 2018-05-01   9851.50
31 2018-06-01   5402.72
32 2018-07-01  10147.00
33 2018-08-01   4902.56
34 2018-09-01  12618.24
35 2018-10-01   9955.22
36 2018-11-01   8377.37
37 2018-12-01   9793.00
38 2019-01-01  17814.06
39 2019-02-01   3856.92
40 2019-03-01  13353.84
probabilidade_zeros :0.0
         data     valor
0  2017-11-01    920.98
1  2017-12-01    324.58
2  2018-01-01   1293.74
3  2018-02-01   1033.02
4  2018-03-01   2677.75
5  2018-04-01    612.24
6  2018-05-01   1380.66
7  2018-06-01   2437.96
8  2018-07-01   1287.28
9  2018-08-01   4376.66
10 2018-09-01   7261.07
11 2018-10-01   8231.16
12 2018-11-01   9257.04
13 2018-12-01  13988.55
14 2019-01-01   3514.74
15 2019-02-01   7623.64
16 2019-03-01  11567.02
periodo de elegibilidade : [datetime.date(2018, 10, 1), datetime.date(2018, 11, 1), datetime.date(2018, 12, 1), datetime.date(2019, 1, 1), datetime.date(2019, 2, 1), datetime.date(2019, 3, 1)]
         data     valor
0  2017-11-01    920.98
1  2017-12-01    324.58
2  2018-01-01   1293.74
3  2018-02-01   1033.02
4  2018-03-01   2677.75
5  2018-04-01    612.24
6  2018-05-01   1380.66
7  2018-06-01   2437.96
8  2018-07-01   1287.28
9  2018-08-01   4376.66
10 2018-09-01   7261.07
11 2018-10-01   8231.16
12 2018-11-01   9257.04
13 2018-12-01  13988.55
14 2019-01-01   3514.74
15 2019-02-01   7623.64
16 2019-03-01  11567.02
probabilidade_zeros :0.0
score : 757.7818181818183
         data     valor
0  2013-09-01    900.00
1  2013-10-01   3780.00
2  2013-11-01   5104.47
3  2013-12-01   9870.00
4  2014-01-01   5360.00
5  2014-02-01  16500.00
6  2014-03-01  29585.00
7  2014-04-01  21765.00
8  2014-05-01  39380.00
9  2014-06-01  23590.00
10 2014-07-01  11970.00
11 2014-08-01  46360.00
12 2014-09-01  30555.00
13 2014-10-01  30980.00
14 2014-11-01  28815.00
15 2014-12-01  25805.00
16 2015-01-01  38075.00
17 2015-02-01  11195.00
18 2015-03-01  21580.00
19 2015-04-01  25295.00
20 2015-05-01  20200.00
21 2015-06-01  26560.00
22 2015-07-01   8905.00
23 2015-08-01  22820.00
24 2015-09-01  17705.00
25 2015-10-01  17435.00
26 2015-11-01  21420.00
27 2015-12-01  23630.00
28 2016-01-01  21325.00
29 2016-02-01  20000.00
..        ...       ...
37 2016-10-01   5880.00
38 2016-11-01   7705.00
39 2016-12-01   3270.00
40 2017-01-01    320.00
41 2017-02-01   3110.00
42 2017-03-01   2480.00
43 2017-04-01    160.00
44 2017-05-01     80.00
45 2017-06-01      0.00
46 2017-07-01      0.00
47 2017-08-01      0.00
48 2017-09-01      0.00
49 2017-10-01      0.00
50 2017-11-01      0.00
51 2017-12-01      0.00
52 2018-01-01      0.00
53 2018-02-01      0.00
54 2018-03-01      0.00
55 2018-04-01    230.00
56 2018-05-01    865.35
57 2018-06-01   2270.00
58 2018-07-01   5958.93
59 2018-08-01   3655.73
60 2018-09-01   1895.96
61 2018-10-01   6875.00
62 2018-11-01   3640.00
63 2018-12-01   2985.00
64 2019-01-01   3700.56
65 2019-02-01   4727.56
66 2019-03-01   3963.41

[67 rows x 2 columns]
periodo de elegibilidade : [datetime.date(2018, 10, 1), datetime.date(2018, 11, 1), datetime.date(2018, 12, 1), datetime.date(2019, 1, 1), datetime.date(2019, 2, 1), datetime.date(2019, 3, 1)]
         data     valor
0  2013-09-01    900.00
1  2013-10-01   3780.00
2  2013-11-01   5104.47
3  2013-12-01   9870.00
4  2014-01-01   5360.00
5  2014-02-01  16500.00
6  2014-03-01  29585.00
7  2014-04-01  21765.00
8  2014-05-01  39380.00
9  2014-06-01  23590.00
10 2014-07-01  11970.00
11 2014-08-01  46360.00
12 2014-09-01  30555.00
13 2014-10-01  30980.00
14 2014-11-01  28815.00
15 2014-12-01  25805.00
16 2015-01-01  38075.00
17 2015-02-01  11195.00
18 2015-03-01  21580.00
19 2015-04-01  25295.00
20 2015-05-01  20200.00
21 2015-06-01  26560.00
22 2015-07-01   8905.00
23 2015-08-01  22820.00
24 2015-09-01  17705.00
25 2015-10-01  17435.00
26 2015-11-01  21420.00
27 2015-12-01  23630.00
28 2016-01-01  21325.00
29 2016-02-01  20000.00
..        ...       ...
37 2016-10-01   5880.00
38 2016-11-01   7705.00
39 2016-12-01   3270.00
40 2017-01-01    320.00
41 2017-02-01   3110.00
42 2017-03-01   2480.00
43 2017-04-01    160.00
44 2017-05-01     80.00
45 2017-06-01      0.00
46 2017-07-01      0.00
47 2017-08-01      0.00
48 2017-09-01      0.00
49 2017-10-01      0.00
50 2017-11-01      0.00
51 2017-12-01      0.00
52 2018-01-01      0.00
53 2018-02-01      0.00
54 2018-03-01      0.00
55 2018-04-01    230.00
56 2018-05-01    865.35
57 2018-06-01   2270.00
58 2018-07-01   5958.93
59 2018-08-01   3655.73
60 2018-09-01   1895.96
61 2018-10-01   6875.00
62 2018-11-01   3640.00
63 2018-12-01   2985.00
64 2019-01-01   3700.56
65 2019-02-01   4727.56
66 2019-03-01   3963.41

[67 rows x 2 columns]
probabilidade_zeros :0.08333333333333333

         data     valor
0  2015-10-01    599.80
1  2015-11-01   8614.58
2  2015-12-01  17106.90
3  2016-01-01  17043.71
4  2016-02-01  20794.46
5  2016-03-01  24821.92
6  2016-04-01  21495.46
7  2016-05-01  26169.05
8  2016-06-01  22023.75
9  2016-07-01  49675.25
10 2016-08-01  38022.99
11 2016-09-01  25532.94
12 2016-10-01  37183.34
13 2016-11-01  24221.90
14 2016-12-01  21561.35
15 2017-01-01  29442.01
16 2017-02-01  15084.46
17 2017-03-01  22026.28
18 2017-04-01  18733.32
19 2017-05-01  26400.91
20 2017-06-01  19753.80
21 2017-07-01  29168.78
22 2017-08-01  34915.39
23 2017-09-01  34940.62
24 2017-10-01  40429.50
25 2017-11-01  34787.30
26 2017-12-01  58721.32
27 2018-01-01  49332.70
28 2018-02-01  47822.17
29 2018-03-01  59640.53
30 2018-04-01  47081.91
31 2018-05-01  44598.48
32 2018-06-01  45516.76
33 2018-07-01  48012.64
34 2018-08-01  58335.43
35 2018-09-01  40716.28
36 2018-10-01  62679.36
37 2018-11-01  44262.85
38 2018-12-01  55267.07
39 2019-01-01  78606.67
40 2019-02-01  48902.16
41 2019-03-01  46935.69
periodo de elegibilidade : [datetime.date(2018, 10, 1), datetime.date(2018, 11, 1), datetime.date(2018, 12, 1), datetime.date(2019, 1, 1), datetime.date(2019, 2, 1), datetime.date(2019, 3, 1)]
         data     valor
0  2015-10-01    599.80
1  2015-11-01   8614.58
2  2015-12-01  17106.90
3  2016-01-01  17043.71
4  2016-02-01  20794.46
5  2016-03-01  24821.92
6  2016-04-01  21495.46
7  2016-05-01  26169.05
8  2016-06-01  22023.75
9  2016-07-01  49675.25
10 2016-08-01  38022.99
11 2016-09-01  25532.94
12 2016-10-01  37183.34
13 2016-11-01  24221.90
14 2016-12-01  21561.35
15 2017-01-01  29442.01
16 2017-02-01  15084.46
17 2017-03-01  22026.28
18 2017-04-01  18733.32
19 2017-05-01  26400.91
20 2017-06-01  19753.80
21 2017-07-01  29168.78
22 2017-08-01  34915.39
23 2017-09-01  34940.62
24 2017-10-01  40429.50
25 2017-11-01  34787.30
26 2017-12-01  58721.32
27 2018-01-01  49332.70
28 2018-02-01  47822.17
29 2018-03-01  59640.53
30 2018-04-01  47081.91
31 2018-05-01  44598.48
32 2018-06-01  45516.76
33 2018-07-01  48012.64
34 2018-08-01  58335.43
35 2018-09-01  40716.28
36 2018-10-01  62679.36
37 2018-11-01  44262.85
38 2018-12-01  55267.07
39 2019-01-01  78606.67
40 2019-02-01  48902.16
41 2019-03-01  46935.69
probabilidade_zeros :0.0
score : 709.7878787878786
         data     valor
0  2015-11-01   9146.87
1  2015-12-01  17077.76
2  2016-01-01  37832.17
3  2016-02-01  30623.60
4  2016-03-01  31435.63
5  2016-04-01  23061.45
6  2016-05-01  23801.81
7  2016-06-01  28036.45
8  2016-07-01  26725.35
9  2016-08-01  32348.70
10 2016-09-01  35238.66
11 2016-10-01  26024.80
12 2016-11-01  24704.75
13 2016-12-01  22545.25
14 2017-01-01  39276.00
15 2017-02-01  29317.22
16 2017-03-01  11377.58
17 2017-04-01  36651.22
18 2017-05-01  24823.44
19 2017-06-01  26037.00
20 2017-07-01  36606.28
21 2017-08-01  46865.71
22 2017-09-01  18824.63
23 2017-10-01  39869.01
24 2017-11-01  52240.83
25 2017-12-01  15335.66
26 2018-01-01  54183.45
27 2018-02-01  30349.00
28 2018-03-01  62575.35
29 2018-04-01  20553.19
30 2018-05-01  76710.87
31 2018-06-01  75075.79
32 2018-07-01  48213.18
33 2018-08-01  66003.66
34 2018-09-01  49361.53
35 2018-10-01  49575.62
36 2018-11-01  60382.93
37 2018-12-01  49564.19
38 2019-01-01  64683.19
39 2019-02-01  63511.59
40 2019-03-01  49429.15
periodo de elegibilidade : [datetime.date(2018, 10, 1), datetime.date(2018, 11, 1), datetime.date(2018, 12, 1), datetime.date(2019, 1, 1), datetime.date(2019, 2, 1), datetime.date(2019, 3, 1)]
         data     valor
0  2015-11-01   9146.87
1  2015-12-01  17077.76
2  2016-01-01  37832.17
3  2016-02-01  30623.60
4  2016-03-01  31435.63
5  2016-04-01  23061.45
6  2016-05-01  23801.81
7  2016-06-01  28036.45
8  2016-07-01  26725.35
9  2016-08-01  32348.70
10 2016-09-01  35238.66
11 2016-10-01  26024.80
12 2016-11-01  24704.75
13 2016-12-01  22545.25
14 2017-01-01  39276.00
15 2017-02-01  29317.22
16 2017-03-01  11377.58
17 2017-04-01  36651.22
18 2017-05-01  24823.44
19 2017-06-01  26037.00
20 2017-07-01  36606.28
21 2017-08-01  46865.71
22 2017-09-01  18824.63
23 2017-10-01  39869.01
24 2017-11-01  52240.83
25 2017-12-01  15335.66
26 2018-01-01  54183.45
27 2018-02-01  30349.00
28 2018-03-01  62575.35
29 2018-04-01  20553.19
30 2018-05-01  76710.87
31 2018-06-01  75075.79
32 2018-07-01  48213.18
33 2018-08-01  66003.66
34 2018-09-01  49361.53
35 2018-10-01  49575.62
36 2018-11-01  60382.93
37 2018-12-01  49564.19
38 2019-01-01  64683.19
39 2019-02-01  63511.59
40 2019-03-01  49429.15
probabilidade_zeros :0.0
score : 814.1939393939396
         data     valor
0  2015-11-01   2497.50
1  2015-12-01   3407.75
2  2016-01-01  13884.65
3  2016-02-01  16073.65
4  2016-03-01  21603.50
5  2016-04-01  16888.55
6  2016-05-01  19686.45
7  2016-06-01  20313.70
8  2016-07-01  24931.55
9  2016-08-01  15813.98
10 2016-09-01  29572.21
11 2016-10-01  21991.79
12 2016-11-01  30795.81
13 2016-12-01  23900.50
14 2017-01-01  44834.55
15 2017-02-01  21495.27
16 2017-03-01  22792.88
17 2017-04-01  31731.19
18 2017-05-01  34370.25
19 2017-06-01  34204.98
20 2017-07-01  35924.40
21 2017-08-01  24604.04
22 2017-09-01  46692.33
23 2017-10-01  29233.10
24 2017-11-01  31574.32
25 2017-12-01  32804.54
26 2018-01-01  46662.70
27 2018-02-01  30641.63
28 2018-03-01  47916.14
29 2018-04-01  56088.57
30 2018-05-01  41979.32
31 2018-06-01  41128.56
32 2018-07-01  51268.16
33 2018-08-01  36287.09
34 2018-09-01  52317.19
35 2018-10-01  58361.21
36 2018-11-01  35422.92
37 2018-12-01  36828.34
38 2019-01-01  68978.35
39 2019-02-01  43607.90
40 2019-03-01    308.16
periodo de elegibilidade : [datetime.date(2018, 10, 1), datetime.date(2018, 11, 1), datetime.date(2018, 12, 1), datetime.date(2019, 1, 1), datetime.date(2019, 2, 1), datetime.date(2019, 3, 1)]
         data     valor
0  2015-11-01   2497.50
1  2015-12-01   3407.75
2  2016-01-01  13884.65
3  2016-02-01  16073.65
4  2016-03-01  21603.50
5  2016-04-01  16888.55
6  2016-05-01  19686.45
7  2016-06-01  20313.70
8  2016-07-01  24931.55
9  2016-08-01  15813.98
10 2016-09-01  29572.21
11 2016-10-01  21991.79
12 2016-11-01  30795.81
13 2016-12-01  23900.50
14 2017-01-01  44834.55
15 2017-02-01  21495.27
16 2017-03-01  22792.88
17 2017-04-01  31731.19
18 2017-05-01  34370.25
19 2017-06-01  34204.98
20 2017-07-01  35924.40
21 2017-08-01  24604.04
22 2017-09-01  46692.33
23 2017-10-01  29233.10
24 2017-11-01  31574.32
25 2017-12-01  32804.54
26 2018-01-01  46662.70
27 2018-02-01  30641.63
28 2018-03-01  47916.14
29 2018-04-01  56088.57
30 2018-05-01  41979.32
31 2018-06-01  41128.56
32 2018-07-01  51268.16
33 2018-08-01  36287.09
34 2018-09-01  52317.19
35 2018-10-01  58361.21
36 2018-11-01  35422.92
37 2018-12-01  36828.34
38 2019-01-01  68978.35
39 2019-02-01  43607.90
40 2019-03-01    308.16
probabilidade_zeros :0.0
score : 396.1414141414141
         data     valor
0  2015-11-01   5244.75
1  2015-12-01  17670.80
2  2016-01-01  17669.60
3  2016-02-01  20421.05
4  2016-03-01  20074.75
5  2016-04-01  26584.25
6  2016-05-01  20394.10
7  2016-06-01  31119.85
8  2016-07-01  33191.35
9  2016-08-01  40253.30
10 2016-09-01  28051.14
11 2016-10-01  22283.52
12 2016-11-01  32558.45
13 2016-12-01  38455.25
14 2017-01-01  53797.90
15 2017-02-01  31929.97
16 2017-03-01  49259.52
17 2017-04-01  41855.18
18 2017-05-01  61779.76
19 2017-06-01  56632.90
20 2017-07-01  75352.93
21 2017-08-01  61847.75
22 2017-09-01  74356.16
23 2017-10-01  59119.43
24 2017-11-01  70243.34
25 2017-12-01  75236.50
26 2018-01-01  58893.36
27 2018-02-01  51411.14
28 2018-03-01  64047.96
29 2018-04-01  55144.51
30 2018-05-01  57672.82
31 2018-06-01  45897.52
32 2018-07-01  66779.60
33 2018-08-01  63031.82
34 2018-09-01  67894.90
35 2018-10-01  70523.12
36 2018-11-01  68235.40
37 2018-12-01  55034.74
38 2019-01-01  71329.32
39 2019-02-01  38905.42
40 2019-03-01  58918.30
periodo de elegibilidade : [datetime.date(2018, 10, 1), datetime.date(2018, 11, 1), datetime.date(2018, 12, 1), datetime.date(2019, 1, 1), datetime.date(2019, 2, 1), datetime.date(2019, 3, 1)]
         data     valor
0  2015-11-01   5244.75
1  2015-12-01  17670.80
2  2016-01-01  17669.60
3  2016-02-01  20421.05
4  2016-03-01  20074.75
5  2016-04-01  26584.25
6  2016-05-01  20394.10
7  2016-06-01  31119.85
8  2016-07-01  33191.35
9  2016-08-01  40253.30
10 2016-09-01  28051.14
11 2016-10-01  22283.52
12 2016-11-01  32558.45
13 2016-12-01  38455.25
14 2017-01-01  53797.90
15 2017-02-01  31929.97
16 2017-03-01  49259.52
17 2017-04-01  41855.18
18 2017-05-01  61779.76
19 2017-06-01  56632.90
20 2017-07-01  75352.93
21 2017-08-01  61847.75
22 2017-09-01  74356.16
23 2017-10-01  59119.43
24 2017-11-01  70243.34
25 2017-12-01  75236.50
26 2018-01-01  58893.36
27 2018-02-01  51411.14
28 2018-03-01  64047.96
29 2018-04-01  55144.51
30 2018-05-01  57672.82
31 2018-06-01  45897.52
32 2018-07-01  66779.60
33 2018-08-01  63031.82
34 2018-09-01  67894.90
35 2018-10-01  70523.12
36 2018-11-01  68235.40
37 2018-12-01  55034.74
38 2019-01-01  71329.32
39 2019-02-01  38905.42
40 2019-03-01  58918.30
probabilidade_zeros :0.0

score : 715.5060606060606
         data     valor
0  2016-01-01   4245.75
1  2016-02-01   4245.75
2  2016-03-01   3576.55
3  2016-04-01  11616.50
4  2016-05-01  10923.65
5  2016-06-01  21809.50
6  2016-07-01  28705.35
7  2016-08-01  31109.85
8  2016-09-01   5195.56
9  2016-10-01  22597.99
10 2016-11-01   3388.95
11 2016-12-01   1087.50
12 2017-01-01  26931.50
13 2017-02-01   7030.55
14 2017-03-01   4893.00
15 2017-04-01  16387.00
16 2017-05-01  11131.25
17 2017-06-01  15013.29
18 2017-07-01  22955.36
19 2017-08-01  22289.63
20 2017-09-01  30441.03
21 2017-10-01  27952.78
22 2017-11-01  13325.91
23 2017-12-01  28793.56
24 2018-01-01  42816.16
25 2018-02-01  28378.75
26 2018-03-01  16705.44
27 2018-04-01  34970.42
28 2018-05-01  31976.39
29 2018-06-01  13232.62
30 2018-07-01  39955.78
31 2018-08-01  40645.97
32 2018-09-01  20315.61
33 2018-10-01  43373.59
34 2018-11-01  22802.84
35 2018-12-01  33932.66
36 2019-01-01  29453.34
37 2019-02-01  45507.40
38 2019-03-01    277.44
periodo de elegibilidade : [datetime.date(2018, 10, 1), datetime.date(2018, 11, 1), datetime.date(2018, 12, 1), datetime.date(2019, 1, 1), datetime.date(2019, 2, 1), datetime.date(2019, 3, 1)]
         data     valor
0  2016-01-01   4245.75
1  2016-02-01   4245.75
2  2016-03-01   3576.55
3  2016-04-01  11616.50
4  2016-05-01  10923.65
5  2016-06-01  21809.50
6  2016-07-01  28705.35
7  2016-08-01  31109.85
8  2016-09-01   5195.56
9  2016-10-01  22597.99
10 2016-11-01   3388.95
11 2016-12-01   1087.50
12 2017-01-01  26931.50
13 2017-02-01   7030.55
14 2017-03-01   4893.00
15 2017-04-01  16387.00
16 2017-05-01  11131.25
17 2017-06-01  15013.29
18 2017-07-01  22955.36
19 2017-08-01  22289.63
20 2017-09-01  30441.03
21 2017-10-01  27952.78
22 2017-11-01  13325.91
23 2017-12-01  28793.56
24 2018-01-01  42816.16
25 2018-02-01  28378.75
26 2018-03-01  16705.44
27 2018-04-01  34970.42
28 2018-05-01  31976.39
29 2018-06-01  13232.62
30 2018-07-01  39955.78
31 2018-08-01  40645.97
32 2018-09-01  20315.61
33 2018-10-01  43373.59
34 2018-11-01  22802.84
35 2018-12-01  33932.66
36 2019-01-01  29453.34
37 2019-02-01  45507.40
38 2019-03-01    277.44
probabilidade_zeros :0.0
score : 387.5084175084175
         data     valor
0  2015-11-01   1748.25
1  2015-12-01   3527.40
2  2016-01-01  11451.05
3  2016-02-01  13481.70
4  2016-03-01   7230.15
5  2016-04-01  23788.60
6  2016-05-01  10895.45
7  2016-06-01  20505.60
8  2016-07-01  25770.75
9  2016-08-01  31789.20
10 2016-09-01  18529.84
11 2016-10-01  19898.91
12 2016-11-01  28931.85
13 2016-12-01  28683.20
14 2017-01-01  25278.85
15 2017-02-01  31660.15
16 2017-03-01  47484.19
17 2017-04-01  43498.47
18 2017-05-01  47871.13
19 2017-06-01  35253.45
20 2017-07-01  53030.08
21 2017-08-01  43314.64
22 2017-09-01  64265.40
23 2017-10-01  44625.37
24 2017-11-01  62782.56
25 2017-12-01  47182.91
26 2018-01-01  68952.57
27 2018-02-01  45174.68
28 2018-03-01  58921.20
29 2018-04-01  67906.23
30 2018-05-01  48234.72
31 2018-06-01  62753.74
32 2018-07-01  81592.66
33 2018-08-01  71407.36
34 2018-09-01  85915.56
35 2018-10-01  70259.50
36 2018-11-01  73875.38
37 2018-12-01  51049.64
38 2019-01-01  96608.68
39 2019-02-01  87784.96
40 2019-03-01  41733.30
periodo de elegibilidade : [datetime.date(2018, 10, 1), datetime.date(2018, 11, 1), datetime.date(2018, 12, 1), datetime.date(2019, 1, 1), datetime.date(2019, 2, 1), datetime.date(2019, 3, 1)]
         data     valor
0  2015-11-01   1748.25
1  2015-12-01   3527.40
2  2016-01-01  11451.05
3  2016-02-01  13481.70
4  2016-03-01   7230.15
5  2016-04-01  23788.60
6  2016-05-01  10895.45
7  2016-06-01  20505.60
8  2016-07-01  25770.75
9  2016-08-01  31789.20
10 2016-09-01  18529.84
11 2016-10-01  19898.91
12 2016-11-01  28931.85
13 2016-12-01  28683.20
14 2017-01-01  25278.85
15 2017-02-01  31660.15
16 2017-03-01  47484.19
17 2017-04-01  43498.47
18 2017-05-01  47871.13
19 2017-06-01  35253.45
20 2017-07-01  53030.08
21 2017-08-01  43314.64
22 2017-09-01  64265.40
23 2017-10-01  44625.37
24 2017-11-01  62782.56
25 2017-12-01  47182.91
26 2018-01-01  68952.57
27 2018-02-01  45174.68
28 2018-03-01  58921.20
29 2018-04-01  67906.23
30 2018-05-01  48234.72
31 2018-06-01  62753.74
32 2018-07-01  81592.66
33 2018-08-01  71407.36
34 2018-09-01  85915.56
35 2018-10-01  70259.50
36 2018-11-01  73875.38
37 2018-12-01  51049.64
38 2019-01-01  96608.68
39 2019-02-01  87784.96
40 2019-03-01  41733.30
probabilidade_zeros :0.0
score : 686.5787878787878
         data     valor
0  2015-11-01   3496.50
1  2015-12-01   9669.80
2  2016-01-01  18322.60
3  2016-02-01  22658.00
4  2016-03-01   8741.60
5  2016-04-01  18222.15
6  2016-05-01  16550.10
7  2016-06-01  23549.65
8  2016-07-01  26269.65
9  2016-08-01  31711.35
10 2016-09-01  32103.27
11 2016-10-01  29957.48
12 2016-11-01  27805.80
13 2016-12-01  34442.75
14 2017-01-01  29957.45
15 2017-02-01  19814.15
16 2017-03-01  22066.24
17 2017-04-01  12361.74
18 2017-05-01  33715.38
19 2017-06-01  21440.25
20 2017-07-01  35489.77
21 2017-08-01  22218.13
22 2017-09-01  19197.42
23 2017-10-01  28364.31
24 2017-11-01  26822.50
25 2017-12-01  33985.09
26 2018-01-01  39460.12
27 2018-02-01  28704.76
28 2018-03-01  36978.19
29 2018-04-01  36397.13
30 2018-05-01  35599.54
31 2018-06-01  23842.37
32 2018-07-01  42788.84
33 2018-08-01  43854.73
34 2018-09-01  45937.53
35 2018-10-01  69565.07
36 2018-11-01  45020.47
37 2018-12-01  30894.94
38 2019-01-01  39964.10
39 2019-02-01  42800.62
40 2019-03-01  36977.46
periodo de elegibilidade : [datetime.date(2018, 10, 1), datetime.date(2018, 11, 1), datetime.date(2018, 12, 1), datetime.date(2019, 1, 1), datetime.date(2019, 2, 1), datetime.date(2019, 3, 1)]
         data     valor
0  2015-11-01   3496.50
1  2015-12-01   9669.80
2  2016-01-01  18322.60
3  2016-02-01  22658.00
4  2016-03-01   8741.60
5  2016-04-01  18222.15
6  2016-05-01  16550.10
7  2016-06-01  23549.65
8  2016-07-01  26269.65
9  2016-08-01  31711.35
10 2016-09-01  32103.27
11 2016-10-01  29957.48
12 2016-11-01  27805.80
13 2016-12-01  34442.75
14 2017-01-01  29957.45
15 2017-02-01  19814.15
16 2017-03-01  22066.24
17 2017-04-01  12361.74
18 2017-05-01  33715.38
19 2017-06-01  21440.25
20 2017-07-01  35489.77
21 2017-08-01  22218.13
22 2017-09-01  19197.42
23 2017-10-01  28364.31
24 2017-11-01  26822.50
25 2017-12-01  33985.09
26 2018-01-01  39460.12
27 2018-02-01  28704.76
28 2018-03-01  36978.19
29 2018-04-01  36397.13
30 2018-05-01  35599.54
31 2018-06-01  23842.37
32 2018-07-01  42788.84
33 2018-08-01  43854.73
34 2018-09-01  45937.53
35 2018-10-01  69565.07
36 2018-11-01  45020.47
37 2018-12-01  30894.94
38 2019-01-01  39964.10
39 2019-02-01  42800.62
40 2019-03-01  36977.46
probabilidade_zeros :0.0
score : 709.1151515151514
         data     valor
0  2015-11-01   6551.80
1  2015-12-01   2109.15
2  2016-01-01   4085.60
3  2016-02-01   8161.05
4  2016-03-01  20858.30
5  2016-04-01  31477.70
6  2016-05-01  29359.80
7  2016-06-01  21997.35
8  2016-07-01  34563.10
9  2016-08-01   5390.00
10 2016-09-01  11510.00
11 2016-10-01  14542.80
12 2016-11-01   5880.00
13 2016-12-01  13400.00
14 2017-01-01  27098.90
15 2017-02-01  27373.85
16 2017-03-01   2577.10
17 2017-04-01   4490.55
18 2017-05-01  76309.84
19 2017-06-01  36643.67
20 2017-07-01  17739.24
21 2017-08-01   8731.62
22 2017-09-01  21828.95
23 2017-10-01  16122.98
24 2017-11-01  11039.17
25 2017-12-01   5882.88
26 2018-01-01  24222.61
27 2018-02-01  22266.85
28 2018-03-01  16773.10
29 2018-04-01  28924.51
30 2018-05-01  21492.85
31 2018-06-01  41179.21
32 2018-07-01  28890.40
33 2018-08-01  37927.94
34 2018-09-01  28202.30
35 2018-10-01  37742.87
36 2018-11-01  21151.74
37 2018-12-01  29359.59
38 2019-01-01  36112.51
39 2019-02-01  28924.92
40 2019-03-01  21455.22
periodo de elegibilidade : [datetime.date(2018, 10, 1), datetime.date(2018, 11, 1), datetime.date(2018, 12, 1), datetime.date(2019, 1, 1), datetime.date(2019, 2, 1), datetime.date(2019, 3, 1)]
         data     valor
0  2015-11-01   6551.80
1  2015-12-01   2109.15
2  2016-01-01   4085.60
3  2016-02-01   8161.05
4  2016-03-01  20858.30
5  2016-04-01  31477.70
6  2016-05-01  29359.80
7  2016-06-01  21997.35
8  2016-07-01  34563.10
9  2016-08-01   5390.00
10 2016-09-01  11510.00
11 2016-10-01  14542.80
12 2016-11-01   5880.00
13 2016-12-01  13400.00
14 2017-01-01  27098.90
15 2017-02-01  27373.85
16 2017-03-01   2577.10
17 2017-04-01   4490.55
18 2017-05-01  76309.84
19 2017-06-01  36643.67
20 2017-07-01  17739.24
21 2017-08-01   8731.62
22 2017-09-01  21828.95
23 2017-10-01  16122.98
24 2017-11-01  11039.17
25 2017-12-01   5882.88
26 2018-01-01  24222.61
27 2018-02-01  22266.85
28 2018-03-01  16773.10
29 2018-04-01  28924.51
30 2018-05-01  21492.85
31 2018-06-01  41179.21
32 2018-07-01  28890.40
33 2018-08-01  37927.94
34 2018-09-01  28202.30
35 2018-10-01  37742.87
36 2018-11-01  21151.74
37 2018-12-01  29359.59
38 2019-01-01  36112.51
39 2019-02-01  28924.92
40 2019-03-01  21455.22
probabilidade_zeros :0.0

         data     valor
0  2018-01-01   4626.01
1  2018-02-01   8422.47
2  2018-03-01   9942.38
3  2018-04-01   8168.83
4  2018-05-01  16256.10
5  2018-06-01   3795.79
6  2018-07-01  27075.22
7  2018-08-01  39573.39
8  2018-09-01  37320.64
9  2018-10-01  47618.76
10 2018-11-01  60951.22
11 2018-12-01  44808.48
12 2019-01-01  71265.61
13 2019-02-01  50583.40
14 2019-03-01  64146.92
periodo de elegibilidade : [datetime.date(2018, 10, 1), datetime.date(2018, 11, 1), datetime.date(2018, 12, 1), datetime.date(2019, 1, 1), datetime.date(2019, 2, 1), datetime.date(2019, 3, 1)]
         data     valor
0  2018-01-01   4626.01
1  2018-02-01   8422.47
2  2018-03-01   9942.38
3  2018-04-01   8168.83
4  2018-05-01  16256.10
5  2018-06-01   3795.79
6  2018-07-01  27075.22
7  2018-08-01  39573.39
8  2018-09-01  37320.64
9  2018-10-01  47618.76
10 2018-11-01  60951.22
11 2018-12-01  44808.48
12 2019-01-01  71265.61
13 2019-02-01  50583.40
14 2019-03-01  64146.92
probabilidade_zeros :0.08333333333333333
score : 763.8606060606062
        data    valor
0 2018-09-01   301.47
1 2018-10-01  7434.60
2 2018-11-01  6831.20
3 2018-12-01  5962.97
4 2019-01-01  3121.98
5 2019-02-01  2051.56
6 2019-03-01   714.73
periodo de elegibilidade : [datetime.date(2018, 10, 1), datetime.date(2018, 11, 1), datetime.date(2018, 12, 1), datetime.date(2019, 1, 1), datetime.date(2019, 2, 1), datetime.date(2019, 3, 1)]
        data    valor
0 2018-09-01   301.47
1 2018-10-01  7434.60
2 2018-11-01  6831.20
3 2018-12-01  5962.97
4 2019-01-01  3121.98
5 2019-02-01  2051.56
6 2019-03-01   714.73
probabilidade_zeros :0.14285714285714285
score : 238.66666666666666
         data     valor
0  2016-07-01      1.02
1  2016-08-01      0.01
2  2016-09-01   8980.29
3  2016-10-01   6965.35
4  2016-11-01  10199.02
5  2016-12-01   2136.03
6  2017-01-01   2348.02
7  2017-02-01  15168.72
8  2017-03-01  13401.34
9  2017-04-01  13691.70
10 2017-05-01  13463.67
11 2017-06-01  11273.37
12 2017-07-01  12438.93
13 2017-08-01   7680.84
14 2017-09-01   8863.72
15 2017-10-01  13767.27
16 2017-11-01   8418.84
17 2017-12-01  13914.33
18 2018-01-01  10122.46
19 2018-02-01   5369.00
20 2018-03-01   8799.82
21 2018-04-01   6154.38
22 2018-05-01   9242.89
23 2018-06-01  10039.49
24 2018-07-01  10683.62
25 2018-08-01  21640.53
26 2018-09-01  11074.54
27 2018-10-01  17449.73
28 2018-11-01  10257.12
29 2018-12-01  19005.67
30 2019-01-01  10915.16
31 2019-02-01   9601.54
32 2019-03-01   9041.04
periodo de elegibilidade : [datetime.date(2018, 10, 1), datetime.date(2018, 11, 1), datetime.date(2018, 12, 1), datetime.date(2019, 1, 1), datetime.date(2019, 2, 1), datetime.date(2019, 3, 1)]
         data     valor
0  2016-07-01      1.02
1  2016-08-01      0.01
2  2016-09-01   8980.29
3  2016-10-01   6965.35
4  2016-11-01  10199.02
5  2016-12-01   2136.03
6  2017-01-01   2348.02
7  2017-02-01  15168.72
8  2017-03-01  13401.34
9  2017-04-01  13691.70
10 2017-05-01  13463.67
11 2017-06-01  11273.37
12 2017-07-01  12438.93
13 2017-08-01   7680.84
14 2017-09-01   8863.72
15 2017-10-01  13767.27
16 2017-11-01   8418.84
17 2017-12-01  13914.33
18 2018-01-01  10122.46
19 2018-02-01   5369.00
20 2018-03-01   8799.82
21 2018-04-01   6154.38
22 2018-05-01   9242.89
23 2018-06-01  10039.49
24 2018-07-01  10683.62
25 2018-08-01  21640.53
26 2018-09-01  11074.54
27 2018-10-01  17449.73
28 2018-11-01  10257.12
29 2018-12-01  19005.67
30 2019-01-01  10915.16
31 2019-02-01   9601.54
32 2019-03-01   9041.04
probabilidade_zeros :0.0
score : 680.6787878787881
         data     valor
0  2015-11-01    749.25
1  2015-12-01      0.00
2  2016-01-01   3109.54
3  2016-02-01   3158.00
4  2016-03-01      0.00
5  2016-04-01   3818.50
6  2016-05-01    592.15
7  2016-06-01   5944.50
8  2016-07-01   5350.90
9  2016-08-01   5626.40
10 2016-09-01   4377.88
11 2016-10-01   1737.68
12 2016-11-01   1086.78
13 2016-12-01    408.69
14 2017-01-01   4395.06
15 2017-02-01   3381.40
16 2017-03-01      0.00
17 2017-04-01   3228.45
18 2017-05-01  13442.43
19 2017-06-01   6980.09
20 2017-07-01   3656.99
21 2017-08-01  14318.27
22 2017-09-01   1438.05
23 2017-10-01   4389.04
24 2017-11-01   4595.26
25 2017-12-01   2843.58
26 2018-01-01   3345.75
27 2018-02-01   1946.88
28 2018-03-01   8856.17
29 2018-04-01   5114.80
30 2018-05-01  10872.36
31 2018-06-01   4082.40
32 2018-07-01   2685.58
33 2018-08-01  17434.06
34 2018-09-01   3553.35
35 2018-10-01    379.88
36 2018-11-01   5407.12
37 2018-12-01   3942.30
38 2019-01-01  11842.56
39 2019-02-01  27248.92
40 2019-03-01   6296.18
periodo de elegibilidade : [datetime.date(2018, 10, 1), datetime.date(2018, 11, 1), datetime.date(2018, 12, 1), datetime.date(2019, 1, 1), datetime.date(2019, 2, 1), datetime.date(2019, 3, 1)]
         data     valor
0  2015-11-01    749.25
1  2015-12-01      0.00
2  2016-01-01   3109.54
3  2016-02-01   3158.00
4  2016-03-01      0.00
5  2016-04-01   3818.50
6  2016-05-01    592.15
7  2016-06-01   5944.50
8  2016-07-01   5350.90
9  2016-08-01   5626.40
10 2016-09-01   4377.88
11 2016-10-01   1737.68
12 2016-11-01   1086.78
13 2016-12-01    408.69
14 2017-01-01   4395.06
15 2017-02-01   3381.40
16 2017-03-01      0.00
17 2017-04-01   3228.45
18 2017-05-01  13442.43
19 2017-06-01   6980.09
20 2017-07-01   3656.99
21 2017-08-01  14318.27
22 2017-09-01   1438.05
23 2017-10-01   4389.04
24 2017-11-01   4595.26
25 2017-12-01   2843.58
26 2018-01-01   3345.75
27 2018-02-01   1946.88
28 2018-03-01   8856.17
29 2018-04-01   5114.80
30 2018-05-01  10872.36
31 2018-06-01   4082.40
32 2018-07-01   2685.58
33 2018-08-01  17434.06
34 2018-09-01   3553.35
35 2018-10-01    379.88
36 2018-11-01   5407.12
37 2018-12-01   3942.30
38 2019-01-01  11842.56
39 2019-02-01  27248.92
40 2019-03-01   6296.18
probabilidade_zeros :0.0
         data     valor
0  2018-05-01     63.77
1  2018-06-01  11216.10
2  2018-07-01   7869.00
3  2018-08-01  14134.15
4  2018-09-01   5265.44
5  2018-10-01   8874.10
6  2018-11-01   9101.22
7  2018-12-01  12552.91
8  2019-01-01   9972.64
9  2019-02-01   6736.94
10 2019-03-01   8533.80
periodo de elegibilidade : [datetime.date(2018, 10, 1), datetime.date(2018, 11, 1), datetime.date(2018, 12, 1), datetime.date(2019, 1, 1), datetime.date(2019, 2, 1), datetime.date(2019, 3, 1)]
         data     valor
0  2018-05-01     63.77
1  2018-06-01  11216.10
2  2018-07-01   7869.00
3  2018-08-01  14134.15
4  2018-09-01   5265.44
5  2018-10-01   8874.10
6  2018-11-01   9101.22
7  2018-12-01  12552.91
8  2019-01-01   9972.64
9  2019-02-01   6736.94
10 2019-03-01   8533.80
probabilidade_zeros :0.09090909090909091
score : 688.5151515151514
         data     valor
0  2017-12-01  16351.23
1  2018-01-01  19236.80
2  2018-02-01  14740.70
3  2018-03-01  21801.95
4  2018-04-01  23296.70
5  2018-05-01  17305.16
6  2018-06-01  38984.03
7  2018-07-01  42881.34
8  2018-08-01  34995.27
9  2018-09-01  43198.03
10 2018-10-01  47962.11
11 2018-11-01  34695.82
12 2018-12-01  56101.37
13 2019-01-01  45137.42
14 2019-02-01  29111.32
15 2019-03-01  29533.76
periodo de elegibilidade : [datetime.date(2018, 10, 1), datetime.date(2018, 11, 1), datetime.date(2018, 12, 1), datetime.date(2019, 1, 1), datetime.date(2019, 2, 1), datetime.date(2019, 3, 1)]
         data     valor
0  2017-12-01  16351.23
1  2018-01-01  19236.80
2  2018-02-01  14740.70
3  2018-03-01  21801.95
4  2018-04-01  23296.70
5  2018-05-01  17305.16
6  2018-06-01  38984.03
7  2018-07-01  42881.34
8  2018-08-01  34995.27
9  2018-09-01  43198.03
10 2018-10-01  47962.11
11 2018-11-01  34695.82
12 2018-12-01  56101.37
13 2019-01-01  45137.42
14 2019-02-01  29111.32
15 2019-03-01  29533.76
probabilidade_zeros :0.0
score : 701.7151515151514
         data     valor
0  2016-07-01   5083.46
1  2016-08-01  11769.83
2  2016-09-01  22759.98
3  2016-10-01  18315.53
4  2016-11-01  15651.70
5  2016-12-01  17125.84
6  2017-01-01  18526.31
7  2017-02-01  18820.64
8  2017-03-01  23364.76
9  2017-04-01  15653.26
10 2017-05-01  19419.35
11 2017-06-01  25968.40
12 2017-07-01  22536.25
13 2017-08-01  31579.70
14 2017-09-01  18079.86
15 2017-10-01  14645.73
16 2017-11-01  13890.99
17 2017-12-01  18493.11
18 2018-01-01  18331.34
19 2018-02-01  12788.85
20 2018-03-01  18778.12
21 2018-04-01  22089.20
22 2018-05-01  26716.00
23 2018-06-01  34416.55
24 2018-07-01  20192.88
25 2018-08-01  27045.15
26 2018-09-01  15835.23
27 2018-10-01  26115.99
28 2018-11-01  17666.28
29 2018-12-01  17085.38
30 2019-01-01  22388.71
31 2019-02-01  20407.14
32 2019-03-01  11761.65
periodo de elegibilidade : [datetime.date(2018, 10, 1), datetime.date(2018, 11, 1), datetime.date(2018, 12, 1), datetime.date(2019, 1, 1), datetime.date(2019, 2, 1), datetime.date(2019, 3, 1)]
         data     valor
0  2016-07-01   5083.46
1  2016-08-01  11769.83
2  2016-09-01  22759.98
3  2016-10-01  18315.53
4  2016-11-01  15651.70
5  2016-12-01  17125.84
6  2017-01-01  18526.31
7  2017-02-01  18820.64
8  2017-03-01  23364.76
9  2017-04-01  15653.26
10 2017-05-01  19419.35
11 2017-06-01  25968.40
12 2017-07-01  22536.25
13 2017-08-01  31579.70
14 2017-09-01  18079.86
15 2017-10-01  14645.73
16 2017-11-01  13890.99
17 2017-12-01  18493.11
18 2018-01-01  18331.34
19 2018-02-01  12788.85
20 2018-03-01  18778.12
21 2018-04-01  22089.20
22 2018-05-01  26716.00
23 2018-06-01  34416.55
24 2018-07-01  20192.88
25 2018-08-01  27045.15
26 2018-09-01  15835.23
27 2018-10-01  26115.99
28 2018-11-01  17666.28
29 2018-12-01  17085.38
30 2019-01-01  22388.71
31 2019-02-01  20407.14
32 2019-03-01  11761.65
probabilidade_zeros :0.0

         data     valor
0  2015-12-01  12998.70
1  2016-01-01  32211.50
2  2016-02-01  29664.55
3  2016-03-01  18129.50
4  2016-04-01  13408.10
5  2016-05-01  15599.65
6  2016-06-01  14521.50
7  2016-07-01  27622.50
8  2016-08-01  20046.30
9  2016-09-01   1660.00
10 2016-10-01  53150.44
11 2016-11-01  40973.51
12 2016-12-01  32232.65
13 2017-01-01  41725.68
14 2017-02-01  14778.18
15 2017-03-01      0.00
16 2017-04-01  10250.00
17 2017-05-01  28944.14
18 2017-06-01  20355.89
19 2017-07-01  28249.76
20 2017-08-01  25331.23
21 2017-09-01  21113.10
22 2017-10-01  19242.81
23 2017-11-01  18801.92
24 2017-12-01  11030.00
25 2018-01-01  32787.93
26 2018-02-01  22793.28
27 2018-03-01  22395.86
28 2018-04-01  30392.94
29 2018-05-01  18878.06
30 2018-06-01  24484.08
31 2018-07-01  34813.72
32 2018-08-01  33067.86
33 2018-09-01  18375.26
34 2018-10-01  26432.16
35 2018-11-01  15899.45
36 2018-12-01  33767.70
37 2019-01-01  27592.25
38 2019-02-01  25553.75
39 2019-03-01  24509.00
periodo de elegibilidade : [datetime.date(2018, 10, 1), datetime.date(2018, 11, 1), datetime.date(2018, 12, 1), datetime.date(2019, 1, 1), datetime.date(2019, 2, 1), datetime.date(2019, 3, 1)]
         data     valor
0  2015-12-01  12998.70
1  2016-01-01  32211.50
2  2016-02-01  29664.55
3  2016-03-01  18129.50
4  2016-04-01  13408.10
5  2016-05-01  15599.65
6  2016-06-01  14521.50
7  2016-07-01  27622.50
8  2016-08-01  20046.30
9  2016-09-01   1660.00
10 2016-10-01  53150.44
11 2016-11-01  40973.51
12 2016-12-01  32232.65
13 2017-01-01  41725.68
14 2017-02-01  14778.18
15 2017-03-01      0.00
16 2017-04-01  10250.00
17 2017-05-01  28944.14
18 2017-06-01  20355.89
19 2017-07-01  28249.76
20 2017-08-01  25331.23
21 2017-09-01  21113.10
22 2017-10-01  19242.81
23 2017-11-01  18801.92
24 2017-12-01  11030.00
25 2018-01-01  32787.93
26 2018-02-01  22793.28
27 2018-03-01  22395.86
28 2018-04-01  30392.94
29 2018-05-01  18878.06
30 2018-06-01  24484.08
31 2018-07-01  34813.72
32 2018-08-01  33067.86
33 2018-09-01  18375.26
34 2018-10-01  26432.16
35 2018-11-01  15899.45
36 2018-12-01  33767.70
37 2019-01-01  27592.25
38 2019-02-01  25553.75
39 2019-03-01  24509.00
probabilidade_zeros :0.0
         data    valor
0  2017-09-01   932.04
1  2017-10-01  1797.00
2  2017-11-01  1015.93
3  2017-12-01  2054.09
4  2018-01-01   471.56
5  2018-02-01  1742.96
6  2018-03-01  2662.31
7  2018-04-01  1914.32
8  2018-05-01  2066.00
9  2018-06-01  2086.08
10 2018-07-01  1390.41
11 2018-08-01  1725.60
12 2018-09-01  2310.23
13 2018-10-01  1616.23
14 2018-11-01  2910.96
15 2018-12-01  3121.24
16 2019-01-01  2513.27
17 2019-02-01  2229.86
18 2019-03-01  2543.65
periodo de elegibilidade : [datetime.date(2018, 10, 1), datetime.date(2018, 11, 1), datetime.date(2018, 12, 1), datetime.date(2019, 1, 1), datetime.date(2019, 2, 1), datetime.date(2019, 3, 1)]
         data    valor
0  2017-09-01   932.04
1  2017-10-01  1797.00
2  2017-11-01  1015.93
3  2017-12-01  2054.09
4  2018-01-01   471.56
5  2018-02-01  1742.96
6  2018-03-01  2662.31
7  2018-04-01  1914.32
8  2018-05-01  2066.00
9  2018-06-01  2086.08
10 2018-07-01  1390.41
11 2018-08-01  1725.60
12 2018-09-01  2310.23
13 2018-10-01  1616.23
14 2018-11-01  2910.96
15 2018-12-01  3121.24
16 2019-01-01  2513.27
17 2019-02-01  2229.86
18 2019-03-01  2543.65
probabilidade_zeros :0.0
score : 754.9272727272728
         data     valor
0  2018-04-01   3635.03
1  2018-05-01   8905.77
2  2018-06-01   4620.20
3  2018-07-01   6117.82
4  2018-08-01  10875.12
5  2018-09-01   5328.88
6  2018-10-01   6190.73
7  2018-11-01   5030.32
8  2018-12-01   5574.96
9  2019-01-01   1670.98
10 2019-02-01   7531.01
11 2019-03-01   5980.32
periodo de elegibilidade : [datetime.date(2018, 10, 1), datetime.date(2018, 11, 1), datetime.date(2018, 12, 1), datetime.date(2019, 1, 1), datetime.date(2019, 2, 1), datetime.date(2019, 3, 1)]
         data     valor
0  2018-04-01   3635.03
1  2018-05-01   8905.77
2  2018-06-01   4620.20
3  2018-07-01   6117.82
4  2018-08-01  10875.12
5  2018-09-01   5328.88
6  2018-10-01   6190.73
7  2018-11-01   5030.32
8  2018-12-01   5574.96
9  2019-01-01   1670.98
10 2019-02-01   7531.01
11 2019-03-01   5980.32
probabilidade_zeros :0.0
         data     valor
0  2017-12-01  32053.67
1  2018-01-01  20288.49
2  2018-02-01   9960.55
3  2018-03-01  21946.34
4  2018-04-01  34937.61
5  2018-05-01  57707.26
6  2018-06-01  62561.72
7  2018-07-01  19491.80
8  2018-08-01  29532.90
9  2018-09-01  34564.68
10 2018-10-01  38006.48
11 2018-11-01  61527.27
12 2018-12-01  65609.45
13 2019-01-01  33139.16
14 2019-02-01  31592.41
15 2019-03-01  18223.15
periodo de elegibilidade : [datetime.date(2018, 10, 1), datetime.date(2018, 11, 1), datetime.date(2018, 12, 1), datetime.date(2019, 1, 1), datetime.date(2019, 2, 1), datetime.date(2019, 3, 1)]
         data     valor
0  2017-12-01  32053.67
1  2018-01-01  20288.49
2  2018-02-01   9960.55
3  2018-03-01  21946.34
4  2018-04-01  34937.61
5  2018-05-01  57707.26
6  2018-06-01  62561.72
7  2018-07-01  19491.80
8  2018-08-01  29532.90
9  2018-09-01  34564.68
10 2018-10-01  38006.48
11 2018-11-01  61527.27
12 2018-12-01  65609.45
13 2019-01-01  33139.16
14 2019-02-01  31592.41
15 2019-03-01  18223.15
probabilidade_zeros :0.0
score : 652.8121212121213
         data     valor
0  2016-10-01  21417.01
1  2016-11-01  28690.27
2  2016-12-01  27445.88
3  2017-01-01  31650.15
4  2017-02-01  25590.85
5  2017-03-01  26603.03
6  2017-04-01  16801.14
7  2017-05-01  29263.84
8  2017-06-01  30056.59
9  2017-07-01  30525.12
10 2017-08-01  28722.50
11 2017-09-01  29425.85
12 2017-10-01  31457.73
13 2017-11-01  37050.72
14 2017-12-01  36652.54
15 2018-01-01  29058.95
16 2018-02-01  29565.58
17 2018-03-01  30429.73
18 2018-04-01  33042.99
19 2018-05-01  44737.39
20 2018-06-01  32709.78
21 2018-07-01  91743.00
22 2018-08-01  80499.95
23 2018-09-01  55361.25
24 2018-10-01  74618.99
25 2018-11-01  61998.99
26 2018-12-01  58331.87
27 2019-01-01  77149.32
28 2019-02-01  60088.00
29 2019-03-01  71343.74
periodo de elegibilidade : [datetime.date(2018, 10, 1), datetime.date(2018, 11, 1), datetime.date(2018, 12, 1), datetime.date(2019, 1, 1), datetime.date(2019, 2, 1), datetime.date(2019, 3, 1)]
         data     valor
0  2016-10-01  21417.01
1  2016-11-01  28690.27
2  2016-12-01  27445.88
3  2017-01-01  31650.15
4  2017-02-01  25590.85
5  2017-03-01  26603.03
6  2017-04-01  16801.14
7  2017-05-01  29263.84
8  2017-06-01  30056.59
9  2017-07-01  30525.12
10 2017-08-01  28722.50
11 2017-09-01  29425.85
12 2017-10-01  31457.73
13 2017-11-01  37050.72
14 2017-12-01  36652.54
15 2018-01-01  29058.95
16 2018-02-01  29565.58
17 2018-03-01  30429.73
18 2018-04-01  33042.99
19 2018-05-01  44737.39
20 2018-06-01  32709.78
21 2018-07-01  91743.00
22 2018-08-01  80499.95
23 2018-09-01  55361.25
24 2018-10-01  74618.99
25 2018-11-01  61998.99
26 2018-12-01  58331.87
27 2019-01-01  77149.32
28 2019-02-01  60088.00
29 2019-03-01  71343.74
probabilidade_zeros :0.0
score : 823.6121212121212
         data     valor
0  2017-07-01    493.57
1  2017-08-01   3879.45
2  2017-09-01   3178.26
3  2017-10-01   1696.98
4  2017-11-01   4394.77
5  2017-12-01    546.93
6  2018-01-01   6123.17
7  2018-02-01    265.72
8  2018-03-01   4570.19
9  2018-04-01   6732.47
10 2018-05-01   4710.00
11 2018-06-01   7351.58
12 2018-07-01   1088.43
13 2018-08-01   1888.25
14 2018-09-01   1966.58
15 2018-10-01   2424.37
16 2018-11-01   2723.63
17 2018-12-01   5940.73
18 2019-01-01  13472.32
19 2019-02-01   2582.07
20 2019-03-01  13288.86
periodo de elegibilidade : [datetime.date(2018, 10, 1), datetime.date(2018, 11, 1), datetime.date(2018, 12, 1), datetime.date(2019, 1, 1), datetime.date(2019, 2, 1), datetime.date(2019, 3, 1)]
         data     valor
0  2017-07-01    493.57
1  2017-08-01   3879.45
2  2017-09-01   3178.26
3  2017-10-01   1696.98
4  2017-11-01   4394.77
5  2017-12-01    546.93
6  2018-01-01   6123.17
7  2018-02-01    265.72
8  2018-03-01   4570.19
9  2018-04-01   6732.47
10 2018-05-01   4710.00
11 2018-06-01   7351.58
12 2018-07-01   1088.43
13 2018-08-01   1888.25
14 2018-09-01   1966.58
15 2018-10-01   2424.37
16 2018-11-01   2723.63
17 2018-12-01   5940.73
18 2019-01-01  13472.32
19 2019-02-01   2582.07
20 2019-03-01  13288.86
probabilidade_zeros :0.0

score : 813.4666666666667
         data      valor
0  2018-04-01    3460.00
1  2018-05-01   28316.06
2  2018-06-01   35152.07
3  2018-07-01   31594.16
4  2018-08-01   71317.61
5  2018-09-01   60398.25
6  2018-10-01   72588.68
7  2018-11-01   97048.29
8  2018-12-01   64107.85
9  2019-01-01  134805.22
10 2019-02-01   90005.51
11 2019-03-01  106944.67
periodo de elegibilidade : [datetime.date(2018, 10, 1), datetime.date(2018, 11, 1), datetime.date(2018, 12, 1), datetime.date(2019, 1, 1), datetime.date(2019, 2, 1), datetime.date(2019, 3, 1)]
         data      valor
0  2018-04-01    3460.00
1  2018-05-01   28316.06
2  2018-06-01   35152.07
3  2018-07-01   31594.16
4  2018-08-01   71317.61
5  2018-09-01   60398.25
6  2018-10-01   72588.68
7  2018-11-01   97048.29
8  2018-12-01   64107.85
9  2019-01-01  134805.22
10 2019-02-01   90005.51
11 2019-03-01  106944.67
probabilidade_zeros :0.08333333333333333
score : 740.2666666666668
         data     valor
0  2016-11-01   6293.40
1  2016-12-01   9696.42
2  2017-01-01   5345.42
3  2017-02-01   3275.62
4  2017-03-01   1689.88
5  2017-04-01   7562.40
6  2017-05-01   3716.14
7  2017-06-01  11366.36
8  2017-07-01   1996.74
9  2017-08-01  11261.00
10 2017-09-01   4539.92
11 2017-10-01   8172.60
12 2017-11-01   3160.48
13 2017-12-01   8804.34
14 2018-01-01   7326.42
15 2018-02-01   6131.30
16 2018-03-01   5765.24
17 2018-04-01   9100.96
18 2018-05-01   8590.96
19 2018-06-01   9611.22
20 2018-07-01  10484.64
21 2018-08-01  13129.48
22 2018-09-01  16649.24
23 2018-10-01   8167.34
24 2018-11-01   9597.44
25 2018-12-01  10308.22
26 2019-01-01   7122.34
27 2019-02-01   8230.82
28 2019-03-01  10724.02
periodo de elegibilidade : [datetime.date(2018, 10, 1), datetime.date(2018, 11, 1), datetime.date(2018, 12, 1), datetime.date(2019, 1, 1), datetime.date(2019, 2, 1), datetime.date(2019, 3, 1)]
         data     valor
0  2016-11-01   6293.40
1  2016-12-01   9696.42
2  2017-01-01   5345.42
3  2017-02-01   3275.62
4  2017-03-01   1689.88
5  2017-04-01   7562.40
6  2017-05-01   3716.14
7  2017-06-01  11366.36
8  2017-07-01   1996.74
9  2017-08-01  11261.00
10 2017-09-01   4539.92
11 2017-10-01   8172.60
12 2017-11-01   3160.48
13 2017-12-01   8804.34
14 2018-01-01   7326.42
15 2018-02-01   6131.30
16 2018-03-01   5765.24
17 2018-04-01   9100.96
18 2018-05-01   8590.96
19 2018-06-01   9611.22
20 2018-07-01  10484.64
21 2018-08-01  13129.48
22 2018-09-01  16649.24
23 2018-10-01   8167.34
24 2018-11-01   9597.44
25 2018-12-01  10308.22
26 2019-01-01   7122.34
27 2019-02-01   8230.82
28 2019-03-01  10724.02
probabilidade_zeros :0.0
score : 721.2242424242426
         data     valor
0  2015-11-01   2747.25
1  2015-12-01   2747.25
2  2016-01-01   5803.90
3  2016-02-01   7370.75
4  2016-03-01   5626.40
5  2016-04-01   4907.15
6  2016-05-01   7469.10
7  2016-06-01   8739.15
8  2016-07-01   4851.30
9  2016-08-01  16593.30
10 2016-09-01   7319.13
11 2016-10-01  10620.28
12 2016-11-01   2860.93
13 2016-12-01   7523.28
14 2017-01-01   5361.90
15 2017-02-01   4350.30
16 2017-03-01   3287.40
17 2017-04-01   2822.49
18 2017-05-01   6385.16
19 2017-06-01   3688.02
20 2017-07-01   1389.90
21 2017-08-01  10121.35
22 2017-09-01   6777.85
23 2017-10-01   6665.68
24 2017-11-01   5301.36
25 2017-12-01  10220.15
26 2018-01-01   9966.40
27 2018-02-01   3876.90
28 2018-03-01   8697.06
29 2018-04-01   9453.23
30 2018-05-01   2101.96
31 2018-06-01   7437.64
32 2018-07-01   9724.40
33 2018-08-01   9391.23
34 2018-09-01  13219.72
35 2018-10-01  11789.48
36 2018-11-01   9970.11
37 2018-12-01   8413.51
38 2019-01-01   7152.56
39 2019-02-01   3736.60
40 2019-03-01  20881.80
periodo de elegibilidade : [datetime.date(2018, 10, 1), datetime.date(2018, 11, 1), datetime.date(2018, 12, 1), datetime.date(2019, 1, 1), datetime.date(2019, 2, 1), datetime.date(2019, 3, 1)]
         data     valor
0  2015-11-01   2747.25
1  2015-12-01   2747.25
2  2016-01-01   5803.90
3  2016-02-01   7370.75
4  2016-03-01   5626.40
5  2016-04-01   4907.15
6  2016-05-01   7469.10
7  2016-06-01   8739.15
8  2016-07-01   4851.30
9  2016-08-01  16593.30
10 2016-09-01   7319.13
11 2016-10-01  10620.28
12 2016-11-01   2860.93
13 2016-12-01   7523.28
14 2017-01-01   5361.90
15 2017-02-01   4350.30
16 2017-03-01   3287.40
17 2017-04-01   2822.49
18 2017-05-01   6385.16
19 2017-06-01   3688.02
20 2017-07-01   1389.90
21 2017-08-01  10121.35
22 2017-09-01   6777.85
23 2017-10-01   6665.68
24 2017-11-01   5301.36
25 2017-12-01  10220.15
26 2018-01-01   9966.40
27 2018-02-01   3876.90
28 2018-03-01   8697.06
29 2018-04-01   9453.23
30 2018-05-01   2101.96
31 2018-06-01   7437.64
32 2018-07-01   9724.40
33 2018-08-01   9391.23
34 2018-09-01  13219.72
35 2018-10-01  11789.48
36 2018-11-01   9970.11
37 2018-12-01   8413.51
38 2019-01-01   7152.56
39 2019-02-01   3736.60
40 2019-03-01  20881.80
probabilidade_zeros :0.0
         data    valor
0  2017-12-01  1531.54
1  2018-01-01  6629.91
2  2018-02-01  3238.74
3  2018-03-01  3043.16
4  2018-04-01  3014.99
5  2018-05-01  2060.64
6  2018-06-01  3397.64
7  2018-07-01  4838.95
8  2018-08-01  1830.37
9  2018-09-01  3121.01
10 2018-10-01  3095.17
11 2018-11-01  2864.04
12 2018-12-01  4015.99
13 2019-01-01  1951.51
14 2019-02-01   633.52
15 2019-03-01  2764.27
periodo de elegibilidade : [datetime.date(2018, 10, 1), datetime.date(2018, 11, 1), datetime.date(2018, 12, 1), datetime.date(2019, 1, 1), datetime.date(2019, 2, 1), datetime.date(2019, 3, 1)]
         data    valor
0  2017-12-01  1531.54
1  2018-01-01  6629.91
2  2018-02-01  3238.74
3  2018-03-01  3043.16
4  2018-04-01  3014.99
5  2018-05-01  2060.64
6  2018-06-01  3397.64
7  2018-07-01  4838.95
8  2018-08-01  1830.37
9  2018-09-01  3121.01
10 2018-10-01  3095.17
11 2018-11-01  2864.04
12 2018-12-01  4015.99
13 2019-01-01  1951.51
14 2019-02-01   633.52
15 2019-03-01  2764.27
probabilidade_zeros :0.0
score : 697.8424242424243
         data     valor
0  2016-03-01  18272.20
1  2016-04-01  19969.46
2  2016-05-01   7610.97
3  2016-06-01  14558.68
4  2016-07-01   9374.04
5  2016-08-01  28752.60
6  2016-09-01  11020.16
7  2016-10-01  18498.78
8  2016-11-01  20016.14
9  2016-12-01  12208.75
10 2017-01-01  23381.05
11 2017-02-01  17940.27
12 2017-03-01  33912.76
13 2017-04-01  15480.18
14 2017-05-01  22172.22
15 2017-06-01  31010.28
16 2017-07-01   9227.61
17 2017-08-01   5056.08
18 2017-09-01  15960.97
19 2017-10-01  29399.47
20 2017-11-01  11685.86
21 2017-12-01   8859.16
22 2018-01-01  29220.31
23 2018-02-01  49626.71
24 2018-03-01   4724.54
25 2018-04-01  21753.48
26 2018-05-01  50283.48
27 2018-06-01   8433.72
28 2018-07-01  30651.02
29 2018-08-01   2527.14
30 2018-09-01  36637.36
31 2018-10-01  15759.47
32 2018-11-01  23004.91
33 2018-12-01  31723.19
34 2019-01-01  19796.55
35 2019-02-01  17174.31
36 2019-03-01  17151.39
periodo de elegibilidade : [datetime.date(2018, 10, 1), datetime.date(2018, 11, 1), datetime.date(2018, 12, 1), datetime.date(2019, 1, 1), datetime.date(2019, 2, 1), datetime.date(2019, 3, 1)]
         data     valor
0  2016-03-01  18272.20
1  2016-04-01  19969.46
2  2016-05-01   7610.97
3  2016-06-01  14558.68
4  2016-07-01   9374.04
5  2016-08-01  28752.60
6  2016-09-01  11020.16
7  2016-10-01  18498.78
8  2016-11-01  20016.14
9  2016-12-01  12208.75
10 2017-01-01  23381.05
11 2017-02-01  17940.27
12 2017-03-01  33912.76
13 2017-04-01  15480.18
14 2017-05-01  22172.22
15 2017-06-01  31010.28
16 2017-07-01   9227.61
17 2017-08-01   5056.08
18 2017-09-01  15960.97
19 2017-10-01  29399.47
20 2017-11-01  11685.86
21 2017-12-01   8859.16
22 2018-01-01  29220.31
23 2018-02-01  49626.71
24 2018-03-01   4724.54
25 2018-04-01  21753.48
26 2018-05-01  50283.48
27 2018-06-01   8433.72
28 2018-07-01  30651.02
29 2018-08-01   2527.14
30 2018-09-01  36637.36
31 2018-10-01  15759.47
32 2018-11-01  23004.91
33 2018-12-01  31723.19
34 2019-01-01  19796.55
35 2019-02-01  17174.31
36 2019-03-01  17151.39
probabilidade_zeros :0.0
         data     valor
0  2015-10-01   9173.60
1  2015-11-01   5669.60
2  2015-12-01  13954.55
3  2016-01-01   9581.95
4  2016-02-01  10808.50
5  2016-03-01  15575.35
6  2016-04-01  11570.35
7  2016-05-01  28194.75
8  2016-06-01  12313.00
9  2016-07-01  19449.05
10 2016-08-01  37056.40
11 2016-09-01  33724.63
12 2016-10-01  37445.45
13 2016-11-01  34836.95
14 2016-12-01  33436.65
15 2017-01-01  30575.75
16 2017-02-01  31554.70
17 2017-03-01  38053.05
18 2017-04-01  25080.76
19 2017-05-01  31518.47
20 2017-06-01  48892.33
21 2017-07-01  38178.04
22 2017-08-01  53971.13
23 2017-09-01  29871.27
24 2017-10-01  49323.14
25 2017-11-01  35223.01
26 2017-12-01  32742.42
27 2018-01-01  54035.55
28 2018-02-01  38641.94
29 2018-03-01  55518.74
30 2018-04-01  54470.12
31 2018-05-01  44838.82
32 2018-06-01  51915.85
33 2018-07-01  63429.63
34 2018-08-01  73267.06
35 2018-09-01  74196.49
36 2018-10-01  40081.82
37 2018-11-01  55311.29
38 2018-12-01  28975.88
39 2019-01-01  18517.30
40 2019-02-01  19134.74
41 2019-03-01    600.00
periodo de elegibilidade : [datetime.date(2018, 10, 1), datetime.date(2018, 11, 1), datetime.date(2018, 12, 1), datetime.date(2019, 1, 1), datetime.date(2019, 2, 1), datetime.date(2019, 3, 1)]
         data     valor
0  2015-10-01   9173.60
1  2015-11-01   5669.60
2  2015-12-01  13954.55
3  2016-01-01   9581.95
4  2016-02-01  10808.50
5  2016-03-01  15575.35
6  2016-04-01  11570.35
7  2016-05-01  28194.75
8  2016-06-01  12313.00
9  2016-07-01  19449.05
10 2016-08-01  37056.40
11 2016-09-01  33724.63
12 2016-10-01  37445.45
13 2016-11-01  34836.95
14 2016-12-01  33436.65
15 2017-01-01  30575.75
16 2017-02-01  31554.70
17 2017-03-01  38053.05
18 2017-04-01  25080.76
19 2017-05-01  31518.47
20 2017-06-01  48892.33
21 2017-07-01  38178.04
22 2017-08-01  53971.13
23 2017-09-01  29871.27
24 2017-10-01  49323.14
25 2017-11-01  35223.01
26 2017-12-01  32742.42
27 2018-01-01  54035.55
28 2018-02-01  38641.94
29 2018-03-01  55518.74
30 2018-04-01  54470.12
31 2018-05-01  44838.82
32 2018-06-01  51915.85
33 2018-07-01  63429.63
34 2018-08-01  73267.06
35 2018-09-01  74196.49
36 2018-10-01  40081.82
37 2018-11-01  55311.29
38 2018-12-01  28975.88
39 2019-01-01  18517.30
40 2019-02-01  19134.74
41 2019-03-01    600.00
probabilidade_zeros :0.0

score : 376.2087542087542
        data     valor
0 2018-08-01  40747.68
1 2018-09-01  44749.60
2 2018-10-01  35164.42
3 2018-11-01  59701.23
4 2018-12-01  33181.33
5 2019-01-01  33882.85
6 2019-02-01  28055.11
7 2019-03-01  32218.27
periodo de elegibilidade : [datetime.date(2018, 10, 1), datetime.date(2018, 11, 1), datetime.date(2018, 12, 1), datetime.date(2019, 1, 1), datetime.date(2019, 2, 1), datetime.date(2019, 3, 1)]
        data     valor
0 2018-08-01  40747.68
1 2018-09-01  44749.60
2 2018-10-01  35164.42
3 2018-11-01  59701.23
4 2018-12-01  33181.33
5 2019-01-01  33882.85
6 2019-02-01  28055.11
7 2019-03-01  32218.27
probabilidade_zeros :0.0
score : 697.6787878787881
         data     valor
0  2018-03-01   4585.21
1  2018-04-01   3266.89
2  2018-05-01   4031.33
3  2018-06-01   3782.26
4  2018-07-01   2077.02
5  2018-08-01   2211.67
6  2018-09-01  11601.75
7  2018-10-01   2784.64
8  2018-11-01   6894.67
9  2018-12-01   3984.63
10 2019-01-01  11211.35
11 2019-02-01   6885.17
12 2019-03-01   3716.73
periodo de elegibilidade : [datetime.date(2018, 10, 1), datetime.date(2018, 11, 1), datetime.date(2018, 12, 1), datetime.date(2019, 1, 1), datetime.date(2019, 2, 1), datetime.date(2019, 3, 1)]
         data     valor
0  2018-03-01   4585.21
1  2018-04-01   3266.89
2  2018-05-01   4031.33
3  2018-06-01   3782.26
4  2018-07-01   2077.02
5  2018-08-01   2211.67
6  2018-09-01  11601.75
7  2018-10-01   2784.64
8  2018-11-01   6894.67
9  2018-12-01   3984.63
10 2019-01-01  11211.35
11 2019-02-01   6885.17
12 2019-03-01   3716.73
probabilidade_zeros :0.0
score : 630.6575757575756
         data    valor
0  2017-12-01  1824.93
1  2018-01-01  2386.26
2  2018-02-01  3981.60
3  2018-03-01  6642.30
4  2018-04-01  5275.38
5  2018-05-01  2090.50
6  2018-06-01  4203.10
7  2018-07-01  8133.30
8  2018-08-01  6697.52
9  2018-09-01  3560.42
10 2018-10-01  4629.62
11 2018-11-01  1600.68
12 2018-12-01  1078.12
13 2019-01-01  3495.44
14 2019-02-01  2990.50
15 2019-03-01  5020.84
periodo de elegibilidade : [datetime.date(2018, 10, 1), datetime.date(2018, 11, 1), datetime.date(2018, 12, 1), datetime.date(2019, 1, 1), datetime.date(2019, 2, 1), datetime.date(2019, 3, 1)]
         data    valor
0  2017-12-01  1824.93
1  2018-01-01  2386.26
2  2018-02-01  3981.60
3  2018-03-01  6642.30
4  2018-04-01  5275.38
5  2018-05-01  2090.50
6  2018-06-01  4203.10
7  2018-07-01  8133.30
8  2018-08-01  6697.52
9  2018-09-01  3560.42
10 2018-10-01  4629.62
11 2018-11-01  1600.68
12 2018-12-01  1078.12
13 2019-01-01  3495.44
14 2019-02-01  2990.50
15 2019-03-01  5020.84
probabilidade_zeros :0.0
         data     valor
0  2016-09-01   3770.25
1  2016-10-01  24394.97
2  2016-11-01  26550.22
3  2016-12-01  18863.46
4  2017-01-01  42079.71
5  2017-02-01  40706.34
6  2017-03-01  26739.86
7  2017-04-01  29631.73
8  2017-05-01  44852.15
9  2017-06-01  40631.57
10 2017-07-01  32581.77
11 2017-08-01  28499.04
12 2017-09-01  47633.04
13 2017-10-01  36150.77
14 2017-11-01  35547.73
15 2017-12-01  36451.96
16 2018-01-01  22980.87
17 2018-02-01  35713.24
18 2018-03-01  26155.39
19 2018-04-01  25664.83
20 2018-05-01  66752.30
21 2018-06-01  39539.97
22 2018-07-01  33990.87
23 2018-08-01  23043.93
24 2018-09-01  19277.30
25 2018-10-01  22279.38
26 2018-11-01  37129.34
27 2018-12-01  47028.09
28 2019-01-01  34694.22
29 2019-02-01  55188.95
30 2019-03-01  42388.85
periodo de elegibilidade : [datetime.date(2018, 10, 1), datetime.date(2018, 11, 1), datetime.date(2018, 12, 1), datetime.date(2019, 1, 1), datetime.date(2019, 2, 1), datetime.date(2019, 3, 1)]
         data     valor
0  2016-09-01   3770.25
1  2016-10-01  24394.97
2  2016-11-01  26550.22
3  2016-12-01  18863.46
4  2017-01-01  42079.71
5  2017-02-01  40706.34
6  2017-03-01  26739.86
7  2017-04-01  29631.73
8  2017-05-01  44852.15
9  2017-06-01  40631.57
10 2017-07-01  32581.77
11 2017-08-01  28499.04
12 2017-09-01  47633.04
13 2017-10-01  36150.77
14 2017-11-01  35547.73
15 2017-12-01  36451.96
16 2018-01-01  22980.87
17 2018-02-01  35713.24
18 2018-03-01  26155.39
19 2018-04-01  25664.83
20 2018-05-01  66752.30
21 2018-06-01  39539.97
22 2018-07-01  33990.87
23 2018-08-01  23043.93
24 2018-09-01  19277.30
25 2018-10-01  22279.38
26 2018-11-01  37129.34
27 2018-12-01  47028.09
28 2019-01-01  34694.22
29 2019-02-01  55188.95
30 2019-03-01  42388.85
probabilidade_zeros :0.0
         data      valor
0  2017-08-01     832.74
1  2017-09-01   18921.20
2  2017-10-01   15206.62
3  2017-11-01   17682.84
4  2017-12-01   24437.93
5  2018-01-01   24444.74
6  2018-02-01   16665.66
7  2018-03-01    8583.64
8  2018-04-01   20391.62
9  2018-05-01   15760.06
10 2018-06-01    4081.63
11 2018-07-01   25331.26
12 2018-08-01   18150.02
13 2018-09-01   26886.46
14 2018-10-01   21125.73
15 2018-11-01   27145.63
16 2018-12-01   63275.78
17 2019-01-01  120272.16
18 2019-02-01   50390.85
19 2019-03-01   79038.85
periodo de elegibilidade : [datetime.date(2018, 10, 1), datetime.date(2018, 11, 1), datetime.date(2018, 12, 1), datetime.date(2019, 1, 1), datetime.date(2019, 2, 1), datetime.date(2019, 3, 1)]
         data      valor
0  2017-08-01     832.74
1  2017-09-01   18921.20
2  2017-10-01   15206.62
3  2017-11-01   17682.84
4  2017-12-01   24437.93
5  2018-01-01   24444.74
6  2018-02-01   16665.66
7  2018-03-01    8583.64
8  2018-04-01   20391.62
9  2018-05-01   15760.06
10 2018-06-01    4081.63
11 2018-07-01   25331.26
12 2018-08-01   18150.02
13 2018-09-01   26886.46
14 2018-10-01   21125.73
15 2018-11-01   27145.63
16 2018-12-01   63275.78
17 2019-01-01  120272.16
18 2019-02-01   50390.85
19 2019-03-01   79038.85
probabilidade_zeros :0.0
score : 745.2090909090908
         data     valor
0  2017-01-01   6831.23
1  2017-02-01  12282.04
2  2017-03-01  19624.53
3  2017-04-01  10231.42
4  2017-05-01  17120.70
5  2017-06-01  14366.74
6  2017-07-01  16934.03
7  2017-08-01  15032.41
8  2017-09-01  12409.85
9  2017-10-01  16021.71
10 2017-11-01  16977.64
11 2017-12-01   7698.69
12 2018-01-01   8459.41
13 2018-02-01   8410.19
14 2018-03-01  15304.28
15 2018-04-01  22711.89
16 2018-05-01  22649.32
17 2018-06-01  14377.16
18 2018-07-01  21900.91
19 2018-08-01  28637.08
20 2018-09-01  27574.60
21 2018-10-01  22161.71
22 2018-11-01  24103.02
23 2018-12-01  25697.14
24 2019-01-01  29496.63
25 2019-02-01  21872.48
26 2019-03-01  12938.06
periodo de elegibilidade : [datetime.date(2018, 10, 1), datetime.date(2018, 11, 1), datetime.date(2018, 12, 1), datetime.date(2019, 1, 1), datetime.date(2019, 2, 1), datetime.date(2019, 3, 1)]
         data     valor
0  2017-01-01   6831.23
1  2017-02-01  12282.04
2  2017-03-01  19624.53
3  2017-04-01  10231.42
4  2017-05-01  17120.70
5  2017-06-01  14366.74
6  2017-07-01  16934.03
7  2017-08-01  15032.41
8  2017-09-01  12409.85
9  2017-10-01  16021.71
10 2017-11-01  16977.64
11 2017-12-01   7698.69
12 2018-01-01   8459.41
13 2018-02-01   8410.19
14 2018-03-01  15304.28
15 2018-04-01  22711.89
16 2018-05-01  22649.32
17 2018-06-01  14377.16
18 2018-07-01  21900.91
19 2018-08-01  28637.08
20 2018-09-01  27574.60
21 2018-10-01  22161.71
22 2018-11-01  24103.02
23 2018-12-01  25697.14
24 2019-01-01  29496.63
25 2019-02-01  21872.48
26 2019-03-01  12938.06
probabilidade_zeros :0.0
score : 684.2242424242426
         data     valor
0  2016-02-01   2367.50
1  2016-03-01    661.00
2  2016-04-01      0.00
3  2016-05-01   5443.20
4  2016-06-01   2022.80
5  2016-07-01   9788.40
6  2016-08-01  10454.60
7  2016-09-01  26858.65
8  2016-10-01   4977.00
9  2016-11-01  10372.20
10 2016-12-01   3689.80
11 2017-01-01  12428.20
12 2017-02-01   4898.40
13 2017-03-01  12492.65
14 2017-04-01  11357.80
15 2017-05-01   2852.20
16 2017-06-01  11691.32
17 2017-07-01  12080.88
18 2017-08-01  11638.20
19 2017-09-01   6279.27
20 2017-10-01  16831.79
21 2017-11-01   5787.58
22 2017-12-01  10298.95
23 2018-01-01   6073.35
24 2018-02-01  11109.29
25 2018-03-01   8650.66
26 2018-04-01  20868.03
27 2018-05-01  17017.25
28 2018-06-01  20600.52
29 2018-07-01  17822.80
30 2018-08-01  38043.58
31 2018-09-01  22928.02
32 2018-10-01  34794.22
33 2018-11-01  13609.32
34 2018-12-01  35095.86
35 2019-01-01  15868.84
36 2019-02-01  19479.02
37 2019-03-01   1313.54
periodo de elegibilidade : [datetime.date(2018, 10, 1), datetime.date(2018, 11, 1), datetime.date(2018, 12, 1), datetime.date(2019, 1, 1), datetime.date(2019, 2, 1), datetime.date(2019, 3, 1)]
         data     valor
0  2016-02-01   2367.50
1  2016-03-01    661.00
2  2016-04-01      0.00
3  2016-05-01   5443.20
4  2016-06-01   2022.80
5  2016-07-01   9788.40
6  2016-08-01  10454.60
7  2016-09-01  26858.65
8  2016-10-01   4977.00
9  2016-11-01  10372.20
10 2016-12-01   3689.80
11 2017-01-01  12428.20
12 2017-02-01   4898.40
13 2017-03-01  12492.65
14 2017-04-01  11357.80
15 2017-05-01   2852.20
16 2017-06-01  11691.32
17 2017-07-01  12080.88
18 2017-08-01  11638.20
19 2017-09-01   6279.27
20 2017-10-01  16831.79
21 2017-11-01   5787.58
22 2017-12-01  10298.95
23 2018-01-01   6073.35
24 2018-02-01  11109.29
25 2018-03-01   8650.66
26 2018-04-01  20868.03
27 2018-05-01  17017.25
28 2018-06-01  20600.52
29 2018-07-01  17822.80
30 2018-08-01  38043.58
31 2018-09-01  22928.02
32 2018-10-01  34794.22
33 2018-11-01  13609.32
34 2018-12-01  35095.86
35 2019-01-01  15868.84
36 2019-02-01  19479.02
37 2019-03-01   1313.54
probabilidade_zeros :0.0

score : 418.5454545454547
         data     valor
0  2017-12-01   1539.36
1  2018-01-01   3695.06
2  2018-02-01   9236.98
3  2018-03-01   8784.09
4  2018-04-01   7429.59
5  2018-05-01  13530.52
6  2018-06-01  15040.08
7  2018-07-01   7315.44
8  2018-08-01  14774.24
9  2018-09-01  11444.07
10 2018-10-01   8576.53
11 2018-11-01   9631.98
12 2018-12-01  11882.79
13 2019-01-01  24183.07
14 2019-02-01   9482.37
15 2019-03-01  12751.47
periodo de elegibilidade : [datetime.date(2018, 10, 1), datetime.date(2018, 11, 1), datetime.date(2018, 12, 1), datetime.date(2019, 1, 1), datetime.date(2019, 2, 1), datetime.date(2019, 3, 1)]
         data     valor
0  2017-12-01   1539.36
1  2018-01-01   3695.06
2  2018-02-01   9236.98
3  2018-03-01   8784.09
4  2018-04-01   7429.59
5  2018-05-01  13530.52
6  2018-06-01  15040.08
7  2018-07-01   7315.44
8  2018-08-01  14774.24
9  2018-09-01  11444.07
10 2018-10-01   8576.53
11 2018-11-01   9631.98
12 2018-12-01  11882.79
13 2019-01-01  24183.07
14 2019-02-01   9482.37
15 2019-03-01  12751.47
probabilidade_zeros :0.0
score : 704.8848484848486
         data     valor
0  2018-03-01  10002.46
1  2018-04-01   8196.64
2  2018-05-01  10943.41
3  2018-06-01   7805.70
4  2018-07-01   7717.22
5  2018-08-01   9505.90
6  2018-09-01   7362.65
7  2018-10-01  16366.32
8  2018-11-01  18087.75
9  2018-12-01   7216.81
10 2019-01-01   7551.13
11 2019-02-01   5602.33
12 2019-03-01   5801.66
periodo de elegibilidade : [datetime.date(2018, 10, 1), datetime.date(2018, 11, 1), datetime.date(2018, 12, 1), datetime.date(2019, 1, 1), datetime.date(2019, 2, 1), datetime.date(2019, 3, 1)]
         data     valor
0  2018-03-01  10002.46
1  2018-04-01   8196.64
2  2018-05-01  10943.41
3  2018-06-01   7805.70
4  2018-07-01   7717.22
5  2018-08-01   9505.90
6  2018-09-01   7362.65
7  2018-10-01  16366.32
8  2018-11-01  18087.75
9  2018-12-01   7216.81
10 2019-01-01   7551.13
11 2019-02-01   5602.33
12 2019-03-01   5801.66
probabilidade_zeros :0.0
         data     valor
0  2017-12-01  43207.69
1  2018-01-01  52063.79
2  2018-02-01  35439.84
3  2018-03-01  42772.07
4  2018-04-01  56078.38
5  2018-05-01  53005.81
6  2018-06-01  91303.41
7  2018-07-01  65316.82
8  2018-08-01  84402.55
9  2018-09-01  50207.62
10 2018-10-01  50140.17
11 2018-11-01  89086.32
12 2018-12-01  72322.01
13 2019-01-01  69644.38
14 2019-02-01  52642.41
15 2019-03-01  37172.65
periodo de elegibilidade : [datetime.date(2018, 10, 1), datetime.date(2018, 11, 1), datetime.date(2018, 12, 1), datetime.date(2019, 1, 1), datetime.date(2019, 2, 1), datetime.date(2019, 3, 1)]
         data     valor
0  2017-12-01  43207.69
1  2018-01-01  52063.79
2  2018-02-01  35439.84
3  2018-03-01  42772.07
4  2018-04-01  56078.38
5  2018-05-01  53005.81
6  2018-06-01  91303.41
7  2018-07-01  65316.82
8  2018-08-01  84402.55
9  2018-09-01  50207.62
10 2018-10-01  50140.17
11 2018-11-01  89086.32
12 2018-12-01  72322.01
13 2019-01-01  69644.38
14 2019-02-01  52642.41
15 2019-03-01  37172.65
probabilidade_zeros :0.0
score : 684.8969696969698
         data     valor
0  2018-04-01     21.59
1  2018-05-01    136.52
2  2018-06-01    948.56
3  2018-07-01    602.52
4  2018-08-01  14916.50
5  2018-09-01  20354.65
6  2018-10-01  27635.03
7  2018-11-01  25761.34
8  2018-12-01  30282.61
9  2019-01-01  20876.44
10 2019-02-01  20113.55
11 2019-03-01  13558.15
periodo de elegibilidade : [datetime.date(2018, 10, 1), datetime.date(2018, 11, 1), datetime.date(2018, 12, 1), datetime.date(2019, 1, 1), datetime.date(2019, 2, 1), datetime.date(2019, 3, 1)]
         data     valor
0  2018-04-01     21.59
1  2018-05-01    136.52
2  2018-06-01    948.56
3  2018-07-01    602.52
4  2018-08-01  14916.50
5  2018-09-01  20354.65
6  2018-10-01  27635.03
7  2018-11-01  25761.34
8  2018-12-01  30282.61
9  2019-01-01  20876.44
10 2019-02-01  20113.55
11 2019-03-01  13558.15
probabilidade_zeros :0.3333333333333333
score : 616.1363636363636
        data     valor
0 2018-09-01   3474.34
1 2018-10-01  12788.70
2 2018-11-01   3753.18
3 2018-12-01   3018.32
4 2019-01-01  10492.94
5 2019-02-01   1632.66
6 2019-03-01    254.75
periodo de elegibilidade : [datetime.date(2018, 10, 1), datetime.date(2018, 11, 1), datetime.date(2018, 12, 1), datetime.date(2019, 1, 1), datetime.date(2019, 2, 1), datetime.date(2019, 3, 1)]
        data     valor
0 2018-09-01   3474.34
1 2018-10-01  12788.70
2 2018-11-01   3753.18
3 2018-12-01   3018.32
4 2019-01-01  10492.94
5 2019-02-01   1632.66
6 2019-03-01    254.75
probabilidade_zeros :0.0
score : 210.0
         data     valor
0  2017-11-01   9104.30
1  2017-12-01  21920.50
2  2018-01-01  34195.79
3  2018-02-01  22975.56
4  2018-03-01  36712.28
5  2018-04-01  28389.22
6  2018-05-01  29795.50
7  2018-06-01  52366.10
8  2018-07-01  33437.96
9  2018-08-01  67446.58
10 2018-09-01  78127.83
11 2018-10-01  94882.65
12 2018-11-01  92038.47
13 2018-12-01  88279.34
14 2019-01-01  72515.28
15 2019-02-01  61317.36
16 2019-03-01   1156.56
periodo de elegibilidade : [datetime.date(2018, 10, 1), datetime.date(2018, 11, 1), datetime.date(2018, 12, 1), datetime.date(2019, 1, 1), datetime.date(2019, 2, 1), datetime.date(2019, 3, 1)]
         data     valor
0  2017-11-01   9104.30
1  2017-12-01  21920.50
2  2018-01-01  34195.79
3  2018-02-01  22975.56
4  2018-03-01  36712.28
5  2018-04-01  28389.22
6  2018-05-01  29795.50
7  2018-06-01  52366.10
8  2018-07-01  33437.96
9  2018-08-01  67446.58
10 2018-09-01  78127.83
11 2018-10-01  94882.65
12 2018-11-01  92038.47
13 2018-12-01  88279.34
14 2019-01-01  72515.28
15 2019-02-01  61317.36
16 2019-03-01   1156.56
probabilidade_zeros :0.0
score : 383.24242424242425
         data     valor
0  2017-11-01   2009.62
1  2017-12-01    989.18
2  2018-01-01      0.00
3  2018-02-01      0.00
4  2018-03-01  14312.76
5  2018-04-01   7236.26
6  2018-05-01   3416.69
7  2018-06-01  15561.98
8  2018-07-01  10245.53
9  2018-08-01   2478.36
10 2018-09-01   9375.57
11 2018-10-01  13277.66
12 2018-11-01  10737.03
13 2018-12-01   3078.33
14 2019-01-01  22200.43
15 2019-02-01   9272.69
16 2019-03-01  12928.84
periodo de elegibilidade : [datetime.date(2018, 10, 1), datetime.date(2018, 11, 1), datetime.date(2018, 12, 1), datetime.date(2019, 1, 1), datetime.date(2019, 2, 1), datetime.date(2019, 3, 1)]
         data     valor
0  2017-11-01   2009.62
1  2017-12-01    989.18
2  2018-01-01      0.00
3  2018-02-01      0.00
4  2018-03-01  14312.76
5  2018-04-01   7236.26
6  2018-05-01   3416.69
7  2018-06-01  15561.98
8  2018-07-01  10245.53
9  2018-08-01   2478.36
10 2018-09-01   9375.57
11 2018-10-01  13277.66
12 2018-11-01  10737.03
13 2018-12-01   3078.33
14 2019-01-01  22200.43
15 2019-02-01   9272.69
16 2019-03-01  12928.84
probabilidade_zeros :0.0
score : 691.1636363636363
         data     valor
0  2015-11-01   1840.90
1  2015-12-01    249.75
2  2016-01-01   6933.50
3  2016-02-01  10247.30
4  2016-03-01  11789.85
5  2016-04-01  22709.40
6  2016-05-01  10267.20
7  2016-06-01  17734.35
8  2016-07-01  27368.25
9  2016-08-01  21573.50
10 2016-09-01  10690.27
11 2016-10-01  15943.72
12 2016-11-01  28918.46
13 2016-12-01  38771.10
14 2017-01-01  38058.79
15 2017-02-01  13989.27
16 2017-03-01   7792.57
17 2017-04-01  20485.04
18 2017-05-01  28596.62
19 2017-06-01  18054.93
20 2017-07-01  24425.63
21 2017-08-01  24703.08
22 2017-09-01  18170.14
23 2017-10-01  33354.57
24 2017-11-01  36599.34
25 2017-12-01  27953.63
26 2018-01-01  46666.76
27 2018-02-01  27935.66
28 2018-03-01  17614.57
29 2018-04-01  30896.29
30 2018-05-01  23183.76
31 2018-06-01  19088.63
32 2018-07-01  29881.01
33 2018-08-01  40426.80
34 2018-09-01  14202.02
35 2018-10-01  44273.37
36 2018-11-01  34642.26
37 2018-12-01  33726.92
38 2019-01-01  27437.56
39 2019-02-01  25134.54
40 2019-03-01    612.76
periodo de elegibilidade : [datetime.date(2018, 10, 1), datetime.date(2018, 11, 1), datetime.date(2018, 12, 1), datetime.date(2019, 1, 1), datetime.date(2019, 2, 1), datetime.date(2019, 3, 1)]
         data     valor
0  2015-11-01   1840.90
1  2015-12-01    249.75
2  2016-01-01   6933.50
3  2016-02-01  10247.30
4  2016-03-01  11789.85
5  2016-04-01  22709.40
6  2016-05-01  10267.20
7  2016-06-01  17734.35
8  2016-07-01  27368.25
9  2016-08-01  21573.50
10 2016-09-01  10690.27
11 2016-10-01  15943.72
12 2016-11-01  28918.46
13 2016-12-01  38771.10
14 2017-01-01  38058.79
15 2017-02-01  13989.27
16 2017-03-01   7792.57
17 2017-04-01  20485.04
18 2017-05-01  28596.62
19 2017-06-01  18054.93
20 2017-07-01  24425.63
21 2017-08-01  24703.08
22 2017-09-01  18170.14
23 2017-10-01  33354.57
24 2017-11-01  36599.34
25 2017-12-01  27953.63
26 2018-01-01  46666.76
27 2018-02-01  27935.66
28 2018-03-01  17614.57
29 2018-04-01  30896.29
30 2018-05-01  23183.76
31 2018-06-01  19088.63
32 2018-07-01  29881.01
33 2018-08-01  40426.80
34 2018-09-01  14202.02
35 2018-10-01  44273.37
36 2018-11-01  34642.26
37 2018-12-01  33726.92
38 2019-01-01  27437.56
39 2019-02-01  25134.54
40 2019-03-01    612.76
probabilidade_zeros :0.0

         data     valor
0  2015-11-01    844.20
1  2015-12-01   3997.20
2  2016-01-01   9653.08
3  2016-02-01  11742.23
4  2016-03-01   8659.20
5  2016-04-01   6635.50
6  2016-05-01   7948.40
7  2016-06-01  10424.50
8  2016-07-01  10551.65
9  2016-08-01   8431.60
10 2016-09-01  11330.75
11 2016-10-01   7322.40
12 2016-11-01   8684.86
13 2016-12-01   6894.28
14 2017-01-01  12897.15
15 2017-02-01   5520.70
16 2017-03-01  10905.60
17 2017-04-01   5220.19
18 2017-05-01  10212.20
19 2017-06-01   9453.32
20 2017-07-01  10944.85
21 2017-08-01  15971.21
22 2017-09-01   8464.49
23 2017-10-01  15071.75
24 2017-11-01  12645.98
25 2017-12-01  10380.47
26 2018-01-01  17741.21
27 2018-02-01  11391.48
28 2018-03-01  14186.22
29 2018-04-01  21673.91
30 2018-05-01  17054.74
31 2018-06-01  13888.69
32 2018-07-01  19607.03
33 2018-08-01  39074.73
34 2018-09-01  27218.98
35 2018-10-01  29873.86
36 2018-11-01  17417.34
37 2018-12-01  15482.23
38 2019-01-01  13315.15
39 2019-02-01  11529.50
40 2019-03-01  19852.23
periodo de elegibilidade : [datetime.date(2018, 10, 1), datetime.date(2018, 11, 1), datetime.date(2018, 12, 1), datetime.date(2019, 1, 1), datetime.date(2019, 2, 1), datetime.date(2019, 3, 1)]
         data     valor
0  2015-11-01    844.20
1  2015-12-01   3997.20
2  2016-01-01   9653.08
3  2016-02-01  11742.23
4  2016-03-01   8659.20
5  2016-04-01   6635.50
6  2016-05-01   7948.40
7  2016-06-01  10424.50
8  2016-07-01  10551.65
9  2016-08-01   8431.60
10 2016-09-01  11330.75
11 2016-10-01   7322.40
12 2016-11-01   8684.86
13 2016-12-01   6894.28
14 2017-01-01  12897.15
15 2017-02-01   5520.70
16 2017-03-01  10905.60
17 2017-04-01   5220.19
18 2017-05-01  10212.20
19 2017-06-01   9453.32
20 2017-07-01  10944.85
21 2017-08-01  15971.21
22 2017-09-01   8464.49
23 2017-10-01  15071.75
24 2017-11-01  12645.98
25 2017-12-01  10380.47
26 2018-01-01  17741.21
27 2018-02-01  11391.48
28 2018-03-01  14186.22
29 2018-04-01  21673.91
30 2018-05-01  17054.74
31 2018-06-01  13888.69
32 2018-07-01  19607.03
33 2018-08-01  39074.73
34 2018-09-01  27218.98
35 2018-10-01  29873.86
36 2018-11-01  17417.34
37 2018-12-01  15482.23
38 2019-01-01  13315.15
39 2019-02-01  11529.50
40 2019-03-01  19852.23
probabilidade_zeros :0.0
score : 696.8303030303031
         data     valor
0  2017-12-01  14614.17
1  2018-01-01  18395.92
2  2018-02-01  12389.14
3  2018-03-01  20002.06
4  2018-04-01  18367.14
5  2018-05-01  36558.03
6  2018-06-01  13344.22
7  2018-07-01  56005.81
8  2018-08-01  35772.36
9  2018-09-01  28237.27
10 2018-10-01  37136.66
11 2018-11-01  42344.08
12 2018-12-01  23754.11
13 2019-01-01  67917.47
14 2019-02-01  24023.26
15 2019-03-01  41628.27
periodo de elegibilidade : [datetime.date(2018, 10, 1), datetime.date(2018, 11, 1), datetime.date(2018, 12, 1), datetime.date(2019, 1, 1), datetime.date(2019, 2, 1), datetime.date(2019, 3, 1)]
         data     valor
0  2017-12-01  14614.17
1  2018-01-01  18395.92
2  2018-02-01  12389.14
3  2018-03-01  20002.06
4  2018-04-01  18367.14
5  2018-05-01  36558.03
6  2018-06-01  13344.22
7  2018-07-01  56005.81
8  2018-08-01  35772.36
9  2018-09-01  28237.27
10 2018-10-01  37136.66
11 2018-11-01  42344.08
12 2018-12-01  23754.11
13 2019-01-01  67917.47
14 2019-02-01  24023.26
15 2019-03-01  41628.27
probabilidade_zeros :0.0
score : 702.6363636363636
        data     valor
0 2018-06-01  37152.21
1 2018-07-01  17285.87
2 2018-08-01  12315.82
3 2018-09-01  35792.77
4 2018-10-01  43885.41
5 2018-11-01  31498.13
6 2018-12-01  36485.08
7 2019-01-01  43650.82
8 2019-02-01  37426.33
9 2019-03-01  27372.90
periodo de elegibilidade : [datetime.date(2018, 10, 1), datetime.date(2018, 11, 1), datetime.date(2018, 12, 1), datetime.date(2019, 1, 1), datetime.date(2019, 2, 1), datetime.date(2019, 3, 1)]
        data     valor
0 2018-06-01  37152.21
1 2018-07-01  17285.87
2 2018-08-01  12315.82
3 2018-09-01  35792.77
4 2018-10-01  43885.41
5 2018-11-01  31498.13
6 2018-12-01  36485.08
7 2019-01-01  43650.82
8 2019-02-01  37426.33
9 2019-03-01  27372.90
probabilidade_zeros :0.0
score : 697.7242424242422
         data     valor
0  2015-11-01   1248.75
1  2015-12-01   6088.65
2  2016-01-01  22889.61
3  2016-02-01  22798.67
4  2016-03-01  40575.15
5  2016-04-01  30139.87
6  2016-05-01  23395.27
7  2016-06-01  30312.86
8  2016-07-01  32405.56
9  2016-08-01  36507.28
10 2016-09-01  19949.05
11 2016-10-01  34126.58
12 2016-11-01  16694.85
13 2016-12-01  35862.24
14 2017-01-01  26574.34
15 2017-02-01  24762.54
16 2017-03-01  15537.44
17 2017-04-01  16973.35
18 2017-05-01  30197.33
19 2017-06-01  18146.01
20 2017-07-01  31027.15
21 2017-08-01  24943.51
22 2017-09-01  16348.64
23 2017-10-01  16303.92
24 2017-11-01  22245.76
25 2017-12-01  31782.38
26 2018-01-01  33734.80
27 2018-02-01  14393.03
28 2018-03-01  25594.57
29 2018-04-01  36509.04
30 2018-05-01  34638.09
31 2018-06-01  27359.30
32 2018-07-01  27890.68
33 2018-08-01  51471.84
34 2018-09-01  18721.24
35 2018-10-01  58247.36
36 2018-11-01  64833.56
37 2018-12-01  42759.88
38 2019-01-01  39627.68
39 2019-02-01  45399.76
40 2019-03-01    720.00
periodo de elegibilidade : [datetime.date(2018, 10, 1), datetime.date(2018, 11, 1), datetime.date(2018, 12, 1), datetime.date(2019, 1, 1), datetime.date(2019, 2, 1), datetime.date(2019, 3, 1)]
         data     valor
0  2015-11-01   1248.75
1  2015-12-01   6088.65
2  2016-01-01  22889.61
3  2016-02-01  22798.67
4  2016-03-01  40575.15
5  2016-04-01  30139.87
6  2016-05-01  23395.27
7  2016-06-01  30312.86
8  2016-07-01  32405.56
9  2016-08-01  36507.28
10 2016-09-01  19949.05
11 2016-10-01  34126.58
12 2016-11-01  16694.85
13 2016-12-01  35862.24
14 2017-01-01  26574.34
15 2017-02-01  24762.54
16 2017-03-01  15537.44
17 2017-04-01  16973.35
18 2017-05-01  30197.33
19 2017-06-01  18146.01
20 2017-07-01  31027.15
21 2017-08-01  24943.51
22 2017-09-01  16348.64
23 2017-10-01  16303.92
24 2017-11-01  22245.76
25 2017-12-01  31782.38
26 2018-01-01  33734.80
27 2018-02-01  14393.03
28 2018-03-01  25594.57
29 2018-04-01  36509.04
30 2018-05-01  34638.09
31 2018-06-01  27359.30
32 2018-07-01  27890.68
33 2018-08-01  51471.84
34 2018-09-01  18721.24
35 2018-10-01  58247.36
36 2018-11-01  64833.56
37 2018-12-01  42759.88
38 2019-01-01  39627.68
39 2019-02-01  45399.76
40 2019-03-01    720.00
probabilidade_zeros :0.0
        data     valor
0 2018-09-01  16576.22
1 2018-10-01  14315.51
2 2018-11-01  12299.20
3 2018-12-01   4200.96
4 2019-01-01   3555.03
5 2019-02-01  17437.28
6 2019-03-01   4438.93
periodo de elegibilidade : [datetime.date(2018, 10, 1), datetime.date(2018, 11, 1), datetime.date(2018, 12, 1), datetime.date(2019, 1, 1), datetime.date(2019, 2, 1), datetime.date(2019, 3, 1)]
        data     valor
0 2018-09-01  16576.22
1 2018-10-01  14315.51
2 2018-11-01  12299.20
3 2018-12-01   4200.96
4 2019-01-01   3555.03
5 2019-02-01  17437.28
6 2019-03-01   4438.93
probabilidade_zeros :0.0
score : 313.037037037037
         data     valor
0  2017-12-01   2732.16
1  2018-01-01      0.00
2  2018-02-01    526.24
3  2018-03-01  10773.36
4  2018-04-01   5349.18
5  2018-05-01  15349.29
6  2018-06-01    719.06
7  2018-07-01   8693.54
8  2018-08-01  16377.10
9  2018-09-01  24601.16
10 2018-10-01   3154.46
11 2018-11-01  11193.38
12 2018-12-01   4164.02
13 2019-01-01   6664.31
14 2019-02-01  69764.12
15 2019-03-01  59202.38
periodo de elegibilidade : [datetime.date(2018, 10, 1), datetime.date(2018, 11, 1), datetime.date(2018, 12, 1), datetime.date(2019, 1, 1), datetime.date(2019, 2, 1), datetime.date(2019, 3, 1)]
         data     valor
0  2017-12-01   2732.16
1  2018-01-01      0.00
2  2018-02-01    526.24
3  2018-03-01  10773.36
4  2018-04-01   5349.18
5  2018-05-01  15349.29
6  2018-06-01    719.06
7  2018-07-01   8693.54
8  2018-08-01  16377.10
9  2018-09-01  24601.16
10 2018-10-01   3154.46
11 2018-11-01  11193.38
12 2018-12-01   4164.02
13 2019-01-01   6664.31
14 2019-02-01  69764.12
15 2019-03-01  59202.38
probabilidade_zeros :0.08333333333333333
score : 823.6666666666666
         data     valor
0  2018-01-01   3833.34
1  2018-02-01   5632.60
2  2018-03-01     50.69
3  2018-04-01   7764.26
4  2018-05-01   9847.11
5  2018-06-01  13998.47
6  2018-07-01  20681.25
7  2018-08-01  12891.06
8  2018-09-01   7070.01
9  2018-10-01  18278.97
10 2018-11-01  15199.84
11 2018-12-01  10565.70
12 2019-01-01   8067.48
13 2019-02-01  18459.13
14 2019-03-01   4667.46
periodo de elegibilidade : [datetime.date(2018, 10, 1), datetime.date(2018, 11, 1), datetime.date(2018, 12, 1), datetime.date(2019, 1, 1), datetime.date(2019, 2, 1), datetime.date(2019, 3, 1)]
         data     valor
0  2018-01-01   3833.34
1  2018-02-01   5632.60
2  2018-03-01     50.69
3  2018-04-01   7764.26
4  2018-05-01   9847.11
5  2018-06-01  13998.47
6  2018-07-01  20681.25
7  2018-08-01  12891.06
8  2018-09-01   7070.01
9  2018-10-01  18278.97
10 2018-11-01  15199.84
11 2018-12-01  10565.70
12 2019-01-01   8067.48
13 2019-02-01  18459.13
14 2019-03-01   4667.46
probabilidade_zeros :0.0

score : 647.0969696969697
         data     valor
0  2018-04-01   8546.31
1  2018-05-01  64080.02
2  2018-06-01  32747.61
3  2018-07-01  59934.85
4  2018-08-01  76586.89
5  2018-09-01  78844.70
6  2018-10-01  75329.85
7  2018-11-01  85357.77
8  2018-12-01  58662.35
9  2019-01-01  78078.75
10 2019-02-01  73100.55
11 2019-03-01  78171.31
periodo de elegibilidade : [datetime.date(2018, 10, 1), datetime.date(2018, 11, 1), datetime.date(2018, 12, 1), datetime.date(2019, 1, 1), datetime.date(2019, 2, 1), datetime.date(2019, 3, 1)]
         data     valor
0  2018-04-01   8546.31
1  2018-05-01  64080.02
2  2018-06-01  32747.61
3  2018-07-01  59934.85
4  2018-08-01  76586.89
5  2018-09-01  78844.70
6  2018-10-01  75329.85
7  2018-11-01  85357.77
8  2018-12-01  58662.35
9  2019-01-01  78078.75
10 2019-02-01  73100.55
11 2019-03-01  78171.31
probabilidade_zeros :0.0
score : 724.2931129476583
         data     valor
0  2018-02-01   3342.96
1  2018-03-01  22262.20
2  2018-04-01  22363.85
3  2018-05-01  11393.02
4  2018-06-01  12507.08
5  2018-07-01  11803.06
6  2018-08-01  14672.47
7  2018-09-01  11286.56
8  2018-10-01  16338.08
9  2018-11-01   2774.25
10 2018-12-01  10647.70
11 2019-01-01  10202.85
12 2019-02-01   4628.33
13 2019-03-01  12200.85
periodo de elegibilidade : [datetime.date(2018, 10, 1), datetime.date(2018, 11, 1), datetime.date(2018, 12, 1), datetime.date(2019, 1, 1), datetime.date(2019, 2, 1), datetime.date(2019, 3, 1)]
         data     valor
0  2018-02-01   3342.96
1  2018-03-01  22262.20
2  2018-04-01  22363.85
3  2018-05-01  11393.02
4  2018-06-01  12507.08
5  2018-07-01  11803.06
6  2018-08-01  14672.47
7  2018-09-01  11286.56
8  2018-10-01  16338.08
9  2018-11-01   2774.25
10 2018-12-01  10647.70
11 2019-01-01  10202.85
12 2019-02-01   4628.33
13 2019-03-01  12200.85
probabilidade_zeros :0.0
score : 694.5454545454546
         data     valor
0  2016-10-01   1634.36
1  2016-11-01   1128.62
2  2016-12-01      0.00
3  2017-01-01   1211.14
4  2017-02-01    377.78
5  2017-03-01   2023.08
6  2017-04-01   1733.86
7  2017-05-01    669.84
8  2017-06-01   2586.08
9  2017-07-01   1418.38
10 2017-08-01   1984.42
11 2017-09-01    511.38
12 2017-10-01   4061.10
13 2017-11-01    837.56
14 2017-12-01   5415.42
15 2018-01-01   3082.38
16 2018-02-01   1555.34
17 2018-03-01    521.98
18 2018-04-01    149.56
19 2018-05-01   1286.70
20 2018-06-01   4103.10
21 2018-07-01   6395.46
22 2018-08-01   7374.01
23 2018-09-01    254.75
24 2018-10-01   1936.10
25 2018-11-01  12555.21
26 2018-12-01   6399.81
27 2019-01-01  11075.61
28 2019-02-01   4932.35
29 2019-03-01   7950.58
periodo de elegibilidade : [datetime.date(2018, 10, 1), datetime.date(2018, 11, 1), datetime.date(2018, 12, 1), datetime.date(2019, 1, 1), datetime.date(2019, 2, 1), datetime.date(2019, 3, 1)]
         data     valor
0  2016-10-01   1634.36
1  2016-11-01   1128.62
2  2016-12-01      0.00
3  2017-01-01   1211.14
4  2017-02-01    377.78
5  2017-03-01   2023.08
6  2017-04-01   1733.86
7  2017-05-01    669.84
8  2017-06-01   2586.08
9  2017-07-01   1418.38
10 2017-08-01   1984.42
11 2017-09-01    511.38
12 2017-10-01   4061.10
13 2017-11-01    837.56
14 2017-12-01   5415.42
15 2018-01-01   3082.38
16 2018-02-01   1555.34
17 2018-03-01    521.98
18 2018-04-01    149.56
19 2018-05-01   1286.70
20 2018-06-01   4103.10
21 2018-07-01   6395.46
22 2018-08-01   7374.01
23 2018-09-01    254.75
24 2018-10-01   1936.10
25 2018-11-01  12555.21
26 2018-12-01   6399.81
27 2019-01-01  11075.61
28 2019-02-01   4932.35
29 2019-03-01   7950.58
probabilidade_zeros :0.16666666666666666
score : 683.0848484848484
         data     valor
0  2017-11-01   6597.70
1  2017-12-01  19786.66
2  2018-01-01  29195.18
3  2018-02-01  14485.82
4  2018-03-01   6836.60
5  2018-04-01  35851.56
6  2018-05-01  51034.54
7  2018-06-01  23358.54
8  2018-07-01  33435.05
9  2018-08-01  14163.82
10 2018-09-01  29860.22
11 2018-10-01  22787.45
12 2018-11-01  36342.54
13 2018-12-01  17837.44
14 2019-01-01  69316.76
15 2019-02-01  71971.00
16 2019-03-01  46730.66
periodo de elegibilidade : [datetime.date(2018, 10, 1), datetime.date(2018, 11, 1), datetime.date(2018, 12, 1), datetime.date(2019, 1, 1), datetime.date(2019, 2, 1), datetime.date(2019, 3, 1)]
         data     valor
0  2017-11-01   6597.70
1  2017-12-01  19786.66
2  2018-01-01  29195.18
3  2018-02-01  14485.82
4  2018-03-01   6836.60
5  2018-04-01  35851.56
6  2018-05-01  51034.54
7  2018-06-01  23358.54
8  2018-07-01  33435.05
9  2018-08-01  14163.82
10 2018-09-01  29860.22
11 2018-10-01  22787.45
12 2018-11-01  36342.54
13 2018-12-01  17837.44
14 2019-01-01  69316.76
15 2019-02-01  71971.00
16 2019-03-01  46730.66
probabilidade_zeros :0.0
score : 697.1841491841492
        data     valor
0 2018-08-01  13459.78
1 2018-09-01  39182.41
2 2018-10-01  41633.01
3 2018-11-01  29148.23
4 2018-12-01  48361.05
5 2019-01-01  33781.36
6 2019-02-01  22607.30
7 2019-03-01  36273.66
periodo de elegibilidade : [datetime.date(2018, 10, 1), datetime.date(2018, 11, 1), datetime.date(2018, 12, 1), datetime.date(2019, 1, 1), datetime.date(2019, 2, 1), datetime.date(2019, 3, 1)]
        data     valor
0 2018-08-01  13459.78
1 2018-09-01  39182.41
2 2018-10-01  41633.01
3 2018-11-01  29148.23
4 2018-12-01  48361.05
5 2019-01-01  33781.36
6 2019-02-01  22607.30
7 2019-03-01  36273.66
probabilidade_zeros :0.0
score : 720.9545454545455
         data     valor
0  2018-04-01   1798.35
1  2018-05-01   4561.25
2  2018-06-01   2920.82
3  2018-07-01   6497.15
4  2018-08-01   6786.90
5  2018-09-01  11475.12
6  2018-10-01  17272.85
7  2018-11-01   9869.60
8  2018-12-01   5224.30
9  2019-01-01  18981.52
10 2019-02-01    176.59
11 2019-03-01  11721.12
periodo de elegibilidade : [datetime.date(2018, 10, 1), datetime.date(2018, 11, 1), datetime.date(2018, 12, 1), datetime.date(2019, 1, 1), datetime.date(2019, 2, 1), datetime.date(2019, 3, 1)]
         data     valor
0  2018-04-01   1798.35
1  2018-05-01   4561.25
2  2018-06-01   2920.82
3  2018-07-01   6497.15
4  2018-08-01   6786.90
5  2018-09-01  11475.12
6  2018-10-01  17272.85
7  2018-11-01   9869.60
8  2018-12-01   5224.30
9  2019-01-01  18981.52
10 2019-02-01    176.59
11 2019-03-01  11721.12
probabilidade_zeros :0.0
score : 682.7030303030302
         data     valor
0  2017-12-01  34018.57
1  2018-01-01   9736.08
2  2018-02-01  14723.62
3  2018-03-01   5066.14
4  2018-04-01  28858.07
5  2018-05-01  13083.71
6  2018-06-01   9362.87
7  2018-07-01  22827.33
8  2018-08-01  27205.48
9  2018-09-01  36679.90
10 2018-10-01  22580.73
11 2018-11-01  26969.46
12 2018-12-01  64147.26
13 2019-01-01  19857.50
14 2019-02-01  16896.12
15 2019-03-01  15542.61
periodo de elegibilidade : [datetime.date(2018, 10, 1), datetime.date(2018, 11, 1), datetime.date(2018, 12, 1), datetime.date(2019, 1, 1), datetime.date(2019, 2, 1), datetime.date(2019, 3, 1)]
         data     valor
0  2017-12-01  34018.57
1  2018-01-01   9736.08
2  2018-02-01  14723.62
3  2018-03-01   5066.14
4  2018-04-01  28858.07
5  2018-05-01  13083.71
6  2018-06-01   9362.87
7  2018-07-01  22827.33
8  2018-08-01  27205.48
9  2018-09-01  36679.90
10 2018-10-01  22580.73
11 2018-11-01  26969.46
12 2018-12-01  64147.26
13 2019-01-01  19857.50
14 2019-02-01  16896.12
15 2019-03-01  15542.61
probabilidade_zeros :0.0
score : 635.2545454545453
         data     valor
0  2017-05-01  12094.64
1  2017-06-01   3596.59
2  2017-07-01  16109.90
3  2017-08-01  10276.49
4  2017-09-01  12857.57
5  2017-10-01  16301.62
6  2017-11-01   2939.48
7  2017-12-01  17260.09
8  2018-01-01   7837.25
9  2018-02-01  17204.38
10 2018-03-01  20008.07
11 2018-04-01   5936.04
12 2018-05-01   6008.63
13 2018-06-01  24736.96
14 2018-07-01  19888.46
15 2018-08-01   6717.74
16 2018-09-01  12636.14
17 2018-10-01  13536.29
18 2018-11-01   5266.36
19 2018-12-01   6685.76
20 2019-01-01   6992.71
21 2019-02-01  12730.79
22 2019-03-01  13716.32
periodo de elegibilidade : [datetime.date(2018, 10, 1), datetime.date(2018, 11, 1), datetime.date(2018, 12, 1), datetime.date(2019, 1, 1), datetime.date(2019, 2, 1), datetime.date(2019, 3, 1)]
         data     valor
0  2017-05-01  12094.64
1  2017-06-01   3596.59
2  2017-07-01  16109.90
3  2017-08-01  10276.49
4  2017-09-01  12857.57
5  2017-10-01  16301.62
6  2017-11-01   2939.48
7  2017-12-01  17260.09
8  2018-01-01   7837.25
9  2018-02-01  17204.38
10 2018-03-01  20008.07
11 2018-04-01   5936.04
12 2018-05-01   6008.63
13 2018-06-01  24736.96
14 2018-07-01  19888.46
15 2018-08-01   6717.74
16 2018-09-01  12636.14
17 2018-10-01  13536.29
18 2018-11-01   5266.36
19 2018-12-01   6685.76
20 2019-01-01   6992.71
21 2019-02-01  12730.79
22 2019-03-01  13716.32
probabilidade_zeros :0.0

         data     valor
0  2016-08-01   1959.80
1  2016-09-01   5315.90
2  2016-10-01   4994.89
3  2016-11-01  17293.62
4  2016-12-01   4365.48
5  2017-01-01   4545.48
6  2017-02-01  10625.89
7  2017-03-01   4247.08
8  2017-04-01   3685.56
9  2017-05-01   6347.01
10 2017-06-01  10914.66
11 2017-07-01   6978.08
12 2017-08-01   8239.84
13 2017-09-01   8486.20
14 2017-10-01   8039.36
15 2017-11-01   8067.94
16 2017-12-01   4783.56
17 2018-01-01    543.09
18 2018-02-01   7917.96
19 2018-03-01   8022.81
20 2018-04-01  11041.44
21 2018-05-01   7124.21
22 2018-06-01   3682.69
23 2018-07-01   5195.78
24 2018-08-01   9817.33
25 2018-09-01   8702.24
26 2018-10-01   5411.74
27 2018-11-01   4262.80
28 2018-12-01   2287.50
29 2019-01-01   7174.74
30 2019-02-01    722.98
31 2019-03-01   3681.91
periodo de elegibilidade : [datetime.date(2018, 10, 1), datetime.date(2018, 11, 1), datetime.date(2018, 12, 1), datetime.date(2019, 1, 1), datetime.date(2019, 2, 1), datetime.date(2019, 3, 1)]
         data     valor
0  2016-08-01   1959.80
1  2016-09-01   5315.90
2  2016-10-01   4994.89
3  2016-11-01  17293.62
4  2016-12-01   4365.48
5  2017-01-01   4545.48
6  2017-02-01  10625.89
7  2017-03-01   4247.08
8  2017-04-01   3685.56
9  2017-05-01   6347.01
10 2017-06-01  10914.66
11 2017-07-01   6978.08
12 2017-08-01   8239.84
13 2017-09-01   8486.20
14 2017-10-01   8039.36
15 2017-11-01   8067.94
16 2017-12-01   4783.56
17 2018-01-01    543.09
18 2018-02-01   7917.96
19 2018-03-01   8022.81
20 2018-04-01  11041.44
21 2018-05-01   7124.21
22 2018-06-01   3682.69
23 2018-07-01   5195.78
24 2018-08-01   9817.33
25 2018-09-01   8702.24
26 2018-10-01   5411.74
27 2018-11-01   4262.80
28 2018-12-01   2287.50
29 2019-01-01   7174.74
30 2019-02-01    722.98
31 2019-03-01   3681.91
probabilidade_zeros :0.0
         data    valor
0  2018-01-01  2647.50
1  2018-02-01  3433.49
2  2018-03-01  4841.84
3  2018-04-01  4346.87
4  2018-05-01  4716.50
5  2018-06-01  5537.81
6  2018-07-01  3222.49
7  2018-08-01  4045.89
8  2018-09-01  5023.96
9  2018-10-01  4422.09
10 2018-11-01  3521.33
11 2018-12-01  4824.53
12 2019-01-01  1966.00
13 2019-02-01  2261.54
14 2019-03-01  1702.00
periodo de elegibilidade : [datetime.date(2018, 10, 1), datetime.date(2018, 11, 1), datetime.date(2018, 12, 1), datetime.date(2019, 1, 1), datetime.date(2019, 2, 1), datetime.date(2019, 3, 1)]
         data    valor
0  2018-01-01  2647.50
1  2018-02-01  3433.49
2  2018-03-01  4841.84
3  2018-04-01  4346.87
4  2018-05-01  4716.50
5  2018-06-01  5537.81
6  2018-07-01  3222.49
7  2018-08-01  4045.89
8  2018-09-01  5023.96
9  2018-10-01  4422.09
10 2018-11-01  3521.33
11 2018-12-01  4824.53
12 2019-01-01  1966.00
13 2019-02-01  2261.54
14 2019-03-01  1702.00
probabilidade_zeros :0.0
score : 668.4757575757577
         data     valor
0  2018-01-01      1.04
1  2018-02-01   4105.67
2  2018-03-01  28211.23
3  2018-04-01  16966.32
4  2018-05-01  11864.34
5  2018-06-01   8896.45
6  2018-07-01   2283.02
7  2018-08-01   5842.01
8  2018-09-01  15797.36
9  2018-10-01  20676.24
10 2018-11-01  10148.17
11 2018-12-01   1018.60
12 2019-01-01   7672.11
13 2019-02-01   4386.93
14 2019-03-01   8885.24
periodo de elegibilidade : [datetime.date(2018, 10, 1), datetime.date(2018, 11, 1), datetime.date(2018, 12, 1), datetime.date(2019, 1, 1), datetime.date(2019, 2, 1), datetime.date(2019, 3, 1)]
         data     valor
0  2018-01-01      1.04
1  2018-02-01   4105.67
2  2018-03-01  28211.23
3  2018-04-01  16966.32
4  2018-05-01  11864.34
5  2018-06-01   8896.45
6  2018-07-01   2283.02
7  2018-08-01   5842.01
8  2018-09-01  15797.36
9  2018-10-01  20676.24
10 2018-11-01  10148.17
11 2018-12-01   1018.60
12 2019-01-01   7672.11
13 2019-02-01   4386.93
14 2019-03-01   8885.24
probabilidade_zeros :0.0
         data     valor
0  2017-08-01    322.84
1  2017-09-01      0.00
2  2017-10-01    545.52
3  2017-11-01   2070.08
4  2017-12-01      0.00
5  2018-01-01      0.00
6  2018-02-01   1301.46
7  2018-03-01   2445.24
8  2018-04-01   3466.88
9  2018-05-01   2937.52
10 2018-06-01  15128.94
11 2018-07-01   8731.44
12 2018-08-01  10993.46
13 2018-09-01   9075.10
14 2018-10-01  10530.12
15 2018-11-01  18197.62
16 2018-12-01  14317.70
17 2019-01-01  17580.36
18 2019-02-01  17626.32
19 2019-03-01  16126.80
periodo de elegibilidade : [datetime.date(2018, 10, 1), datetime.date(2018, 11, 1), datetime.date(2018, 12, 1), datetime.date(2019, 1, 1), datetime.date(2019, 2, 1), datetime.date(2019, 3, 1)]
         data     valor
0  2017-08-01    322.84
1  2017-09-01      0.00
2  2017-10-01    545.52
3  2017-11-01   2070.08
4  2017-12-01      0.00
5  2018-01-01      0.00
6  2018-02-01   1301.46
7  2018-03-01   2445.24
8  2018-04-01   3466.88
9  2018-05-01   2937.52
10 2018-06-01  15128.94
11 2018-07-01   8731.44
12 2018-08-01  10993.46
13 2018-09-01   9075.10
14 2018-10-01  10530.12
15 2018-11-01  18197.62
16 2018-12-01  14317.70
17 2019-01-01  17580.36
18 2019-02-01  17626.32
19 2019-03-01  16126.80
probabilidade_zeros :0.0
score : 722.5515151515152
         data     valor
0  2017-05-01   5757.86
1  2017-06-01   4899.57
2  2017-07-01      0.00
3  2017-08-01  25117.48
4  2017-09-01  28959.52
5  2017-10-01   1360.88
6  2017-11-01  20470.64
7  2017-12-01  18277.11
8  2018-01-01  17784.16
9  2018-02-01  18000.61
10 2018-03-01   6371.30
11 2018-04-01  52262.93
12 2018-05-01  35676.30
13 2018-06-01  51624.88
14 2018-07-01  64725.36
15 2018-08-01  33649.74
16 2018-09-01  44406.94
17 2018-10-01  36764.45
18 2018-11-01  65337.84
19 2018-12-01  52991.20
20 2019-01-01  29483.49
21 2019-02-01  27060.37
22 2019-03-01  27929.19
periodo de elegibilidade : [datetime.date(2018, 10, 1), datetime.date(2018, 11, 1), datetime.date(2018, 12, 1), datetime.date(2019, 1, 1), datetime.date(2019, 2, 1), datetime.date(2019, 3, 1)]
         data     valor
0  2017-05-01   5757.86
1  2017-06-01   4899.57
2  2017-07-01      0.00
3  2017-08-01  25117.48
4  2017-09-01  28959.52
5  2017-10-01   1360.88
6  2017-11-01  20470.64
7  2017-12-01  18277.11
8  2018-01-01  17784.16
9  2018-02-01  18000.61
10 2018-03-01   6371.30
11 2018-04-01  52262.93
12 2018-05-01  35676.30
13 2018-06-01  51624.88
14 2018-07-01  64725.36
15 2018-08-01  33649.74
16 2018-09-01  44406.94
17 2018-10-01  36764.45
18 2018-11-01  65337.84
19 2018-12-01  52991.20
20 2019-01-01  29483.49
21 2019-02-01  27060.37
22 2019-03-01  27929.19
probabilidade_zeros :0.0
score : 686.6090909090909
         data    valor
0  2017-09-01  1992.20
1  2017-10-01  4050.47
2  2017-11-01  4134.66
3  2017-12-01  5514.89
4  2018-01-01  3443.77
5  2018-02-01  5693.10
6  2018-03-01  7209.47
7  2018-04-01  8245.32
8  2018-05-01  5337.49
9  2018-06-01  7166.35
10 2018-07-01  5954.86
11 2018-08-01  5940.92
12 2018-09-01  6848.87
13 2018-10-01  6915.99
14 2018-11-01  5664.48
15 2018-12-01  7555.67
16 2019-01-01  3885.87
17 2019-02-01  4771.77
18 2019-03-01  4965.99
periodo de elegibilidade : [datetime.date(2018, 10, 1), datetime.date(2018, 11, 1), datetime.date(2018, 12, 1), datetime.date(2019, 1, 1), datetime.date(2019, 2, 1), datetime.date(2019, 3, 1)]
         data    valor
0  2017-09-01  1992.20
1  2017-10-01  4050.47
2  2017-11-01  4134.66
3  2017-12-01  5514.89
4  2018-01-01  3443.77
5  2018-02-01  5693.10
6  2018-03-01  7209.47
7  2018-04-01  8245.32
8  2018-05-01  5337.49
9  2018-06-01  7166.35
10 2018-07-01  5954.86
11 2018-08-01  5940.92
12 2018-09-01  6848.87
13 2018-10-01  6915.99
14 2018-11-01  5664.48
15 2018-12-01  7555.67
16 2019-01-01  3885.87
17 2019-02-01  4771.77
18 2019-03-01  4965.99
probabilidade_zeros :0.0
score : 702.7242424242422
         data     valor
0  2018-04-01   5859.54
1  2018-05-01  15187.20
2  2018-06-01  16334.58
3  2018-07-01  12332.06
4  2018-08-01  10515.40
5  2018-09-01  14388.60
6  2018-10-01  21917.01
7  2018-11-01  19062.98
8  2018-12-01  10933.16
9  2019-01-01  10172.22
10 2019-02-01   9385.14
11 2019-03-01  18963.18
periodo de elegibilidade : [datetime.date(2018, 10, 1), datetime.date(2018, 11, 1), datetime.date(2018, 12, 1), datetime.date(2019, 1, 1), datetime.date(2019, 2, 1), datetime.date(2019, 3, 1)]
         data     valor
0  2018-04-01   5859.54
1  2018-05-01  15187.20
2  2018-06-01  16334.58
3  2018-07-01  12332.06
4  2018-08-01  10515.40
5  2018-09-01  14388.60
6  2018-10-01  21917.01
7  2018-11-01  19062.98
8  2018-12-01  10933.16
9  2019-01-01  10172.22
10 2019-02-01   9385.14
11 2019-03-01  18963.18
probabilidade_zeros :0.0

score : 748.2787878787877
         data     valor
0  2018-01-01   1923.06
1  2018-02-01   3303.82
2  2018-03-01   8858.97
3  2018-04-01   5069.58
4  2018-05-01  14098.12
5  2018-06-01   2277.28
6  2018-07-01   3429.93
7  2018-08-01  13970.98
8  2018-09-01   5621.27
9  2018-10-01   9529.76
10 2018-11-01   2832.46
11 2018-12-01  13780.99
12 2019-01-01   6483.01
13 2019-02-01   5967.95
14 2019-03-01   6064.57
periodo de elegibilidade : [datetime.date(2018, 10, 1), datetime.date(2018, 11, 1), datetime.date(2018, 12, 1), datetime.date(2019, 1, 1), datetime.date(2019, 2, 1), datetime.date(2019, 3, 1)]
         data     valor
0  2018-01-01   1923.06
1  2018-02-01   3303.82
2  2018-03-01   8858.97
3  2018-04-01   5069.58
4  2018-05-01  14098.12
5  2018-06-01   2277.28
6  2018-07-01   3429.93
7  2018-08-01  13970.98
8  2018-09-01   5621.27
9  2018-10-01   9529.76
10 2018-11-01   2832.46
11 2018-12-01  13780.99
12 2019-01-01   6483.01
13 2019-02-01   5967.95
14 2019-03-01   6064.57
probabilidade_zeros :0.0
score : 646.7272727272726
         data     valor
0  2018-04-01   3386.55
1  2018-05-01  12049.49
2  2018-06-01  11926.07
3  2018-07-01   2104.89
4  2018-08-01   1083.73
5  2018-09-01   1505.77
6  2018-10-01   5229.05
7  2018-11-01   6053.62
8  2018-12-01   2920.50
9  2019-01-01   2789.18
10 2019-02-01   4573.05
11 2019-03-01   7017.09
periodo de elegibilidade : [datetime.date(2018, 10, 1), datetime.date(2018, 11, 1), datetime.date(2018, 12, 1), datetime.date(2019, 1, 1), datetime.date(2019, 2, 1), datetime.date(2019, 3, 1)]
         data     valor
0  2018-04-01   3386.55
1  2018-05-01  12049.49
2  2018-06-01  11926.07
3  2018-07-01   2104.89
4  2018-08-01   1083.73
5  2018-09-01   1505.77
6  2018-10-01   5229.05
7  2018-11-01   6053.62
8  2018-12-01   2920.50
9  2019-01-01   2789.18
10 2019-02-01   4573.05
11 2019-03-01   7017.09
probabilidade_zeros :0.0
score : 673.2909090909092
        data     valor
0 2018-07-01   1355.08
1 2018-08-01   8372.05
2 2018-09-01   6195.23
3 2018-10-01  15947.51
4 2018-11-01  17532.91
5 2018-12-01  13982.27
6 2019-01-01  81687.73
7 2019-02-01  37656.75
8 2019-03-01  72361.67
periodo de elegibilidade : [datetime.date(2018, 10, 1), datetime.date(2018, 11, 1), datetime.date(2018, 12, 1), datetime.date(2019, 1, 1), datetime.date(2019, 2, 1), datetime.date(2019, 3, 1)]
        data     valor
0 2018-07-01   1355.08
1 2018-08-01   8372.05
2 2018-09-01   6195.23
3 2018-10-01  15947.51
4 2018-11-01  17532.91
5 2018-12-01  13982.27
6 2019-01-01  81687.73
7 2019-02-01  37656.75
8 2019-03-01  72361.67
probabilidade_zeros :0.1111111111111111
score : 845.9212121212122
         data      valor
0  2017-08-01   34544.81
1  2017-09-01   37541.28
2  2017-10-01   45978.53
3  2017-11-01   17902.58
4  2017-12-01   16692.09
5  2018-01-01   97865.28
6  2018-02-01   60710.12
7  2018-03-01   30184.61
8  2018-04-01   34291.12
9  2018-05-01   81471.26
10 2018-06-01   18353.98
11 2018-07-01   46044.53
12 2018-08-01   30019.84
13 2018-09-01   40816.85
14 2018-10-01   80127.42
15 2018-11-01   65094.33
16 2018-12-01   19054.06
17 2019-01-01   18796.03
18 2019-02-01  139677.76
19 2019-03-01  187162.26
periodo de elegibilidade : [datetime.date(2018, 10, 1), datetime.date(2018, 11, 1), datetime.date(2018, 12, 1), datetime.date(2019, 1, 1), datetime.date(2019, 2, 1), datetime.date(2019, 3, 1)]
         data      valor
0  2017-08-01   34544.81
1  2017-09-01   37541.28
2  2017-10-01   45978.53
3  2017-11-01   17902.58
4  2017-12-01   16692.09
5  2018-01-01   97865.28
6  2018-02-01   60710.12
7  2018-03-01   30184.61
8  2018-04-01   34291.12
9  2018-05-01   81471.26
10 2018-06-01   18353.98
11 2018-07-01   46044.53
12 2018-08-01   30019.84
13 2018-09-01   40816.85
14 2018-10-01   80127.42
15 2018-11-01   65094.33
16 2018-12-01   19054.06
17 2019-01-01   18796.03
18 2019-02-01  139677.76
19 2019-03-01  187162.26
probabilidade_zeros :0.0
score : 862.3636363636364
         data     valor
0  2018-04-01  11359.27
1  2018-05-01  17750.01
2  2018-06-01  27600.51
3  2018-07-01  62332.23
4  2018-08-01  57624.91
5  2018-09-01  54259.19
6  2018-10-01  54856.40
7  2018-11-01  39492.71
8  2018-12-01  42599.14
9  2019-01-01  39917.51
10 2019-02-01  34913.28
11 2019-03-01  26990.53
periodo de elegibilidade : [datetime.date(2018, 10, 1), datetime.date(2018, 11, 1), datetime.date(2018, 12, 1), datetime.date(2019, 1, 1), datetime.date(2019, 2, 1), datetime.date(2019, 3, 1)]
         data     valor
0  2018-04-01  11359.27
1  2018-05-01  17750.01
2  2018-06-01  27600.51
3  2018-07-01  62332.23
4  2018-08-01  57624.91
5  2018-09-01  54259.19
6  2018-10-01  54856.40
7  2018-11-01  39492.71
8  2018-12-01  42599.14
9  2019-01-01  39917.51
10 2019-02-01  34913.28
11 2019-03-01  26990.53
probabilidade_zeros :0.0
score : 670.9757575757575
         data      valor
0  2017-11-01   11689.23
1  2017-12-01   98882.68
2  2018-01-01   90598.94
3  2018-02-01   75441.25
4  2018-03-01   72141.11
5  2018-04-01   65575.86
6  2018-05-01  107510.63
7  2018-06-01  118137.70
8  2018-07-01  130687.53
9  2018-08-01  132699.05
10 2018-09-01  134550.56
11 2018-10-01  143732.05
12 2018-11-01  147369.85
13 2018-12-01  147785.55
14 2019-01-01  129944.62
15 2019-02-01  118873.12
16 2019-03-01   96606.52
periodo de elegibilidade : [datetime.date(2018, 10, 1), datetime.date(2018, 11, 1), datetime.date(2018, 12, 1), datetime.date(2019, 1, 1), datetime.date(2019, 2, 1), datetime.date(2019, 3, 1)]
         data      valor
0  2017-11-01   11689.23
1  2017-12-01   98882.68
2  2018-01-01   90598.94
3  2018-02-01   75441.25
4  2018-03-01   72141.11
5  2018-04-01   65575.86
6  2018-05-01  107510.63
7  2018-06-01  118137.70
8  2018-07-01  130687.53
9  2018-08-01  132699.05
10 2018-09-01  134550.56
11 2018-10-01  143732.05
12 2018-11-01  147369.85
13 2018-12-01  147785.55
14 2019-01-01  129944.62
15 2019-02-01  118873.12
16 2019-03-01   96606.52
probabilidade_zeros :0.0
score : 700.7060606060605
         data      valor
0  2016-11-01   76463.93
1  2016-12-01   90024.38
2  2017-01-01   79791.08
3  2017-02-01   69427.33
4  2017-03-01  104353.97
5  2017-04-01   66954.00
6  2017-05-01   78764.37
7  2017-06-01   82671.32
8  2017-07-01   84327.96
9  2017-08-01   77849.67
10 2017-09-01  103699.03
11 2017-10-01  104489.25
12 2017-11-01  107507.33
13 2017-12-01  103340.80
14 2018-01-01   90079.82
15 2018-02-01   86618.81
16 2018-03-01   66581.65
17 2018-04-01   58461.83
18 2018-05-01   19927.64
19 2018-06-01   38925.37
20 2018-07-01   31739.36
21 2018-08-01   21446.21
22 2018-09-01   43169.32
23 2018-10-01   60166.29
24 2018-11-01   41476.28
25 2018-12-01   42558.08
26 2019-01-01   25662.37
27 2019-02-01   31537.83
28 2019-03-01   47005.37
periodo de elegibilidade : [datetime.date(2018, 10, 1), datetime.date(2018, 11, 1), datetime.date(2018, 12, 1), datetime.date(2019, 1, 1), datetime.date(2019, 2, 1), datetime.date(2019, 3, 1)]
         data      valor
0  2016-11-01   76463.93
1  2016-12-01   90024.38
2  2017-01-01   79791.08
3  2017-02-01   69427.33
4  2017-03-01  104353.97
5  2017-04-01   66954.00
6  2017-05-01   78764.37
7  2017-06-01   82671.32
8  2017-07-01   84327.96
9  2017-08-01   77849.67
10 2017-09-01  103699.03
11 2017-10-01  104489.25
12 2017-11-01  107507.33
13 2017-12-01  103340.80
14 2018-01-01   90079.82
15 2018-02-01   86618.81
16 2018-03-01   66581.65
17 2018-04-01   58461.83
18 2018-05-01   19927.64
19 2018-06-01   38925.37
20 2018-07-01   31739.36
21 2018-08-01   21446.21
22 2018-09-01   43169.32
23 2018-10-01   60166.29
24 2018-11-01   41476.28
25 2018-12-01   42558.08
26 2019-01-01   25662.37
27 2019-02-01   31537.83
28 2019-03-01   47005.37
probabilidade_zeros :0.0
score : 726.2931129476583
         data     valor
0  2018-04-01   4014.33
1  2018-05-01  20881.17
2  2018-06-01  14928.72
3  2018-07-01  15628.20
4  2018-08-01  20237.68
5  2018-09-01  41918.48
6  2018-10-01  35300.43
7  2018-11-01  16504.27
8  2018-12-01  25639.73
9  2019-01-01  27910.63
10 2019-02-01  36698.30
11 2019-03-01  78706.80
periodo de elegibilidade : [datetime.date(2018, 10, 1), datetime.date(2018, 11, 1), datetime.date(2018, 12, 1), datetime.date(2019, 1, 1), datetime.date(2019, 2, 1), datetime.date(2019, 3, 1)]
         data     valor
0  2018-04-01   4014.33
1  2018-05-01  20881.17
2  2018-06-01  14928.72
3  2018-07-01  15628.20
4  2018-08-01  20237.68
5  2018-09-01  41918.48
6  2018-10-01  35300.43
7  2018-11-01  16504.27
8  2018-12-01  25639.73
9  2019-01-01  27910.63
10 2019-02-01  36698.30
11 2019-03-01  78706.80
probabilidade_zeros :0.0

score : 870.1696969696969
         data     valor
0  2018-01-01  56783.17
1  2018-02-01  40139.14
2  2018-03-01  62998.60
3  2018-04-01  46897.28
4  2018-05-01  50921.63
5  2018-06-01  44471.97
6  2018-07-01  53562.87
7  2018-08-01  42211.03
8  2018-09-01  46789.68
9  2018-10-01  55153.20
10 2018-11-01  37707.07
11 2018-12-01  52355.14
12 2019-01-01  51870.02
13 2019-02-01  35295.42
14 2019-03-01  29337.25
periodo de elegibilidade : [datetime.date(2018, 10, 1), datetime.date(2018, 11, 1), datetime.date(2018, 12, 1), datetime.date(2019, 1, 1), datetime.date(2019, 2, 1), datetime.date(2019, 3, 1)]
         data     valor
0  2018-01-01  56783.17
1  2018-02-01  40139.14
2  2018-03-01  62998.60
3  2018-04-01  46897.28
4  2018-05-01  50921.63
5  2018-06-01  44471.97
6  2018-07-01  53562.87
7  2018-08-01  42211.03
8  2018-09-01  46789.68
9  2018-10-01  55153.20
10 2018-11-01  37707.07
11 2018-12-01  52355.14
12 2019-01-01  51870.02
13 2019-02-01  35295.42
14 2019-03-01  29337.25
probabilidade_zeros :0.0
score : 689.9424242424243
         data     valor
0  2018-04-01  37165.11
1  2018-05-01  45621.96
2  2018-06-01  49119.93
3  2018-07-01  40859.34
4  2018-08-01  56560.88
5  2018-09-01  49001.79
6  2018-10-01  53351.71
7  2018-11-01  47653.60
8  2018-12-01  51135.13
9  2019-01-01  24969.00
10 2019-02-01  60111.81
11 2019-03-01  43487.84
periodo de elegibilidade : [datetime.date(2018, 10, 1), datetime.date(2018, 11, 1), datetime.date(2018, 12, 1), datetime.date(2019, 1, 1), datetime.date(2019, 2, 1), datetime.date(2019, 3, 1)]
         data     valor
0  2018-04-01  37165.11
1  2018-05-01  45621.96
2  2018-06-01  49119.93
3  2018-07-01  40859.34
4  2018-08-01  56560.88
5  2018-09-01  49001.79
6  2018-10-01  53351.71
7  2018-11-01  47653.60
8  2018-12-01  51135.13
9  2019-01-01  24969.00
10 2019-02-01  60111.81
11 2019-03-01  43487.84
probabilidade_zeros :0.0
         data     valor
0  2018-04-01   2620.74
1  2018-05-01  23288.46
2  2018-06-01  18261.98
3  2018-07-01  29522.98
4  2018-08-01  18114.98
5  2018-09-01  14103.00
6  2018-10-01  16545.70
7  2018-11-01  15536.22
8  2018-12-01  20172.42
9  2019-01-01  23743.94
10 2019-02-01  14374.05
11 2019-03-01  21873.48
periodo de elegibilidade : [datetime.date(2018, 10, 1), datetime.date(2018, 11, 1), datetime.date(2018, 12, 1), datetime.date(2019, 1, 1), datetime.date(2019, 2, 1), datetime.date(2019, 3, 1)]
         data     valor
0  2018-04-01   2620.74
1  2018-05-01  23288.46
2  2018-06-01  18261.98
3  2018-07-01  29522.98
4  2018-08-01  18114.98
5  2018-09-01  14103.00
6  2018-10-01  16545.70
7  2018-11-01  15536.22
8  2018-12-01  20172.42
9  2019-01-01  23743.94
10 2019-02-01  14374.05
11 2019-03-01  21873.48
probabilidade_zeros :0.0
score : 719.4585858585857
         data      valor
0  2017-09-01   28547.00
1  2017-10-01  117149.65
2  2017-11-01  162821.39
3  2017-12-01  220173.10
4  2018-01-01  233713.98
5  2018-02-01  158429.08
6  2018-03-01  207087.16
7  2018-04-01  282024.63
8  2018-05-01  249953.40
9  2018-06-01  244103.02
10 2018-07-01  260229.47
11 2018-08-01  223392.77
12 2018-09-01  217036.29
13 2018-10-01  265599.04
14 2018-11-01  233971.87
15 2018-12-01  287927.92
16 2019-01-01  273301.68
17 2019-02-01  172282.00
18 2019-03-01  228654.68
periodo de elegibilidade : [datetime.date(2018, 10, 1), datetime.date(2018, 11, 1), datetime.date(2018, 12, 1), datetime.date(2019, 1, 1), datetime.date(2019, 2, 1), datetime.date(2019, 3, 1)]
         data      valor
0  2017-09-01   28547.00
1  2017-10-01  117149.65
2  2017-11-01  162821.39
3  2017-12-01  220173.10
4  2018-01-01  233713.98
5  2018-02-01  158429.08
6  2018-03-01  207087.16
7  2018-04-01  282024.63
8  2018-05-01  249953.40
9  2018-06-01  244103.02
10 2018-07-01  260229.47
11 2018-08-01  223392.77
12 2018-09-01  217036.29
13 2018-10-01  265599.04
14 2018-11-01  233971.87
15 2018-12-01  287927.92
16 2019-01-01  273301.68
17 2019-02-01  172282.00
18 2019-03-01  228654.68
probabilidade_zeros :0.0
score : 711.8060606060607
         data     valor
0  2016-11-01   6578.06
1  2016-12-01  33773.70
2  2017-01-01  25021.72
3  2017-02-01  21457.05
4  2017-03-01  25940.92
5  2017-04-01  22867.26
6  2017-05-01  31584.89
7  2017-06-01  29500.31
8  2017-07-01  53314.29
9  2017-08-01  32149.89
10 2017-09-01   8721.87
11 2017-10-01   8221.24
12 2017-11-01   4873.16
13 2017-12-01      0.00
14 2018-01-01      0.00
15 2018-02-01    895.88
16 2018-03-01      0.00
17 2018-04-01      0.00
18 2018-05-01      0.00
19 2018-06-01      0.00
20 2018-07-01      0.00
21 2018-08-01   2150.34
22 2018-09-01  58457.93
23 2018-10-01  67496.17
24 2018-11-01  59460.13
25 2018-12-01  67580.35
26 2019-01-01  74006.29
27 2019-02-01  55130.03
28 2019-03-01  59521.53
periodo de elegibilidade : [datetime.date(2018, 10, 1), datetime.date(2018, 11, 1), datetime.date(2018, 12, 1), datetime.date(2019, 1, 1), datetime.date(2019, 2, 1), datetime.date(2019, 3, 1)]
         data     valor
0  2016-11-01   6578.06
1  2016-12-01  33773.70
2  2017-01-01  25021.72
3  2017-02-01  21457.05
4  2017-03-01  25940.92
5  2017-04-01  22867.26
6  2017-05-01  31584.89
7  2017-06-01  29500.31
8  2017-07-01  53314.29
9  2017-08-01  32149.89
10 2017-09-01   8721.87
11 2017-10-01   8221.24
12 2017-11-01   4873.16
13 2017-12-01      0.00
14 2018-01-01      0.00
15 2018-02-01    895.88
16 2018-03-01      0.00
17 2018-04-01      0.00
18 2018-05-01      0.00
19 2018-06-01      0.00
20 2018-07-01      0.00
21 2018-08-01   2150.34
22 2018-09-01  58457.93
23 2018-10-01  67496.17
24 2018-11-01  59460.13
25 2018-12-01  67580.35
26 2019-01-01  74006.29
27 2019-02-01  55130.03
28 2019-03-01  59521.53
probabilidade_zeros :0.4166666666666667
score : 781.3272727272729
         data     valor
0  2017-09-01  13228.02
1  2017-10-01   7166.56
2  2017-11-01   4062.78
3  2017-12-01   7908.26
4  2018-01-01   9672.16
5  2018-02-01   3371.70
6  2018-03-01   9934.86
7  2018-04-01  12423.16
8  2018-05-01  22122.38
9  2018-06-01  18318.18
10 2018-07-01  38603.12
11 2018-08-01  45942.83
12 2018-09-01  34655.37
13 2018-10-01  29865.57
14 2018-11-01  39398.20
15 2018-12-01  46617.43
16 2019-01-01  28266.36
17 2019-02-01  25458.40
18 2019-03-01  25047.84
periodo de elegibilidade : [datetime.date(2018, 10, 1), datetime.date(2018, 11, 1), datetime.date(2018, 12, 1), datetime.date(2019, 1, 1), datetime.date(2019, 2, 1), datetime.date(2019, 3, 1)]
         data     valor
0  2017-09-01  13228.02
1  2017-10-01   7166.56
2  2017-11-01   4062.78
3  2017-12-01   7908.26
4  2018-01-01   9672.16
5  2018-02-01   3371.70
6  2018-03-01   9934.86
7  2018-04-01  12423.16
8  2018-05-01  22122.38
9  2018-06-01  18318.18
10 2018-07-01  38603.12
11 2018-08-01  45942.83
12 2018-09-01  34655.37
13 2018-10-01  29865.57
14 2018-11-01  39398.20
15 2018-12-01  46617.43
16 2019-01-01  28266.36
17 2019-02-01  25458.40
18 2019-03-01  25047.84
probabilidade_zeros :0.0
score : 692.7272727272726
         data     valor
0  2016-11-01   4766.02
1  2016-12-01  26096.02
2  2017-01-01  24997.82
3  2017-02-01   9764.72
4  2017-03-01  19704.72
5  2017-04-01  13890.92
6  2017-05-01  19991.50
7  2017-06-01  11084.82
8  2017-07-01  26507.08
9  2017-08-01  19677.90
10 2017-09-01  17374.86
11 2017-10-01  15899.58
12 2017-11-01  21288.10
13 2017-12-01  30354.16
14 2018-01-01  28359.67
15 2018-02-01  22496.90
16 2018-03-01  17517.14
17 2018-04-01  26518.24
18 2018-05-01  28099.82
19 2018-06-01  28408.76
20 2018-07-01  43124.90
21 2018-08-01  52937.74
22 2018-09-01  45401.48
23 2018-10-01  43402.56
24 2018-11-01  43582.35
25 2018-12-01  48072.14
26 2019-01-01  56555.26
27 2019-02-01  46230.82
28 2019-03-01  57595.20
periodo de elegibilidade : [datetime.date(2018, 10, 1), datetime.date(2018, 11, 1), datetime.date(2018, 12, 1), datetime.date(2019, 1, 1), datetime.date(2019, 2, 1), datetime.date(2019, 3, 1)]
         data     valor
0  2016-11-01   4766.02
1  2016-12-01  26096.02
2  2017-01-01  24997.82
3  2017-02-01   9764.72
4  2017-03-01  19704.72
5  2017-04-01  13890.92
6  2017-05-01  19991.50
7  2017-06-01  11084.82
8  2017-07-01  26507.08
9  2017-08-01  19677.90
10 2017-09-01  17374.86
11 2017-10-01  15899.58
12 2017-11-01  21288.10
13 2017-12-01  30354.16
14 2018-01-01  28359.67
15 2018-02-01  22496.90
16 2018-03-01  17517.14
17 2018-04-01  26518.24
18 2018-05-01  28099.82
19 2018-06-01  28408.76
20 2018-07-01  43124.90
21 2018-08-01  52937.74
22 2018-09-01  45401.48
23 2018-10-01  43402.56
24 2018-11-01  43582.35
25 2018-12-01  48072.14
26 2019-01-01  56555.26
27 2019-02-01  46230.82
28 2019-03-01  57595.20
probabilidade_zeros :0.0

score : 779.8181818181816
         data     valor
0  2016-10-01  18377.86
1  2016-11-01   5084.75
2  2016-12-01  12315.31
3  2017-01-01  14922.08
4  2017-02-01   6769.85
5  2017-03-01  12738.22
6  2017-04-01   3532.40
7  2017-05-01   5688.99
8  2017-06-01   2663.10
9  2017-07-01  11940.21
10 2017-08-01  18602.59
11 2017-09-01  17801.74
12 2017-10-01  16892.67
13 2017-11-01  18129.20
14 2017-12-01  20969.55
15 2018-01-01  15887.52
16 2018-02-01  16877.98
17 2018-03-01  23029.65
18 2018-04-01   5642.57
19 2018-05-01  10637.29
20 2018-06-01   9642.58
21 2018-07-01  41307.97
22 2018-08-01  72709.28
23 2018-09-01  49966.29
24 2018-10-01  48101.68
25 2018-11-01  44573.73
26 2018-12-01  40184.73
27 2019-01-01  61209.80
28 2019-02-01  41446.22
29 2019-03-01  68659.41
periodo de elegibilidade : [datetime.date(2018, 10, 1), datetime.date(2018, 11, 1), datetime.date(2018, 12, 1), datetime.date(2019, 1, 1), datetime.date(2019, 2, 1), datetime.date(2019, 3, 1)]
         data     valor
0  2016-10-01  18377.86
1  2016-11-01   5084.75
2  2016-12-01  12315.31
3  2017-01-01  14922.08
4  2017-02-01   6769.85
5  2017-03-01  12738.22
6  2017-04-01   3532.40
7  2017-05-01   5688.99
8  2017-06-01   2663.10
9  2017-07-01  11940.21
10 2017-08-01  18602.59
11 2017-09-01  17801.74
12 2017-10-01  16892.67
13 2017-11-01  18129.20
14 2017-12-01  20969.55
15 2018-01-01  15887.52
16 2018-02-01  16877.98
17 2018-03-01  23029.65
18 2018-04-01   5642.57
19 2018-05-01  10637.29
20 2018-06-01   9642.58
21 2018-07-01  41307.97
22 2018-08-01  72709.28
23 2018-09-01  49966.29
24 2018-10-01  48101.68
25 2018-11-01  44573.73
26 2018-12-01  40184.73
27 2019-01-01  61209.80
28 2019-02-01  41446.22
29 2019-03-01  68659.41
probabilidade_zeros :0.0
score : 752.9961038961037
         data    valor
0  2016-10-01  2113.12
1  2016-11-01   407.44
2  2016-12-01     0.00
3  2017-01-01  1320.44
4  2017-02-01     0.00
5  2017-03-01     0.00
6  2017-04-01     0.00
7  2017-05-01     0.00
8  2017-06-01     0.00
9  2017-07-01     0.00
10 2017-08-01     0.00
11 2017-09-01     0.00
12 2017-10-01     0.00
13 2017-11-01     0.00
14 2017-12-01     0.00
15 2018-01-01     0.00
16 2018-02-01     0.00
17 2018-03-01     0.00
18 2018-04-01  1565.64
19 2018-05-01  4433.43
20 2018-06-01  3733.40
21 2018-07-01  3586.25
22 2018-08-01  3969.77
23 2018-09-01  2256.14
24 2018-10-01  1903.46
25 2018-11-01  3269.94
26 2018-12-01  5234.52
27 2019-01-01  7113.63
28 2019-02-01  4851.18
29 2019-03-01  2940.42
periodo de elegibilidade : [datetime.date(2018, 10, 1), datetime.date(2018, 11, 1), datetime.date(2018, 12, 1), datetime.date(2019, 1, 1), datetime.date(2019, 2, 1), datetime.date(2019, 3, 1)]
         data    valor
0  2016-10-01  2113.12
1  2016-11-01   407.44
2  2016-12-01     0.00
3  2017-01-01  1320.44
4  2017-02-01     0.00
5  2017-03-01     0.00
6  2017-04-01     0.00
7  2017-05-01     0.00
8  2017-06-01     0.00
9  2017-07-01     0.00
10 2017-08-01     0.00
11 2017-09-01     0.00
12 2017-10-01     0.00
13 2017-11-01     0.00
14 2017-12-01     0.00
15 2018-01-01     0.00
16 2018-02-01     0.00
17 2018-03-01     0.00
18 2018-04-01  1565.64
19 2018-05-01  4433.43
20 2018-06-01  3733.40
21 2018-07-01  3586.25
22 2018-08-01  3969.77
23 2018-09-01  2256.14
24 2018-10-01  1903.46
25 2018-11-01  3269.94
26 2018-12-01  5234.52
27 2019-01-01  7113.63
28 2019-02-01  4851.18
29 2019-03-01  2940.42
probabilidade_zeros :0.0
score : 677.7060606060605
        data     valor
0 2018-07-01   7287.22
1 2018-08-01  12072.82
2 2018-09-01  23101.64
3 2018-10-01  32614.02
4 2018-11-01  45740.81
5 2018-12-01  39415.20
6 2019-01-01  49434.28
7 2019-02-01  25456.91
8 2019-03-01  33931.93
periodo de elegibilidade : [datetime.date(2018, 10, 1), datetime.date(2018, 11, 1), datetime.date(2018, 12, 1), datetime.date(2019, 1, 1), datetime.date(2019, 2, 1), datetime.date(2019, 3, 1)]
        data     valor
0 2018-07-01   7287.22
1 2018-08-01  12072.82
2 2018-09-01  23101.64
3 2018-10-01  32614.02
4 2018-11-01  45740.81
5 2018-12-01  39415.20
6 2019-01-01  49434.28
7 2019-02-01  25456.91
8 2019-03-01  33931.93
probabilidade_zeros :0.0
score : 695.309090909091

In [278]:
dscore = pd.concat(resp)

In [282]:
dscore.shape

(170, 2)

In [280]:
dcalc.head()

,cnpj,segmento,probabilidade,valor_divida,composicao,fat_medio,pi,lambda,impacto_segmento,risco,dscore,peso,score
2,00272073000302,outros,1.0,9659.96,1.0,139381.200000,0.046204,0.046204,0.011551,0.011551,691.914295,1,691.914295
8,05164765000180,outros,1.0,3100.56,1.0,94885.300000,0.021785,0.021785,0.005446,0.005446,696.187692,1,696.187692
9,05674948000146,outros,1.0,6202.47,1.0,14578.056667,0.283644,0.283644,0.070911,0.070911,650.362280,1,650.362280
11,06135496000197,outros,1.0,74.77,1.0,7751.399167,0.006431,0.006431,0.001608,0.001608,698.874633,1,698.874633
12,07127571000130,outros,1.0,2648.22,1.0,147721.475000,0.011951,0.011951,0.002988,0.002988,697.908503,1,697.908503

In [285]:
final = dcalc[dcalc['cnpj'].isin(dfpv['cnpj'].tolist())]

In [288]:
final['cnpj'].unique().tolist().__len__()

170

In [291]:
final.rename(columns={'dscore' : 'dscore_seg', 'score' : 'dscore'}, inplace=True)

In [293]:
final.head()

,cnpj,segmento,probabilidade,valor_divida,composicao,fat_medio,pi,lambda,impacto_segmento,risco,dscore_seg,peso,dscore
271,01509450000177,outros,1.0,408.43,1.0,36894.373333,0.007380,0.007380,0.001845,0.001845,698.708471,1,698.708471
272,81780819000110,outros,1.0,2744.47,1.0,3738.148333,0.489453,0.489453,0.122363,0.122363,614.345783,1,614.345783
273,01344355000160,outros,1.0,9530.28,1.0,11823.616667,0.537358,0.537358,0.134340,0.134340,605.962276,1,605.962276
274,81576472000199,outros,1.0,639.56,1.0,41173.462500,0.010356,0.010356,0.002589,0.002589,698.187781,1,698.187781
275,08312694000104,outros,1.0,270.00,1.0,40641.924167,0.004429,0.004429,0.001107,0.001107,699.224938,1,699.224938

In [298]:
final = final.merge(dscore, left_on='cnpj', right_on='cnpj', how='left')

In [300]:
final.head()

,cnpj,segmento,probabilidade,valor_divida,composicao,fat_medio,pi,lambda,impacto_segmento,risco,dscore_seg,peso,dscore,lscore
0,01509450000177,outros,1.0,408.43,1.0,36894.373333,0.007380,0.007380,0.001845,0.001845,698.708471,1,698.708471,709
1,81780819000110,outros,1.0,2744.47,1.0,3738.148333,0.489453,0.489453,0.122363,0.122363,614.345783,1,614.345783,677
2,01344355000160,outros,1.0,9530.28,1.0,11823.616667,0.537358,0.537358,0.134340,0.134340,605.962276,1,605.962276,626
3,81576472000199,outros,1.0,639.56,1.0,41173.462500,0.010356,0.010356,0.002589,0.002589,698.187781,1,698.187781,752
4,08312694000104,outros,1.0,270.00,1.0,40641.924167,0.004429,0.004429,0.001107,0.001107,699.224938,1,699.224938,826

In [ ]:
def calcula_dscore(risco_, score_limite):
    return -score_limite*risco_ + score_limite

In [303]:
final['dscore_final_seg'] = final.apply(lambda x : calcula_dscore(x['risco'], 0.8*x['lscore']) , axis=1)

In [307]:
final[final['cnpj']=='09286118000100']

,cnpj,segmento,probabilidade,valor_divida,composicao,fat_medio,pi,lambda,impacto_segmento,risco,dscore_seg,peso,dscore,lscore,dscore_final_seg
154,09286118000100,credito,0.375,2982.75,0.774569,23899.456667,0.083203,0.064446,0.766112,0.287292,498.895713,4,572.549444,749,427.054731
155,09286118000100,infra,0.250,202.10,0.052482,23899.456667,0.005638,0.000296,0.250074,0.062518,656.237056,2,572.549444,749,561.738920
156,09286118000100,outros,0.375,666.00,0.172949,23899.456667,0.018578,0.003213,0.000803,0.000301,699.789146,1,572.549444,749,599.019509

In [309]:
# calcula dscore final
def calcula_score_total(cnpj, df):
    dt = df[df['cnpj']==cnpj]
    dt["dscore_final"] = dt["dscore_final_seg"]*dt["peso"]
    score = dt["dscore_final"].sum()/dt["peso"].sum()
    dt["dscore_final"] = score
    return dt

In [310]:
resp = []
for el in final['cnpj'].unique().tolist():
    _df = calcula_score_total(el, final)
    resp.append(_df)

In [315]:
def calcula(lscore, dscore):
    return np.mean([lscore, dscore])

In [313]:
final = pd.concat(resp)

In [316]:
final["score"] = final.apply(lambda x : calcula(x["lscore"], x["dscore_final"]), axis=1)

In [317]:
resp = final[['cnpj', "lscore", "dscore_final", "score"]].drop_duplicates()

In [324]:
resp.head()

             cnpj  lscore  dscore_final       score
0  01509450000177     709    566.153492  637.576746
1  81780819000110     677    475.328109  576.164055
2  01344355000160     626    433.522726  529.761363
3  81576472000199     752    600.042527  676.021264
4  08312694000104     826    660.068342  743.034171

In [320]:
dcalc[dcalc['cnpj']=='00661205000118']

,cnpj,segmento,probabilidade,valor_divida,composicao,fat_medio,pi,lambda,impacto_segmento,risco,dscore,peso,score
279,00661205000118,credito,1.0,27496.75,1.0,28635.588333,0.640153,0.640153,0.910038,0.910038,62.973171,4,62.973171

In [321]:
resp[resp['cnpj']=='00661205000118']

             cnpj  lscore  dscore_final       score
6  00661205000118     738     53.113371  395.556686

In [322]:
cnpj = '00661205000118'
plot_dividas(cnpj, dcalc)
plot_probabilidade(cnpj, dcalc)
plot_risco(cnpj, dcalc)

In [326]:
dcalc[dcalc['cnpj']=='04509695000192']

,cnpj,segmento,probabilidade,valor_divida,composicao,fat_medio,pi,lambda,impacto_segmento,risco,dscore,peso,score
308,04509695000192,credito,1.0,34146.03,1.0,23566.275,0.965957,0.965957,0.991489,0.991489,5.957438,4,5.957438

In [327]:
resp[resp['cnpj']=='04509695000192']

              cnpj  lscore  dscore_final       score
13  04509695000192     749      5.099567  377.049784

In [328]:
cnpj = '04509695000192'
plot_dividas(cnpj, dcalc)
plot_probabilidade(cnpj, dcalc)
plot_risco(cnpj, dcalc)

In [331]:
dcalc[dcalc['cnpj']=='55057392000117']

,cnpj,segmento,probabilidade,valor_divida,composicao,fat_medio,pi,lambda,impacto_segmento,risco,dscore,peso,score
411,55057392000117,outros,0.666667,1696.66,0.059596,122789.42,0.009212,0.000549,0.000137,0.000091,699.935952,1,606.503585
412,55057392000117,processos,0.333333,26772.58,0.940404,122789.42,0.145358,0.136695,0.534174,0.178058,575.359463,3,606.503585

In [332]:
resp[resp['cnpj']=='55057392000117']

              cnpj  lscore  dscore_final       score
59  55057392000117     700    485.202868  592.601434

In [334]:
cnpj = '55057392000117'
plot_dividas(cnpj, dcalc)
plot_probabilidade(cnpj, dcalc)
plot_risco(cnpj, dcalc)

In [330]:
final[final["segmento"]=="processos"]

,cnpj,segmento,probabilidade,valor_divida,composicao,fat_medio,pi,lambda,impacto_segmento,risco,dscore_seg,peso,dscore,lscore,dscore_final_seg,dscore_final,score
60,55057392000117,processos,0.333333,26772.58,0.940404,122789.420000,0.145358,0.136695,0.534174,0.178058,575.359463,3,606.503585,700,460.287570,485.202868,592.601434
66,13231036000128,processos,0.333333,15769.07,0.362907,36933.527500,0.284639,0.103297,0.525824,0.175275,577.307651,3,564.563555,701,462.505901,452.296059,576.648030
94,58921719000145,processos,0.333333,9562.96,0.729777,28197.395000,0.226096,0.164999,0.541250,0.180417,573.708372,3,604.621446,870,570.430038,601.166467,735.583233
120,20203811000105,processos,0.166667,1821.81,0.385406,5059.270000,0.240062,0.092521,0.523130,0.087188,638.968125,3,645.648231,210,153.352350,154.955575,182.477788
135,03598113000129,processos,0.500000,0.00,0.000000,38377.860000,0.000000,0.000000,0.500000,0.250000,525.000000,3,568.622280,689,413.400000,447.749430,568.374715
196,18917920000134,processos,1.000000,1009.04,1.000000,22843.333333,0.029448,0.029448,0.507362,0.507362,344.846578,3,344.846578,684,269.571497,269.571497,476.785748
197,21295614000118,processos,1.000000,3138.82,1.000000,18769.333333,0.111488,0.111488,0.527872,0.527872,330.489682,3,330.489682,823,310.849152,310.849152,566.924576
198,53244075000184,processos,1.000000,16555.56,1.000000,39141.307500,0.281979,0.281979,0.570495,0.570495,300.653616,3,300.653616,670,230.214769,230.214769,450.107384
199,15576591000117,processos,1.000000,24088.33,1.000000,66311.530833,0.242173,0.242173,0.560543,0.560543,307.619661,3,307.619661,740,260.158342,260.158342,500.079171
200,05337303000118,processos,1.000000,3214.00,1.000000,22084.569000,0.097021,0.097021,0.524255,0.524255,333.021327,3,333.021327,618,235.208206,235.208206,426.604103
201,05702753000162,processos,1.000000,1409.07,1.000000,9813.526667,0.095723,0.095723,0.523931,0.523931,333.248479,3,333.248479,680,258.981675,258.981675,469.490837
202,03334511000138,processos,1.000000,1769.35,1.000000,10729.931667,0.109932,0.109932,0.527483,0.527483,330.761838,3,330.761838,720,272.169741,272.169741,496.084870

In [335]:
final.groupby("cnpj").count().sort_values('segmento', ascending=False).head(20)

,segmento,probabilidade,valor_divida,composicao,fat_medio,pi,lambda,impacto_segmento,risco,dscore_seg,peso,dscore,lscore,dscore_final_seg,dscore_final,score
cnpj,,,,,,,,,,,,,,,,
06102005000101,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3
13231036000128,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3
11368505000120,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3
09286118000100,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3
07486105000141,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2
03941181000149,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2
04160069000133,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2
24936037000194,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2
09189540000130,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2
04634050000181,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2
23389850000129,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2
05121187000103,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2
03598113000129,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2
08917146000108,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2
05458709000159,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2
20862369000110,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2
08756051000150,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2
18836786000147,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2
08310428000142,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2
20203811000105,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2