In [1]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

from plotly.offline import init_notebook_mode, iplot
import plotly.graph_objs as go
init_notebook_mode(connected=True)
import warnings
warnings.filterwarnings("ignore")
%matplotlib inline

In [2]:
df_dividas = pd.read_excel("../tabelas/base_dividas_201904.xlsx")

In [3]:
df_dividas['cnpj'] = df_dividas.apply(lambda x : '0' + str(x['cnpj']) if len(str(x['cnpj']))==13
                              else ('00' + str(x['cnpj']) if len(str(x['cnpj']))==12 else str(x['cnpj'])), axis=1)

In [4]:
df_p = df_dividas[df_dividas['tipo']=='processos']

In [5]:
df_dividas = df_dividas[df_dividas['tipo']!='processos']

In [6]:
df_p['modalidade_natureza'] = df_p['descricao_natureza']

In [7]:
df_p.drop(columns=['descricao_natureza'], axis=1, inplace=True)

In [8]:
df_p.head()

,cnpj,data_ocorrencia,modalidade_natureza,natureza,tipo,uf,valor
0,03403405000169,03/07/2017,EXC JUD TRAB,Execução de Título Judicial Trabalhista,processos,SC,"R$ 17788,37"
1,03403405000169,24/01/2017,EXC JUD TRAB,Execução de Título Judicial Trabalhista,processos,RS,"R$ 75143,93"
2,03403405000169,11/08/2016,FISCAL ESTADUAL,Execução Fiscal Estadual,processos,SC,"R$ 0,00"
0,04501499000171,25/01/2019,FISCAL ESTADUAL,Execução Fiscal Estadual,processos,MG,"R$ 0,00"
1,04501499000171,18/01/2018,EXECUCAO,Execução,processos,MG,"R$ 0,00"

In [9]:
df_dividas.drop(columns=['descricao_natureza'], axis=1, inplace=True)

In [10]:
df = pd.concat([df_dividas, df_p])

In [11]:
df.head()

,cnpj,data_ocorrencia,modalidade_natureza,natureza,tipo,uf,valor
0,19008188000142,21/05/2018,Dívida não contestada.,Falta Pagamento,protestos,SP,"R$ 892,53"
1,19008188000142,22/03/2018,Dívida não contestada.,Falta Pagamento,protestos,SP,"R$ 560,00"
2,19008188000142,15/03/2018,Dívida não contestada.,Falta Pagamento,protestos,SP,"R$ 560,80"
3,19008188000142,01/03/2018,Dívida não contestada.,Falta Pagamento,protestos,SP,"R$ 452,50"
4,19008188000142,22/02/2018,Dívida não contestada.,Falta Pagamento,protestos,SP,"R$ 452,50"

In [12]:
df['modalidade_natureza'] = df.apply(lambda x : x['modalidade_natureza'].replace(" ", "") if isinstance(x['modalidade_natureza'], str) else "OUTROS", axis=1)

In [13]:
df['modalidade_natureza'].unique().tolist()

['Dívidanãocontestada.',
 'DUPLICATA',
 'OUTRASOPER',
 'OUTROS',
 'NOTAFISCAL',
 'EMPRESCONTA',
 'CREDCARTAO',
 'FINANCIAMENT',
 'OPERIMOBILI',
 'VENDAMERCAD',
 'TITDESCONTA',
 'ADIANTCONTA',
 'SERVTELEFON',
 'EMPRESTIMO',
 'ALUGUEL',
 'ARRECADADOR',
 'CONDOMINIO',
 'ENERGIAELET',
 'CONFISSDIV',
 'CREDITOEFINANCIAMENTO-FINANC',
 'CREDIARIO',
 'TITULOSDESCONTADOS-TURISMO',
 'DIVIDASCHEQ',
 'OPERAJUIZAD',
 'REPASSES',
 'LEASING',
 'OUTRASOPERACOES-FINANCEIRA',
 'SEGUROSAUDE',
 'CONSORCIOCO',
 'CONSORCIOCONTEMPLADO',
 'CONSBENS',
 'TELEFFX',
 'TELEFFIXA',
 'TELEFMOVEL',
 'FATAGUA',
 'CONSVEICULO',
 'EXCJUDTRAB',
 'FISCALESTADUAL',
 'EXECUCAO',
 'FISCALFEDERAL',
 'FISCALMUNICIPAL',
 'EXECUCAO-JE',
 'BUSCAEAPREENSAO']

In [14]:
segmento_infra = ['FATAGUA', 'TELEFFX', 'TELEFFIXA', 'TELEFMOVEL', 'CONDOMINIO', 'ENERGIAELET', 'ALUGUEL', 
                  'SERVTELEFON']

segmento_credito = ['EMPRESCONTA', 'CREDCARTAO', 'FINANCIAMENT', 'CREDITOEFINANCIAMENTO-FINANC']

segmento_processos = ['EXCJUDTRAB', 'FISCALESTADUAL', 'EXECUCAO', 'FISCALFEDERAL', 'FISCALMUNICIPAL',
                     'EXECUCAO-JE', 'BUSCAEAPREENSAO']

In [15]:
df[df['tipo']=='processos']['modalidade_natureza'].unique().tolist()

['EXCJUDTRAB',
 'FISCALESTADUAL',
 'EXECUCAO',
 'FISCALFEDERAL',
 'FISCALMUNICIPAL',
 'EXECUCAO-JE',
 'BUSCAEAPREENSAO']

In [16]:
df['natureza'].unique().tolist()

['Falta Pagamento',
 'CÓDIGO DE ANOTAÇÃO NÃO ENCONTRADO',
 nan,
 'Empréstimos em contas - c/c garantidas, financiamentos de capital de giro, programas especiais, etc',
 'Cartão de crédito',
 'Créditos e financiamentos - empréstimos a pessoas físicas , financiamentos ao consumidor final , etc',
 'Operações imobiliárias em geral, inclusive de sociedades de poupança',
 'Adiantamento a depositantes - c/c devedores em geral',
 'Empréstimos agrícolas e industriais - financiamentos de custeio de investimentos agrícolas e industriais',
 'Operações ajuizadas ',
 'Arrendamentos, inclusive leasing',
 'Consórcio outros bens móveis',
 'Consórcio veículos leves',
 'Execução de Título Judicial Trabalhista',
 'Execução Fiscal Estadual',
 'Execução',
 'Execução Fiscal Federal',
 'Execução Fiscal Municipal',
 'Execução - Pequenas Causas',
 'Busca e Apreensão']

In [17]:
df[df['natureza']=='Empréstimos em contas - c/c garantidas, financiamentos de capital de giro, programas especiais, etc']['modalidade_natureza'].unique().tolist()

['EMPRESCONTA']

In [18]:
df[df['natureza']=='Cartão de crédito']['modalidade_natureza'].unique().tolist()

['CREDCARTAO']

In [19]:
df[df['natureza']=='Créditos e financiamentos - empréstimos a pessoas físicas , financiamentos ao consumidor final , etc']['modalidade_natureza'].unique().tolist()

['FINANCIAMENT']

In [20]:
df[df['natureza']=='Empréstimos agrícolas e industriais - financiamentos de custeio de investimentos agrícolas e industriais']['modalidade_natureza'].unique().tolist()

['EMPRESTIMO']

In [21]:
df['segmento'] = df.apply(lambda x : 'processos' if x['tipo']=='processos'
                          else('credito' if x['modalidade_natureza'] in segmento_credito
                              else ('infra' if x['modalidade_natureza'] in segmento_infra else "outros")), axis=1)

In [22]:
df.head()

,cnpj,data_ocorrencia,modalidade_natureza,natureza,tipo,uf,valor,segmento
0,19008188000142,21/05/2018,Dívidanãocontestada.,Falta Pagamento,protestos,SP,"R$ 892,53",outros
1,19008188000142,22/03/2018,Dívidanãocontestada.,Falta Pagamento,protestos,SP,"R$ 560,00",outros
2,19008188000142,15/03/2018,Dívidanãocontestada.,Falta Pagamento,protestos,SP,"R$ 560,80",outros
3,19008188000142,01/03/2018,Dívidanãocontestada.,Falta Pagamento,protestos,SP,"R$ 452,50",outros
4,19008188000142,22/02/2018,Dívidanãocontestada.,Falta Pagamento,protestos,SP,"R$ 452,50",outros

In [23]:
df['valor'] = df.apply(lambda x : x['valor'].split("R$ ")[1].replace(",", "."), axis=1)

In [24]:
df["valor"] = df.apply(lambda x : float(x["valor"]), axis=1)

In [25]:
df["valor"].iloc[0]

892.53

In [68]:
dt = df[df['cnpj']=='00178663000281']

In [69]:
dt.shape

(177, 8)

In [70]:
dt.drop_duplicates(inplace=True)

In [71]:
dprob = dt.groupby("segmento").count().reset_index()[["segmento", "cnpj"]]

dprob.columns = ["segmento", "ocorrencias"]

dprob["probabilidade"] = dprob["ocorrencias"]/dprob["ocorrencias"].sum()

In [72]:
dprob

    segmento  ocorrencias  probabilidade
0    credito            7       0.041667
1      infra           17       0.101190
2     outros          142       0.845238
3  processos            2       0.011905

In [74]:
dt["valor_impacto"] = dt.apply(lambda x : W.get(x["segmento"])*x["valor"], axis=1)

In [77]:
_df = dt.groupby("segmento").sum()

In [79]:
_df["impacto1"] = _df["valor"]/_df["valor"].sum()

In [81]:
_df["impacto2"] = _df["valor_impacto"]/_df["valor_impacto"].sum()

In [83]:
_df["impacto2"].sum()

0.9999999999999999

In [86]:
dr2 = _df.merge(dprob, left_on="segmento", right_on="segmento", how='left')

In [87]:
dr2

,segmento,valor,valor_impacto,impacto1,impacto2,ocorrencias,probabilidade
0,credito,262744.38,1050977.52,0.227796,0.346155,7,0.041667
1,infra,346604.91,693209.82,0.300502,0.228319,17,0.101190
2,outros,170122.43,170122.43,0.147494,0.056032,142,0.845238
3,processos,373946.72,1121840.16,0.324207,0.369494,2,0.011905

In [88]:
dr2["risco1"] = dr2["impacto1"]*dr2["probabilidade"]

In [90]:
dr2["risco2"] = dr2["impacto2"]*dr2["probabilidade"]

In [91]:
dr2

,segmento,valor,valor_impacto,impacto1,impacto2,ocorrencias,probabilidade,risco1,risco2
0,credito,262744.38,1050977.52,0.227796,0.346155,7,0.041667,0.009492,0.014423
1,infra,346604.91,693209.82,0.300502,0.228319,17,0.101190,0.030408,0.023104
2,outros,170122.43,170122.43,0.147494,0.056032,142,0.845238,0.124668,0.047361
3,processos,373946.72,1121840.16,0.324207,0.369494,2,0.011905,0.003860,0.004399

In [94]:
dr2["w"] = dr2.apply(lambda x : W.get(x["segmento"]), axis=1)

In [96]:
dr2["w"] = dr2["risco2"]*dr2["w"]

In [98]:
dr2["w"].sum()/10

0.016445665522911275

In [102]:
dscore(0.01644)

958.9

In [31]:
dimp = dt.groupby(["segmento"]).sum().reset_index()

dimp["impact"] = dimp["valor"]/dimp["valor"].sum()

In [32]:
dimp

    segmento      valor    impact
0    credito  262744.38  0.227796
1      infra  346604.91  0.300502
2     outros  170122.43  0.147494
3  processos  373946.72  0.324207

In [38]:
I = {"credito" : 3, "processos" : 2, "infra" : 1, "outros" : 0.1}

In [39]:
drisk = dprob.merge(dimp, left_on="segmento", right_on="segmento", how="left")

drisk["risk"] = drisk["probabilidade"]*drisk["impact"]

In [40]:
drisk

    segmento  ocorrencias  probabilidade      valor    impact      risk
0    credito            7       0.041667  262744.38  0.227796  0.009492
1      infra           17       0.101190  346604.91  0.300502  0.030408
2     outros          142       0.845238  170122.43  0.147494  0.124668
3  processos            2       0.011905  373946.72  0.324207  0.003860

In [41]:
drisk["impact2"] = drisk.apply(lambda x : x["impact"]*I.get(x["segmento"]), axis=1)

In [42]:
drisk["risk2"] = drisk

,segmento,ocorrencias,probabilidade,valor,impact,risk,impact2
0,credito,7,0.041667,262744.38,0.227796,0.009492,0.683389
1,infra,17,0.101190,346604.91,0.300502,0.030408,0.300502
2,outros,142,0.845238,170122.43,0.147494,0.124668,0.014749
3,processos,2,0.011905,373946.72,0.324207,0.003860,0.648415

In [43]:
W = {"credito" : 4,
    "processos" : 3,
     "infra" : 2,
     "outros" : 1    
    }

In [44]:
drisk["weight"] = drisk.apply(lambda x : W.get(x["segmento"]), axis=1)

drisk["total_risk"] = drisk["risk"]*drisk["weight"]

drisk["total_risk"].sum()/drisk["weight"].sum()

0.02350284606826561

In [49]:
def probability(dt):
    dprob = dt.groupby("segmento").count().reset_index()[["segmento", "cnpj"]]
    dprob.columns = ["segmento", "ocorrencias"]
    dprob["probabilidade"] = dprob["ocorrencias"]/dprob["ocorrencias"].sum()
    return dprob

In [50]:
probability(dt)

    segmento  ocorrencias  probabilidade
0    credito            7       0.041667
1      infra           17       0.101190
2     outros          142       0.845238
3  processos            2       0.011905

In [51]:
def impact(dt):
    dimp = dt.groupby(["segmento"]).sum().reset_index()
    dimp["impact"] = dimp["valor"]/dimp["valor"].sum()
    dimp["impact"] = dimp.apply(lambda x : x["impact"]*I.get(x["segmento"]), axis=1)
    return dimp

In [52]:
impact(dt)

    segmento      valor    impact
0    credito  262744.38  0.683389
1      infra  346604.91  0.300502
2     outros  170122.43  0.014749
3  processos  373946.72  0.648415

In [100]:
def get_risk(cnpj, df):
    dt = df[df['cnpj']==cnpj]
    dt.drop_duplicates(inplace=True)
    dprob = probability(dt)
    dimp = impact(dt)
    
    drisk = dprob.merge(dimp, left_on="segmento", right_on="segmento", how="left")
    drisk["risk"] = drisk["probabilidade"]*drisk["impact"]
    drisk["weight"] = drisk.apply(lambda x : W.get(x["segmento"]), axis=1)
    drisk["total_risk"] = drisk["risk"]*drisk["weight"]
    risk = drisk["total_risk"].sum()/10
    return risk

In [60]:
df_comp[df_comp["cnpj"]=='00661205000118']

,cnpj,segmento,valor_divida,total_divida,composicao_divida,fat_medio,prop_divida,quantidade_cheques,segmento_principal,composicao_principal,tempo_medio,idade_maxima
9,00661205000118,credito,27496.75,27496.75,1.0,28635.588333,0.96023,0,credito,1.0,0.0,935

In [63]:
df_comp[df_comp["segmento_principal"]=="outros"].sort_values("composicao_principal", ascending=False).head()

,cnpj,segmento,valor_divida,total_divida,composicao_divida,fat_medio,prop_divida,quantidade_cheques,segmento_principal,composicao_principal,tempo_medio,idade_maxima
4,00225356000123,outros,174.98,174.98,1.0,24467.000000,0.007152,0,outros,1.0,0.00000,1793
630,18058375000178,outros,1544.19,1544.19,1.0,9410.254167,0.164097,0,outros,1.0,1035.00000,1578
620,17513235000180,processos,0.00,735178.94,0.0,6869.333333,107.023332,0,outros,1.0,5.14881,986
622,17651859000163,outros,1307.24,1307.24,1.0,5204.009167,0.251199,0,outros,1.0,0.00000,1100
623,17781914000130,outros,5214.99,5214.99,1.0,0.000000,0.000000,0,outros,1.0,0.00000,42

In [54]:
get_risk("00661205000118", df)

1.2

In [64]:
get_risk("00225356000123", df)

0.01

In [65]:
def dscore3(r):
    return (-1)*(750/1.2)*r + 750

In [67]:
dscore3(0)

750.0

In [44]:
get_risk("00806759000166", df)

0.21590958326343768

In [46]:
# df_comp[df_comp["cnpj"]=="00806759000166"]

In [47]:
# df_comp["segmento"].unique().tolist()

In [48]:
# evaluating risk for the entire dataset

In [49]:
resp = []
for el in df["cnpj"].unique().tolist():
    r = get_risk(el, df)
    resp.append(pd.DataFrame({"cnpj" : [el], "risk" : [r]}))

In [50]:
resp = pd.concat(resp)

In [51]:
resp["risk"].max()

0.4

In [52]:
resp["risk"].min()

0.0

In [53]:
trace = go.Histogram(
    x = resp["risk"],
    marker = dict(color="#87EBB3", line=dict(color="rgb(0, 0, 0)", width=1))
)
layout = go.Layout(title="Distribution of Risk based on Debt quality", xaxis=dict(title="risk"),
                  yaxis=dict(title="number of samples"))
fig = go.Figure(data = [trace], layout=layout)
iplot(fig)

In [164]:
# calculating the D-score

In [101]:
def dscore(risk):
    return 1000*((-1)*(5/2)*risk + 1)

In [55]:
dscore(0.2)

500.0

In [56]:
resp["dscore"] = resp.apply(lambda x : dscore(x["risk"]), axis=1)

In [57]:
resp.head()

             cnpj      risk      dscore
0  19008188000142  0.100000  750.000000
0  00748390000182  0.100000  750.000000
0  00272073000302  0.100000  750.000000
0  03403405000169  0.095696  760.760648
0  04501499000171  0.050229  874.426892

In [58]:
trace = go.Histogram(
    x = resp["dscore"],
    marker = dict(color="rgb(142,120,163)", line=dict(color="rgb(0, 0, 0)", width=1))
)
layout = go.Layout(title="Distribution of D-score - entire dataset")
fig = go.Figure(data = [trace], layout=layout)
iplot(fig)

In [179]:
# selecting samples with ratio debt/income less than 1.5 and no cheques

In [184]:
_df = df_comp[(df_comp["prop_divida"]<1.5) & (df_comp["quantidade_cheques"]==0)]

In [186]:
resp_ = resp[resp["cnpj"].isin(_df["cnpj"].tolist())]

In [187]:
trace = go.Histogram(
    x = resp_["dscore"],
    marker = dict(color="rgb(142,120,163)", line=dict(color="rgb(0, 0, 0)", width=1))
)
layout = go.Layout(title="Distribution of D-score - approved sample")
fig = go.Figure(data = [trace], layout=layout)
iplot(fig)

In [189]:
resp[resp["dscore"]==0].head()

             cnpj  risk  dscore
0  19819235000138   0.4     0.0
0  18455950000176   0.4     0.0
0  15389888000173   0.4     0.0
0  11223079000136   0.4     0.0
0  15497859000125   0.4     0.0

In [56]:
df_comp = pd.read_excel("../tabelas/dataset_variaveis_completo_201904.xlsx")

In [57]:
df_comp["cnpj"] = df_comp.apply(lambda x : str(x["cnpj"]), axis=1)

In [58]:
df_comp["cnpj"] = df_comp.apply(lambda x : "0" + x["cnpj"] if len(x["cnpj"])==13 else
                                ("00" + x["cnpj"] if len(x["cnpj"])==12 else x["cnpj"]), axis=1)

In [59]:
df_comp.head()

,cnpj,segmento,valor_divida,total_divida,composicao_divida,fat_medio,prop_divida,quantidade_cheques,segmento_principal,composicao_principal,tempo_medio,idade_maxima
0,00178663000281,credito,262744.38,1158237.23,0.226849,9010.214167,128.547136,17,processos,0.322858,6.497006,1134
1,00178663000281,infra,346604.91,1158237.23,0.299252,9010.214167,128.547136,17,processos,0.322858,6.497006,1134
2,00178663000281,outros,174941.22,1158237.23,0.151041,9010.214167,128.547136,17,processos,0.322858,6.497006,1134
3,00178663000281,processos,373946.72,1158237.23,0.322858,9010.214167,128.547136,17,processos,0.322858,6.497006,1134
4,00225356000123,outros,174.98,174.98,1.000000,24467.000000,0.007152,0,outros,1.000000,0.000000,1793

In [69]:
df_comp[df_comp["cnpj"]=="15497859000125"]

,cnpj,segmento,valor_divida,total_divida,composicao_divida,fat_medio,prop_divida,quantidade_cheques,segmento_principal,composicao_principal,tempo_medio,idade_maxima
556,15497859000125,credito,116073.75,116073.75,1.0,5353.230833,21.682934,0,credito,1.0,1.5,539

In [79]:
resp.sort_values("dscore", ascending=False).iloc[:200,:]

              cnpj      risk       dscore
0   11248203000118  0.000000  1000.000000
0   11682254000153  0.000000  1000.000000
0   60889128000180  0.012362   969.095500
0   71673990000177  0.013471   966.323079
0   10877027000110  0.019713   950.716944
0   01776827000154  0.021593   946.018593
0   00178663000281  0.023503   941.242885
0   01753779000189  0.024915   937.713313
0   04423704000209  0.025195   937.011859
0   62148093000153  0.028811   927.973302
0   17464661000170  0.030450   923.873918
0   38936787000170  0.030692   923.270290
0   16367304000121  0.031988   920.030786
0   61365284001186  0.032326   919.184916
0   08792013000152  0.033192   917.019128
0   11065974000170  0.033841   915.397584
0   02595658000119  0.036242   909.395898
0   03704136000170  0.036536   908.659616
0   03722779000147  0.037558   906.106160
0   11377065000177  0.038700   903.249550
0   11296199000163  0.039622   900.943954
0   02092455000100  0.040098   899.754453
0   20314546000124  0.040844   897.889057
0   97546276000101  0.041414   896.465937
0   12539654000177  0.041912   895.220094
0   09189540000130  0.042580   893.549706
0   03314295000169  0.042649   893.376761
0   05376703000132  0.043683   890.793059
0   03317210000104  0.045161   887.097457
0   16548890000100  0.046471   883.822345
..             ...       ...          ...
0   02865647000101  0.100000   750.000000
0   13727153000187  0.100000   750.000000
0   25533593000182  0.100000   750.000000
0   11498652000114  0.100000   750.000000
0   11018748000138  0.100000   750.000000
0   76327030000179  0.100000   750.000000
0   11208274000197  0.100000   750.000000
0   51282341000219  0.100000   750.000000
0   30898048000120  0.100000   750.000000
0   27340387000181  0.100000   750.000000
0   17456726000136  0.100000   750.000000
0   11228015000128  0.100000   750.000000
0   11270163000100  0.100000   750.000000
0   11415084000140  0.100000   750.000000
0   07585962000107  0.100000   750.000000
0   27253894000188  0.100000   750.000000
0   05921508000146  0.100000   750.000000
0   12314749000192  0.100000   750.000000
0   05735828000101  0.100000   750.000000
0   02234090000100  0.100000   750.000000
0   12668058000197  0.100000   750.000000
0   07592667000170  0.100000   750.000000
0   12797977000160  0.100000   750.000000
0   10214597000120  0.100000   750.000000
0   71702716000189  0.100000   750.000000
0   41586439000125  0.100000   750.000000
0   01541647000193  0.100000   750.000000
0   13521776000107  0.100000   750.000000
0   21446197000167  0.100000   750.000000
0   22697828000183  0.100000   750.000000

[200 rows x 3 columns]

In [89]:
df_comp[df_comp["cnpj"]=="11296199000163"]

,cnpj,segmento,valor_divida,total_divida,composicao_divida,fat_medio,prop_divida,quantidade_cheques,segmento_principal,composicao_principal,tempo_medio,idade_maxima
446,11296199000163,credito,35668.71,42687.18,0.835584,71055.775,0.600756,0,credito,0.835584,36.5,879
447,11296199000163,outros,7018.47,42687.18,0.164416,71055.775,0.600756,0,credito,0.835584,36.5,879
448,11296199000163,processos,0.00,42687.18,0.000000,71055.775,0.600756,0,credito,0.835584,36.5,879

In [90]:
df[df['cnpj']=="11296199000163"]

,cnpj,data_ocorrencia,modalidade_natureza,natureza,tipo,uf,valor,segmento
0,11296199000163,12/01/2017,FINANCIAMENT,Créditos e financiamentos - empréstimos a pess...,restricoes_financeiras,,35668.71,credito
0,11296199000163,10/02/2017,Dívidanãocontestada.,Falta Pagamento,protestos,MG,1498.68,outros
1,11296199000163,18/01/2017,Dívidanãocontestada.,Falta Pagamento,protestos,MG,430.52,outros
2,11296199000163,11/01/2017,Dívidanãocontestada.,Falta Pagamento,protestos,MG,430.52,outros
3,11296199000163,04/01/2017,Dívidanãocontestada.,Falta Pagamento,protestos,MG,542.77,outros
4,11296199000163,28/12/2016,Dívidanãocontestada.,Falta Pagamento,protestos,MG,542.77,outros
5,11296199000163,22/12/2016,Dívidanãocontestada.,Falta Pagamento,protestos,MG,975.43,outros
6,11296199000163,21/12/2016,Dívidanãocontestada.,Falta Pagamento,protestos,MG,542.77,outros
7,11296199000163,08/12/2016,Dívidanãocontestada.,Falta Pagamento,protestos,MG,730.00,outros
8,11296199000163,13/11/2016,Dívidanãocontestada.,Falta Pagamento,protestos,MG,386.00,outros
0,11296199000163,05/12/2016,DUPLICATA,CÓDIGO DE ANOTAÇÃO NÃO ENCONTRADO,pendencias,NaN,518.48,outros
1,11296199000163,02/12/2016,DUPLICATA,CÓDIGO DE ANOTAÇÃO NÃO ENCONTRADO,pendencias,NaN,420.53,outros
0,11296199000163,25/01/2018,EXECUCAO,Execução,processos,MG,0.00,processos

In [98]:
dt = df[df['cnpj']=='14761474000160']
dp = probability(dt)
dp

    segmento  ocorrencias  probabilidade
0    credito            8       0.048193
1     outros          156       0.939759
2  processos            2       0.012048

In [99]:
di = impact(dt)
di

    segmento      valor    impact
0    credito  144433.71  0.181423
1     outros  614586.22  0.771980
2  processos   37097.24  0.046598

In [101]:
dr = dp.merge(di, left_on="segmento", right_on="segmento", how="left")

In [103]:
dr["risk"] = dr["probabilidade"]*dr["impact"]

In [115]:
dr["dscore"] = dr.apply(lambda x : dscore_inter(x["risk"]), axis=1)

In [117]:
dr["impact2"] = dr.apply(lambda x : W.get(x["segmento"]), axis=1)

In [119]:
dr["impact2"] = dr["impact"]*dr["impact2"]

In [121]:
dr["dscore"] = dr.apply(lambda x : dscore_inter(x["impact2"]), axis=1)

In [124]:
dr["dscore"].mean()

454.17884488870726

In [125]:
dr

,segmento,ocorrencias,probabilidade,valor,impact,risk,dscore,impact2
0,credito,8,0.048193,144433.71,0.181423,0.008743,274.309283,0.725691
1,outros,156,0.939759,614586.22,0.771980,0.725475,228.020393,0.771980
2,processos,2,0.012048,37097.24,0.046598,0.000561,860.206859,0.139793

In [113]:
def dscore_inter(r):
    return 1000*((-1)*r + 1)

In [114]:
dscore_inter(0.7254)

274.59999999999997

In [126]:
# ponderando o impacto

In [142]:
dt = df[df["cnpj"]=="14761474000160"]

In [143]:
dt.groupby("segmento").sum()

               valor
segmento
credito    144433.71
outros     614586.22
processos   37097.24

In [144]:
dimp = dt.groupby(["segmento"]).sum().reset_index()
dimp["impact"] = dimp["valor"]/dimp["valor"].sum()
dimp["impact_pond"] = dimp.apply(lambda x : W.get(x["segmento"])*x["impact"], axis=1)

In [145]:
dimp

    segmento      valor    impact  impact_pond
0    credito  144433.71  0.181423     0.725691
1     outros  614586.22  0.771980     0.771980
2  processos   37097.24  0.046598     0.139793

In [146]:
dprob = probability(dt)

In [150]:
dr = dprob.merge(dimp, left_on="segmento", right_on="segmento", how="left")

In [152]:
dr["risco"] = dr["probabilidade"]*dr["impact_pond"]

In [154]:
def dscore2(r):
    return -250*(r-4)

In [155]:
dr["dscore2"] = dr.apply(lambda x : dscore2(x["risco"]), axis=1)

In [156]:
dr

,segmento,ocorrencias,probabilidade,valor,impact,impact_pond,risco,dscore2
0,credito,8,0.048193,144433.71,0.181423,0.725691,0.034973,991.256738
1,outros,156,0.939759,614586.22,0.771980,0.771980,0.725475,818.631297
2,processos,2,0.012048,37097.24,0.046598,0.139793,0.001684,999.578936

In [137]:
df_comp[df_comp["segmento_principal"]=="credito"].sort_values("composicao_principal", ascending=False).head()

,cnpj,segmento,valor_divida,total_divida,composicao_divida,fat_medio,prop_divida,quantidade_cheques,segmento_principal,composicao_principal,tempo_medio,idade_maxima
257,07810124000181,credito,116051.09,116051.09,1.0,2309.699167,50.245111,0,credito,1.0,212.5,852
146,04509695000192,credito,34146.03,34146.03,1.0,23566.275000,1.448936,0,credito,1.0,0.0,1243
102,03429278000177,credito,191144.39,191144.39,1.0,10844.425833,17.626050,0,credito,1.0,0.0,834
559,15523647000175,credito,5183.43,5183.43,1.0,5347.440833,0.969329,0,credito,1.0,0.0,1275
556,15497859000125,credito,116073.75,116073.75,1.0,5353.230833,21.682934,0,credito,1.0,1.5,539

In [157]:
resp

              cnpj      risk       dscore
0   19008188000142  0.100000   750.000000
0   00748390000182  0.100000   750.000000
0   00272073000302  0.100000   750.000000
0   03403405000169  0.095696   760.760648
0   04501499000171  0.050229   874.426892
0   05164765000180  0.100000   750.000000
0   05674948000146  0.100000   750.000000
0   05690993000194  0.100000   750.000000
0   06135496000197  0.100000   750.000000
0   07127571000130  0.100000   750.000000
0   07670088000106  0.100000   750.000000
0   08792013000152  0.033192   917.019128
0   09252459000157  0.100000   750.000000
0   09300308000127  0.100000   750.000000
0   10483781000176  0.100000   750.000000
0   10656548000148  0.100000   750.000000
0   11296199000163  0.039622   900.943954
0   11368892000102  0.100000   750.000000
0   13339969000133  0.100000   750.000000
0   13633267000168  0.100000   750.000000
0   13709442000153  0.100000   750.000000
0   13952531000126  0.100000   750.000000
0   14168536000125  0.100000   750.000000
0   14761474000160  0.076213   809.466972
0   15435714000108  0.100000   750.000000
0   16613061000164  0.100000   750.000000
0   16672426000121  0.100000   750.000000
0   17495410000153  0.100000   750.000000
0   17969170000181  0.100000   750.000000
0   19256652000110  0.100000   750.000000
..             ...       ...          ...
0   20124081000149  0.200000   500.000000
0   27537765000111  0.100000   750.000000
0   22668371000189  0.101585   746.038435
0   20423038000184  0.100000   750.000000
0   26411719000109  0.100000   750.000000
0   09036323000100  0.095663   760.842072
0   09567988000140  0.100000   750.000000
0   39468574000124  0.100000   750.000000
0   08887253000130  0.100000   750.000000
0   09396386000177  0.100000   750.000000
0   51452795000100  0.096522   758.695753
0   06910296000164  0.100000   750.000000
0   18703372000140  0.100000   750.000000
0   01136501000162  0.088799   778.003137
0   09456517000164  0.076929   807.678147
0   11682254000153  0.000000  1000.000000
0   06233291000144  0.300000   250.000000
0   18917920000134  0.300000   250.000000
0   18371750000135  0.300000   250.000000
0   21295614000118  0.300000   250.000000
0   61699971000166  0.300000   250.000000
0   53244075000184  0.300000   250.000000
0   15576591000117  0.300000   250.000000
0   05337303000118  0.300000   250.000000
0   05702753000162  0.300000   250.000000
0   06222722000843  0.300000   250.000000
0   24629252000142  0.300000   250.000000
0   24873314000167  0.300000   250.000000
0   11248203000118  0.000000  1000.000000
0   03334511000138  0.300000   250.000000

[717 rows x 3 columns]